The ann:websocket.annotation.ServerWebSocket[] annotation can be applied to any class that should map to a WebSocket URI. The following example is a simple chat WebSocket implementation:

snippet::io.micronaut.docs.http.server.netty.websocket.ChatServerWebSocket[tags="clazz", indent=0,title="WebSocket Chat Example"]

<1> The ann:websocket.annotation.ServerWebSocket[] annotation defines the path the WebSocket is mapped under. The URI can be a URI template.
<2> The ann:websocket.annotation.OnOpen[] annotation declares the method to invoke when the WebSocket is opened.
<3> The ann:websocket.annotation.OnMessage[] annotation declares the method to invoke when a message is received.
<4> You can use a api:websocket.WebSocketBroadcaster[] to broadcast messages to every WebSocket session. You can filter which sessions to send to with a `Predicate`. Also, you could use the api:websocket.WebSocketSession[] instance to send a message to it with `WebSocketSession::send`.
<5> The ann:websocket.annotation.OnClose[] annotation declares the method to invoke when the WebSocket is closed.

TIP: A working example of WebSockets in action can be found at https://guides.micronaut.io/latest/micronaut-websocket.html[Micronaut Guides].

For binding, method arguments to each WebSocket method can be:

* A variable from the URI template (in the above example `topic` and `username` are URI template variables)
* An instance of api:websocket.WebSocketSession[]

=== The @OnClose Method

The ann:websocket.annotation.OnClose[] method can optionally receive a api:websocket.CloseReason[]. The `@OnClose` method is invoked prior to the session closing.

=== The @OnMessage Method

The ann:websocket.annotation.OnMessage[] method can define a parameter for the message body. The parameter can be one of the following:

* A Netty `WebSocketFrame`
* Any Java primitive or simple type (such as `String`). In fact, any type that can be converted from `ByteBuf` (you can register additional api:core.convert.TypeConverter[] beans to support a custom type).
* A `byte[]`, a `ByteBuf` or a Java NIO `ByteBuffer`.
* A POJO. In this case, it will be decoded by default as JSON using api:jackson.codec.JsonMediaTypeCodec[]. You can register a custom codec and define the content type of the handler using the ann:http.annotation.Consumes[] annotation.
* A api:websocket.WebSocketPongMessage[]. This is a special case: The method will not receive regular messages, but instead handle WebSocket pongs that arrive as a reply to a ping sent to the client.

=== The @OnError Method

A method annotated with ann:websocket.annotation.OnError[] can be added to implement custom error handling. The `@OnError` method can define a parameter that receives the exception type to be handled. If no `@OnError` handling is present and an unrecoverable exception occurs, the WebSocket is automatically closed.

=== Using @ExecuteOn For Blocking Methods

The callback methods of a ann:websocket.annotation.ServerWebSocket[] are invoked on the main Netty server event loop by default. If you do any blocking I/O operations in your WebSocket handler methods, then you must offload those tasks to a separate thread pool in the same manner as with HTTP. As with a ann:http.annotation.Controller[] or ann:http.annotation.Filter[], the ann:scheduling.annotation.ExecuteOn[] annotation can be applied to a ann:websocket.annotation.ServerWebSocket[] handler at either the type or method level.

=== Non-Blocking Message Handling

The previous example uses the `broadcastSync` method of the api:websocket.WebSocketBroadcaster[] interface which blocks until the broadcast is complete. A similar `sendSync` method exists in api:websocket.WebSocketSession[] to send a message to a single receiver in a blocking manner. You can however implement non-blocking WebSocket servers by instead returning a rs:Publisher[] or a link:{jdkapi}/java.base/java/util/concurrent/Future.html[Future] from each WebSocket handler method. For example:

snippet::io.micronaut.docs.http.server.netty.websocket.ReactivePojoChatServerWebSocket[tags="onmessage", indent=0,title="WebSocket Chat Example"]

The example above uses `broadcast`, which creates an instance of rs:Publisher[] and returns the value to Micronaut. The Micronaut framework sends the message asynchronously based on the Publisher interface. The similar `send` method sends a single message asynchronously via Micronaut return value.

For sending messages asynchronously outside Micronaut annotated handler methods, you can use `broadcastAsync` and `sendAsync` methods in their respective api:websocket.WebSocketBroadcaster[] and api:websocket.WebSocketSession[] interfaces. For blocking sends, the `broadcastSync` and `sendSync` methods can be used.

=== @ServerWebSocket and Scopes

By default, the `@ServerWebSocket` instance is shared for all WebSocket connections. Extra care must be taken to synchronize local state to avoid thread safety issues.

If you prefer to have an instance for each connection, annotate the class with ann:context.annotation.Prototype[]. This lets you retrieve the api:websocket.WebSocketSession[] from the `@OnOpen` handler and assign it to a field of the `@ServerWebSocket` instance.

=== Sharing Sessions with the HTTP Session

The api:websocket.WebSocketSession[] is by default backed by an in-memory map. If you add the `session` module you can however share <<sessions,sessions>> between the HTTP server and the WebSocket server.

NOTE: When sessions are backed by a persistent store such as Redis, after each message is processed the session is updated to the backing store.

[TIP]
.Using the CLI
====
If you created your project using Application Type `Micronaut Application`, you can use the `create-websocket-server` command with the Micronaut CLI to create a class annotated with api:websocket.annotation.ServerWebSocket[].

----
$ mn create-websocket-server MyChat
| Rendered template WebsocketServer.java to destination src/main/java/example/MyChatServer.java
----
====

=== Connection Timeouts

By default, Micronaut framework times out idle connections with no activity after five minutes. Normally this is not a problem as browsers automatically reconnect WebSocket sessions, however you can control this behaviour by setting the `micronaut.server.idle-timeout` setting (a negative value results in no timeout):

.Setting the Connection Timeout for the Server
[configuration]
----
micronaut:
  server:
    idle-timeout: 30m
----

If you use Micronaut's WebSocket client you may also wish to set the timeout on the client:

.Setting the Connection Timeout for the Client
[configuration]
----
micronaut:
  http:
    client:
      read-idle-timeout: 30m
----
