
NOTE: This section applies to Java & Kotlin functions - for functions written in Groovy, see <<groovyFunctions,Groovy Functions>>

To write your function's behavior, annotate your class with the ann:function.FunctionBean[] annotation. Your class must also implement one of the interfaces from the `java.util.function` package.

TIP: If you have the Micronaut CLI installed you can quickly create a Java function with `mn create-function hello-world` or `mn create-function hello-world --lang kotlin` for Kotlin

The following examples implement Java's link:{javase}java/util/function/Supplier.html[Supplier] functional interface.

.Example Java Function
[source,java]
----
package example;

import io.micronaut.function.FunctionBean;
import java.util.function.Supplier;

@FunctionBean("hello-world-java")
public class HelloJavaFunction implements Supplier<String> {

    @Override
    public String get() { //<1>
        return "Hello world!";
    }
}
----
<1> Override the `get` method of link:{javase}java/util/function/Supplier.html[Supplier] to return the response from your function.

Alternatively you can also define a api:context.annotation.Factory[] that returns a Java lambda:


.Example Java Function as a Lambda
[source,java]
----
package example;

import io.micronaut.context.annotation.*;
import io.micronaut.function.FunctionBean;
import java.util.function.Supplier;

@Factory // <1>
public class MyFunctions {

    @FunctionBean("hello-world-java")
    public Supplier<String> helloWorld() { // <2>
        return () -> "Hello world!";
    }
}
----

<1> A api:context.annotation.Factory[] bean is defined
<2> The ann:function.FunctionBean[] annotation is used on a method that returns the function.

If you are using Kotlin then process is exactly the same:

.Example Kotlin Function
[source,kotlin]
----
package example

import io.micronaut.function.FunctionBean
import java.util.function.Supplier

@FunctionBean("hello-world-kotlin")
class HelloKotlinFunction : Supplier<String> {

    override fun get(): String { //<1>
        return "Hello world!"
    }
}
----
<1> Override the `get` method of link:{javase}java/util/function/Supplier.html[Supplier] to return the response from your function.

The following table summarizes the supported interfaces:

.Functional Interfaces
|===
|Interface|Dependency

|jdk:java.util.function.Supplier[] | Accepts no arguments and returns a single result
|jdk:java.util.function.Consumer[] | Accepts a single argument and returns no result
|jdk:java.util.function.BiConsumer[] | Accepts two arguments and returns no result
|jdk:java.util.function.Function[] | Accepts a single argument and returns a single result
|jdk:java.util.function.BiFunction[] | Accepts two arguments and returns a single result
|===

In addition, functions have an input and/or an output. The input is represented by the accepted argument and represents the body consumed by the function and the output is represented by the return value of the function. The input and the output should be either a Java primitive or simple type (`int`, `String` etc.) or a POJO.

A single project can define multiple functions, however only a single function should be configured for execution by the application. This can be configured using the `micronaut.function.name` property in `application.yml`:

.Configuring the Function Name to Execute
[source,yaml]
----
micronaut:
    function:
        name: hello-world-java
----

Alternatively you can specify the value when running your function (for example in the `Dockerfile`) either as an environment variable:

.Specifying the Function to Execute as a Environment variable
[source,bash]
----
$ export MICRONAUT_FUNCTION_NAME=hello-world-java
$ java -jar build/libs/hello-world-function-all.jar
----

Or as a system property:

.Specifying the Function to Execute as a System property
[source,bash]
----
$ java -Dmicronaut.function.name=hello-world-java -jar build/libs/hello-world-function-all.jar
----
