Eager initialization of `@Singleton` beans maybe desirable in certain scenarios, such as on AWS Lambda where more CPU resources are assigned to Lamdba construction than execution.

You can specify whether you want to initialize eagerly `@Singleton` scoped beans using the link:{api}/io/micronaut/context/ApplicationContextBuilder.html[ApplicationContextBuilder] interface:

.Enabling Eager Initialization of Singletons
[source,java]
----
public class Application {

    public static void main(String[] args) {
        Micronaut.build(args)
            .eagerInitSingletons(true) // <1>
            .mainClass(Application.class)
            .start();
    }
}
----

<1> Setting eager init to true initializes all singletons

When you use Micronaut in environments such as <<serverlessFunctions, Serverless Functions>>, you will not have an Application class and instead you extend a Micronaut provided class. In those cases, Micronaut provides methods which you can override to enhance the api:context.ApplicationContextBuilder[]

.Override of newApplicationContextBuilder()
[source,java]
----
public class MyFunctionHandler extends MicronautRequestHandler<APIGatewayProxyRequestEvent, APIGatewayProxyResponseEvent> {
...
    @Nonnull
    @Override
    protected ApplicationContextBuilder newApplicationContextBuilder() {
        ApplicationContextBuilder builder = super.newApplicationContextBuilder();
        builder.eagerInitSingletons(true);
        return builder;
    }
    ...
}
----

ann:context.annotation.ConfigurationReader[] beans such as ann:context.annotation.EachProperty[]  or ann:context.annotation.ConfigurationProperties[] are singleton beans. If you want to eager init configuration, but keep other `@Singleton` scoped beans creation lazy, use `eagerInitConfiguration`:

.Enabling Eager Initialization of Configuration
[source,java]
----
public class Application {

    public static void main(String[] args) {
        Micronaut.build(args)
            .eagerInitConfiguration(true) // <1>
            .mainClass(Application.class)
            .start();
    }
}
----

<1> Setting eager init to true initializes all configuration reader beans.

