/*
 * Copyright 2017-2020 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aop;

import io.micronaut.context.BeanRegistration;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.UsedByGeneratedCode;
import io.micronaut.inject.proxy.InterceptedBean;

import java.util.List;

/**
 * An interface implemented by generated proxy classes.
 *
 * @author Graeme Rocher
 * @since 1.0
 */
public interface Intercepted extends InterceptedBean {

    /**
     * The interceptor registrations a proxy generated before 5.3 retained when it was constructed.
     *
     * @return The retained interceptor registrations, never {@code null}; empty for a proxy generated since 5.3
     * @since 5.2.0
     * @deprecated Since 5.3.0 a proxy retains nothing, and this returns an empty list for a proxy generated since
     * 5.3: the non-singleton interceptors bound to a bean are the bean's own, created as its dependents and found
     * there by every interception point. A listener reads them from
     * {@link io.micronaut.context.event.BeanEvent#getDependentBeans()}, anything else from
     * {@link io.micronaut.context.BeanRegistration#getDependentBeans()}. Proxies generated by 5.2 still override this
     * and the runtime still honours what they return.
     */
    @Deprecated(since = "5.3.0", forRemoval = true)
    @Override
    @Internal
    @UsedByGeneratedCode
    // The $ prefix marks this as generated-code infrastructure and keeps it clear of any method on the proxied type.
    @SuppressWarnings({"checkstyle:MethodName", "java:S100", "removal"})
    default List<BeanRegistration<Interceptor<?, ?>>> $interceptorRegistrations() {
        return List.of();
    }
}
