Since 1.1.x, the Micronaut framework supports API versioning via a dedicated ann:core.version.annotation.Version[] annotation.

The following example demonstrates how to version an API:

snippet::io.micronaut.docs.web.router.version.VersionedController[tags="imports,clazz", indent=0, title="Versioning an API"]

<1> The `helloV1` method is declared as version `1`
<2> The `helloV2` method is declared as version `2`

Then enable versioning by setting `micronaut.router.versioning.enabled` to `true` in your configuration file (e.g `application.yml`):

.Enabling Versioning
[configuration]
----
micronaut:
  router:
    versioning:
      enabled: true
----

By default, the Micronaut framework has two strategies for resolving the version based on an HTTP header named `X-API-VERSION` or a request parameter named `api-version`, however this is configurable. A full configuration example can be seen below:

.Configuring Versioning
[configuration]
----
micronaut:
  router:
    versioning:
      enabled: true
      parameter:
        enabled: false
        names: 'v,api-version'
      header:
        enabled: true
        names:
          - 'X-API-VERSION'
          - 'Accept-Version'
----

- This example enables versioning
- `parameter.enabled` enables or disables parameter-based versioning
- `parameter.names` specifies the parameter names as a comma-separated list
- `header.enabled` enables or disables header-based versioning
- `header.names` specifies the header names as a list

If this is not enough you can also implement the api:web.router.version.resolution.RequestVersionResolver[] interface which receives the api:http.HttpRequest[] and can implement any strategy you choose.

=== Default Version

It is possible to supply a default version through configuration.

.Configuring Default Version
[configuration]
----
micronaut:
  router:
    versioning:
      enabled: true
      default-version: 3
----

- This example enables versioning and sets the default version

A route is *not* matched if the following conditions are met:

* The default version is configured
* No version is found in the request
* The route defines a version
* The route version does not match the default version

If the incoming request specifies a version, the default version has no effect.

=== Versioning Client Requests

Micronaut's <<clientAnnotation, Declarative HTTP client>> also supports automatic versioning of outgoing requests via the ann:core.version.annotation.Version[] annotation.

By default, if you annotate a client interface with ann:core.version.annotation.Version[], the value supplied to the annotation is included using the `X-API-VERSION` header.

For example:

snippet::io.micronaut.docs.client.versioning.HelloClient[tags="imports,clazz"]

<1> The ann:core.version.annotation.Version[] annotation can be used at the type level to specify the version to use for all methods
<2> When defined at the method level it is used only for that method

The default behaviour for how the version is sent for each call can be configured with api:http.client.interceptor.configuration.DefaultClientVersioningConfiguration[]:

include::{includedir}configurationProperties/io.micronaut.http.client.interceptor.configuration.DefaultClientVersioningConfiguration.adoc[]

For example to use `Accept-Version` as the header name:

.Configuring Client Versioning
[configuration]
----
micronaut:
  http:
    client:
      versioning:
        default:
          headers:
            - 'Accept-Version'
            - 'X-API-VERSION'
----

The `default` key refers to the default configuration. You can specify client-specific configuration by using the value passed to `@Client` (typically the service ID). For example:

.Configuring Versioning
[configuration]
----
micronaut:
  http:
    client:
      versioning:
        greeting-service:
          headers:
            - 'Accept-Version'
            - 'X-API-VERSION'
----

The above uses a key named `greeting-service` which can be used to configure a client annotated with `@Client('greeting-service')`.
