The examples in the previous section demonstrates how Micronaut allows you to bind method parameters from URI path variables. This section will discuss how to bind arguments from other parts of the request.

== Binding Annotations

All of the binding annotations support customization of the name of the variable being bound from with their `name` member.

The following table summarizes the annotations, their purpose and provides an example:

.Parameter Binding Annotations
|===
|Annotation|Description |Example

|link:{api}/io/micronaut/http/annotation/Body.html[@Body]
|Binds from the body of the request
|`@Body String body`

|link:{api}/io/micronaut/http/annotation/CookieValue.html[@CookieValue]
|Binds a parameter from a cookie
|`@CookieValue String myCookie`

|link:{api}/io/micronaut/http/annotation/Header.html[@Header]
|Binds a parameter from an HTTP header
|`@Header String contentType`

|link:{api}/io/micronaut/http/annotation/QueryValue.html[@QueryValue]
|Binds from a request query parameter
|`@QueryValue String myParam`

|link:{api}/io/micronaut/http/annotation/Part.html[@Part]
|Binds from a part of a multipart request
|`@Part CompletedFileUpload file`

|link:{api}/io/micronaut/http/annotation/RequestAttribute.html[@RequestAttribute]
|Binds from an attribute of the request. Attributes are typically created in filters
|`@RequestAttribute String myAttribute`

|link:{api}/io/micronaut/http/annotation/PathVariable.html[@PathVariable]
|Binds from the path of the request
|`@PathVariable String id`

|link:{api}/io/micronaut/http/annotation/RequestBean.html[@RequestBean]
|Binds any Bindable value to single Bean object
|`@RequestBean MyBean bean`
|===

When a value is not specified to any binding annotation then the parameter name is used. In other words the following two methods are equivalent and both bind from a cookie called `myCookie`:

snippet::io.micronaut.docs.server.binding.BindingController[tags="cookie1,cookie2",indent=0]

Because hyphens are not allowed in variable names it may be necessary to set the name in the annotation. The following two definitions are equivalent:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header1,header2",indent=0]

== Binding from Multiple Query values

Instead of binding from a single section of the request, it may be desirable to bind all query values for example to a POJO. This can be achieved by using the exploded operator (`?pojo*`) in the URI template. For example:

snippet::io.micronaut.docs.server.binding.BookmarkController[tags="imports,class", indent=0, title="Binding Request parameters to POJO"]

== Binding from Multiple Bindable values

Instead of binding just Query values, it is also possible to bind any Bindable value to POJO  (e.g. when you want to bind `HttpRequest`, `@PathVariable`, `@QueryValue` and `@Header` to single POJO).
This can be achieved with `@RequestBean` annotation and custom Bean class that has fields with Bindable annotations or fields that can be bound by type (e.g. HttpRequest, BasicAuth, Authentication etc.).
For example:

snippet::io.micronaut.docs.server.binding.MovieTicketController[tags="class", indent=0, title="Binding Bindable values to POJO"]

snippet::io.micronaut.docs.server.binding.MovieTicketBean[tags="class", indent=0, title="Bean definition"]

Bean class has to be introspected with `@Introspected`. It can be one of:

1. Mutable Bean class with setters and getters
2. Immutable Bean class with getters and all argument constructor (or `@Creator` annotation on a constructor or static method).
Arguments of constructor have to match field names so object can be constructed without reflection.

WARNING: Since Java does not retain argument names in the byte code, you have to compile code with `-parameters` in case you want to use Immutable Bean class from another Jar.
Another option is to extend Bean class in your source.

== Bindable Types

Generally any type that can be converted from a String representation to a Java type via the link:{api}/io/micronaut/core/convert/ConversionService.html[ConversionService] API can be bound to.

This includes most common Java types, however additional link:{api}/io/micronaut/core/convert/TypeConverter.html[TypeConverter] instances can be registered simply be creating `@Singleton` beans of type `TypeConverter`.

The handling of nullability deserves special mention. Consider for example the following example:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header2",indent=0]

In this case if the HTTP header `Content-Type` is not present in the request the route is considered invalid, since it cannot be satisfied and a HTTP 400 `BAD REQUEST` is returned.

If you wish for the `Content-Type` header to be optional, you can instead write:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header3",indent=0]

An null string will be passed if the header is absent from the request.

NOTE: `java.util.Optional` can also be used, however that is discouraged for method parameters.

Additionally, any `DateTime` that conforms to link:{jdkapi}/java/time/format/DateTimeFormatter.html#RFC_1123_DATE_TIME[RFC-1123] can be bound to a parameter, alternatively the format can be customized with the link:{api}/io/micronaut/core/convert/format/Format.html[Format] annotation:

snippet::io.micronaut.docs.server.binding.BindingController[tags="format1,format2",indent=0]

== Type Based Binding Parameters

Some parameters are recognized by their type instead of their annotation. The following table summarizes the parameter types, their purpose, and provides an example:

|===
|Type |Description |Example

|api:http.BasicAuth[]
|Allows binding of basic authorization credentials
|`BasicAuth basicAuth`

|===

== Variables resolution

Micronaut will try to populate method arguments in the following order:

1. URI variables like `/{id}`.
2. If the request is a `GET` request from query parameters (ie. `?foo=bar`).
3. If there is a `@Body` and request allows the body, bind the body to it.
4. if the request can have a body and no `@Body` is defined then try parse the body (either JSON or form data) and
bind the method arguments from the body.
5. Finally, if the method arguments cannot be populated return `400 BAD REQUEST`.

