The examples in the previous section demonstrate how the Micronaut framework lets you bind method parameters from URI path variables. This section shows how to bind arguments from other parts of the request.

== Binding Annotations

All binding annotations support customization of the name of the variable being bound from with their `name` member.

The following table summarizes the annotations and their purpose, and provides examples:

.Parameter Binding Annotations
|===
|Annotation|Description |Example

|link:{api}/io/micronaut/http/annotation/Body.html[@Body]
|Binds from the body of the request
|`@Body String body`

|link:{api}/io/micronaut/http/annotation/CookieValue.html[@CookieValue]
|Binds a parameter from a cookie
|`@CookieValue String myCookie`

|link:{api}/io/micronaut/http/annotation/Header.html[@Header]
|Binds a parameter from an HTTP header
|`@Header String requestId`

|link:{api}/io/micronaut/http/annotation/QueryValue.html[@QueryValue]
|Binds from a request query parameter
|`@QueryValue String myParam`

|link:{api}/io/micronaut/http/annotation/Part.html[@Part]
|Binds from a part of a multipart request
|`@Part CompletedFileUpload file`

|link:{api}/io/micronaut/http/annotation/RequestAttribute.html[@RequestAttribute]
|Binds from an attribute of the request. Attributes are typically created in filters
|`@RequestAttribute String myAttribute`

|link:{api}/io/micronaut/http/annotation/PathVariable.html[@PathVariable]
|Binds from the path of the request
|`@PathVariable String id`

|link:{api}/io/micronaut/http/annotation/RequestBean.html[@RequestBean]
|Binds any Bindable value to single Bean object
|`@RequestBean MyBean bean`
|===

The method parameter name is used when a value is not specified in a binding annotation. In other words the following two methods are equivalent and both bind from a cookie named `myCookie`:

snippet::io.micronaut.docs.server.binding.BindingController[tags="cookie1,cookie2",indent=0]

Because hyphens are not allowed in variable names, it may be necessary to set the name in the annotation. The following definitions are equivalent:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header1,header2",indent=0]

== Stream Support

The Micronaut framework also supports binding the body to an `InputStream`. If the method is reading the stream, the method execution must be offloaded to another thread pool to avoid blocking the event loop.

snippet::io.micronaut.docs.http.server.stream.StreamController[tags="read", indent=0, title="Performing Blocking I/O With InputStream"]

<1> The controller method is executed on the IO thread pool
<2> The body is passed to the method as an input stream
<3> The stream is read

== Binding from Multiple Query values

Instead of binding from a single section of the request, it may be desirable to bind all query values for example to a POJO. This can be achieved by using the exploded operator (`?pojo*`) in the URI template. For example:

snippet::io.micronaut.docs.server.binding.BookmarkController[tags="imports,class", indent=0, title="Binding Request parameters to POJO"]

== Binding from Multiple Bindable values

Instead of binding just query values, it is also possible to bind any Bindable value to a POJO (e.g. to bind `HttpRequest`, `@PathVariable`, `@QueryValue` and `@Header` to a single POJO). This can be achieved with the `@RequestBean` annotation and a custom Bean class with fields with Bindable annotations, or fields that can be bound by type (e.g. `HttpRequest`, `BasicAuth`, `Authentication`, etc.).

For example:

snippet::io.micronaut.docs.server.binding.MovieTicketController[tags="class", indent=0, title="Binding Bindable values to POJO"]

which uses this bean class:

snippet::io.micronaut.docs.server.binding.MovieTicketBean[tags="class", indent=0, title="Bean definition"]

The bean class has to be introspected with `@Introspected`. It can be one of:

. Mutable Bean class with setters and getters
. Immutable Bean class with getters and an all-argument constructor (or `@Creator` annotation on a constructor or static method). Arguments of the constructor must match field names so the object can be instantiated without reflection.

WARNING: Since Java does not retain argument names in bytecode, you must compile code with `-parameters` to use an immutable bean class from another jar. Another option is to extend Bean class in your source.

== Bindable Types

Generally any type that can be converted from a String representation to a Java type via the link:{api}/io/micronaut/core/convert/ConversionService.html[ConversionService] API can be bound to.

This includes most common Java types, however additional link:{api}/io/micronaut/core/convert/TypeConverter.html[TypeConverter] instances can be registered via the service loader or by creating beans of type `TypeConverter`,

The handling of nullability deserves special mention. Consider for example the following example:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header2",indent=0]

In this case, if the HTTP header `Content-Type` is not present in the request, the route is considered invalid, since it cannot be satisfied, and a HTTP 400 `BAD REQUEST` is returned.

To make the `Content-Type` header optional, you can instead write:

snippet::io.micronaut.docs.server.binding.BindingController[tags="header3",indent=0]

A `null` string is passed if the header is absent from the request.

NOTE: `java.util.Optional` can also be used, but that is discouraged for method parameters.

Additionally, any `DateTime` that conforms to link:{jdkapi}/java.base/java/time/format/DateTimeFormatter.html#RFC_1123_DATE_TIME[RFC-1123] can be bound to a parameter. Alternatively the format can be customized with the link:{api}/io/micronaut/core/convert/format/Format.html[Format] annotation:

snippet::io.micronaut.docs.server.binding.BindingController[tags="format1,format2",indent=0]

== Type-Based Binding Parameters

Some parameters are recognized by their type instead of their annotation. The following table summarizes the parameter types, their purpose, and provides an example:

|===
|Type |Description |Example

|api:http.BasicAuth[]
|Allows binding of basic authorization credentials
|`BasicAuth basicAuth`

|===

== Variable resolution

The Micronaut framework tries to populate method arguments in the following order:

. URI variables like `/{id}`.
. From query parameters if the request is a `GET` request (e.g. `?foo=bar`).
. If there is a `@Body` and request allows the body, bind the body to it.
. If the request can have a body and no `@Body` is defined then try to parse the body (either JSON or form data) and bind the method arguments from the body.
. Finally, if the method arguments cannot be populated return `400 BAD REQUEST`.
