A Micronaut controller action consumes `application/json` by default. Consuming other content types is supported with the `@Consumes` annotation, or the `consumes` member of any HTTP method annotation.

snippet::io.micronaut.docs.server.consumes.ConsumesController[tags="imports,clazz", indent=0]

<1> By default, a controller action consumes request with `Content-Type` of type `application/json`.
<2> The `@Consumes` annotation takes a `String[]` of supported media types for an incoming request.
<3> Content types can also be specified with the `consumes` member of the method annotation.

=== Customizing Processed Content Types

JSON is read and written for `application/json` and a few other well known JSON media types, such as `application/hal+json` and `application/problem+json`. Text is read and written for `text/plain`. To read and write another media type the same way, for example a vendor type such as `application/vnd.acme+json`, add it to the `additional-types` of the api:io.micronaut.http.codec.CodecConfiguration[]:

[configuration]
----
micronaut:
  codec:
    json:
      additional-types:
        - application/vnd.acme+json
        - application/prs.hal-forms+json
        - text/javascript
----

This applies to the server and to HTTP clients created by the application context, for both request and response bodies. A api:io.micronaut.http.body.MessageBodyReader[] or api:io.micronaut.http.body.MessageBodyWriter[] registered with `@Consumes` or `@Produces` for the exact media type still takes precedence.

The currently supported configuration prefixes are `json`, `json-stream`, `text`, and `text-stream`.
