A Micronaut controller action consumes `application/json` by default. Consuming other content types is supported with the `@Consumes` annotation, or the `consumes` member of any HTTP method annotation.

snippet::io.micronaut.docs.server.consumes.ConsumesController[tags="imports,clazz", indent=0]

<1> By default, a controller action consumes request with `Content-Type` of type `application/json`.
<2> The `@Consumes` annotation takes a `String[]` of supported media types for an incoming request.
<3> Content types can also be specified with the `consumes` member of the method annotation.

=== Customizing Processed Content Types

JSON is read and written for `application/json` and a few other well known JSON media types, such as `application/hal+json` and `application/problem+json`. Any media type with the `+json` structured suffix, for example `application/vnd.acme+json` or `application/prs.hal-forms+json`, is also read and written as JSON, both by the server and by the HTTP client, unless a api:io.micronaut.http.body.MessageBodyReader[] or api:io.micronaut.http.body.MessageBodyWriter[] is registered for that exact media type with `@Consumes` or `@Produces`. Such a handler takes precedence over the JSON handler.

To process a media type that has no `+json` suffix, for example `text/javascript`, as JSON, extend the list of media types of the codec with configuration that will be stored in api:io.micronaut.http.codec.CodecConfiguration[]:

[configuration]
----
micronaut:
  codec:
    json:
      additional-types:
        - text/javascript
        - ...
----

The currently supported configuration prefixes are `json`, `json-stream`, `text`, and `text-stream`.
