
== Custom argument binding

Micronaut uses an api:http.bind.binders.ArgumentBinderRegistry[ArgumentBinderRegistry] to look up api:core.bind.ArgumentBinder[ArgumentBinder]s
capable of binding to the arguments in the controller methods. The default implementation will look for an annotation on
the argument that is, itself, annotation with `@Bindable`. If one exists the argument binder registry will search for an
argument binder that supports that annotation.

If no fitting annotation is found Micronaut will try to find an argument binder that supports the argument's type.

An api:core.bind.ArgumentBinder[ArgumentBinder] can be registered as a bean. In this case it is only present when a
api:context.BeanContext[BeanContext] is initialized.

Key interfaces are:

=== AnnotatedRequestArgumentBinders
* api:htp.bind.binders.AnnotatedRequestArgumentBinder[AnnotatedRequestArgumentBinder]

- An interface for classes that bind an api:core.type.Argument[Argument] from an api:http.HttpRequest[HttpRequest] driven
by an annotation.

TIP: It is common to use api:io.micronaut.core.convert.ConversionService[ConversionService] to convert the data to the type of argument.

=== TypedRequestArgumentBinders

* api:http.bind.binders.TypedRequestArgumentBinder[TypedRequestArgumentBinder]

- An interface for classes that bind an api:core.type.Argument[Argument] from an api:http.HttpRequest[HttpRequest] driven by
the argument's type.

Binders are called by the api:io.micronaut.http.annotation.Controller[Controller] once the request is received and the argument
is resolved in the api:http.bind.binders.ArgumentBinderRegistry[ArgumentBinderRegistry]. api:io.micronaut.http.filter.HttpFilter[HttpFilter]s
are called before returning results to the Controller. Your api:io.micronaut.core.bind.BindingResult[BindingResult] may
depend on those being initialized before returning the binding result.

A binding result of the class you are binding will be returned from the bind method in the implementation written. The
result will be classified as either `SATISFIED` or `UNSATISFIED`. Returning a binding of the type `EMPTY` will be considered
SATISFIED. If the returned binding is UNSATISFIED the registry will continue to attempt to find argument binders that match
the argument.

If the binding result throws an exception that is not handled it will bubble up to the api:io.micronaut.http.annotation.Controller[Controller]
where it can be caught by an api:io.micronaut.http.annotation.Error[Error] handler.

.Setting up an annotated argument binder
[source,java]
----
@Singleton
public class MyBoundBeanTypeAnnotationBinder extends AbstractAnnotatedArgumentBinder<MyBindingAnnotation, MyBoundBean, HttpRequest<?>>
        implements AnnotatedRequestArgumentBinder<MyBindingAnnotation, MyBoundBean> {
    ...
    @Override
    public BindingResult<MyBoundBean> bind(ArgumentConversionContext<MyBoundBean> context, HttpRequest<?> source) {
        MyBoundBean myBoundBean = new MyBoundBean();
        myBoundBean.setShoppingCart(source.getCookies.get("shopping-cart"));
        myBoundBean.getBrowser("User-Agent");
        return () -> Optional.of(myBoundBean);
    }
    ...
}
----