Micronaut uses an api:http.bind.binders.ArgumentBinderRegistry[ArgumentBinderRegistry] to look up api:core.bind.ArgumentBinder[ArgumentBinder]s beans
capable of binding to the arguments in the controller methods. The default implementation will look for an annotation on
the argument that is, itself, annotated with ann:core.bind.annotation.Bindable[]. If one exists the argument binder registry will search for an
argument binder that supports that annotation.

If no fitting annotation is found Micronaut will try to find an argument binder that supports the argument's type.

An argument binder returns a api:core.bind.ArgumentBinder.BindingResult[]. The binding result gives Micronaut more information than just the value. Binding results are either satisfied or unsatisfied, and either empty or not empty. If an argument binder returns an unsatisfied result, the binder may be called again at different times in the request processing. Argument binders are initially called before the body is read and before any filters are executed. If a binder relies on any of that data and the data is not present, then an api:core.bind.ArgumentBinder.BindingResult#UNSATISFIED[] result should be returned. Returning an api:core.bind.ArgumentBinder.BindingResult#EMPTY[] or satisfied result will be the final result and the binder will not be called again for that request.

NOTE: At the end of processing if the result is still api:core.bind.ArgumentBinder.BindingResult#UNSATISFIED[], it is considered api:core.bind.ArgumentBinder.BindingResult#EMPTY[].

Key interfaces are:

=== AnnotatedRequestArgumentBinders

Argument binders that bind based on the presence of an annotation must implement api:http.bind.binders.AnnotatedRequestArgumentBinder[AnnotatedRequestArgumentBinder]. For example:

snippet::io.micronaut.docs.http.bind.binders.MyBindingAnnotation[tags="class", indent=0, title="An example of a binding annotation"]

<1> The binding annotation must itself be annotated as api:io.micronaut.core.bind.annotation.Bindable[@Bindable]

snippet::io.micronaut.docs.http.bind.binders.MyBoundBeanAnnotatedRequestArgumentBinder[tags="class", indent=0, title="Example of annotated data binding"]

<1> Use an extension of api:io.micronaut.core.bind.annotation.AbstractAnnotatedArgumentBinder[AbstractAnnotatedArgumentBinder] that implements api:io.micronaut.http.bind.binders.AnnotatedRequestArgumentBinder[AnnotatedRequestArgumentBinder] using the annotation intended to trigger this binder, in this case MyBindingAnnotation
<2> Override the bind method with the data type to bind
<3> Also override the getAnnotationType method which is used by the ArgumentBinderRegistry.

TIP: It is common to use api:io.micronaut.core.convert.ConversionService[ConversionService] to convert the data to the type of the value to the type of the argument.

Once the binder is created, it can be used like in the following example:

snippet::io.micronaut.docs.http.bind.binders.MyBoundBeanController[tags="annotated", indent=0, title="A controller operation with this annotated binding"]

<1> The parameter will be bound with with the annotated binder. This will take precedence over the typed binder.

=== TypedRequestArgumentBinders

Argument binders that bind based on the type of the argument must implement api:http.bind.binders.TypedRequestArgumentBinder[TypedRequestArgumentBinder]. For example:

snippet::io.micronaut.docs.http.bind.binders.MyBoundBeanTypedRequestArgumentBinder[tags="class", indent=0, title="Example of typed data binding"]

<1> Override the bind method with the data type to bind, in this case MyBoundBean
<2> After building the bound type as desired return the api:io.micronaut.core.bind.BindingResult[BindingResult]
<3> Also override the argumentType method which is used by the ArgumentBinderRegistry.

Once the binder is created, it can be used like in the following example:

snippet::io.micronaut.docs.http.bind.binders.MyBoundBeanController[tags="typed", indent=0, title="A controller operation with this typed binding"]

<1> The parameter will be bound with no annotation.


