Sometimes with distributing applications, bad things happen. Thus having a good way to handle errors is important.

To define local error handling simply define a method in a controller where the last argument is the type of the exception you wish to handle. For example the following method will handling JSON parse exceptions from Jackson for the scope of the declaring controller:

.Handling Controller Exceptions
[source,java]
----
include::{testsuite}/server/json/PersonController.java[tags=localError, indent=0]
----

<1> A method that explicitly handles `JsonParseException` is declared
<2> An instance of api:http.hateos.VndError[] is returned which outputs the error in https://github.com/blongden/vnd.error[application/vnd.error+json].
<3> A custom response is returned to handle the error

Note that the previous example will only handle errors thrown from the declaring controller. To handle errors globally with the api:http.annotation.Error[] annotation:

.Handling Global Errors
[source,java]
----
include::{testsuite}/server/json/PersonController.java[tags=globalError, indent=0]
----

<1> The api:http.annotation.Error[] is used to declare the method a global error handler
<2> A api:http.hateos.VndError[] instance is returned for all errors
<3> An api:http.HttpStatus#INTERNAL_SERVER_ERROR[] response is returned

TIP: You can also specify an exception type to the api:http.annotation.Error[] to add a more specific exception handler

Finally, you can also add global handlers for error status responses:

.Handling Global HTTP Status Errors
[source,java]
----
include::{testsuite}/server/json/PersonController.java[tags=statusError, indent=0]
----

<1> The api:http.annotation.Error[] declares which api:http.HttpStatus[] error code to handle (in this case 404)
<2> A api:http.hateos.VndError[] instance is returned for all 404 responses
<3> An api:http.HttpStatus#NOT_FOUND[] response is returned

IMPORTANT: A few things to note about the api:http.annotation.Error[] annotation. Two id@entical Error annotations that are
global cannot be declared. Two identical Error annotations that are non-global cannot be declared in the same controller.
If an Error annotation with the same parameter exists as global and another as a local, the local one will take precedence.