Sometimes with distributed applications, bad things happen. Having a good way to handle errors is important.

== Status Handlers

The api:http.annotation.Error[] annotation supports defining either an exception class or an HTTP status. Methods decorated with the annotation will be invoked as the result of other controller methods. The annotation also supports the notion of global and local, local being the default.

Local error handlers will only respond to methods defined in the same controller. Global error handlers can respond to any method in any controller. A local error handler is always searched for first when resolving which handler to execute.

TIP: When defining an error handler for an exception, you can specify the exception instance as an argument to the method and omit the exception property of the annotation.

== Local Error Handling

For example the following method will handling JSON parse exceptions from Jackson for the scope of the declaring controller:

snippet::io.micronaut.docs.server.json.PersonController[tags="localError", indent=0, title="Local exception handler"]

<1> A method that explicitly handles `JsonParseException` is declared
<2> An instance of api:http.hateoas.JsonError[] is returned.
<3> A custom response is returned to handle the error

snippet::io.micronaut.docs.server.json.PersonController[tags="statusError", indent=0, title="Local status handler"]

<1> The api:http.annotation.Error[] declares which api:http.HttpStatus[] error code to handle (in this case 404)
<2> A api:http.hateoas.JsonError[] instance is returned for all 404 responses
<3> An api:http.HttpStatus#NOT_FOUND[] response is returned

== Global Error Handling

snippet::io.micronaut.docs.server.json.PersonController[tags="globalError", indent=0, title="Global error handler"]

<1> The api:http.annotation.Error[] is used to declare the method a global error handler
<2> A api:http.hateoas.JsonError[] instance is returned for all errors
<3> An api:http.HttpStatus#INTERNAL_SERVER_ERROR[] response is returned

snippet::io.micronaut.docs.server.json.PersonController[tags="statusError", indent=0, title="Global status handler"]

<1> The api:http.annotation.Error[] declares which api:http.HttpStatus[] error code to handle (in this case 404)
<2> A api:http.hateoas.JsonError[] instance is returned for all 404 responses
<3> An api:http.HttpStatus#NOT_FOUND[] response is returned

IMPORTANT: A few things to note about the api:http.annotation.Error[] annotation. Two identical `@Error` annotations that are
global cannot be declared. Two identical `@Error` annotations that are non-global cannot be declared in the same controller.
If an `@Error` annotation with the same parameter exists as global and another as a local, the local one will take precedence.

== ExceptionHandler

Additionally you can implement a api:http.server.exceptions.ExceptionHandler[]; a generic hook for handling exceptions that occurs during the execution of an HTTP request.

Imagine your e-commerce app throws an `OutOfStockException` when a book is out of stock:

snippet::io.micronaut.docs.server.exception.OutOfStockException[tags="clazz", indent=0]

Along with `BookController`:

snippet::io.micronaut.docs.server.exception.BookController[tags="clazz", indent=0]

If you don't handle the exception the server returns a 500 (Internal Server Error) status code.

If you want to respond 200 OK with 0 (stock level) as the response body when the `OutOfStockException` is thrown, you could register a `ExceptionHandler`:

snippet::io.micronaut.docs.server.exception.OutOfStockExceptionHandler[tags="clazz", indent=0]

IMPORTANT: An `@Error` annotation capturing an exception has precedence over an implementation of `ExceptionHandler` capturing the same exception.
