Sometimes with distributed applications, bad things happen. Having a good way to handle errors is important.

== Status Handlers

The api:http.annotation.Error[] annotation supports defining either an exception class or an HTTP status. Methods decorated with the annotation are invoked as the result of other controller methods. The annotation also supports the notion of global and local, local being the default.

Local error handlers only respond to methods defined in the same controller. Global error handlers can respond to any method in any controller. A local error handler is always searched for first when resolving which handler to execute.

TIP: When defining an error handler for an exception, you can specify the exception instance as an argument to the method and omit the exception property of the annotation.

== Local Error Handling

For example, the following method handles JSON parse exceptions from Jackson for the scope of the declaring controller:

snippet::io.micronaut.docs.server.json.PersonController[tags="localError", indent=0, title="Local exception handler"]

<1> A method that explicitly handles `JsonParseException` is declared
<2> An instance of api:http.hateoas.JsonError[] is returned.
<3> A custom response is returned to handle the error

snippet::io.micronaut.docs.server.json.PersonController[tags="statusError", indent=0, title="Local status handler"]

<1> The api:http.annotation.Error[] declares which api:http.HttpStatus[] error code to handle (in this case 404)
<2> A api:http.hateoas.JsonError[] instance is returned for all 404 responses
<3> An api:http.HttpStatus#NOT_FOUND[] response is returned

== Global Error Handling

snippet::io.micronaut.docs.server.json.PersonController[tags="globalError", indent=0, title="Global error handler"]

<1> The api:http.annotation.Error[] declares the method a global error handler
<2> A api:http.hateoas.JsonError[] instance is returned for all errors
<3> An api:http.HttpStatus#INTERNAL_SERVER_ERROR[] response is returned

snippet::io.micronaut.docs.server.json.PersonController[tags="statusError", indent=0, title="Global status handler"]

<1> The api:http.annotation.Error[] declares which api:http.HttpStatus[] error code to handle (in this case 404)
<2> A api:http.hateoas.JsonError[] instance is returned for all 404 responses
<3> An api:http.HttpStatus#NOT_FOUND[] response is returned

IMPORTANT: A few things to note about the api:http.annotation.Error[] annotation. You cannot declare identical global `@Error` annotations. Identical non-global `@Error` annotations cannot be declared in the same controller. If an `@Error` annotation with the same parameter exists as global and another as local, the local one takes precedence.

== ExceptionHandler

Additionally, you can implement an api:http.server.exceptions.ExceptionHandler[], a generic hook for handling exceptions that occur during execution of an HTTP request.

Imagine your e-commerce app throws an `OutOfStockException` when a book is out of stock:

snippet::io.micronaut.docs.server.exception.OutOfStockException[tags="clazz", indent=0]

Along with `BookController`:

snippet::io.micronaut.docs.server.exception.BookController[tags="clazz", indent=0]

The server returns a 500 (Internal Server Error) status code if you don't handle the exception.

To respond with 400 Bad Request as the response when the `OutOfStockException` is thrown, you can register a `ExceptionHandler`:

snippet::io.micronaut.docs.server.exception.OutOfStockExceptionHandler[tags="clazz", indent=0]

<1> The default api:http.server.exceptions.format.JsonErrorResponseFactory[] is used to create the body of the response

IMPORTANT: An `@Error` annotation capturing an exception has precedence over an implementation of `ExceptionHandler` capturing the same exception.

== Error Formatting

By default Micronaut produces error response bodies in the link:https://github.com/blongden/vnd.error[vnd.error] format. This is accomplished through the provided api:http.server.exceptions.format.HateoasErrorResponseFactory[]. To change or customize the response bodies being created, create your own implementation of api:http.server.exceptions.format.JsonErrorResponseFactory[] and replace the default implementation.

If customization of the response other than body is desired, the exception handler that is handling the exception needs to be overridden.
