The Micronaut HTTP server supports applying filters to request/response processing in a similar (but reactive) way to Servlet filters in traditional Java applications.

Filters support the following use cases:

* Decoration of the incoming api:http.HttpRequest[]
* Modification of the outgoing api:http.HttpResponse[]
* Implementation of cross-cutting concerns such as security, tracing, etc.

For a server application, the api:http.filter.HttpServerFilter[] interface `doFilter` method can be implemented.

The `doFilter` method accepts the api:http.HttpRequest[] and an instance of api:http.filter.ServerFilterChain[].

The `ServerFilterChain` interface contains a resolved chain of filters where the final entry in the chain is the matched route. The api:http.filter.ServerFilterChain.proceed(io.micronaut.http.HttpRequest)[] method resumes processing of the request.

The `proceed(..)` method returns a Reactive Streams rs:Publisher[] that emits the response to be returned to the client. Implementors of filters can subscribe to the rs:Publisher[] and mutate the emitted api:http.MutableHttpResponse[] to modify the response prior to returning the response to the client.

To put these concepts into practice lets look at an example.

IMPORTANT: Filters execute in the event loop, so blocking operations must be offloaded to another thread pool.

== Writing a Filter

Suppose you wish to trace each request to the Micronaut "Hello World" example using some external system. This system could be a database or a distributed tracing service, and may require I/O operations.

You should not block the underlying Netty event loop in your filter; instead the filter should proceed with execution once any I/O is complete.

As an example, consider this `TraceService` that uses https://projectreactor.io[Project Reactor] to compose an I/O operation:

snippet::io.micronaut.docs.server.filters.TraceService[tags="imports,class", indent=0, title="A TraceService Example using Reactive Streams"]

<1> The reactor:Mono[] type creates logic that executes potentially blocking operations to write the trace data from the request
<2> Since this is just an example, the logic does nothing yet
<3> The `Schedulers.boundedElastic` executes the logic

You can then inject this implementation into your filter definition:

snippet::io.micronaut.docs.server.filters.TraceFilter[tags="imports,class,endclass", indent=0, title="An Example HttpServerFilter"]

<1> The api:http.annotation.Filter[] annotation defines the URI pattern(s) the filter matches
<2> The class implements the api:http.filter.HttpServerFilter[] interface
<3> The previously defined `TraceService` is injected via constructor

The final step is to write the `doFilter` implementation of the api:http.filter.HttpServerFilter[] interface.

snippet::io.micronaut.docs.server.filters.TraceFilter[tags="doFilter", indent=0, title="The doFilter implementation"]

<1> `TraceService` is invoked to trace the request
<2> If the call succeeds, the filter resumes request processing using https://projectreactor.io[Project Reactor]'s `switchMap` method, which invokes the `proceed` method of the api:http.filter.ServerFilterChain[]
<3> Finally, the https://projectreactor.io[Project Reactor]'s `doOnNext` method adds a `X-Trace-Enabled` header to the response.

The previous example demonstrates some key concepts such as executing logic in a non-blocking manner before proceeding with the request and modifying the outgoing response.

TIP: The examples use https://projectreactor.io[Project Reactor], however you can use any reactive framework that supports the Reactive streams specifications

The api:http.annotation.Filter[] annotation uses api:core.util.AntPathMatcher[] for path matching. The mapping matches URLs using the following rules:

* ? matches one character
* * matches zero or more characters
* ** matches zero or more subdirectories in a path

.@Fitler Annotation Path Matching Examples
|===
|Pattern|Example Matched Paths

|`/**`
|any path

|`customer/j?y`
|customer/joy, customer/jay

|`customer/*/id`
|customer/adam/id, com/amy/id

|`customer/**`
|customer/adam, customer/adam/id, customer/adam/name

|`customer/**/*.html`
|customer/index.html, customer/adam/profile.html, customer/adam/job/description.html

== Error States

The publisher returned from `chain.proceed` should never emit an error. In the cases where an upstream filter emitted an error or the route itself threw an exception, the error response should be emitted instead of the exception. In some cases it may be desirable to know the cause of the error response and for this purpose an attribute exists on the response if it was created as a result of an exception being emitted or thrown. The original cause is stored as the attribute api:http.HttpAttributes#EXCEPTION[].
