Since Micronaut framework 2.x, Micronaut Netty-based HTTP server can be configured to support HTTP/2.

==== Configuring the Server for HTTP/2

The first step is to set the supported HTTP version in the server configuration:

.Enabling HTTP/2 Support
[configuration]
----
micronaut:
  server:
    http-version: 2.0
----

With this configuration, the Micronaut framework enables support for the `h2c` protocol (see https://httpwg.org/specs/rfc7540.html#discover-http[HTTP/2 over cleartext]) which is fine for development.

Since browsers don't support `h2c` and in general https://httpwg.org/specs/rfc7540.html#discover-https[HTTP/2 over TLS] (the `h2` protocol), it is recommended for production that you enable <<https, HTTPS support>>. For development this can be done with:

.Enabling `h2` Protocol Support
[configuration]
----
micronaut:
  server:
    http-version: 2.0
    ssl:
      enabled: true
      buildSelfSigned: true
----

For production, see the <<https, configuring HTTPS>> section of the documentation.

Note that if your deployment environment uses JDK 8, or for improved support for OpenSSL, define the following dependencies on Netty Tomcat Native:

dependency:io.netty:netty-tcnative:2.0.58.Final[scope="runtimeOnly"]

dependency:io.netty:netty-tcnative-boringssl-static:2.0.58.Final[scope="runtimeOnly"]

In addition to a dependency on the appropriate native library for your architecture. For example:

.Configuring Tomcat Native
[source,groovy]
----
runtimeOnly "io.netty:netty-tcnative-boringssl-static:2.0.58.Final:${Os.isFamily(Os.FAMILY_MAC) ? (Os.isArch("aarch64") ? "osx-aarch_64" : "osx-x86_64") : 'linux-x86_64'}"
----

See the documentation on https://netty.io/wiki/forked-tomcat-native.html[Tomcat Native] for more information.

==== HTTP/2 Server Push Support

Support for server push has been added in Micronaut framework 3.2. Server push allows for a single request to trigger multiple responses. This is most often used in the case of browser based resources. The goal is to improve latency for the client, because they do not have to request that resource manually anymore, and can save a round trip.

A new interface, api:http.PushCapableHttpRequest[], has been created to support the feature. Simply add a api:http.PushCapableHttpRequest[] parameter to a controller method and use its API to trigger additional requests.

NOTE: api:http.PushCapableHttpRequest[] extends api:http.HttpRequest[] so its not necessary to have both as arguments in a controller method.

Before triggering additional requests, the `isServerPushSupported()` method should be called to ensure the feature is available. Once it's known the feature is supported, use the `serverPush(HttpRequest)` method to trigger additional requests. For example: `request.serverPush(HttpRequest.GET("/static/style.css"))`).
