:jackson-annotations: https://fasterxml.github.io/jackson-annotations/javadoc/2.9/
:jackson-databind: https://fasterxml.github.io/jackson-databind/javadoc/2.9/
:jackson-core: https://fasterxml.github.io/jackson-core/javadoc/2.9/

The most common data interchange format nowadays is JSON.

By default, the api:http.annotation.Controller[] annotation specifies that the controllers in Micronaut framework consume and produce JSON by default.

Since Micronaut Framework 4.0, users must choose how they want to serialize (Jackson Databind or Micronaut Serialization). Both approaches allow the usage of https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html#jacksonAnnotations[Jackson Annotations].

With either approach, the Micronaut framework reads incoming JSON in a non-blocking manner.

== Serialize using Micronaut Serialization

https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html#quickStart[Micronaut Serialization] offers reflection-free serialization using build-time <<introspection, Bean Introspections>>. It supports alternative formats such as https://micronaut-projects.github.io/micronaut-serialization/latest/guide/index.html#jsonpQuick[JSON-P or JSON-B]. You need to add the following dependencies:

dependency:micronaut-serde-processor[groupId=io.micronaut.serde,scope=annotationProcessor]
dependency:micronaut-serde-jackson[groupId=io.micronaut.serde]

== Serialization using Jackson Databind

To serialize using https://github.com/FasterXML/jackson[Jackson] Databind include the following dependency:

dependency:micronaut-jackson-databind[]

== JsonMapper

You may be used to work with https://fasterxml.github.io/jackson-databind/javadoc/2.7/com/fasterxml/jackson/databind/ObjectMapper.html[Jackson's `ObjectMapper`]. However, we don't recommend using Jackson's `ObjectMapper` directly; instead you should use api:json.JsonMapper[], an API almost identical to Jackson's `ObjectMapper`. Moreover, both <<jsonBinding, Micronaut Serialization and Micronaut Jackson Databind>> implement api:json.JsonMapper[].

You can inject a bean of type `JsonMapper` or manually instantiate one via `JsonMapper.createDefault()`.

== Binding using Reactive Frameworks

From a developer perspective however, you can generally just work with Plain Old Java Objects (POJOs) and can optionally use a Reactive framework such as https://github.com/ReactiveX/RxJava[RxJava] or https://projectreactor.io[Project Reactor]. The following is an example of a controller that reads and saves an incoming POJO in a non-blocking way from JSON:

snippet::io.micronaut.docs.server.json.PersonController[tags="class,single,endclass", indent=0, title="Using Reactive Streams to Read the JSON"]

<1> The method receives a `Publisher` which emits the POJO once the JSON has been read
<2> The `map` method stores the instance in a `Map`
<3> An api:http.HttpResponse[] is returned

Using cURL from the command line, you can POST JSON to the `/people` URI:

.Using cURL to Post JSON
----
$ curl -X POST localhost:8080/people -d '{"firstName":"Fred","lastName":"Flintstone","age":45}'
----

== Binding Using CompletableFuture

The same method as the previous example can also be written with the link:{jdkapi}/java.base/java/util/concurrent/CompletableFuture.html[CompletableFuture] API instead:

snippet::io.micronaut.docs.server.json.PersonController[tags="class,future,endclass", indent=0, title="Using CompletableFuture to Read the JSON"]

The above example uses the `thenApply` method to achieve the same as the previous example.

== Binding using POJOs

Note however you can just as easily write:

snippet::io.micronaut.docs.server.json.PersonController[tags="class,regular,endclass", indent=0, title="Binding JSON POJOs"]

The Micronaut framework only executes your method once the data has been read in a non-blocking manner.

TIP: You can customize the output in various ways, such as using https://github.com/FasterXML/jackson-annotations/wiki/Jackson-Annotations[Jackson annotations].

== Jackson Configuration

If you use <<jsonBinding, `micronaut-jackson-databind`>>, the Jackson's `ObjectMapper` can be configured through configuration with the api:io.micronaut.jackson.JacksonConfiguration[] class.

All Jackson configuration keys start with `jackson`.

|=======
| dateFormat | String | The date format
| locale     | String | Uses link:{jdkapi}/java.base/java/util/Locale.html#forLanguageTag-java.lang.String-[Locale.forLanguageTag]. Example: `en-US`
| timeZone   | String |Uses link:{jdkapi}/java.base/java/util/TimeZone.html#getTimeZone-java.lang.String-[TimeZone.getTimeZone]. Example: `PST`
| serializationInclusion | String | One of link:{jackson-annotations}com/fasterxml/jackson/annotation/JsonInclude.Include.html[JsonInclude.Include]. Example: `ALWAYS`
| propertyNamingStrategy | String | Name of an instance of link:{jackson-databind}com/fasterxml/jackson/databind/PropertyNamingStrategy.html[PropertyNamingStrategy]. Example: `SNAKE_CASE`
| defaultTyping          | String | The global defaultTyping for polymorphic type handling from enum link:{jackson-databind}com/fasterxml/jackson/databind/ObjectMapper.DefaultTyping.html[ObjectMapper.DefaultTyping]. Example: `NON_FINAL`
|=======

Example:

[configuration]
----
jackson:
  serializationInclusion: ALWAYS
----

=== Features

If you use <<jsonBinding, `micronaut-jackson-databind`>>, all Jackson's features can be configured with their name as the key and a boolean to indicate enabled or disabled.

|======
|serialization | Map | link:{jackson-databind}com/fasterxml/jackson/databind/SerializationFeature.html[SerializationFeature]
|deserialization | Map | link:{jackson-databind}com/fasterxml/jackson/databind/DeserializationFeature.html[DeserializationFeature]
|mapper | Map | link:{jackson-databind}com/fasterxml/jackson/databind/MapperFeature.html[MapperFeature]
|parser | Map | link:{jackson-core}com/fasterxml/jackson/core/JsonParser.Feature.html[JsonParser.Feature]
|generator | Map | link:{jackson-core}com/fasterxml/jackson/core/JsonGenerator.Feature.html[JsonGenerator.Feature]
|factory | Map | link:{jackson-core}com/fasterxml/jackson/core/JsonFactory.Feature.html[JsonFactory.Feature]
|======

Example:

[configuration]
----
jackson:
  serialization:
    indentOutput: true
    writeDatesAsTimestamps: false
  deserialization:
    useBigIntegerForInts: true
    failOnUnknownProperties: false
----

=== Further customising `JsonFactory`

If you use <<jsonBinding, `micronaut-jackson-databind`>>, there may be situations where you wish to customise the `JsonFactory` used by the `ObjectMapper` beyond the configuration of features (for example to allow custom character escaping).
This can be achieved by providing your own `JsonFactory` bean, or by providing a `BeanCreatedEventListener<JsonFactory>` which configures the default bean on startup.

=== Support for `@JsonView`

If you use <<jsonBinding, `micronaut-jackson-databind`>>, you can use the `@JsonView` annotation on controller methods if you set `jackson.json-view.enabled` to `true` in your configuration file (e.g `application.yml`).

Jackson's `@JsonView` annotation lets you control which properties are exposed on a per-response basis. See https://www.baeldung.com/jackson-json-view-annotation[Jackson JSON Views] for more information.

=== Beans

If you use <<jsonBinding, `micronaut-jackson-databind`>>, in addition to configuration, beans can be registered to customize Jackson. All beans that extend any of the following classes are registered with the object mapper:

* link:{jackson-databind}com/fasterxml/jackson/databind/Module.html[Module]
* link:{jackson-databind}com/fasterxml/jackson/databind/JsonDeserializer.html[JsonDeserializer]
* link:{jackson-databind}com/fasterxml/jackson/databind/JsonSerializer.html[JsonSerializer]
* link:{jackson-databind}com/fasterxml/jackson/databind/KeyDeserializer.html[KeyDeserializer]
* link:{jackson-databind}com/fasterxml/jackson/databind/deser/BeanDeserializerModifier.html[BeanDeserializerModifier]
* link:{jackson-databind}com/fasterxml/jackson/databind/ser/BeanSerializerModifier.html[BeanSerializerModifier]

=== Service Loader

Any modules registered via the service loader are also added to the default object mapper.

=== Number Precision

During JSON parsing, the framework may convert any incoming data to an intermediate object model. By default, this model uses `BigInteger`, `long` and `double` for numeric values. This means some information that could be represented by `BigDecimal` may be lost. For example, numbers with many decimal places that cannot be represented by `double` may be truncated, even if the target type for deserialization uses `BigDecimal`. Metadata on the number of trailing zeroes (`BigDecimal.precision()`), e.g. the difference between `0.12` and `0.120`, is also discarded.

If you need full accuracy for number types, use the following configuration:

[configuration]
----
jackson:
  deserialization:
    useBigIntegerForInts: true
    useBigDecimalForFloats: true
----

== Text Binding

Micronaut Framework supports "text/plain" Content-Type as a way of binding to plain text. However, `text/plain` messages are more restrictive about allowed types. To return plain text responses for answers other than strings, manually call the object `toString()` method.

snippet::io.micronaut.docs.http.server.response.textplain.TextPlainController[tags="class", indent=0, title="Text Content-Type example"]

<1> The Controller endpoint specifies `text/plain` as the Content-Type.
<2> The endpoint returns type `String`, and the implementation converts the data to a string explicitly using the `toString()` method.

For Micronaut Framework 3.x any type was allowed. For writing, the object was converted using `toString`, and for reading, the object was converted using `ConversionService`. This is not permitted anymore for Micronaut Framework 4.x, except for some restricted types. The recommended approach is to move to `application/json` as the content type. `toString` is not a stable serialization format, JSON is more reliable. Alternatively, set the `micronaut.http.legacy-text-conversion` configuration option to `true` to restore the old – but not recommended – behavior.

