Micronaut includes experimental support for producing OpenAPI (Swagger) YAML at compilation time. Micronaut will at compile time produce a Swagger 2.x compliant YAML file just based on the regular Micronaut annotations and the javadoc comments within your code.

You can customize the generated Swagger using the standard https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations[Swagger Annotations].


=== Getting Started with Swagger

To enable this support you should add the following dependencies to your build configuration:

.Adding the Swagger Dependencies
[source,groovy]
----
annotationProcessor "io.micronaut.configuration:micronaut-openapi" // <1>
compile "io.swagger.core.v3:swagger-annotations" // <2>
----

<1> The `openapi` configuration gets added into the annotation processor scope
<2> The https://github.com/swagger-api/swagger-core/wiki/Swagger-2.X---Annotations[Swagger Annotations] are added to the compile classpath

NOTE: For Kotlin the `openapi` dependency should be in the `kapt` scope and for Groovy in the `compileOnly` scope.

TIP: You can use the `swagger-*` feature when creating your app to setup Swagger / OpenAPI correctly: `mn create-app my-app --features swagger-java`

Once dependencies have been configured a minimum requirement is to add a `@OpenAPIDefinition` annotation to your `Application` class:

.Example @OpenAPIDefinition usage
[source,java]
----
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.info.*;

@OpenAPIDefinition(
    info = @Info(
            title = "Hello World",
            version = "0.0",
            description = "My API",
            license = @License(name = "Apache 2.0", url = "http://foo.bar"),
            contact = @Contact(url = "http://gigantic-server.com", name = "Fred", email = "Fred@gigagantic-server.com")
    )
)
public class Application {

    public static void main(String[] args) {
        Micronaut.run(Application.class);
    }
}
----

With that in place you compile your project and a Swagger YAML file will be generated to the `META-INF/swagger` directory of your project's class output. For example the above configuration for Java will be generated to `build/classes/java/main/META-INF/swagger/hello-world-0.0.yml`.


The previously defined annotations will produce YAML like the following:

.Generated Swagger YAML
[source,yaml]
----
openapi: 3.0.1
info:
  title: the title
  description: My API
  contact:
    name: Fred
    url: http://gigantic-server.com
    email: Fred@gigagantic-server.com
  license:
    name: Apache 2.0
    url: http://foo.bar
  version: "0.0"
----

=== Exposing Swagger Output

If you wish to expose the generated Swagger output from your running application you can simply add the necessary static resource configuration. For example:

.Exposing Swagger YAML
[source,yaml]
----
micronaut:
    router:
        static-resources:
            swagger:
                paths: classpath:META-INF/swagger
                mapping: /swagger/**
----

With the above configuration in place when you run your application you can access your Swagger documentation at `http://localhost:8080/swagger/the-title-0.0.yml`.

=== Controllers and Swagger Annotations

By default Micronaut will automatically at compile time build out the Swagger YAML definition from your defined controllers and methods. For example given the following class:

.Hello World Example
[source,java]
----
@Controller("/")
@Validated
public class HelloController {

    /**
     * @param name The person's name
     * @return The greeting
     */
    @Get(uri="/hello/{name}", produces=MediaType.TEXT_PLAIN)
    public Single<String> hello(@NotBlank String name) {
        return Single.just("Hello " + name + "!");
    }
}
----

The resulting output will be:

.Example Generated Swagger Output
[source,yaml]
----
paths:
  /hello/{name}:
    get:
      description: ""
      operationId: hello
      parameters:
      - name: name
        in: path
        description: The person's name
        required: true
        explode: false
        schema:
          type: string
      responses:
        default:
          description: The greeting
          content:
            text/plain:
              schema:
                type: string
----

Notice how the javadoc comments are used to fill out the description of the API. If this is not desirable then you can take full control by augmenting your definition with Swagger annotations:

.Using Swagger Annotations
[source,java]
----
import io.swagger.v3.oas.annotations.*;
import io.swagger.v3.oas.annotations.parameters.*;
import io.swagger.v3.oas.annotations.responses.*;
import io.swagger.v3.oas.annotations.security.*;
import io.swagger.v3.oas.annotations.tags.*;
import io.swagger.v3.oas.annotations.media.*;
import io.swagger.v3.oas.annotations.enums.*;

@Controller("/")
@Validated
public class HelloController {

    /**
     * @param name The person's name
     * @return The greeting
     */
    @Get(uri="/hello/{name}", produces=MediaType.TEXT_PLAIN)
    @Operation(summary = "Greets a person",
               description = "A friendly greeting is returned",
    )
    @ApiResponse(
            content = @Content(mediaType = "text/plain",
            schema = @Schema(type="string"))
    )
    @ApiResponse(responseCode = "400", description = "Invalid Name Supplied")
    @ApiResponse(responseCode = "404", description = "Person not found")
    @Tag(name = "greeting")
    public Single<String> hello(@Parameter(description="The name of the person") @NotBlank String name) {
        return Single.just("Hello " + name + "!");
    }
}
----

=== Schemas and POJOs

If you return types are not simple strings and primitive types then Micronaut will attempt to generate a Schema definition. You can customize the
generation of the Schema by using the `@Schema` annotation on your POJO. For example:

.Using the @Schema Annotation
[source,java]
----
@Schema(name="MyPet", description="Pet description") // <1>
class Pet {
    private PetType type;
    private int age;
    private String name;

    public void setAge(int a) {
        age = a;
    }

    /**
     * The age
     */
    @Schema(description="Pet age", maximum="20") // <2>
    public int getAge() {
        return age;
    }

    public void setName(String n) {
        name = n;
    }

    @Schema(description="Pet name", maxLength=20)
    public String getName() {
        return name;
    }

    public void setType(PetType t) {
        type = t;
    }

    public PetType getType() {
        return type;
    }
}

enum PetType {
    DOG, CAT;
}
----

<1> The `@Schema` annotation is used to customize the name of the schema
<2> Properties can be customized too.

=== Schemas and Generics

If a method return type includes generics then these will included when calculating the schema name. For example the following:

.Swagger returns types and generics
[source,java]
----
class Response<T> {
    private T r;
    public T getResult() {
        return r;
    };
}

@Controller("/")
class MyController {

    @Put("/")
    public Response<Pet> updatePet(Pet pet) {
        ...
    }
}
----

Will result in a schema called `#/components/schemas/Response<Pet>` being generated. If you wish to alter the name of the schema you can do so with the `@Schema` annotation:

.Changing the name of response schema
[source,java]
----
@Put("/")
@Schema(name="ResponseOfPet")
public Response<Pet> updatePet(Pet pet) {
    ...
}
----

In the above case the generated schema will be named `#/components/schemas/ResponseOfPet`.
