The link:{api}/io/micronaut/http/annotation/Controller.html[@Controller] annotation used in the previous section is one of link:{api}/io/micronaut/http/annotation/package-summary.html[several annotations] that allow you to control the construction of HTTP routes.

== URI Paths

In the previous example a value of `/hello` was specified as the path to the controller. If no value is specified to the `@Controller` action then the URI is formulated from the class name.

The following table summarizes values for the `@Controller` annotation and the calculated base paths:


|===
|Class Name | Annotation |Path

|`HelloController`
|`@Controller`
|`/hello`

|`HelloWorldController`
|`@Controller`
|`/hello-world`

|`HelloController`
|`@Controller("/somepath")`
|`/somepath`

|`HelloController`
|`@Controller("/")`
|`/`
|===

The value of the `@Controller` annotation is a https://tools.ietf.org/html/rfc6570[RFC-6570 URI template] you can therefore embed URI variables within the path using the syntax defined by the URI template specification.

NOTE: Many other frameworks, including Spring, implement the URI template specification

The actual implementation is handled by the api:http.uri.UriMatchTemplate[] class, which extends api:http.uri.UriTemplate[].

You can use this class explicitly within your application to build URIs. For example:

.Using a UriTemplate
[source,java]
----
include::{testsuite}/server/uris/UriTemplateTest.java[tags=match, indent=0]
----

<1> The `match` method can be used to match a path
<2> The `expand` method can be used to expand a template into a URI.

If you have a requirement to build paths to include in your responses you can use api:http.uri.UriTemplate[] to do so.

== URI Path Variables

URI variables can be referenced via method arguments. For example:

.URI Variables Example
[source,java]
----
include::{testsuite}/server/routes/IssuesController.java[tags=imports, indent=0]

include::{testsuite}/server/routes/IssuesController.java[tags=class, indent=0]
----

<1> The `@Controller` annotation is specified without an argument resulting in a base URI of `/issues`
<2> The link:{api}/io/micronaut/http/annotation/Get.html[Get] annotation is used to map the method to an HTTP link:{api}/io/micronaut/http/HttpMethod.html#GET[GET] with a URI variable embedded in the URI called `number`
<3> The value of the URI variable is referenced in the implementation

Micronaut will map the URI `/issues/{number}` for the above controller. We can assert this is the case by writing a unit test, this time in Java and JUnit:

.Testing URI Variables
[source,java]
----
include::{testsuite}/server/routes/IssuesControllerTest.java[tags=imports, indent=0]

public class IssuesControllerTest {
include::{testsuite}/server/routes/IssuesControllerTest.java[tags=setup, indent=4]

include::{testsuite}/server/routes/IssuesControllerTest.java[tags=test, indent=4]
}
----

<1> For JUnit you can write methods to start and stop the server for the scope of the test
<2> The tests sends a request to the URI `/issues/12`
<3> And then asserts the response is "Issue # 12"

If you invoke the previous endpoint without the required URI variable or with an invalid type, Micronaut responds with the appropriate HTTP failure codes as illustrated in the following Spock tests that use the <<httpClient,HTTP client>>.

.Testing for Response Errors
[source,java]
----
include::{testsuite}/server/routes/IssuesControllerSpec.groovy[indent=0,tags=badrequest]

include::{testsuite}/server/routes/IssuesControllerSpec.groovy[indent=0,tags=notfound]
----

Note that the URI template in the previous example requires that the `number` variable is specified. You can specify optional URI templates with the syntax: `/issues{/number}` and by annotating the `number` parameter with `@Nullable`.

The following table provides some examples of URI templates and what they match:

.URI Template Matching
|===
|Template |Description|Matching URI

|`/books/{id}`
| Simple match
| `/books/1`

|`/books/{id:2}`
| A variable of 2 characters max
| `/books/10`

|`/books{/id}`
| An optional URI variable
| `/books/10` or `/books`

| `/book{/id:[a-zA-Z]+}`
| An optional URI variable with regex
| `/books/foo`

| `/books{?max,offset}`
| Optional query parameters
| `/books?max=10&offset=10`

| `/books{/path:.*}{.ext}`
| Regex path match with extension
| `/books/foo/bar.xml`

|===

== URI Reserved Character Matching

By default URI variables as defined by the https://tools.ietf.org/html/rfc6570[RFC-6570 URI template] spec cannot include reserved characters such as `/`, `?` etc.

If you wish to match or expand entire paths then this can be problematic. As per https://tools.ietf.org/html/rfc6570#section-3.2.3[section 3.2.3 of the specification], you can use reserved expansion or matching using the `+` operator.

For example the URI `/books/{+path}` will match both `/books/foo` and `/books/foo/bar` since the `+` indicates that the variable `path` should include reserved characters (in this case `/`).

== Routing Annotations

The previous example used the link:{api}/io/micronaut/http/annotation/Get.html[@Get] annotation to add method that accepted HTTP link:{api}/io/micronaut/http/HttpMethod.html#GET[GET] requests. The following tables summarizes the available annotations and how they map to the different HTTP methods:


.HTTP Routing Annotations
|===
|Annotation |HTTP Method

|link:{api}/io/micronaut/http/annotation/Delete.html[@Delete]
|link:{api}/io/micronaut/http/HttpMethod.html#DELETE[DELETE]

|link:{api}/io/micronaut/http/annotation/Get.html[@Get]
|link:{api}/io/micronaut/http/HttpMethod.html#GET[GET]

|link:{api}/io/micronaut/http/annotation/Head.html[@Head]
|link:{api}/io/micronaut/http/HttpMethod.html#HEAD[HEAD]

|link:{api}/io/micronaut/http/annotation/Options.html[@Options]
|link:{api}/io/micronaut/http/HttpMethod.html#OPTIONS[OPTIONS]

|link:{api}/io/micronaut/http/annotation/Patch.html[@Patch]
|link:{api}/io/micronaut/http/HttpMethod.html#PATCH[PATCH]

|link:{api}/io/micronaut/http/annotation/Put.html[@Put]
|link:{api}/io/micronaut/http/HttpMethod.html#PUT[PUT]

|link:{api}/io/micronaut/http/annotation/Post.html[@Post]
|link:{api}/io/micronaut/http/HttpMethod.html#POST[POST]

|link:{api}/io/micronaut/http/annotation/Trace.html[@Trace]
|link:{api}/io/micronaut/http/HttpMethod.html#TRACE[TRACE]

|===

If no URI path is specified to any of the annotations then the method name is used as the URI. In other words both of the following methods are essentially equivalent and map to the `/hello` URI:

[source,java]
----
@Get("/hello")
String hello() {
    return "Hello World";
}

@Get
String hello() {
    return "Hello World";
}
----

== Building Routes Programmatically

If you prefer to not use annotations and declare all of your routes in code then never fear, Micronaut has a flexible link:{api}/io/micronaut/web/router/RouteBuilder.html[RouteBuilder] API that makes it a breeze to define routes programmatically.

To start off with you should subclass link:{api}/io/micronaut/web/router/DefaultRouteBuilder.html[DefaultRouteBuilder] and then simply inject the controller you wish to route to into the method and define your routes:

.RouteBuilder Example
[source,java]
----
include::{testsuite}/server/routes/MyRoutes.java[tags=imports, indent=0]

include::{testsuite}/server/routes/MyRoutes.java[tags=class, indent=0]
----

<1> Route definitions should subclass link:{api}/io/micronaut/web/router/DefaultRouteBuilder.html[DefaultRouteBuilder]
<2> Use `@Inject` to inject a method with the controllers you want to route to
<3> Use methods such as link:{api}/io/micronaut/web/router/RouteBuilder.html#GET-java.lang.String-java.lang.Class-java.lang.String-java.lang.Class...-[GET] to route to controller methods

TIP: Unfortunately due to type erasure a Java method lambda reference cannot be used with the API. For Groovy there is a `GroovyRouteBuilder` class which can be subclassed that allows passing Groovy method references.
