The HTTP server features a number of configuration options you may wish to tweak. They are defined in the api:http.server.netty.configuration.NettyHttpServerConfiguration[] configuration class, which extends api:http.server.HttpServerConfiguration[].

The following example shows how to tweak configuration options for the server via `application.yml`:

.Configuring HTTP server settings
[source,yaml]
----
micronaut:
    server:
        maxRequestSize: 1MB
        host: localhost # <1>
        netty:
           maxHeaderSize: 500KB # <2>
           worker:
              threads: 8 # <3>
           childOptions:
              autoRead: true # <4>
----
<1> By default Micronaut will bind to all the network interfaces. Use `localhost` to bind only to loopback network interface
<2> Maximum size for headers
<3> Number of netty worker threads
<4> Auto read request body

include::{includedir}configurationProperties/io.micronaut.http.server.netty.configuration.NettyHttpServerConfiguration.adoc[]

The `use-native-transport` option also requires the relevant netty dependency to take effect. The native transports add features specific to a particular platform, generate less garbage, and generally improve performance when compared to the NIO based transport.

For macOS:

dependency:netty-transport-native-kqueue[groupId="io.netty",scope="runtime",classifier="osx-x86_64"]

For Linux:

dependency:netty-transport-native-epoll[groupId="io.netty",scope="runtime",classifier="linux-x86_64"]
