By default Micronaut is a stateless HTTP server, however depending on your application requirements you may need the notion of HTTP sessions.

Micronaut includes a `session` module inspired by https://projects.spring.io/spring-session/[Spring Session] that enables this which currently has two implementations:

* In-Memory sessions - which you should combine with an a sticky session proxy if you plan to run multiple instances.
* Redis sessions - In this case https://redis.io[Redis] stores sessions, and non-blocking I/O is used to read/write sessions to Redis.

== Enabling Sessions

To enable support for in-memory sessions you just need the `session` dependency:

dependency:micronaut-session[groupId=io.micronaut.session]

=== Redis Sessions

To store https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] instances in Redis, use the https://micronaut-projects.github.io/micronaut-redis/latest/guide/#sessions[Micronaut Redis] module which includes detailed instructions.

To quickly get up and running with Redis sessions you must also have the `redis-lettuce` dependency in your build:

.build.gradle
[source,groovy]
----
compile "io.micronaut-session:micronaut-session"
compile "io.micronaut.redis:micronaut-redis-lettuce"
----

And enable Redis sessions via configuration in `application.yml`:

.Enabling Redis Sessions
[source,yaml]
----
redis:
  uri: redis://localhost:6379
micronaut:
  session:
    http:
      redis:
        enabled: true
----

== Configuring Session Resolution

https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] resolution can be configured with https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/http/HttpSessionConfiguration.html[HttpSessionConfiguration].

By default, sessions are resolved using https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/http/HttpSessionFilter.html[HttpSessionFilter] that looks for session identifiers via either an HTTP header (using the `Authorization-Info` or `X-Auth-Token` headers) or via a Cookie named `SESSION`.

You can disable either header resolution or cookie resolution via configuration in `application.yml`:

.Disabling Cookie Resolution
[source,yaml]
----
micronaut:
  session:
    http:
      cookie: false
      header: true
----

The above configuration enables header resolution, but disables cookie resolution. You can also configure header and cookie names.

== Working with Sessions

A https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] can be retrieved with a parameter of type https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] in a controller method. For example consider the following controller:

snippet::io.micronaut.docs.session.ShoppingController[tags="imports,class,add,endclass", indent=0]

<1> `ShoppingController` declares a https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] attribute named `cart`
<2> The https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] is declared as a method parameter
<3> The `cart` attribute is retrieved
<4> Otherwise a new `Cart` instance is created and stored in the session

Note that because the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] is declared as a required parameter, to execute the controller action a https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] will be created and saved to the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/SessionStore.html[SessionStore].

If you don't want to create unnecessary sessions, declare the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] as `@Nullable` in which case a session will not be created and saved unnecessarily. For example:

snippet::io.micronaut.docs.session.ShoppingController[tags="clear", indent=0,title="Using @Nullable with Sessions"]

The above method only injects a new https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] if one already exists.

== Session Clients

If the client is a web browser, sessions should work if cookies are enabled. However, for programmatic HTTP clients you need to propagate the session ID between HTTP calls.

For example, when invoking the `viewCart` method of the `StoreController` in the previous example, the HTTP client receives by default a `AUTHORIZATION_INFO` header. The following example, using a Spock test, demonstrates this:

.Retrieving the AUTHORIZATION_INFO header
snippet::io.micronaut.docs.session.ShoppingControllerSpec[tags="view", indent=0]

<1> A request is made to `/shopping/cart`
<2> The `AUTHORIZATION_INFO` header is present in the response

You can then pass this `AUTHORIZATION_INFO` in subsequent requests to reuse the existing https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session]:

.Sending the AUTHORIZATION_INFO header
snippet::io.micronaut.docs.session.ShoppingControllerSpec[tags="add", indent=0]

<1> The `AUTHORIZATION_INFO` is retrieved from the response
<2> And then sent as a header in the subsequent request

== Using @SessionValue

Rather than explicitly injecting the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] into a controller method, you can instead use https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/annotation/SessionValue.html[@SessionValue]. For example:

snippet::io.micronaut.docs.session.ShoppingController[tags="view", indent=0,title="Using @SessionValue"]

<1> https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/annotation/SessionValue.html[@SessionValue] is declared on the method resulting in the return value being stored in the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session]. Note that you must specify the attribute name when used on a return value
<2> https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/annotation/SessionValue.html[@SessionValue] is used on a `@Nullable` parameter which results in looking up the value from the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] in a non-blocking way and supplying it if present. In the case a value is not specified to https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/annotation/SessionValue.html[@SessionValue] resulting in the parameter name being used to lookup the attribute.

== Session Events

You can register api:context.event.ApplicationEventListener[] beans to listen for https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] related events located in the https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/event/package-summary.html[session.event] package.

The following table summarizes the events:

.Session Events
|===
|Type|Description

|https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/event/SessionCreatedEvent.html[SessionCreatedEvent]
|Fired when a https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] is created

|https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/event/SessionDeletedEvent.html[SessionDeletedEvent]
|Fired when a https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] is deleted

|https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/event/SessionExpiredEvent.html[SessionExpiredEvent]
|Fired when a https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/Session.html[Session] expires

|https://micronaut-projects.github.io/micronaut-session/snapshot/api/io/micronaut/session/event/SessionDestroyedEvent.html[SessionDestroyedEvent]
|Parent of both `SessionDeletedEvent` and `SessionExpiredEvent`

|===
