Static resource resolution is disabled by default.

The following configuration options are available through link:{api}/io/micronaut/web/router/resource/StaticResourceConfiguration.html[StaticResourceConfiguration]:
|=======
|enabled |boolean |Whether static resources will be resolved at all
|mapping |String |The path resources should be served from. Uses ant path matching. Options might be `/\****` or `/static/****`
|paths |List<String> |A list of paths either starting with `classpath:` or `file:`. You can serve files from anywhere on disk or the classpath. For example to serve static resources from `src/main/resources/public`, you would use `classpath:public` as the path.
|=======

Here is what an example YAML configuration might look like (note that the `router` declaration must be at the top-level of the file and not nested under any other items):

[source,yaml]
----
micronaut:
    router:
        static:
            resources:
                enabled: true
                mapping: /static/**
                paths: classpath:public
----

TIP: `index.html` will be resolved by default, __but only in the top level directory__. In the above example a request to `/static` will attempt to retrieve `src/main/resources/public/index.html`. Requests to `/static/foo` will *not* result in `src/main/resources/public/foo/index.html` being resolved.
