Micronaut supports the sending of files to the client in a couple of easy ways.

== Sending File Objects

It is possible to simply return a jdk:java.io.File[] object from your controller method and the data will be returned to the client.

For files that should be downloaded (i.e. using the `Content-Disposition` header) you should instead construct an api:http.server.types.files.AttachedFile[] with the file object and the name you would like to be used. For example:

.Sending an AttachedFile
[source,java]
----
@Get
public AttachedFile download() {
    File file = ...
    return new AttachedFile(file, "myfile.txt");
}
----

== Sending an InputStream

For cases where a reference to a `File` object is not possible (for example resources contained within JAR files), Micronaut supports transferring of input streams. To return a stream of data from the controller method, construct a api:http.server.types.files.StreamedFile[].

TIP: The constructor for `StreamedFile` also accepts a `java.net.URL` for your convenience.

.Sending a StreamedFile
[source,java]
----
@Get
public StreamedFile download() {
    InputStream inputStream = ...
    return new StreamedFile(inputStream, "download.txt")
}
----

NOTE: The `Content-Type` header of file responses will be calculated based on the name of the file.

The server supports returning `304` (Not Modified) responses if the files being transferred have not changed and the request contains the appropriate header. In addition, if the client accepts encoded responses, Micronaut will encode the file if it is deemed appropriate. Encoding will happen if the file is text based and greater than 1 kilobyte.