Handling of file uploads has special treatment in Micronaut. Support is provided for both streaming of data through non-blocking file uploads, either as streaming uploads or completed uploads.

== Streaming File Uploads

To receive a file as a non-blocking file transfer, you can use the api:http.multipart.StreamingFileUpload[] interface:

.Using the Streaming File Upload Interface
[source,java]
----
include::{testsuite}/server/upload/UploadController.java[tags=imports, indent=0]

include::{testsuite}/server/upload/UploadController.java[tags=class, indent=0]

include::{testsuite}/server/upload/UploadController.java[tags=upload, indent=4]

}
----

<1> The method is set to consume api:http.MediaType#MULTIPART_FORM_DATA[]
<2> The method parameters match form attribute names. In this case the `file` will match for example an `<input type="file" name="file">`
<3> The api:http.multipart.StreamingFileUpload.transferTo(java.lang.String)[] method is used to transfer the file to the server. The method returns a rs:Publisher[]
<4> The returned rx:Single[] subscribes to the rs:Publisher[] and outputs a response once the upload is complete, without blocking.

== Completed File Uploads

To receive complete file uploads, so that the route is resolved only after the entire file is available, you can use the api:http.server.netty.multipart.CompletedFileUpload[] class:

[source,java]
----
include::{testsuite}/server/upload/UploadController.java[tags=completedImports, indent=0]

include::{testsuite}/server/upload/UploadController.java[tags=class, indent=0]

include::{testsuite}/server/upload/UploadController.java[tags=completedUpload, indent=4]

}
----

<1> The method is set to consume api:http.MediaType#MULTIPART_FORM_DATA[]
<2> The method parameters match form attribute names. In this case the `file` will match for example an `<input type="file" name="file">`
<3> The `CompletedFileUpload` instance gives access to metadata about the upload (such as `filename` and `size`), as well as access to the file's contents as an `InputStream` or byte array.