Handling of file uploads has special treatment in Micronaut. Support is provided for streaming of uploads in a non-blocking manner through streaming uploads or completed uploads.

To receive data from a multipart request, set the `consumes` argument of the method annotation to api:http.MediaType#MULTIPART_FORM_DATA[]. For example:

[source,java]
----
@Post(consumes = MediaType.MULTIPART_FORM_DATA)
HttpResponse upload( ... )
----

== Route Arguments

Method argument types determine how files are received. Data can be received a chunk at a time or when an upload is completed.

TIP: If the route argument name cannot or should not match the name of the part in the request, add the api:http.annotation.Part[@Part] annotation to the argument and specify the expected name in the request.

=== Chunk Data Types

api:io.micronaut.http.multipart.PartData[] represents a chunk of data received in a multipart request. api:io.micronaut.http.multipart.PartData[] interface methods convert the data to a `byte[]`, link:{javase}java/io/InputStream.html[InputStream], or a link:{javase}java/nio/ByteBuffer.html[ByteBuffer].

NOTE: Data can only be retrieved from a api:io.micronaut.http.multipart.PartData[] once. The underlying buffer is released, causing further attempts to fail.

Route arguments of type rs:Publisher[Publisher<PartData>] are treated as intended to receive a single file, and each chunk of the received file will be sent downstream. If the generic type is other than api:io.micronaut.http.multipart.PartData[], conversion will be attempted using Micronaut's conversion service. Conversions to `String` and `byte[]` are supported by default.

If you need knowledge about the metadata of an uploaded file, the api:http.multipart.StreamingFileUpload[] class is a rs:Publisher[Publisher<PartData>] that also has file information such as the content type and file name.

snippet::io.micronaut.docs.server.upload.UploadController[tags="class,file", indent=0, title="Streaming file upload"]

<1> The method consumes api:http.MediaType#MULTIPART_FORM_DATA[]
<2> The method parameters match form attribute names. In this case `file` will match for example an `<input type="file" name="file">`
<3> The api:http.multipart.StreamingFileUpload.transferTo(File)[] method transfers the file to the server. The method returns a rs:Publisher[]
<4> The returned reactor:Mono[] subscribes to the rs:Publisher[] and outputs a response once the upload is complete, without blocking.

It is also possible to pass an output stream with the `transferTo` method.

NOTE: The reading of the file or stream will be offloaded to the IO thread pool to prevent the possibility of blocking the event loop.

snippet::io.micronaut.docs.server.upload.UploadController[tags="class,outputStream", indent=0, title="Streaming file upload"]

<1> The method consumes api:http.MediaType#MULTIPART_FORM_DATA[]
<2> The method parameters match form attribute names. In this case `file` will match for example an `<input type="file" name="file">`
<3> A stream is created to output the data to. In real world scenarios this would come from some other source.
<4> The api:http.multipart.StreamingFileUpload.transferTo(OutputStream)[] method transfers the file to the server. The method returns a rs:Publisher[]
<5> The returned reactor:Mono[] subscribes to the rs:Publisher[] and outputs a response once the upload is complete, without blocking.

=== Whole Data Types

Route arguments that are not publishers cause route execution to be delayed until the upload has finished. The received data will attempt to be converted to the requested type. Conversions to a `String` or `byte[]` are supported by default. In addition, the file can be converted to a POJO if a media type codec is registered that supports the media type of the file. A media type codec is included by default that allows conversion of JSON files to POJOs.

snippet::io.micronaut.docs.server.upload.BytesUploadController[tags="class", indent=0, title="Receiving a byte array"]

If you need knowledge about the metadata of an uploaded file, the api:http.multipart.CompletedFileUpload[] class has methods to retrieve the data of the file, and also file information such as the content type and file name.

snippet::io.micronaut.docs.server.upload.CompletedUploadController[tags="class", indent=0, title="File upload with metadata"]

<1> The method consumes api:http.MediaType#MULTIPART_FORM_DATA[]
<2> The method parameters match form attribute names. In this case the `file` will match for example an `<input type="file" name="file">`
<3> The `CompletedFileUpload` instance gives access to metadata about the upload as well as access to the file contents.

IMPORTANT: If a file will not be read, the `discard` method on the file object *must* be called to prevent memory leaks.

== Multiple Uploads

=== Different Names

If a multipart request has multiple uploads that have different part names, create an argument to your route that receives each part. For example:

[source,java]
----
HttpResponse upload(String title, String name)
----

A route method signature like the above expects two different parts, one named "title" and the other "name".

=== Same Name

To receive multiple parts with the same part name, the argument must be a rs:Publisher[]. When used in one of the following ways, the publisher emits one item per part found with the specified name. The publisher must accept one of the following types:

* api:http.multipart.StreamingFileUpload[]
* api:http.multipart.CompletedFileUpload[]
* api:http.multipart.CompletedPart[] for attributes
* Any POJO, assuming a media codec that supports the content type exists
* Another rs:Publisher[] that accepts one of the chunked data types described above

For example:
[source,java]
----
HttpResponse upload(Publisher<StreamingFileUpload> files)
HttpResponse upload(Publisher<CompletedFileUpload> files)
HttpResponse upload(Publisher<MyObject> files)
HttpResponse upload(Publisher<Publisher<PartData>> files)
HttpResponse upload(Publisher<CompletedPart> attributes)
----

== Whole Body Binding

When request part names aren't known ahead of time, or to read the entire body, a special type can be used to indicate the entire body is desired.

If a route has an argument of type api:io.micronaut.http.server.multipart.MultipartBody[] (not to be confused with the class for the client) annotated with ann:http.annotation.Body[], each part of the request will be emitted through the argument. A api:io.micronaut.http.server.multipart.MultipartBody[] is a publisher of api:io.micronaut.http.multipart.CompletedPart[] instances.

For example:

snippet::io.micronaut.docs.server.upload.WholeBodyUploadController[tags="class", indent=0, title="Binding to the entire multipart body"]
