To use the templating features described in this section, add the dependency on your classpath. For example, in `build.gradle`

.build.gradle
[source,groovy]
----
compile "io.micronaut:views"
----

Place your templates at `src/main/resource/views`.

If you wish to use a different folder instead of `views`, set the property `micronaut.views.folder`.

Your controller's method can render the response with a template with the the api:views.View[] annotation.

The following is an example of a controller which renders a template.

[source,java]
.src/main/java/myapp/ViewsController.java
----
include::{testsviews}/ViewsController.groovy[tags=clazz]

include::{testsviews}/ViewsController.groovy[tags=map]

}
----

<1> Use `@View` annotation to indicate the template name which should be used to render a view for the route.

Moreover, you can render a POJO with a template to:

[source,java]
.src/main/java/myapp/ViewsController.java
----
include::{testsviews}/ViewsController.groovy[tags=clazz]

include::{testsviews}/ViewsController.groovy[tags=pogo]

}
----

<1> Use `@View` annotation to indicate the template name which should be used to render the POJO responded by the controller.

You can also return a api:views.ModelAndView[] and skip specifying the api:views.View[] annotation.

[source,java]
.src/main/java/myapp/ViewsController.java
----
include::{testsviews}/ViewsController.groovy[tags=clazz]

include::{testsviews}/ViewsController.groovy[tags=modelAndView]
----

The next sections show different template engines integrations.

To create your own implementation create a class which implements api:views.ViewRenderer[] and annotate it with api:http.annotation.Produces[@Produces] to indicate
the media type produced.