https://www.jaegertracing.io[Jaeger] is a distributed tracing system developed at Uber that is more or less the reference implementation for http://opentracing.io[Open Tracing].

== Running Jaeger

The easiest way to get started with Jaeger is with Docker:

[source,bash]
----
$ docker run -d \
  -e COLLECTOR_ZIPKIN_HTTP_PORT=9411 \
  -p 5775:5775/udp \
  -p 6831:6831/udp \
  -p 6832:6832/udp \
  -p 5778:5778 \
  -p 16686:16686 \
  -p 14268:14268 \
  -p 9411:9411 \
  jaegertracing/all-in-one:1.6
----

Navigate to `http://localhost:16686` to access the Jaeger UI.

See https://www.jaegertracing.io/docs/getting-started/[Getting Started with Jaeger] for more information.

== Sending Traces to Jaeger

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `tracing-jaeger` feature to include Jaeger tracing in your project:
----
$ mn create-app my-app --features tracing-jaeger
----
====

To send tracing spans to Jaeger, the minimal configuration requires the following dependency in your build:

dependency:io.jaegertracing:jaeger-thrift:0.31.0[]

Then enable Jaeger tracing in your configuration (potentially only your production configuration):

.application.yml
[source,yaml]
----
tracing:
  jaeger:
    enabled: true
----

By default, Jaeger will be configured to send traces to a locally running Jaeger agent.

== Jaeger Configuration

There are many configuration options available for the Jaeger client that sends Spans to Jaeger, and they are generally exposed via the api:tracing.jaeger.JaegerConfiguration[] class. Refer to the Javadoc for available options.

Below is an example of customizing JaegerConfiguration configuration:

.Customizing Jaeger Configuration
[source,yaml]
----
tracing:
  jaeger:
    enabled: true
    sampler:
      probability: 0.5
    sender:
      agentHost: foo
      agentPort: 5775
    reporter:
      flushInterval: 2000
      maxQueueSize: 200
----

You can also optionally dependency-inject common configuration classes into api:tracing.jaeger.JaegerConfiguration[] such as `io.jaegertracing.Configuration.SamplerConfiguration` just by defining them as beans. See the API for api:tracing.jaeger.JaegerConfiguration[] for available injection points.
