https://zipkin.io[Zipkin] is a distributed tracing system. It helps gather timing data to troubleshoot latency problems in microservice architectures. It manages both the collection and retrieval of this data.

== Running Zipkin

The quickest way to get up and started with Zipkin is with Docker:

.Running Zipkin with Docker
[source,bash]
----
$ docker run -d -p 9411:9411 openzipkin/zipkin
----

Navigate to `http://localhost:9411` to view traces.

== Sending Traces to Zipkin

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `tracing-zipkin` feature to include Zipkin tracing in your project:
----
$ mn create-app my-app --features tracing-zipkin
----
====

To send tracing spans to Zipkin, the minimal configuration requires the following dependencies in your build:

.Adding Zipkin Dependencies
[source,groovy]
----
runtime 'io.zipkin.brave:brave-instrumentation-http'
runtime 'io.zipkin.reporter2:zipkin-reporter'
compile 'io.opentracing.brave:brave-opentracing'
----

Then enable ZipKin tracing in your configuration (potentially only your production configuration):

.application.yml
[source,yaml]
----
tracing:
  zipkin:
    enabled: true
----

== Customizing the Zipkin Sender

To send spans you configure a Zipkin sender. You can configure a api:tracing.brave.sender.HttpClientSender[] that sends Spans asynchronously using Micronaut's native HTTP client with the `tracing.zipkin.http.url` setting:

.Configuring Multiple Zipkin Servers
[source,yaml]
----
tracing:
  zipkin:
    enabled: true
    http:
      url: http://localhost:9411
----

It is unlikely that sending spans to localhost will be suitable for production deployment, so you generally need to configure the location of one or more Zipkin servers for production:

.Configuring Multiple Zipkin Servers
[source,yaml]
----
tracing:
  zipkin:
    enabled: true
    http:
      urls:
        - http://foo:9411
        - http://bar:9411
----

TIP: In production, setting `TRACING_ZIPKIN_HTTP_URLS` environment variable with a comma-separated list of URLs also works.

Alternatively to use a different `zipkin2.reporter.Sender` implementation, you can define a bean of type `zipkin2.reporter.Sender` and it will be picked up.

== Zipkin Configuration

There are many configuration options available for the Brave client that sends Spans to Zipkin, and they are generally exposed via the api:tracing.brave.BraveTracerConfiguration[] class. Refer to the Javadoc for available options.

Below is an example of customizing Zipkin configuration:

.Customizing Zipkin Configuration
[source,yaml]
----
tracing:
  zipkin:
    enabled: true
    traceId128Bit: true
    sampler:
      probability: 1
  exclusions: # Optionally exclude http path patterns from tracing
    - /health
    - /admin/.*
----

You can also optionally dependency-inject common configuration classes into api:tracing.brave.BraveTracerConfiguration[] such as `brave.sampler.Sampler` just by defining them as beans. See the API for api:tracing.brave.BraveTracerConfiguration[] for available injection points.
