https://zipkin.io[Zipkin] is a distributed tracing system. It helps gather timing data needed to troubleshoot latency problems in microservice architectures. It manages both the collection and lookup of this data.

== Running Zipkin

The quickest way to get up and started with Zipkin is with Docker:

.Running Zipkin with Docker
[source,bash]
----
$ docker run -d -p 9411:9411 openzipkin/zipkin
----

You can then open a browser tab to the location `http://localhost:9411` to view traces.

== Sending Traces to Zipkin

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `tracing-zipkin` feature to include Zipkin tracing in your project:
----
$ mn create-app my-app --features tracing-zipkin
----
====

To send tracing spans to Zipkin the minimal configuration requires you add the following dependencies to `build.gradle` or `pom.xml`:

[source.multi-language-sample,gradle-groovy,title="Adding Zipkin Dependencies"]
----
runtime 'io.zipkin.brave:brave-instrumentation-http'
runtime 'io.zipkin.reporter2:zipkin-reporter'
compile 'io.opentracing.brave:brave-opentracing'
----

[source.multi-language-sample,gradle-kotlin]
----
runtime("io.zipkin.brave:brave-instrumentation-http")
runtime("io.zipkin.reporter2:zipkin-reporter")
compile("io.opentracing.brave:brave-opentracing")
----

[source.multi-language-sample,maven]
----
<dependency>
    <groupId>io.zipkin.brave</groupId>
    <artifactId>brave-instrumentation-http</artifactId>
</dependency>
<dependency>
    <groupId>io.zipkin.reporter2</groupId>
    <artifactId>zipkin-reporter</artifactId>
</dependency>
<dependency>
    <groupId>io.opentracing.brave</groupId>
    <artifactId>brave-opentracing</artifactId>
</dependency>
----

Then you need to enable ZipKin tracing in your configuration (potentially only your production configuration):

.application.yml
[source,yaml]
----
tracing:
    zipkin:
        enabled: true
----

TIP: Or alternatively if you have the Micronaut CLI installed you can configure Zipkin when creating your service with: `mn create-app hello-world --features tracing-zipkin`

== Customizing the Zipkin Sender

In order to send spans you need to configure a Zipkin sender. You can configure a api:tracing.brave.sender.HttpClientSender[] that sends Spans asynchronously using Micronaut's native HTTP client using the `tracing.zipkin.http.url` setting:

.Configuring Multiple Zipkin Servers
[source,yaml]
----
tracing:
    zipkin:
        enabled: true
        http:
            url: http://localhost:9411
----

It is unlikely that sending spans to localhost will be suitable for production deployment so you generally will want to configure the location of one or many Zipkin servers for production:

.Configuring Multiple Zipkin Servers
[source,yaml]
----
tracing:
    zipkin:
        enabled: true
        http:
            urls:
                - http://foo:9411
                - http://bar:9411
----

TIP: In production, setting `TRACING_ZIPKIN_HTTP_URLS` environment variable with a comma separated list of URLs will also work.

Alternatively if you wish to use a different `zipkin2.reporter.Sender` implementation, you can simply define a bean that is of type `zipkin2.reporter.Sender` and it will be picked up.

== Zipkin Configuration

There are many configuration options available for the Brave client that sends Spans to Zipkin and they are generally exposed via the api:tracing.brave.BraveTracerConfiguration[] class. You can refer to the javadoc for all the available options.

Below is an example of customizing Zipkin configuration:

.Customizing Zipkin Configuration
[source,yaml]
----
tracing:
    zipkin:
        enabled: true
        traceId128Bit: true
        sampler:
            probability: 1
----

You can also optionally dependency inject common configuration classes into api:tracing.brave.BraveTracerConfiguration[] such as `brave.sampler.Sampler` just by defining them as beans. See the API for api:tracing.brave.BraveTracerConfiguration[] for available injection points.

