Args = \
       -Ob \
       --add-modules=java.compiler \
       --initialize-at-build-time=com.sun.tools.javac.api.JavacTool \
       -H:EnableURLProtocols=jar \
       --initialize-at-run-time=jdk.internal.loader.ClassLoaders \
       --initialize-at-run-time=io.micronaut.inject.visitor.TypeElementVisitor \
       --initialize-at-run-time=io.micronaut.inject.visitor.TypeElementVisitor$VisitorKind \
       --initialize-at-run-time=com.sun.tools.javac \
       --initialize-at-run-time=com.sun.tools.javac.file \
       --initialize-at-run-time=com.sun.source \
       --initialize-at-run-time=jdk.javadoc.internal \
       --initialize-at-run-time=com.sun.tools.doclint \
       --initialize-at-run-time=jdk.internal.jshell.tool \
       --initialize-at-run-time=jdk.internal.org.jline.terminal.impl.ffm \
       -H:+UnlockExperimentalVMOptions \
       -H:+RuntimeClassLoading \
       -H:+AllowJRTFileSystem \
       -H:-UnlockExperimentalVMOptions
