Signed claims prevents an attacker to tamper its contents to introduce malicious data or try a privilege escalation by adding more roles. However, the claims can be decoded just by using Base 64.

If the claims contains sensitive information, you can use a JSON Web Encryption algorithm to prevent them to be decoded.

To enable a JWT encryption in token generation, you need to have in your app a bean of type  link:{api}/io/micronaut/security/token/jwt/encryption/rsa/RSAEncryptionConfiguration.html[RSAEncryptionConfiguration],
link:{api}/io/micronaut/security/token/jwt/encryption/ec/ECEncryptionConfiguration.html[ECEncryptionConfiguration],
link:{api}/io/micronaut/security/token/jwt/encryption/secret/SecretEncryptionConfiguration.html[SecretEncryptionConfiguration] qualified with name `generator`.

== Example of JWT Signed with Secret and Encrypted with RSA

Setup a link:{api}/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.html[SecretSignatureConfiguration] through configuration properties

[source, groovy]
----
include::{testssecurityjwt}/signandencrypt/SignSecretEncryptRSASpec.groovy[indent=0, tag=yamlconfig]
pem:
  path: /home/user/rsa-2048bit-key-pair.pem //<2>
----

<1> Name the Signature configuration `generator` to make it participate in JWT token generation.
<2> Location of PEM file

Generate a 2048-bit RSA private + public key pair:

[source, bash]
----
openssl genrsa -out rsa-2048bit-key-pair.pem 2048
----

[source, groovy]
----
include::{testssecurityjwt}/signandencrypt/RSAOAEPEncryptionConfiguration.groovy[indent=0, tag=clazz]
----

<1> Name Bean `generator` to designate this bean as participant in the JWT Token Generation.

To parse the PEM key, use a collaborator as described in https://connect2id.com/products/nimbus-jose-jwt/openssl-key-generation[OpenSSL key generation].

[source, groovy]
----
include::{testssecurityjwt}/signandencrypt/KeyPairProvider.groovy[indent=0, tag=clazz]
----
