Micronaut security capabilities use signed JWT’s as specified by the
https://tools.ietf.org/html/rfc7515[JSON Web Signature] specification.

To enable a JWT signature in token generation, you need to have in your app a bean of type link:{api}/io/micronaut/security/token/jwt/signature/rsa/RSASignatureConfiguration.html[RSASignatureConfiguration],
link:{api}/io/micronaut/security/token/jwt/signature/ec/ECSignatureConfiguration.html[ECSignatureConfiguration],
link:{api}/io/micronaut/security/token/jwt/signature/secret/SecretSignatureConfiguration.html[SecretSignatureConfiguration] qualified with name `generator`.

You can setup a `SecretSignatureConfiguration` named `generator` easily via configuration properties:

[source, yaml]
----
include::{testssecurityjwt}/signandencrypt/SignSecretEncryptRSASpec.groovy[indent=0, tag=yamlconfig]
----

<1> **Change this for your own secret and keep it safe**.
<2> Json Web Token Signature name. In this example, HMAC using SHA-256 hash algorithm.

You can supply the secret with Base64 encoding.

[source, yaml]
----
include::{testssecurityjwt}/base64/JwtBase64Spec.groovy[indent=0, tag=yamlconfig]
----

<1> Secret Base64 encoded
<2> Signal that the secret is Base64 encoded