# These settings are synced to GitHub by https://probot.github.io/apps/settings/

# Extend from https://github.com/micronaut-projects/.github/blob/master/.github/settings.yml
_extends: .github

#repository:
  # See https://developer.github.com/v3/repos/#edit for all available settings.

  # Updates the default branch for this repository.
#  default_branch: master


# Labels: define labels for Issues and Pull Requests, that are locally relevant to this repo.

#labels:
#  - name: 'relates-to: caffeine'
#    color: fbca04
#    description: Relates to Caffeine


# Branch protection is enabled by default. Uncomment to disable

#branches:
#  - name: master
#    protection: null