The Micronaut CLI is the recommended way to create new Micronaut projects. The CLI includes commands for generating specific categories of projects, allowing you to choose between build tools, test frameworks, and even pick the language to use in your application. The CLI also provides commands for generating artifacts such as controllers, client interfaces, and serverless functions.

TIP: We have a website that can be used to generate projects instead of the CLI. Check out https://micronaut.io/launch/[Micronaut Launch] to get started!

When <<buildCLI, Micronaut framework is installed on your computer>>, you can call the CLI with the `mn` command.

[source,bash]
----
$ mn create-app my-app
----

A Micronaut framework CLI project can be identified by the `micronaut-cli.yml` file, which is included at the project root if it was generated via the CLI. This file will include the project's profile, default package, and other variables. The project's default package is evaluated based on the project name.

[source,bash]
----
$ mn create-app my-demo-app
----

results in the default package being `my.demo.app`.

You can supply your own default package when creating the application by prefixing the application name with the package:

[source,bash]
----
$ mn create-app example.my-demo-app
----

results in the default package being `example`.

== Interactive Mode

If you run `mn` without any arguments, the Micronaut CLI launches in interactive mode. This is a shell-like mode which lets you run multiple CLI commands without re-initializing the CLI runtime, and is especially suitable when you use code-generation commands (such as `create-controller`), create multiple projects, or are just exploring CLI features. Tab-completion is enabled, enabling you to hit the `TAB` key to see possible options for a given command or flag.

[source,bash]
----
$ mn
| Starting interactive mode...
| Enter a command name to run. Use TAB for completion:
mn>
----

== Help and Info

General usage information can be viewed using the `help` flag on a command.

[source,bash]
----
mn> create-app -h
Usage: mn create-app [-hivVx] [--list-features] [-b=BUILD-TOOL] [--jdk=<javaVersion>] [-l=LANG]
                     [-t=TEST] [-f=FEATURE[,FEATURE...]]... [NAME]
Creates an application
      [NAME]               The name of the application to create.
  -b, --build=BUILD-TOOL   Which build tool to configure. Possible values: gradle, gradle_kotlin,
                             maven.
  -f, --features=FEATURE[,FEATURE...]
  -h, --help               Show this help message and exit.
  -i, --inplace            Create a service using the current directory
      --jdk, --java-version=<javaVersion>
                           The JDK version the project should target
  -l, --lang=LANG          Which language to use. Possible values: java, groovy, kotlin.
      --list-features      Output the available features and their descriptions
  -t, --test=TEST          Which test framework to use. Possible values: junit, spock, kotest.
----

A list of available features can be viewed using the `--list-features` flag on any of the create commands.

[source,bash]
----
mn> create-app --list-features
Available Features
(+) denotes the feature is included by default
  Name                             Description
  -------------------------------  ---------------
  Cache
  cache-caffeine                   Adds support for cache using Caffeine (https://github.com/ben-manes/caffeine)
  cache-ehcache                    Adds support for cache using EHCache (https://www.ehcache.org/)
  cache-hazelcast                  Adds support for cache using Hazelcast (https://hazelcast.org/)
  cache-infinispan                 Adds support for cache using Infinispan (https://infinispan.org/)

----
