[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI's `create-app` command, the `http-server` dependency is included by default.
====

Micronaut includes both non-blocking HTTP server and client APIs based on https://netty.io[Netty].

The design of the HTTP server in Micronaut is optimized for interchanging messages between Microservices, typically in JSON, and is not intended as a full server-side MVC framework. For example, there is currently no support for server-side views or features typical of a traditional server-side MVC framework.

The goal of the HTTP server is to make it as easy as possible to expose APIs that can be consumed by HTTP clients, whatever language they may be written in. To use the HTTP server you must have the `http-server-netty` dependency on your classpath. For example in `build.gradle`:

.build.gradle
[source,groovy]
----
compile "io.micronaut:micronaut-http-server-netty"
----

A "Hello World" server application can be seen below:

[source.multi-language-sample,java]
.Java
----
include::{testsuite}/server/intro/javacode/HelloController.java[tags=imports, indent=0]

include::{testsuite}/server/intro/javacode/HelloController.java[tags=class, indent=0]
----
[source.multi-language-sample,kotlin]
.Kotlin
----
include::{testsuitekotlin}/server/intro/kotlincode/HelloController.kt[tags=imports, indent=0]

include::{testsuitekotlin}/server/intro/kotlincode/HelloController.kt[tags=class, indent=0]
----
[source.multi-language-sample,groovy]
.Groovy
----
include::{testsuite}/server/intro/groovycode/HelloController.groovy[tags=imports, indent=0]

include::{testsuite}/server/intro/groovycode/HelloController.groovy[tags=class, indent=0]
----

<1> The class is defined as a controller with the link:{api}/io/micronaut/http/annotation/Controller.html[@Controller] annotation mapped to the path `/hello`
<2> The scope of the `@Controller` is singleton
<3> By defining method called `index`, by convention the method is exposed via the `/hello` URI


