When most developers think of Inversion of Control (also known as Dependency Injection and referred to as such from this point onwards) the Spring Framework comes to mind.

Micronaut takes inspiration from Spring, and in fact, the core developers of Micronaut are former SpringSource/Pivotal engineers now working for https://objectcomputing.com[OCI].

Unlike Spring which relies exclusively on runtime reflection and proxies, Micronaut uses compile time data to implement dependency injection.

This is a similar approach taken by tools such as Google's https://google.github.io/dagger/[Dagger], which is designed primarily with Android in mind. Micronaut, on the other hand, is designed for building server-side microservices and provides many of the same tools and utilities as Spring but without using reflection or caching excessive amounts of reflection metadata.

The goals of the Micronaut IoC container are summarized as:

* Use reflection as a last resort
* Avoid proxies
* Optimize start-up time
* Reduce memory footprint
* Provide clear, understandable error handling

Note that the IoC part of Micronaut can be used completely independently of Micronaut itself for whatever application type you may wish to build. To do so all you need to do is configure your build appropriately to include the `micronaut-inject-java` dependency as an annotation processor. For example with Gradle:

[source.multi-language-sample,gradle-groovy,title="Configuring Gradle",subs="attributes"]
----
plugins {
  id "net.ltgt.apt" version "0.18" // <1>
}

// ...
dependencies {
    annotationProcessor "io.micronaut:micronaut-inject-java:{version}" // <2>
    compile "io.micronaut:micronaut-inject:{version}"

    testAnnotationProcessor "io.micronaut:micronaut-inject-java:{version}" // <3>
}

----

[source.multi-language-sample,gradle-kotlin,title="Configuring Gradle",subs="attributes"]
----
plugins {
  kotlin("kapt") // <1>
}

...
dependencies {
    kapt("io.micronaut:micronaut-inject-java:{version}") // <2>
    compile("io.micronaut:micronaut-inject:{version}")

    kaptTest("io.micronaut:micronaut-inject-java:{version}") // <3>
}

----

<1> Apply the Annotation Processing plugin (for Kotlin projects this is `kapt`)
<2> Include the minimal dependencies required to perform dependency injection
<3> This is necessary to create beans in the `test` directory

NOTE: For the Groovy language you should include `micronaut-inject-groovy` in the `compileOnly` and `testCompileOnly` scopes. Kotlin projects should use the `kapt` scope as shown in the Kotlin DSL example.

The entry point for IoC is then the api:context.ApplicationContext[] interface, which includes a `run` method. The following example demonstrates using it:

.Running the `ApplicationContext`
[source,java]
----
try (ApplicationContext context = ApplicationContext.run()) { // <1>
    MyBean myBean = context.getBean(MyBean.class); // <2>
    // do something with your bean
}
----
// TODO should this be converted? The commentary is calling out a specific language's feature

<1> Run the api:context.ApplicationContext[]
<2> Retrieve a bean that has been dependency injected

NOTE: The example uses Java's https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[try-with-resources] syntax to ensure the api:context.ApplicationContext[] is cleanly shutdown when the application exits.
