Unlike other frameworks which rely on runtime reflection and proxies, the Micronaut framework uses compile time data to implement dependency injection.

This is a similar approach taken by tools such as Google https://google.github.io/dagger/[Dagger], which is designed primarily with Android in mind. Micronaut, on the other hand, is designed for building server-side microservices and provides many of the same tools and utilities as other frameworks but without using reflection or caching excessive amounts of reflection metadata.

The goals of the Micronaut IoC container are summarized as:

* Use reflection as a last resort
* Avoid proxies
* Optimize start-up time
* Reduce memory footprint
* Provide clear, understandable error handling

Note that the IoC part of the Micronaut framework can be used completely independently of Micronaut for whatever application type you wish to build.

To do so, configure your build to include the `micronaut-inject-java` dependency as an annotation processor.

The easiest way to do this is with Micronaut's Gradle or Maven plugins. For example with Gradle:

.Configuring Gradle
[source,groovy,subs="attributes+"]
----
plugins {
    id 'io.micronaut.library' version '1.3.2' // <1>
}

version "0.1"
group "com.example"

repositories {
    mavenCentral()
}

micronaut {
    version = "{version}" // <2>
}
----
<1> Define the https://plugins.gradle.org/plugin/io.micronaut.library[Micronaut Library plugin]
<2> Specify the Micronaut framework version to use

The entry point for IoC is then the api:context.ApplicationContext[] interface, which includes a `run` method. The following example demonstrates using it:

.Running the `ApplicationContext`
[source,java]
----
try (ApplicationContext context = ApplicationContext.run()) { // <1>
    MyBean myBean = context.getBean(MyBean.class); // <2>
    // do something with your bean
}
----

<1> Run the api:context.ApplicationContext[]
<2> Retrieve a bean from the `ApplicationContext`

NOTE: The example uses Java https://docs.oracle.com/javase/tutorial/essential/exceptions/tryResourceClose.html[try-with-resources] syntax to ensure the api:context.ApplicationContext[] is cleanly shutdown when the application exits.
