Micronaut {version} includes the following changes:

=== GraalVM 19 Native Image Support

Micronaut {version} is the first version to support GraalVM 19's native image changes. 

NOTE: Although GraalVM 19 is the first official stable release of GraalVM, Substrate and the `native-image` tool remain in early adopter / experimental status. Therefore support for native images in Micronaut also remains experimental at this stage.

=== Native Bean Validation Support

Hibernate Validator is no longer a required dependency, with a new <<beanValidation,native implementation of Bean Validation>> available that is reflection free and supports reactive and AST level validations now available.

=== Micronaut Security 1.2 update

TODO

=== Optional Beans Returned from Factories

A ann:context.annotation.Factory[] bean can now return `null` if it is not possible to create the bean which will indicate to the dependency injection container that the bean does not exist. This allows for more complex logic within factory beans that can conditionally disable the bean if certain conditions are not met.

=== HashiCorp Vault Support

Initial support distributed configuration for https://www.vaultproject.io[HashiCorp Vault] has been added. See the documentation on <<distributedConfigurationVault,HashiCorp Vault Support>> for more information. Thanks to https://github.com/thiagolocatelli[Thiago Locatelli] for this contribution.

=== Oracle Cloud Support

Initial support for environment detection and cloud metadata for Oracle Cloud has been added. Thanks to https://github.com/recursivecodes[Todd Sharp] for this contribution.

=== Dependency Upgrades

- Groovy `2.5.4` -> `2.5.6`
- Micronaut SQL `1.1.1` -> `1.2.0.M1`
- Micronaut Micrometer `1.1.0` -> `1.2.0.RC1`
- Micronaut Security `1.1.1` -> `1.2.0.M1`
- Micronaut Views `1.1.3` -> `1.2.0.RC1`