Apart from https://github.com/micronaut-projects/micronaut-core/milestone/3?closed=1[issues resolved and minor enhancements] since the last release of Micronaut, this section covers significant new features.

=== Bean Generics Computed at Compile Time

Generic information for beans is now calculated at compile time, improving performance and allowing more uses cases.

For example it is now possible to define converters, serverless functions etc. as Java lambdas because the generic information is computed from the method signature:

.Functions as Java Lambdas
[source,java]
----
@Factory
public class FunctionFactory {

    @FunctionBean("round")
    Function<Double, Long> round() {
        return (doub) -> Math.round(doub.doubleValue());
    }
}
----

The api:inject.BeanDefinition[] interface features a new `getTypeArguments(..)` method that can be used to retrieve the generic types of any bean without using reflection and having to deal with type erasure.

=== New @Adapter AOP Advice

Micronaut's AOP API has been extended introducing a new ann:aop.Adapter[] annotation that allows any method to be adapted to a new SAM (single abstract method) type at compile time that is automatically registered as a bean.

For example:

.Using the `@Adapter` annotation
[source,java]
----
import io.micronaut.aop.*;
import io.micronaut.context.event.*;

@javax.inject.Singleton
class MyBean{

    @Adapter(ApplicationEventListener.class)
    void onStartup(StartupEvent event) {
        // startup logic
    }
}
----

The above example will create a new bean at compile time that implements the api:context.event.ApplicationEventListener[] interface and delegates to the `onStartup` method of `MyBean`. Micronaut will automatically align the generic type arguments (if the SAM type features any) and will also perform checks at compile time to verify the method is a valid candidate, failing compilation if it isn't.

=== Improved Events API

The ann:aop.Adapter[] annotation can be used as an annotation stereotype (meta annotation), and in fact is already used that way - the new ann:runtime.event.annotation.EventListener[] annotation allows more elegant definition of application event listeners:

.Using the `@EventListener` annotation
[source,java]
----
import io.micronaut.aop.*;
import io.micronaut.context.event.*;
import io.micronaut.runtime.event.annotation.EventListener;

@javax.inject.Singleton
class MyBean{

    @EventListener // <1>
    void onStartup(StartupEvent event) {
        // startup logic
    }
}
----

<1> Simply define the `@EventListener` annotation on any method to create a new listener

In addition the ann:scheduling.annotation.Async[] annotation can be used to make any ann:runtime.event.annotation.EventListener[] asynchronous:

[source,java]
----
@EventListener // <1>
@Async // <2>
void onStartup(StartupEvent event) {
    // startup logic
}
----

<1> An `@EventListener` is defined
<2> The `@Async` annotation tells Micronaut to run the operation asynchronously (by default on the `scheduled` executor)

