Apart from https://github.com/micronaut-projects/micronaut-core/milestone/9?closed=1[issues resolved and minor enhancements] since the last release of Micronaut, this section covers significant new features and improvements.

=== Micronaut for Spring

It is now possible using Ahead of Time compilation to use the Spring annotation based programming model to build Micronaut applications. See the documentation for https://github.com/micronaut-projects/micronaut-spring[Micronaut for Spring] for details.

=== Improved GraalVM Docker Files

The Dockerfiles for GraalVM have been improved including a new all-in-one docker file that will build a slimmed down image including only your application using:

.Using `DockerAllInOne`
[source,bash]
----
$ docker build . -f DockerfileAllInOne -t hello-world
----

=== Inheritance support for Swagger

Compile-time support for Swagger has been improved to support inheritance when building the Swagger models.

=== Improvements for JDK 11

Various improvements have been made to improve the Micronaut experience on JDK 11.

=== Improved support for OpenFaaS

<<<<<<< HEAD
- Netty `4.1.29` -> `4.1.30`
- RxJava `2.2.0` -> `2.2.2`
//- Groovy `2.5.1` -> `2.5.2`
- Hibernate Core `5.3.4` -> `5.3.6.Final`
- Jackson `2.9.6` -> `2.9.7`
//- Lettuce `5.0.4` -> `5.1.0`
- Reactor `3.1.8` -> `3.2.0`
- SnakeYAML `1.20` -> `1.23`
- Jaeger `0.30.4` -> `0.31.0`
- Brave `5.2.0` -> `5.4.2`
- Zipkin Reporter `2.7.7` -> `2.7.9`
- Spring `5.0.8` -> `5.1.0`
=======
The OpenFaaS feature of the CLI now generates an appropriate `function.yml` file so you can use the OpenFaaS CLI to deploy functions implemented in Micronaut.
>>>>>>> 1.0.x

=== AOP Advice on Factory Beans

It is now possible to apply AOP advice like `@Retryable` at the class level for `@Factory` beans allowing for the container to be dynamic (for example to retry bean creation if it fails in a cloud environment).