Micronaut {version} includes the following changes:

=== Native Bean Validation Support

Hibernate Validator is no longer a required dependency to activate bean validation, with a new <<beanValidation,native implementation of Bean Validation>> available that is reflection free and supports reactive and AST level validations now available.

The `micronaut-validation` dependency is all that it is needed now and provides the following benefits over Hibernate Validator:

* Reflection Free
* Compile Time Computed Bean Metadata resulting in lower memory requirements
* Reduction in JAR size by 2MB
* Reduction in startup time by 300ms which was the cost of initializing Hibernate validator
* Out-of-the-box GraalVM native image support
* Reduction in GraalVM native image size by 10MB

=== Reactive Bean Validation Support

In previous versions of Micronaut manual validation had to be applied to reactive flows. You can now declare `@Valid` on method parameters that receive a reactive type and validation will automatically be applied.

=== Implicit @Validated and @Valid

It is no longer necessary to apply the ann:validation.Validated[] annotation to beans that accept `@Valid` arguments or use any `javax.validation` annotation.

=== Micronaut Security 1.2 Update

Support for OAuth 2.0 and OpenID clients has been added to the Micronaut security module through a new dependency: `micronaut-security-oauth2`. It is now very easy to add support for login through an OAuth providers. See the https://micronaut-projects.github.io/micronaut-security/latest/guide/#oauth[Oauth section] in the security documentation for more information.

=== Micronaut Micrometer 1.2 Update

https://micronaut-projects.github.io/micronaut-micrometer/1.2.x/guide/[Micronaut Micrometer has been updated to 1.2] which includes the following new features:

* Support for GraalVM native images
* Meter registry support for Datadog, Influx and Elastic

Thanks to https://github.com/thiagolocatelli[Thiago Locatelli] for this contribution.

=== Optional Beans Returned from Factories

A ann:context.annotation.Factory[] bean can now return `null` if it is not possible to create the bean which will indicate to the dependency injection container that the bean does not exist. This allows for more complex logic within factory beans that can conditionally disable the bean if certain conditions are not met.

=== HashiCorp Vault Support

Initial support distributed configuration for https://www.vaultproject.io[HashiCorp Vault] has been added. See the documentation on <<distributedConfigurationVault,HashiCorp Vault Support>> for more information. Thanks to https://github.com/thiagolocatelli[Thiago Locatelli] for this contribution.

=== Oracle Cloud Support

Initial support for environment detection and cloud metadata for Oracle Cloud has been added. Thanks to https://github.com/recursivecodes[Todd Sharp] for this contribution.

=== @Client and Manual Service Discovery

If a service is configured statically with `micronaut.http.services.*`, it was previously not possible to override the configuration with the ann:http.client.annotation.Client[] annotation. It is now possible to override the configuration, which will result in a new client being created for the given client class.

=== Client and Server Host Resolution

New beans have been added to support lookup of the client address and the current server host. The implementations are aware of proxy headers and are configurable to look for custom headers. The api:http.server.util.HttpHostResolver[] can be injected to resolve the current server hostname and api:http.server.util.HttpClientAddressResolver[] can be injected to resolve the client address of the current request.

=== Default Implementation Support

When writing libraries for Micronaut, it is often the case that users will want to override part of your implementation. The most common way of doing so is creating custom beans that use the ann:context.annotation.Replaces[] annotation to replace your implementation. Because the ann:context.annotation.Replaces[] annotation requires a class argument to indicate which implementation to replace, it was required to make the implementation part of the public API. The class needed to be public because the user would need to reference the class directly in the annotation.

A new annotation has been added to solve this problem: ann:context.annotation.DefaultImplementation[]. See the section on <<replaces,Bean Replacements>> for more information.

=== HEAD Routes

For each route registered with the server that responds to GET requests, an additional route will be registered that responds to HEAD requests and will not include the body. This only applies to routes created by Micronaut through annotations. Any GET routes registered by custom route builders will not have corresponding HEAD routes added automatically.

=== Request Scope

A new bean scope has been created to allow for beans that only exist in the scope of a given HTTP request. See ann:runtime.http.scope.RequestScope[].

=== Environment Order and Priority

In previous versions of Micronaut, the property sources for an active environment had no priority over any other active environment. It was non deterministic which environment's properties would override other environments. Now the last environment supplied has the highest priority. For example, if an application is started with `-Dmicronaut.environments=first,second`, `application-second.yml` will override properties in `application-first.yml`. This change affects all sources of properties, including distributed configuration sources.

== RSS 2.0 and iTunes Podcast

This version references the https://micronaut-projects.github.io/micronaut-rss/latest/guide/index.html[RSS configuration] which eases the generation of a RSS 2.0 feed or an iTunes Podcast feed in a Micronaut app.

=== Dependency Upgrades

- Groovy `2.5.4` -> `2.5.6`
- Micronaut SQL `1.1.1` -> `1.2.0.M1`
- Micronaut Micrometer `1.1.0` -> `1.2.0.RC1`
- Micronaut Security `1.1.1` -> `1.2.0.M1`
- Micronaut Views `1.1.3` -> `1.2.0.RC1`