Micronaut {version} includes the following changes:

=== GraalVM 19 Native Image Support

Micronaut {version} is the first version to support GraalVM 19's native image changes. 

NOTE: Although GraalVM 19 is the first official stable release of GraalVM, Substrate and the `native-image` tool remain in early adopter / experimental status. Therefore support for native images in Micronaut also remains experimental at this stage.

=== Native Bean Validation Support

Hibernate Validator is no longer a required dependency, with a new <<beanValidation,native implementation of Bean Validation>> available that is reflection free and supports reactive and AST level validations now available.

=== Dependency Upgrades

- Groovy `2.5.4` -> `2.5.6`
- TODO

=== Conditional Beans with Factories

The use of `@Requires` is the preferred method for dealing with conditional beans, however it does not fit all use cases. When using `@EachProperty` it is common to require additional beans based on the configuration. `@EachBean` allows a bean to be created for each configuration, however a common use case is creating a bean only if some configuration property condition is met. To allow for this use case, it is now possible to return `null` from `@Factory` methods.

