Micronaut {version} includes the following changes:


=== Modularization

Micronaut is now modular with parts of Micronaut being shifted into subprojects. See the following links for new subprojects that now have indepent release cycles outside of Micronaut core:

* https://micronaut-projects.github.io/micronaut-kafka/latest/guide/index.html[Micronaut Kafka]
* https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/index.html[Micronaut Micrometer]
* https://micronaut-projects.github.io/micronaut-groovy/latest/guide/index.html[Micronaut Groovy]
* https://micronaut-projects.github.io/micronaut-sql/latest/guide/index.html[Micronaut SQL]
* https://micronaut-projects.github.io/micronaut-mongodb/latest/guide/index.html[Micronaut MongoDB]
* https://micronaut-projects.github.io/micronaut-redis/latest/guide/index.html[Micronaut Redis]
* https://micronaut-projects.github.io/micronaut-test/latest/guide/index.html[Micronaut Test]
* https://micronaut-projects.github.io/micronaut-netflix/latest/guide/index.html[Micronaut Netflix]
* https://micronaut-projects.github.io/micronaut-aws/latest/guide/index.html[Micronaut AWS]
* https://micronaut-projects.github.io/micronaut-grpc/latest/guide/index.html[Micronaut GRPC]

=== File Watch and Server Restart

A new <<automaticRestart,Automatic Restart>> feature is included that allows the server to restart if a change occurs to a file. This feature can be used both in production and at development time to achieve automatic application restarts when changing source code (when combined with a third party tool such as Gradle or Kubernetes in production).

[TIP]
.Using the CLI
====
----
$ mn create-app my-app --features file-watch
----
====


=== AWS API Gateway Proxy Support

Support for AWS API Gateway Proxy has been added allowing AWS Lambda's to be defined as regular controllers. See the documentation on https://micronaut-projects.github.io/micronaut-aws/latest/guide/#apiProxy[AWS API Gateway Proxy Support] for more information and links to examples.

[TIP]
.Using the CLI
====
----
$ mn create-app my-app --features aws-api-gateway
----
====

=== AWS Lambda Custom Runtime + GraalVM Support

Support for creating AWS API Gateway applications (see above) that are compiled into GraalVM native images and run using an AWS Lambda Custom Runtime has been added. This reduces cold starts on Lambda to 100-200ms.

[TIP]
.Using the CLI
====
----
$ mn create-app my-app --features aws-api-gateway-graal
----
====

=== Micrometer 1.1 and @Timed Support

Micrometer has been upgraded to 1.1 and support for https://micrometer.io/docs/concepts#_the_code_timed_code_annotation[@Timed] AOP advice added.


[TIP]
.Using the CLI
====
----
$ mn create-app my-app --features micrometer
----
====

=== API Versioning Support

API versioning is now supported. See the <<apiVersioning, API Versioning>> documentation for more information on how to use this feature.

=== Jackson `@JsonView` Support

Support for using `@JsonView` on controller methods has been added can be optionally enabled by setting `jackson.json-view.enabled` to `true` in `application.yml`.

=== Support for Spring Cloud Config Server

If you are already using https://spring.io/projects/spring-cloud-config[Spring Config Server] then Micronaut now features native integration for distributed configuration.

See the <<distributedConfigurationSpringCloud, Documentation on Distributed Configuration with Spring Cloud Config>> for more information.

=== Refactoring of File Responses

In an effort to make a more consistent and understandable API, some methods and classes related to sending file responses have been deprecated. api:http.server.types.files.SystemFile[] is the replacement for api:http.server.types.files.AttachedFile[] and the constructors of api:http.server.types.files.StreamedFile[] have been deprecated in favor of new constructors that better convey the intended functionality.

=== Support for Freemarker Views

Support for rendering <<freemarker,Freemaker Views>> has been added.

=== Constraint Bean Support

For those using the `micronaut-hibernate-validator` configuration, constraints will now be attempted to be retrieved from the bean context. This means you can now use dependency injection in your custom constraints.

=== Support for JCache Caching

Support has been added for the JCache specification. If you define a `javax.cache.CacheManager` bean it will be used for caching. For example:

.Using JCache Caching
[source,java]
----
@Factory
class CacheFactory {

    @Singleton
    @Bean
    CacheManager cacheManager() {
        CacheManager cacheManager = Caching.getCachingProvider()
                                           .getCacheManager();
        cacheManager.createCache('my-cache', new MutableConfiguration());
        return cacheManager;
    }
}

----

=== Dependency Upgrades

- Gradle `4.10.2` -> `5.1.1`
- Kafka `2.0.1` -> `2.1.0`
- Micrometer `1.0.6` -> `1.1.1`
- Reactive Streams `1.0.1` -> `1.0.2`
- Jackson `2.9.7` -> `2.9.8`
