micronaut:
  application:
    name: hello-world
  server:
    port: 8080
  security:
    enabled: true
    jwt:
      secret: qrD6h8K6S9503Q06Y6Rfk21TErImPYqa
    interceptUrlMap:
      -
        pattern: /
        httpMethod: GET
        access:
          - IS_AUTHENTICATED_ANONYMOUSLY
      -
        pattern: /books/grails
        httpMethod: GET
        access:
          - ROLE_GRAILS
      -
        pattern: /books/groovy
        httpMethod: GET
        access:
          - ROLE_GROOVY
endpoints:
  login:
    enabled: true
    sensitive: false
  token:
    enabled: true
    sensitive: false
  beans:
    enabled: true
    sensitive: true
  health:
    enabled: true
    sensitive: false
ldap:
  server: ldap.forumsys.com
  port: 389
  bindDN: cn=read-only-admin,dc=example,dc=com
  bindPassword: password