plugins {
    id "io.micronaut.build.internal.parent"
    id "io.micronaut.build.internal.dependency-updates"
    id "io.micronaut.build.internal.version-catalog-updates"
    id "io.micronaut.build.internal.convention-quality"
}

repositories {
    mavenCentral()
}

tasks.named("updateVersionCatalogs") {
    // we set the list to empty because we accept upgrades which improve the status
    rejectedQualifiers = []
    // Invalid POM files
    ignoredModules.add("io.micronaut.ignite:micronaut-ignite-core")
    ignoredModules.add("io.micronaut.ignite:micronaut-ignite-cache")
    // workaround Gradle variant selection problem
    ignoredModules.add("com.github.ben-manes.caffeine:caffeine")
}

if (System.getenv("SONAR_TOKEN") != null) {
    // deprecated and compile time only classes excluded from coverage
    def coverageExcludes = [
        "**/StreamSoftServiceLoader.java",
        "**/ServiceDescriptionProcessor.java",
        "**/GraalReflectionConfigurer.java",
        "**/graal/ServiceLoaderInitialization.java",
        "**/graal/ServiceLoaderInitialization.java",
        "**/DirectoryClassWriterOutputVisitor.java",
        "**/GroovyClassWriterOutputVisitor.java",
        "**/MutableHttpRequestWrapper.java",
        "**/tck/**",
        "**/test/support/**",
        "**/micronaut/annotation/processing/test/**"
    ]
    sonarqube {
        skipProject = project.name.contains("test")
        properties {
            property "sonar.exclusions", coverageExcludes.join(",")
        }
    }
}

configurations.jacocoAggregation.dependencies.removeIf {
    it instanceof ProjectDependency && it.path.startsWith(":test-")
}
configurations.javadocAggregatorBase.dependencies.removeIf {
    it instanceof ProjectDependency && it.path.startsWith(":test-")
}

configurations.configureEach {
    resolutionStrategy.eachDependency {
        if (requested.group == "org.apache.commons" && requested.name == "commons-lang3" && requested.version == "3.8.1") {
            useVersion("3.18.0")
            because("Sonatype scan flags commons-lang3:3.8.1 via CVE-2025-48924")
        }
        if (requested.group == "org.codehaus.plexus" && requested.name == "plexus-utils" && requested.version == "3.3.0") {
            useVersion("4.0.2")
            because("Sonatype scan flags plexus-utils:3.3.0 via CVE-2025-67030")
        }
    }
}
