The previous section presented a trivial example of what is possible with the ann:configuration.kafka.annotation.KafkaListener[] annotation.

Using the `@KafkaListener` annotation Micronaut will build a link:{kafkaapi}/org/apache/kafka/clients/consumer/KafkaConsumer.html[KafkaConsumer] and start the `poll` loop by running the `KafkaConsumer` in a special `consumer` thread pool. You can re-configure the size of the thread pool based on the number of consumers in your application in `application.yml` as desired:

.Configuring the `consumer` thread pool
[source,yaml]
----
micronaut:
    executors:
        consumer:
            type: fixed
            nThreads: 25
----

`KafkaConsumer` instances are single threaded, hence for each `@KafkaListener` method you define a new thread is created to execute the `poll` loop.

By default Micronaut will inspect the method signature of the method annotated with `@Topic` that will listen for `ConsumerRecord` instances and from the types infer an appropriate key and value link:{kafkaapi}/org/apache/kafka/common/serialization/Deserializer.html[Deserializer].
