Profiles can include commands for generating common code artifacts. Not all commands are supported by all profiles; the available commands for a given profile can be viewed using the `profile-info` command.

[source,bash]
----
mn> profile-info service
Profile: service
------------------
The service profile

Provided Commands:
------------------
  create-bean        Creates a singleton bean
  create-client      Creates a client interface
  create-controller  Creates a controller and associated test
  create-job         Creates a job with scheduled method
  help               Prints help information for a specific command

Provided Features:
------------------
...
----

All of the code-generation commands will honor the values written in `micronaut-cli.yml`. For example, assume the following `micronaut-cli.yml` file.

.micronaut-cli.yml
[source,yaml]
----
profile: service
defaultPackage: example
---
testFramework: spock
sourceLanguage: java
----

With the above settings, the `create-controller` command will (by default) generate Java controllers with an associated Spock test, under the `example` package. Commands accept arguments and these defaults can be overriden on a per-command basis.

== Base Profile Commands

Commands in the base profile are inherited by all other profiles and are always available.

=== Create-Bean

.Create-Bean Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the bean class
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-bean` command generates a simple {jeeapi}/javax/inject/Singleton.html[Singleton] class. It does not create an associated test.

[source,bash]
----
$ mn create-bean EmailService
| Rendered template Bean.java to destination src/main/java/example/EmailService.java
----

=== Create-Job

.Create-Job Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the job class
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-job` command generates a simple api:scheduling.annotation.Scheduled[] class. It follows a `*Job` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-job UpdateFeeds --lang groovy
| Rendered template Job.groovy to destination src/main/groovy/example/UpdateFeedsJob.groovy
----

== Service Profile Commands

The service profile includes commands that are dependent upon the HTTP server and client dependencies (which are not included in the base profile).

=== Create-Controller

.Create-Controller Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the controller
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-controller` command generates a link:{api}/io/micronaut/http/annotation/Controller.html[Controller] class. It follows a `*Controller` convention for generating the class name. It creates an associated test that will run the application and instantiate an HTTP client, which can make requests against the controller.

[source,bash]
----
$ mn create-controller Book
| Rendered template Controller.java to destination src/main/java/example/BookController.java
| Rendered template ControllerTest.java to destination src/test/java/example/BookControllerTest.java
----

=== Create-Client

.Create-Client Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the client
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-client` command generates a simple api:http.client.Client[] interface. It follows a `*Client` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-client Book
| Rendered template Client.java to destination src/main/java/example/BookClient.java
----


== CLI Profile Commands

The cli profile lets you generate CLI commands to control your application.

=== Create-Command

.Create-Command Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the command
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-command` command generates a standalone application that can be executed as a
http://picocli.info[picocli] link:http://picocli.info/apidocs/picocli/CommandLine.Command.html[Command].
It follows a `*Command` convention for generating the class name.
It creates an associated test that will run the application and verify that a command line option was set.

[source,bash]
----
$ mn create-command print
| Rendered template Command.java to destination src/main/java/example/PrintCommand.java
| Rendered template CommandTest.java to destination src/test/java/example/PrintCommandTest.java
----
