You can view a full list of available commands using the help flag, like this:

[source,bash]
----
$ mn -h
Usage: mn [-hvVx] [COMMAND]
Micronaut CLI command line interface for generating projects and services.
Application generation commands are: # <1>

*  create-app NAME
*  create-cli-app NAME
*  create-function-app NAME
*  create-grpc-app NAME
*  create-messaging-app NAME

Options:
  -h, --help         Show this help message and exit.
  -v, --verbose      Create verbose output.
  -V, --version      Print version information and exit.
  -x, --stacktrace   Show full stack trace when exceptions occur.

Commands: # <2>
  create-app             Creates an application
  create-cli-app         Creates a CLI application
  create-function-app    Creates a Cloud Function
  create-grpc-app        Creates a gRPC application
  create-messaging-app   Creates a messaging application
  create-test            Creates a simple test for the projects testing framework # <3>
  create-websocket-server  Creates a Websocket server
  create-client            Creates a client interface
  create-controller        Creates a controller and associated test
  create-bean              Creates a singleton bean
----

<1> Here you can see the project generation commands lists
<2> All commands available in the current directory are listed here
<3> **Note:** the things listed after the project creation commands (always available) will depend on the current directory context

All of the code-generation commands will honor the values written in `micronaut-cli.yml`. For example, assume the following `micronaut-cli.yml` file.

.micronaut-cli.yml
[source,yaml]
----
defaultPackage: example
---
testFramework: spock
sourceLanguage: java
----

With the above settings, the `create-bean` command will (by default) generate a Java class with an associated Spock test, under the `example` package. Commands accept arguments and these defaults can be overriden on a per-command basis.

== Base Commands

These commands are always available within the context of a micronaut project.

=== Create-Bean

.Create-Bean Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the bean class
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-bean` command generates a simple {jeeapi}/javax/inject/Singleton.html[Singleton] class. It does not create an associated test.

[source,bash]
----
$ mn create-bean EmailService
| Rendered template Bean.java to destination src/main/java/example/EmailService.java
----

=== Create-Job

.Create-Job Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the job class
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-job` command generates a simple api:scheduling.annotation.Scheduled[] class. It follows a `*Job` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-job UpdateFeeds --lang groovy
| Rendered template Job.groovy to destination src/main/groovy/example/UpdateFeedsJob.groovy
----

== HTTP-Related Commands

=== Create-Controller

.Create-Controller Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the controller
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-controller` command generates a link:{api}/io/micronaut/http/annotation/Controller.html[Controller] class. It follows a `*Controller` convention for generating the class name. It creates an associated test that will run the application and instantiate an HTTP client, which can make requests against the controller.

[source,bash]
----
$ mn create-controller Book
| Rendered template Controller.java to destination src/main/java/example/BookController.java
| Rendered template ControllerTest.java to destination src/test/java/example/BookControllerTest.java
----

=== Create-Client

.Create-Client Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the client
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-client` command generates a simple api:http.client.annotation.Client[] interface. It follows a `*Client` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-client Book
| Rendered template Client.java to destination src/main/java/example/BookClient.java
----

=== Create-Websocket-Server

.Create-Websocket-Server Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the server
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-websocket-server` command generates a simple api:websocket.WebSocketServer[] class. It follows a `*Server` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-websocket-server MyChat
| Rendered template WebsocketServer.java to destination src/main/java/example/MyChatServer.java
----


=== Create-Websocket-Client

.Create-Websocket-Client Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the client
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-websocket-client` command generates a simple api:websocket.WebSocketClient[] abstract class. It follows a `*Client` convention for generating the class name. It does not create an associated test.

[source,bash]
----
$ mn create-websocket-client MyChat
| Rendered template WebsocketClient.java to destination src/main/java/example/MyChatClient.java
----

== CLI Project Commands

=== Create-Command

.Create-Command Flags
|===
|Flag|Description|Example

|`-l`, `--lang`
|The language used for the command
|`--lang groovy`

|`-f`, `--force`
|Whether to overwrite existing files
|`--force`

|
|===

The `create-command` command generates a standalone application that can be executed as a
http://picocli.info[picocli] link:http://picocli.info/apidocs/picocli/CommandLine.Command.html[Command].
It follows a `*Command` convention for generating the class name.
It creates an associated test that will run the application and verify that a command line option was set.

[source,bash]
----
$ mn create-command print
| Rendered template Command.java to destination src/main/java/example/PrintCommand.java
| Rendered template CommandTest.java to destination src/test/java/example/PrintCommandTest.java
----

This list is just a small subset of all the code generation commands in the Micronaut CLI.
To see all the context-sensitive commands the CLI has available (and under what circumstances they apply), check out the
https://github.com/micronaut-projects/micronaut-starter[micronaut-starter] project and find the classes that
extend `CodeGenCommand`. The `applies` method dictates whether a command is available or not.