Creating a project is the primary usage of the CLI. There primary command for creating a new project is `create-app`. That will create a standard server application that communicates over HTTP. For other types of applications, see the documentation below.

.Micronaut CLI Project Creation Commands
[cols="1,2,2,4"]
|===
|Command|Description|Options|Example

|`create-app`
|Creates a basic Micronaut application.
a|
* `-l`, `--lang`
* `-t`, `--test`
* `-b`, `--build`
* `-f`, `--features`
* `-i`, `--inplace`
a|
[source,bash]
----
mn create-app my-project --features
 mongo-reactive,security-jwt --build maven
----

|`create-cli-app`
|Creates a command-line Micronaut application.
a|
* `-l`, `--lang`
* `-t`, `--test`
* `-b`, `--build`
* `-f`, `--features`
* `-i`, `--inplace`
a|
[source,bash]
----
mn create-cli-app my-project --features
 http-client,jdbc-hikari --build maven
 --lang kotlin --test kotlintest
----


|`create-function-app`
|Creates a Micronaut serverless function, using AWS by default.
a|
* `-l`, `--lang`
* `-t`, `--test`
* `-b`, `--build`
* `-f`, `--features`
* `-i`, `--inplace`
a|
[source,bash]
----
mn create-function-app my-lambda-function
 --lang groovy --test spock
----

|`create-messaging-app`
|Creates a Micronaut application that only communicates via a messaging protocol. Uses Kafka by default but can be switched to RabbitMQ with `--features rabbitmq`.
a|
* `-l`, `--lang`
* `-t`, `--test`
* `-b`, `--build`
* `-f`, `--features`
* `-i`, `--inplace`
a|
[source,bash]
----
mn create-messaging-app my-broker
 --lang groovy --test spock
----

|`create-grpc-app`
|Creates a Micronaut application that uses gRPC.
a|
* `-l`, `--lang`
* `-t`, `--test`
* `-b`, `--build`
* `-f`, `--features`
* `-i`, `--inplace`
a|
[source,bash]
----
mn create-grpc-app my-grpc-app
 --lang groovy --test spock
----

|===


== Create Command Flags

The create-* commands will generate a basic Micronaut project, with optional flags to specify features, language, test framework, and build tool. All projects except functions will include a default `Application` class for starting the application.


.Flags
[cols="2,3,3"]
|===
|Flag|Description|Example

|`-l`, `--lang`
|Language to use for the project (one of `java`, `groovy`, `kotlin` - default is `java`)
|`--lang groovy`

|`-t`, `--test`
|Test framework to use for the project (one of `junit`, `spock` - default is `junit`)
|`--test spock`

|`-b`, `--build`
|Build tool (one of `gradle`, `gradle_kotlin`, `maven` - default is `gradle` for the languages `java` and `groovy`; default is `gradle_kotlin` for language `kotlin`)
|`--build maven`

|`-f`, `--features`
|Features to use for the project, comma-separated
a|
[source,bash]
----
--features security-jwt,mongo-gorm
----
or
[source,bash]
----
-f security-jwt -f mongo-gorm
----

|`-i`, `--inplace`
|If present, generates the project in the current directory (project name is optional if this flag is set)
|`--inplace`

|===

Once created, the application can be started using the `Application` class, or the appropriate build tool task.

.Starting a Gradle project
[source,bash]
----
$ ./gradlew run
----

.Starting a Maven project
[source,bash]
----
$ ./mvnw mn:run
----

=== Language/Test Features

By default, the create commands will generate a Java application, with JUnit configured as the test framework. All of the options chosen and features applied are stored as properties in the `micronaut-cli.yml` file, as shown below:

.micronaut-cli.yml
[source,yaml]
----
applicationType: default
defaultPackage: com.example
testFramework: junit
sourceLanguage: java
buildTool: gradle
features: [annotation-api, app-name, application, gradle, http-client, java, junit, logback, netty-server, shade, yaml]
----

Some commands rely on the data in this file in order to determine if they should be executable. For example, the `create-kafka-listener` command requires `kafka` to be one of the features in the list.

NOTE: The values in `micronaut-cli.yml` are used by the CLI for code generation purposes. After a project has been generated, you can edit these values to change the project defaults, however you will still need to supply the required dependencies and/or configuration in order to use your chosen language/framework. E.g, you could edit the `testFramework` property to `spock` to cause the CLI to generate Spock tests when running commands (such as `create-controller`), but you will still need to add the Spock dependency to your project.

==== Groovy

To create an app with Groovy support (which comes with Spock by default), supply the appropriate language via the `lang` flag:

[source,bash]
----
$ mn create-app my-groovy-app --lang groovy
----

This will include the Groovy & Spock dependencies in your project, and write the appropriates values in `micronaut-cli.yml`.

==== Kotlin

To create an app with Kotlin support (which comes with Kotlintest by default), supply the appropriate language via the `lang` flag:

[source,bash]
----
$ mn create-app my-kotlin-app --lang kotlin
----

This will include the Kotlin & Kotlintest dependencies in your project, and write the appropriates values in `micronaut-cli.yml`.


=== Build Tool

By default `create-app` will create a Gradle project, with a `build.gradle` file at the root of the project directory. To create an app using the Maven build tool, supply the appropriate option via the `build` flag:

[source,bash]
----
$ mn create-app my-maven-app --build maven
----


== Create-Cli-App

The `create-cli-app` command will generate a <<commandLineApps,Micronaut command line application>> project,
with optional flags to specify language, test framework, features, profile, and build tool.
By default the project will have the `picocli` feature to support command line option parsing.
The project will include a `*Command` class (based on the project name - e.g., `hello-world` will generate `HelloWorldCommand`),
and an associated test which will instantiate the command and verify that it can parse command line options.

Once created, the application can be started using the `*Command` class, or the appropriate build tool task.

.Starting a Gradle project
[source,bash]
----
$ ./gradlew run
----

.Starting a Maven project
[source,bash]
----
$ ./mvnw mn:run
----

== Create Function App

The `create-function-app` command will generate a <<serverlessFunctions,Micronaut function>> project, optimized for serverless environments, with optional flags to specify language, test framework, features and build tool. The project will include a `*Function` class (based on the project name - e.g., `hello-world` will generate `HelloWorldFunction`), and an associated test which will instantiate the function and verify that it can receive requests.

TIP: Currently AWS Lambda, Micronaut Azure, and Google Cloud are the supported cloud providers for Micronaut functions. To use other providers, add one in the features: `--features azure-function` or `--features google-cloud-function`.

== Contribute

The CLI's source code is at https://github.com/micronaut-projects/micronaut-starter. Information about how to contribute and other resources are there.