Profiles are essentially project templates, consisting of a "skeleton" project structure with default configuration, build dependencies and other assets, along with a set of commands for generating appropriate artifacts (such as controllers, client interfaces, etc).

Profiles can inherit from other profiles, augmenting/overriding defaults set in their parent. All profiles inherit from the `base` profile, which provides the bare minimum required to set up a Micronaut application. Most Micronaut apps (including projects generated by the `create-app` command) will use the `service` profile, which augments the `base` profile to add HTTP client/server libraries, `create-controller` and `create-client` commands, and other features that are appropriate for web service applications.

Profiles can be chosen using the `profile` flag on the `create-app` & `create-federation` commands.

[source,bash]
----
$ mn create-app my-project
----

//TODO: Include more details from https://docs.grails.org/latest/guide/profiles.html, add section on creating profiles