This section covers the steps required to upgrade a Micronaut 2.x application to Micronaut 3.0.0.

=== Inject Annotations

The `javax.inject` annotations are no longer a transitive dependency. Micronaut now ships with the Jakarta inject annotations. To upgrade, either add a dependency on `javax-inject`, or replace all `javax.inject` imports with `jakarta.inject`.

dependency:javax.inject:javax.inject:1[]

Any code that relied on the inject annotations being present in the annotation metadata will still work as expected, however any code that interacts with them must be changed to no longer reference the annotation classes themselves. Static variables in the link:{api}/io/micronaut/core/annotation/AnnotationUtil.html[AnnotationUtil] class (e.g. `AnnotationUtil.INJECT`, `AnnotationUtil.SINGLETON`, etc.) should be used in place of the annotation classes when working with annotation metadata.

=== Nullability Annotations

Micronaut now only comes with its own set of annotations to declare nullability. The findbugs, javax, or jetbrains annotations are all still supported, however it will require an explicit dependency in your build to use them. To upgrade, either add a dependency for the annotation library you wish to use, or switch to the Micronaut ann:core.annotation.Nullable[] / ann:core.annotation.NonNull[] annotations.

=== RxJava2

Micronaut no longer ships any reactive implementation as a default in any of our modules or core libraries. Upgrading to Micronaut 3 requires choosing which reactive streams implementation to use, and then adding the relevant dependency.

For those already using RxJava3 or Project Reactor, there should be no changes required to upgrade to Micronaut 3. If you use RxJava2 and wish to continue using it, you must add a dependency:

dependency:io.micronaut.rxjava2:micronaut-rxjava2[gradleScope="implementation"]

In addition, if any of the `Rx` HTTP client interfaces were used, a dependency must be added and the imports must be updated.

dependency:io.micronaut.rxjava2:micronaut-rxjava2-http-clent[gradleScope="implementation"]

.RxJava2 HTTP Client Imports
|===
|Old |New

| io.micronaut.http.client.RxHttpClient
| io.micronaut.rxjava2.http.client.RxHttpClient

| io.micronaut.http.client.RxProxyHttpClient
| io.micronaut.rxjava2.http.client.proxy.RxProxyHttpClient

| io.micronaut.http.client.RxStreamingHttpClient
| io.micronaut.rxjava2.http.client.RxStreamingHttpClient

| io.micronaut.http.client.sse.RxSseClient
| io.micronaut.rxjava2.http.client.sse.RxSseClient

| io.micronaut.websocket.RxWebSocketClient
| io.micronaut.rxjava2.http.client.websockets.RxWebSocketClient

|===

If the Netty based server implementation is being used, another dependency must be added:

dependency:io.micronaut.rxjava2:micronaut-rxjava2-http-server-netty[gradleScope="implementation"]

NOTE: We recommend switching to Project Reactor as that is the implementation used internally by Micronaut. Adding a dependency to RxJava2 will result in both implementations in the runtime classpath of your application.
