//Micronaut {version} includes the following changes:
== 4.0.0

=== Apache Groovy 4.0

Micronaut Framework 4.x supports https://groovy-lang.org/releasenotes/groovy-4.0.html[Apache Groovy 4.0].

=== Core Changes

==== Java 17 Baseline

Micronaut 4 now requires a minimum of Java 17 for building and running applications. 

==== Improved Modularity

The core of Micronaut has been further refactored to improve modularity and reduce the footprint of a Micronaut application, including:

* Third-party dependencies on SnakeYAML and Jackson Databind are now optional and can be removed if other implementations are present.
* The runtime and compiler code has been split, allowing the removal of the re-packaging of ASM and Caffeine.
* The built in <<retry, Retry>>, <<serviceDiscovery, Service Discovery>>, <<sessions, HTTP Session>> and <<websocket, WebSocket>> features have been split into separate modules allowing removal of this functionality if not needed.

==== GraalVM Metadata Repository and Runtime Initialization

The https://graalvm.github.io/native-build-tools/latest/gradle-plugin.html#metadata-support[GraalVM Metadata Repository] in Micronaut's Gradle and Maven plugins is now enabled by default and Micronaut has been altered to by default primarily initialize at runtime to ensure consistency in behaviour between JIT and Native applications.

==== Completed `javax` to `jakarta` Migration

The remaining functionality depending on the `javax` specification has been migrated to `jakarta` including the validation module (for `jakarta.validation`) and support for Hibernate 6 (for `jakarta.persistence`).

==== Injection of Maps

It is now possible to inject a `java.util.Map` of beans where the key is the bean name. The name of the bean is derived from the <<qualifiers, qualifier>> or (if not present) the simple name of the class.

==== Arbitrary Nesting of Configuration Properties

With Micronaut 4 it is now possible to arbitrarily nest ann:context.annotation.ConfigurationProperties[] and ann:context.annotation.EachProperty[] annotations allowing for more dynamic configuration possibilities.

==== Improved Error Messages for Missing Configuration

When a bean is not present due to missing configuration (such as a bean that uses ann:context.annotation.EachProperty[]) error messages have been improved to display the configuration that is required to activate the bean.

==== Improved Error Messages for Missing Beans

When a bean annotated with ann:context.annotation.EachProperty[] or ann:context.annotation.Bean[] is not found due to missing configuration an error is thrown showing the configuration prefix necessary to resolve the issue.

=== HTTP Changes

==== Initial Support for Virtual Threads (Loom)

Preview <<virtualThreads, support for Virtual Threads>> has been added. When using JDK 19 or above with preview features enabled you can off load processing to a virtual thread pool.

==== Rewritten HTTP layer

The HTTP layer has been rewritten to improve performance and reduce the presence of reactive stack frames if reactive is not used (such as with Virtual threads).

=== Modules Upgrades

TODO:

- Micronaut AWS 3.5.3 to 3.7.0
- Micronaut Azure 3.2.3 to 3.3.0
- Micronaut Cache 3.4.1 to 3.5.0
- Micronaut Cassandra 4.0.0 to 5.1.1
- Micronaut Coherence 3.4.1 to 3.5.1
- Micronaut Data 3.4.3 to 3.7.2
- Micronaut Elasticsearch 4.2.0 to 4.3.0
- Micronaut Email 1.2.3 to 1.3.1
- Micronaut Flyway 5.3.0 to 5.4.0
- Micronaut GCP 4.2.1 to 4.4.0
- Micronaut GraphQL 3.0.0 to 3.1.0
- Micronaut Groovy 3.1.0 to 3.2.0
- Micronaut JaxRS 3.3.0 to 3.4.0
- Micronaut JMX 3.0.0 to 3.1.0
- Micronaut Kafka 4.3.1 to 4.4.0
- Micronaut Micrometer 4.3.0 to 4.4.0
- Micronaut Microstream 1.0.0-M1 to 1.0.0
- Micronaut Liquibase 5.3.0 to 5.4.1
- Micronaut Mongo 4.2.0 to 4.4.0
- Micronaut Neo4J 5.0.0 to 5.1.0
- Micronaut Nats 3.0.0 to 3.1.0
- Micronaut OpenAPI 4.2.2 to 4.4.3
- Micronaut Picocli 4.2.1 to 4.3.0
- Micronaut Problem 2.3.1 to 2.4.0
- Micronaut RabbitMQ 3.1.0 to 3.3.0
- Micronaut R2DBC 3.0.0 to 3.0.1
- Micronaut Reactor 2.2.3 to 2.3.1
- Micronaut Redis 5.2.0 to 5.3.0
- Micronaut RxJava3 2.2.1 to 2.3.0
- Micronaut Serialization 1.1.1 to 1.3.0
- Micronaut Servlet 3.2.3 to 3.3.0
- Micronaut Spring 4.1.1 to 4.2.1
- Micronaut SQL 4.4.1 to 4.6.3
- Micronaut Test 3.3.1 to 3.4.0
- Micronaut TOML 1.0.0 to 1.1.1
- Micronaut Tracing 4.1.1 to 4.2.1
- Micronaut Views 3.4.0 to 3.5.0
- Micronaut Jackson XML 3.0.1 to 3.1.0


