Micronaut {version} includes the following changes:

=== Core Features

==== Kotlin 1.4

Micronaut now ships with Kotlin 1.4 for those users using Kotlin.

==== Introspections for JDK 14 Records

It is now possible to define <<introspection, bean introspections>> on JDK 14+ record types (note these currently require the `––enable–preview` flag to the compiler and JVM).

==== Client Binding API

A new API has been created to allow for binding declarative HTTP client method arguments to an HTTP request. See the <<clientParameters, documentation>> for more information.

==== Websocket Improvements

Query parameters are now respected and bindable in the Micronaut websocket support.

==== HttpResponse Improvements

Cookies in HTTP responses from the client side are now retrievable on the HttpResponse. These are the cookies found in the `Set-Cookie` header.

==== Default Environment

Micronaut 2.1 introduces the concept of a default environment. One or more default environments can be set and they will apply if no other environments are explicitly specified. See the <<environments, environments documentation>> for information on how to use this new feature.


=== Module Upgrades

TODO

=== Dependency Upgrades

TODO
