//Micronaut {version} includes the following changes:
== 4.0.0

=== Kotlin 1.8.0

Micronaut framework 4.0 supports https://kotlinlang.org/docs/whatsnew18.html[Kotlin 1.8.0]

=== Experimental Support for Kotlin Symbol Processing (KSP)

Micronaut framework has offered support for Kotlin via <<kapt, KAPT>>. With version 4.0, Micronaut framework supports Kotlin also via <<ksp, Kotlin Symbol Processing (KSP) API>>.

=== Apache Groovy 4.0

Micronaut framework 4.x supports https://groovy-lang.org/releasenotes/groovy-4.0.html[Apache Groovy 4.0].

=== Core Changes

* <<virtualThreads, Support for Virtual Threads>>
* <<filtermethods, Filter Methods>>

* <<javanetClient, Additional implementation of the HTTP Client based on Java HTTP Client>>

==== Injection of Maps

It is now possible to inject a `java.util.Map` of beans where the key is the bean name. The name of the bean is derived from the <<qualifiers, qualifier>> or (if not present) the simple name of the class.

==== Improved Error Messages for Missing Beans

When a bean annotated with ann:context.annotation.EachProperty[] or ann:context.annotation.Bean[] is not found due to missing configuration an error is thrown showing the configuration prefix necessary to resolve the issue.

==== Tracking of Disabled Beans

Beans that are disabled via <<conditionalBeans, Bean Requirements>> are now tracked and an appropriate error thrown if a bean has been disabled.

The disabled beans are also now visible via the <<beansEndpoint, Beans Endpoint>> in the <<management, Management module>> aiding in understanding the state of your application configuration.

=== Other Dependency Upgrades

- Kotlin 1.7.10

<<breaks, Breaking changes in Micronaut framework 4.0>>

