Micronaut {version} includes the following changes:

=== Support for HTTP/2

Micronaut's Netty-based HTTP client and server have been updated to support HTTP/2.

See the <<http2Server, HTTP/2 documentation>> for more information on how to enable support for HTTP/2.

=== Micronaut Servlet

Micronaut now includes support for creating https://github.com/micronaut-projects/micronaut-servlet[Servlet applications] and users can use the command line to create an application that targets popular Servlet containers:

[source,bash]
----
$ mn create-app myapp --features jetty-server    # for Jetty
$ mn create-app myapp --features tomcat-server   # for Tomcat
$ mn create-app myapp --features undertow-server # for Undertow
----

=== Improved Support for Server-Side Content Negotiation

Micronaut will now correctly handle the HTTP `Accept` header and pick the most appropriate route for the specified accepted media types using https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[Server-Side Content Negotiation].

NOTE: This also applies to `@Error` routes making it possible to send different error responses for different content types

TIP: To add XML support use the https://github.com/micronaut-projects/micronaut-jackson-xml[Jackson XML] module

=== Improved Support for Cloud Foundry

Micronaut will now process the `VCAP_APPLICATION` and `VCAP_SERVICES` environment variables and treat them as property sources.

Thanks to https://github.com/fnonnenmacher[Fabian Nonnenmacher] for this contribution.

=== Event Loop Group Improvements

Micronaut 2.0 uses a new shared default Netty `EventLoopGroup` for server worker threads and client request threads. This reduces context switching and improves resource utilization.

See the <<clientConfiguration, HTTP Client Configuration>> section for information on how to configure the default `EventLoopGroup` and add additional `EventLoopGroup`'s that are configured per client.

=== HTTP Client Improvements

It is no longer necessary to use `@Client(..)` to inject a default api:http.client.RxHttpClient[] instance. You can now inject the default client simply with:

[source,java]
----
@Inject RxHttpClient client;
----

If no host is provided at the time of a request, a api:http.client.exceptions.NoHostException[] will be thrown.

=== Spot Bugs Instead of JSR-305 Nullable/NonNull Annotations

In Micronaut 1.x the Google distributed JSR-305 annotations library (`com.google.code.findbugs:jsr305`) was used to specify `@Nullable` and `@NonNull` on interfaces of the Micronaut API using the annotations contained within the `javax.annotation` package.

Due to the fact that JSR-305 has been cancelled and that this dependency has potential licensing issues (by using the `javax` namespace) as well as problems with the cross packages on Java 9+ with the module system Micronaut 2.x switches to the `spotbugs-annotations` module provided by the https://spotbugs.github.io/[SpotBugs project].

It is recommended users of Micronaut use this API instead (although the `javax.annotation.Nullable` and `javax.annotation.NotNull` annotations continue to be supported).

==== Module Upgrades

* Micronaut Neo4j - `1.3.0` -> `2.0.0`