Micronaut {version} includes the following changes:

=== Immutable `@ConfigurationProperties` and `@EachProperty`

Support for immutable ann:context.annotation.ConfigurationProperties[] has been added by annotating the constructor of any configuration class with ann:context.annotation.ConfigurationInject[]. See the docummentation on <<immutableConfig, Immutable Configuration>> for more information.

=== Kotlin Coroutine Support in Controller Methods

Support for <<coroutines, Kotlin Coroutines>> has been added such that you can define functions that use the `suspend` keyword in Kotlin controllers.

=== @Requires OS

The ann:context.annotation.Requires[] annotation now has support for disabling beans based on the current operating system.

=== Basic Auth binding support

In the client and server, an argument of type api:http.BasicAuth[] can be used to generate or parse a basic authorization header.

=== Request Certificate

For SSL requests, the certificate is now available as a request attribute. See api:http.HttpRequest#getCertificate--[HttpRequest#getCertificate]

=== Dependency Upgrades

Third Party Dependencies:

* ASM `7.0` -> `7.2`
* Caffeine `2.5.6` -> `2.8.0`
* Micrometer `1.2.1` -> `1.3.1`
* Mongo Reactive Driver `1.11.0` -> `1.12.0`
* Neo4j Java Driver `1.7.2` -> `1.7.5`
* Jackson `2.9.9` -> `2.10.1`
* Jaeger `0.35.5` -> `1.0.0`
* Reactive Streams `1.0.2` -> `1.0.3`
* Spring `5.1.8` -> `5.2.1`
* Zipkin/Brave `5.6.5` -> `5.9.0`

Modules:

* Micronaut GRPC `1.0.1` -> `1.1.0`
* Micronaut Micrometer `1.2.1` -> `1.3.0`
* Micronaut MongoDB `1.1.0` -> `1.2.0`
* Micronaut Neo4j `1.1.0` -> `1.2.0`
* Micronaut OpenAPI `1.2.0` -> `1.3.0`
* Micronaut Redis `1.1.0` -> `1.2.0`
* Micronaut SQL `1.2.3` -> `1.3.0`
* Micronaut Views `1.2.0` -> `1.3.0`
