Micronaut {version} includes the following changes:

=== Core Features

==== IO Stream Support

It is now possible to define a body argument of a controller method with an InputStream. For example `@Body InputStream inputStream`. Note that you must offload the execution to another thread pool to avoid blocking the event loop when reading the stream. `InputStream` can also be returned from controller methods. The stream will be read by Micronaut on the IO thread pool if the controller method is executed on the event loop.

==== HTTP to HTTPS redirect with Dual Protocol

If Dual Protocol is enabled, now it is possible to redirect all HTTP requests automatically to the HTTPS port. See more information <<dualProtocol, about how to enable and configure it>>.

==== GraalVM 21.1.0 Support

Micronaut has been updated to support the latest GraalVM 21.1.0 release with the Gradle and Maven plugins now defaulting to 21.1.0.

==== Support for JDK 16 and Gradle 7.0 in Micronaut Launch

https://micronaut.io/launch/[Micronaut Launch] has been updated with support for JDK 16 and Gradle 7.0.


==== Random Configuration Values

It is now possible to set a max and a range for random numbers in configuration. For example to set an integer between 0 and 9, `${random.int(10)}` can be used as the configuration value. See the <<propertySource, documentation>> under "Using Random Properties" for more information.

=== Module Upgrades

==== Micronaut Data 2.4.0

Huge https://micronaut-projects.github.io/micronaut-data/latest/guide/[Micronaut Data] update including many new features including:

- Full support for immutable entities. You can use Java 16 records or Kotlin immutable data classes
- Integrated support for R2DBC, now the `data-r2dbc` module is a part of the data project and shares the same code with JDBC
- Optimistic locking for JDBC/R2DBC
- Repositories now support batch insert/update/delete even with a custom query
- Rewritten entity mapper allows more complex mapping for JDBC/R2DBC entities
- Support for `@JoinTable` and `@JoinColumn` annotations
- A lot of bugfixes!

==== Micronaut Micrometer 3.4.0

The https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micrometer module] has been upgraded and now supports repeated definitions of the https://micrometer.io/docs/concepts#_the_timed_annotation[@Timed] annotation as well as also supporting the `@Counted` annotation for counters when you add the `micronaut-micrometer-annotation` dependency to your annotation processor classpath.

==== Micronaut Oracle Cloud 1.3.0

Micronaut's https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/[Oracle Cloud Integration] has been updated with support for Cloud Monitoring and Tracing.

==== Other Modules

- Micronaut Security 2.4.2
- Micronaut Azure 2.2.0
- Micronaut Aws 2.6.0
- Micronaut Grpc 2.4.0
- Micronaut OpenApi 2.4.0
- Micronaut Kafka 3.3.0
- Micronaut Flyway 3.6.0
- Micronaut Liquibase 3.3.1
- Micronaut Discovery Client 2.4.0
- Micronaut ElasticSearch 2.3.0

=== Dependency Upgrades

- Kafka 2.8.0
- GraalVM 21.1.0
- Liquibase 4.3.4
- Flyway 7.7.3
- Elasticsearch 7.12.0
