Micronaut {version} includes the following changes:

=== Build Features

==== Maven Plugin Improvements

TODO

==== Gradle Plugin Improvements

The Gradle plugin has a new `testNativeImage` task that builds the GraalVM Native Image and uses the native application as an embedded server enabling the ability to write native integration tests.

=== Micronaut Launch Enhancements

==== Push to Github

It is now possible to create an application with and https://micronaut.io/launch/[Micronaut Launch] and have it pushed automatically to Github, creating the necessary repository. When generating an application just select the "Push to Github" option.

=== New Micronaut Modules

==== MQTT Support

Micronaut now has integration with MQTT similar to the integration with Kafka and RabbitMQ. See the https://micronaut-projects.github.io/micronaut-mqtt/latest/guide/[Micronaut MQTT documentation] to get started.

==== Micronaut Data R2DBC

A new module that adds support for R2DBC has been added in preview status. Micronaut Data R2DBC lets you define reactive data repositories using R2DBC that work with any of the supported drivers and include support for GraalVM Native Image.

See the https://micronaut-projects.github.io/micronaut-r2dbc/1.0.x/guide/[Documentation for Micronaut R2DBC] for more information.

=== Module Upgrades

TODO

=== Dependency Upgrades

TODO
