//Micronaut {version} includes the following changes:

== 3.2.0

===  GraalVM 21.3.0

Micronaut has been updated to support the latest GraalVM 21.3.0 release. Please keep in mind that starting with 21.3.0 GraalVM doesn't release a version based on JDK 8. If you still use Java 8 use the GraalVM JDK 11 distribution.

The official GraalVM Maven plugin has new GAV coordinates so if you have declared it in your `pom.xml` update the coordinates to:

[source,xml]
----
<plugin>
    <groupId>org.graalvm.buildtools</groupId>
    <artifactId>native-maven-plugin</artifactId>
...
</plugin>
----

Please check https://graalvm.github.io/native-build-tools/0.9.7.1/maven-plugin.html[the official documentation] about how to customize the plugin.

=== Gradle plugin 3.0.0

A new major version of the Gradle plugin has been released, including internal changes to use Gradle's lazy configuration APIs and make bugfixing simpler.
In the process, https://micronaut-projects.github.io/micronaut-gradle-plugin/snapshot/[documentation] has been rewritten.

Support for GraalVM now delegates to https://graalvm.github.io/native-build-tools/0.9.7.1/gradle-plugin.html[the official GraalVM plugin].
This constitutes a breaking change for Micronaut users:

- the `nativeImage` task is now replaced with `nativeCompile`
- native image configuration happens in the `graalvmNative` DSL extension instead of the `nativeCompile` task
- native image building makes use of Gradle's toolchain support. Please refer to the https://micronaut-projects.github.io/micronaut-gradle-plugin/latest/[documentation] for help.

=== Kotlin 1.6.0

Micronaut 3.2.0 includes support for Kotlin 1.6.0.

== 3.1.0

=== Core Features

==== Primitive Beans

<<factories, Factory Beans>> can now create beans that are primitive types or primitive array types.

See the section on <<factories, Primitive Beans and Arrays>> in the documentation for more information.

==== Repeatable Qualifiers

<<qualifiers, Qualifiers>> can now be repeatable (an annotation annotated with `java.lang.annotation.Repeatable`) allowing narrowing bean resolution by a complete or partial match of the qualifiers declared on the injection point.

==== InjectScope

A new ann:context.annotation.InjectScope[] annotation has been added which destroys any beans with no defined scope and injected into a method or constructor annotated with `@Inject` after the method or constructor completes.

==== More Build Time Optimizations

Further build time metadata optimizations have been added included reducing the number and size of the classes generated to support <<introspection, Bean Introspection>> and including knowledge of repeatable annotations in generated metadata avoiding further reflective calls and optimizing Micronaut's memory usage, in particular with GraalVM.

==== Improvements to Context Propagation

Support for <<context,Reactive context propagation>> has been further improved by inclusion of request context information in the https://projectreactor.io/docs/core/release/reference/#context[Reactor context] and <<kotlinContextPropagation, documentation on how to effectively propagate the context across reactive flows>> when using Kotlin coroutines.

==== Improvements to the Element API

The build-time api:inject.ast.Element[] API has been improved in a number of ways:

* New methods were added to the api:inject.ast.MethodElement[] API to resolve the retriever type and throws declaration
* A new experimental API has been added to the api:inject.ast.ClassElement[] API  to resolve generic placeholders and resolve the generic bound to the element

=== HTTP Features

==== Filter By Regex

HTTP filters now support matching URLs by a regular expression. Set the `patternStyle` member of the annotation to `REGEX` and the value will be treated as a regular expression.

==== Random Port Binding

The way the server binds to random ports has improved and should result in fewer port binding exceptions in tests.

==== Client Data Formatting

The ann:core.convert.format.Format[] annotation now supports several new values that can be used in conjunction with the declarative HTTP client to support formatting data in several new ways. See the <<clientParameters, client parameters>> documentation for more information.

==== StreamingFileUpload

The api:http.multipart.StreamingFileUpload[] API has been improved to support streaming directly to an output stream. As with the other `transferTo` methods, the write to the stream is offloaded to the IO pool automatically.

==== Server SSL Configuration

The SSL configuration for the Netty server now responds to refresh events. This allows for swapping out certificates without having to restart the server. See the <<https, https documentation>> for information on how to trigger the refresh.

==== New Netty Server API

If you wish to programmatically start additional Netty servers on different ports with potentially different configurations, new APIs have been added to do so including a new api:http.server.netty.NettyEmbeddedServerFactory[] interface.

See the documentation on <<secondaryServers, Starting Secondary Servers>> for more information.

=== Deprecations

The `netty.responses.file.\*` configuration is deprecated in favor of `micronaut.server.netty.responses.file.*`. The old configuration key will be removed in the next major version of the framework.

=== Module Upgrades

==== Micronaut Data 3.1.0

- Kotlin's coroutines support. New repository interface `CoroutineCrudRepository`.
- Support for `AttributeConverter`
- R2DBC upgraded to `Arabba-SR11`
- JPA Criteria specifications

==== Micronaut JAX-RS 3.1

The https://micronaut-projects.github.io/micronaut-jaxrs/latest/guide/[JAX-RS module] now integrated with Micronaut Security allowing binding of the JAX-RS `SecurityContext`

==== Micronaut Kubernetes 3.1.0

Micronaut Kubernetes 3.1 introduces new annotation https://micronaut-projects.github.io/micronaut-kubernetes/latest/api/io/micronaut/kubernetes/client/informer/Informer.html[@Informer]. By using the annotation on the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/ResourceEventHandler.html[ResourceEventHandler] the Micronaut will instantiate the https://javadoc.io/doc/io.kubernetes/client-java/latest/io/kubernetes/client/informer/SharedIndexInformer.html[SharedInformer] from the official https://github.com/kubernetes-client/java[Kubernetes Java SDK]. Then you only need to take care of handling the changes of the watched Kubernetes resource. See more on https://micronaut-projects.github.io/micronaut-kubernetes/latest/guide/#kubernetes-informer[Kubernetes Informer].

==== Micronaut Oracle Coherence 3.0.0

The https://micronaut-projects.github.io/micronaut-coherence/latest/guide/[Micronaut Oracle Coherence] module is now out of preview status and includes broad integration with Oracle Coherence including support for caching, messaging and Micronaut Data.

== 3.0.0

=== Core Features

==== Optimized Build-Time Metadata

Micronaut 3.0 introduces a new build time metadata format that is more efficient in terms of startup and code size.

The result is significant improvements to startup and native image sizes when building native images with GraalVM Native Image.

It is recommended that users re-compile their applications and libraries with Micronaut 3.0 to benefit from these changes.

==== Support for GraalVM 21.2

Micronaut has been updated to support the latest GraalVM 21.2 release.

==== Jakarta Inject

The `jakarta.inject` annotations are now the default injection annotations for Micronaut 3

==== Support for JSR-330 Bean Import

Using the ann:context.annotation.Import[] annotation it is now possible to import bean definitions into your application where JSR-330 (either `javax.inject` or `jakarta.inject` annotations) are used in an external library.

See the documentation on <<beanImport, Bean Import>> for more information.

==== Support for Controlling Annotation Inheritance

api:core.annotation.AnnotationMetadata[] inheritance can now be controlled via Java's `@Inherited` annotation. If an annotation is not explicitly annotated with `@Inherited` it will not be included in the metadata. See the <<annotationMetadata, Annotation Inheritance>> section of the documentation for more information.

NOTE: This is an important behavioural change from Micronaut 2.x, see the <<breaks, Breaking Changes>> section for information on how to upgrade.

==== Support Narrowing Injection by Generic Type Arguments

Micronaut can now resolve the correct bean to inject based on the generic type arguments specified on the injection point:

snippet::io.micronaut.docs.inject.generics.Vehicle[tags="constructor",indent=0]

For more information see the section on <<qualifiers, Qualifying by Generic Type Arguments>>.

==== Support for using Annotation Members in Qualifiers

You can now use annotation members in qualifiers and specify which members should be excluded with the new ann:context.annotation.NonBinding[] annotation.

For more information see the section on <<qualifiers, Qualifying By Annotation Members>>.

==== Support for Limiting the Injectable Types

You can now limit the exposed types of a bean using the `typed` member of the ann:context.annotation.Bean[] annotation:

snippet::io.micronaut.docs.inject.typed.V8Engine[tags="class",indent=0]

For more information see the section on <<typed, Limiting Injectable Types>>.

==== Factories can produce bean from fields

Beans defined with the ann:context.annotation.Factory[] annotation can now produce beans from public or package protected fields, for example:

snippet::io.micronaut.docs.factories.VehicleMockSpec[tags="class",indent=0]

For more information see the <<factories, Bean Factories>> section of the documentation.

==== Enhanced `BeanProvider` Interface

The api:context.BeanProvider[] interface has been enhanced with new methods such as `iterator()` and `stream()` as well as methods to check for bean existence and uniqueness.

==== New `@Any` Qualifier for use in Bean Factories

A new ann:context.annotation.Any[] qualifier has been introduced to allow injecting any available instance into an injection point and can be used in combination with the new `BeanProvider` interface mentioned above to allow more dynamic behaviour.

snippet::io.micronaut.docs.qualifiers.any.Vehicle[tags="imports,clazz", indent=0, title="Using BeanProvider with Any"]

The annotation can also be used on ann:context.annotation.Factory[] methods to allow customization of how objects are injected via the api:inject.InjectionPoint[] API.

==== Support for Fields in Bean Introspections

Bean introspections on public or package protected fields are now supported:

snippet::io.micronaut.docs.ioc.beans.User[tags="class", indent=0]

For more information see the "Bean Fields" section of the <<introspection, Bean Introspections>> documentation.

==== `ApplicationEventPublisher` has now a generic event type

For the performance reasons it's advised to inject an instance of `ApplicationEventPublisher` with a generic type parameter - `ApplicationEventPublisher<MyEvent>`.

=== AOP Features

==== Support for Constructor Interception

It is now possible to intercept bean construction invocations through the api:aop.ConstructorInterceptor[] interface and ann:aop.AroundConstruct[] annotation.

See the section on <<lifecycleAdvise, Bean Life Cycle Advice>> for more information.

==== Support for `@PostConstruct` & `@PreDestroy` Interception

It is now possible to intercept `@PostConstruct` and `@PreDestroy` method invocations through the api:aop.MethodInterceptor[] interface and ann:aop.InterceptorBinding[] annotation.

See the section on <<lifecycleAdvise, Bean Life Cycle Advice>> for more information.


==== Random Configuration Values

It is now possible to set a max and a range for random numbers in configuration. For example to set an integer between 0 and 9, `${random.int(10)}` can be used as the configuration value. See the <<propertySource, documentation>> under "Using Random Properties" for more information.

==== Project Reactor used internally instead of RxJava2

Micronaut 3 uses internally https://projectreactor.io[Project Reactor] instead https://github.com/ReactiveX/RxJava[RxJava 2]. Project Reactor allows
Micronaut 3 to simplify instrumentation, thanks to https://projectreactor.io/docs/core/release/api/reactor/util/context/Context.html[Reactor's Context],  simplifies conversion login and eases the integration with R2DBC drivers. We recommend users to migrate to Reactor. However, it is possible to continue to use RxJava. See <<reactiveConfigs, Reactive Programming section>>.

=== Module Upgrades

==== Micronaut Data 3.1.0

- Kotlin's coroutines support. New repository interface `CoroutineCrudRepository`.
- Support for `AttributeConverter`
- R2DBC upgraded to `Arabba-SR11`
- JPA Criteria specifications

==== Micronaut Micrometer 4.0.0

The https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micrometer module] has been upgraded and now supports repeated definitions of the https://micrometer.io/docs/concepts#_the_timed_annotation[@Timed] annotation as well as also supporting the `@Counted` annotation for counters when you add the `micronaut-micrometer-annotation` dependency to your annotation processor classpath.

==== Micronaut Oracle Cloud 2.0.0

Micronaut's https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/[Oracle Cloud Integration] has been updated with support for Cloud Monitoring and Tracing.


==== Micronaut Cassandra 4.0.0

The https://micronaut-projects.github.io/micronaut-cassandra/latest/guide/[Micronaut Cassandra] integration now includes support for GraalVM out of the box.

==== Other Modules

- Micronaut Acme 3.0.0
- Micronaut Aws 3.0.0
- Micronaut Azure 3.0.0
- Micronaut Cache 3.0.0
- Micronaut Discovery Client 3.0.0
- Micronaut ElasticSearch 3.0.0
- Micronaut Flyway 4.1.0
- Micronaut GCP 4.0.0
- Micronaut GraphQL 3.0.0
- Micronaut Groovy 3.0.0
- Micronaut Grpc 3.0.0
- Micronaut Jackson XML 3.0.0
- Micronaut Jaxrs 3.0.0
- Micronaut JMX 3.0.0
- Micronaut Kafka 4.0.0
- Micronaut Kotlin 3.0.0
- Micronaut Kubernetes 3.0.0
- Micronaut Liquibase 4.0.2
- Micronaut Mongo 4.0.0
- Micronaut MQTT 2.0.0
- Micronaut Multitenancy 4.0.0
- Micronaut Nats Io 3.0.0
- Micronaut Neo4j 5.0.0
- Micronaut OpenApi 3.0.1
- Micronaut Picocli 4.0.0
- Micronaut Problem Json 2.0.0
- Micronaut R2DBC 2.0.0
- Micronaut RabbitMQ 3.0.0
- Micronaut Reactor 2.0.0
- Micronaut Redis 5.0.0
- Micronaut RSS 3.0.0
- Micronaut RxJava2 1.0.0 (new)
- Micronaut RxJava3 2.0.0
- Micronaut Security 3.0.0
- Micronaut Servlet 3.0.0
- Micronaut Spring 4.0.0
- Micronaut SQL 4.0.0
- Micronaut Test 3.0.0
- Micronaut Views 3.0.0

=== Dependency Upgrades

- Caffeine 2.9.1
- Cassandra 4.11.1
- Elasticsearch 7.12.0
- Flyway 7.12.1
- GraalVM 21.2.0
- H2 Database 1.4.200
- Hazelcast 4.2.1
- Hibernate 5.5.3.Final
- Hikari 4.0.3
- Infinispan 12.1.6.Final
- Jackson 2.12.4
- Jaeger 1.6.0
- Jakarta Annotation API 2.0.0
- JAsync 1.2.2
- JDBI 3.20.1
- JOOQ 3.14.12
- JUnit 5.7.2
- Kafka 2.8.0
- Kotlin 1.5.21
- Kotlin Coroutines 1.5.1
- Ktor 1.6.1
- Liquibase 4.4.3
- MariaDB Driver 2.7.3
- Micrometer 1.7.1
- MongoDB 4.3.0
- MS SQL Driver 9.2.1.jre8
- MySQL Driver 8.0.25
- Neo4j Driver 4.2.7
- Postgres Driver 42.2.23
- Reactor 3.4.8
- RxJava3 3.0.13
- SLF4J 1.7.29
- Snake YAML 1.29
- Spock 2.0-groovy-3.0
- Spring 5.3.9
- Spring Boot 2.5.3
- Testcontainers 1.15.3
- Tomcat JDBC 10.0.8
- Vertx SQL Drivers 4.1.1
