Micronaut {version} includes the following changes:

=== Core Features

==== Jakarta Inject

The `jakarta.inject` inject annotations are now supported as an alternative to `javax.inject`. Micronaut 3 will change the default inject annotations to Jakarta, however the javax annotations will continue to be supported if added to your build explicitly.

Micronaut 3 will change the bean context API to return our custom provider contract, api:context.BeanProvider[]. We suggest existing applications to change to use that interface instead of `javax.inject.Provider`, however both the `jakarta.inject.Provider` and `javax.inject.Provider` interfaces will continue to be supported.

==== Core Nullability Annotations

With the future of JSR-305 unclear and issues with regards to the module system with existing solutions, Micronaut 2.4 will replace usages of Spotbugs with core nullability annotations: ann:core.annotation.Nullable[] and ann:core.annotation.NotNull[].

Existing applications should switch to using these annotations. If other annotations are preferable, the dependency should be added explicitly to your build because no third party `Nullable` or `NonNull` annotations will be available transitively in the next major version.

==== Improvements to Interceptor Binding

Micronaut's support for AOP interceptors has been improved allowing interceptors to be attached to any annotation through the use of api:inject.annotation.AnnotationMapper[] instances. It is also now possible to bind multiple api:aop.MethodInterceptor[] instances to a single annotation instead of there being a 1-to-1 mapping between annotation and interceptor.

From 2.4.x onwards the recommending way to define AOP advise is to use the ann:aop.InterceptorBinding[] annotation on the annotation you wish to trigger AOP advise:

snippet::io.micronaut.docs.aop.around.NotNull[tags="imports,annotation", indent=0, title="Around Advice Annotation Example"]

Then use ann:aop.InterceptorBinding[] again on the api:aop.MethodInterceptor[] you wish to bind to the above advise:

snippet::io.micronaut.docs.aop.around.NotNullInterceptor[tags="imports,interceptor", indent=0, title="MethodInterceptor Example"]

Multiple api:aop.MethodInterceptor[] types can bind to a single advise annotation.

=== Cloud Features

==== Easier Configuration of Oracle Cloud Autonomous Database

A new `micronaut-oraclecloud-atp` has been added that makes it easier to https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#autonomousDatabase[automatically download the Oracle Wallet definition and connect to Autonomous Database] on Oracle Cloud.

==== Support for Oracle Cloud Monitoring via Micrometer

A new `micronaut-oraclecloud-micrometer` module has been added that adds support for https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#micrometer[exporting Micrometer metrics to Oracle Cloud].

==== Official Kubernetes Client

With the new `micronaut-kubernetes-client` module you can now inject apis objects from the https://github.com/kubernetes-client/java[official Kubernetes Java SDK] as regular beans.

In Micronaut 3 this new module will be used as primary kubernetes client, making the current one deprecated.

=== Module Upgrades

* Micronaut Oracle Cloud `1.1.1` -> `1.2.1`

=== Dependency Upgrades

* Jaeger Version `1.3.1` -> `1.5.0`
* Zipkin Version `2.15.0` -> `2.16.3`
