Micronaut {version} includes the following changes:

=== Core Features

==== Support for JDK 14

Micronaut has been updated to support JDK 14.

==== Groovy 3

Micronaut now supports applications written in Groovy 3.

==== Startup Performance Improvements

Startup time has been further improved in this release with typical startup time for a new application around 20% faster.

==== Improvements to Bean Introspections

Bean introspections have been improved to support static creator methods, interfaces and enums. This means you can define a bean introspection on an interface with a private implementation such as:

.Introspections on interfaces
[source,java]
----
import io.micronaut.core.annotation.Creator;

@io.micronaut.core.annotation.Introspected
interface Example {
    String getName();

    @Creator
    static Example create(String name) {
        return () -> name;
    }
}
----

==== Support for Analyzing the Injection Point

Micronaut's Dependency Injection implementation has been improved such that you can now receive an api:inject.InjectionPoint[] instance to any ann:context.annotation.Factory[] method. This makes it possible to customize how the bean is created based on the annotation metadata at the point at which the bean is injected.

For example consider the following definition:

[source,java]
----
@Inject @Client("http://foo.com") RxHttpClient client;
----

A factory method can receive the injection point and create a client based off of the value:

[source,java]
----
@Bean
protected DefaultHttpClient httpClient(InjectionPoint<?> injectionPoint) {
    String url = metadata.stringValue(Client.class).orElse(null);
    if (url != null) {
        return new DefaultHttpClient(url);
    } else {
        return new DefaultHttpClient();
    }
}
----

==== Support for Eager Initialization of Beans

Eager initialization of beans is useful in certain cases, such as on AWS Lambda where more CPU resources are assigned to Lamdba construction than execution. Therefore as for Micronaut 2.0, you can specify whether you want to eager initialization configuration or all singletons using the api:context.ApplicationContextBuilder[] interface:

.Enabling Eager Initialization
[source,java]
----
public class Application {

    public static void main(String[] args) {
        Micronaut.build(args)
            .eagerInitSingletons(true) // <1>
            .mainClass(Application.class)
            .start();
    }
}
----

<1> Setting eager init to true initializes all singletons

It is also possible to just eager init configuration using `eagerInitConfiguration` which will initialize all ann:context.annotation.ConfigurationProperties[] beans.

==== Spot Bugs Instead of JSR-305 Nullable/NonNull Annotations

In Micronaut 1.x the Google distributed JSR-305 annotations library (`com.google.code.findbugs:jsr305`) was used to specify `@Nullable` and `@NonNull` on interfaces of the Micronaut API using the annotations contained within the `javax.annotation` package.

Due to the fact that JSR-305 has been cancelled and that this dependency has potential licensing issues (by using the `javax` namespace) as well as problems with the cross packages on Java 9+ with the module system Micronaut 2.x switches to the `spotbugs-annotations` module provided by the https://spotbugs.github.io/[SpotBugs project].

It is recommended users of Micronaut use this API instead (although the `javax.annotation.Nullable` and `javax.annotation.NotNull` annotations continue to be supported).

=== CLI Features

==== New Native CLI

Micronaut's `mn` command for the CLI has been rewritten in Micronaut itself and is now compiled into a native image https://github.com/micronaut-projects/micronaut-starter/releases/tag/v{version}[available on Linux, MacOS X and Windows].

==== Micronaut Launch

Create Micronaut 2.0 applications without having the CLI installed using `curl`:

[source,bash]
----
$ curl https://launch.micronaut.io/demo.zip -o demo.zip
$ unzip demo.zip -d demo
----

Or by visiting https://launch.micronaut.io in your browser.

Run `curl https://launch.micronaut.io` for more instructions on how to use the API or visit the https://launch.micronaut.io/swagger/views/swagger-ui/index.html[OpenAPI documentation].

==== Diff Command

Run `mn feature-diff --features=[FEATURE NAME]` from the root of another Micronaut project to create a diff of the changes that need to be applied to enable the feature. For example:

.Using `feature-diff`
[source,bash]
----
$ mn feature-diff --features=azure-function
--- micronaut-cli.yml
+++ micronaut-cli.yml
@@ -3,4 +3,4 @@
 testFramework: junit
 sourceLanguage: java
 buildTool: gradle
-features: [app-name, application, gradle, http-client, java, junit, logback, netty-server, shade, yaml]
+features: [app-name, application, azure-function, azure-function-http, gradle, java, junit, logback, yaml]


--- host.json
+++ host.json
@@ -1,0 +1,7 @@
+{
+  "version": "2.0",
+  "extensionBundle": {
+    "id": "Microsoft.Azure.Functions.ExtensionBundle",
+    "version": "[1.*, 2.0.0)"
+  }
+}

----

=== Build Improvements

==== New Maven Parent POM

Micronaut now provides a new parent POM that can be used in Maven projects to get setup quickly:

.Using the Maven Parent POM
[source,xml]
----
<parent>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-parent</artifactId>
    <version>${micronaut.version}</version>
</parent>
----

==== New Maven Plugin

The parent POM mentioned above includes a new Micronaut Maven Plugin that enables automatic application restart during development. Just run the following:

[source,bash]
----
$ ./mvnw mn:run
----

Whenever you make a change to a class file the server will restart automatically.

==== Gradle 6.3 Update

For Gradle users who create new applications Gradle 6.3 is used which is compatible with JDK 14.

=== HTTP Features

==== Support for HTTP/2

Micronaut's Netty-based HTTP client and server have been updated to support HTTP/2.

See the <<http2Server, HTTP/2 documentation>> for more information on how to enable support for HTTP/2.


==== Threading Model and Event Loop Group Improvements

Micronaut 2.0 uses a new shared default Netty `EventLoopGroup` for server worker threads and client request threads. This reduces context switching and improves resource utilization.

See the <<clientConfiguration, HTTP Client Configuration>> section for information on how to configure the default `EventLoopGroup` and add additional `EventLoopGroup`'s that are configured per client.

In addition, as of Micronaut 2.0 all operations are by default executed on the `EventLoop` and users can optionally use the new ann:scheduling.annotation.ExecuteOn[] annotation to specify a named executor to execute an operation on if required (for example to offload blocking operations such as interactions with JPA/JDBC to a specific thread pool).

==== Support for `@RequestBean`

It is now possible to bind the properties of a POJO argument to a `@Controller` to request parameters, headers and so on using the ann:http.annotation.RequestBean[] annotation.

Thanks to Github user https://github.com/asodja[asodja] for this contribution.

==== Micronaut Servlet

Micronaut now includes support for creating https://github.com/micronaut-projects/micronaut-servlet[Servlet applications] and users can use the command line to create an application that targets popular Servlet containers:

[source,bash]
----
$ mn create-app myapp --features jetty-server    # for Jetty
$ mn create-app myapp --features tomcat-server   # for Tomcat
$ mn create-app myapp --features undertow-server # for Undertow
----

==== Improved Support for Server-Side Content Negotiation

Micronaut will now correctly handle the HTTP `Accept` header and pick the most appropriate route for the specified accepted media types using https://developer.mozilla.org/en-US/docs/Web/HTTP/Content_negotiation[Server-Side Content Negotiation].

NOTE: This also applies to `@Error` routes making it possible to send different error responses for different content types

TIP: To add XML support use the https://github.com/micronaut-projects/micronaut-jackson-xml[Jackson XML] module

==== Improved Support for Cloud Foundry

Micronaut will now process the `VCAP_APPLICATION` and `VCAP_SERVICES` environment variables and treat them as property sources.

Thanks to https://github.com/fnonnenmacher[Fabian Nonnenmacher] for this contribution.


==== HTTP Client Improvements

It is no longer necessary to use `@Client(..)` to inject a default api:http.client.RxHttpClient[] instance. You can now inject the default client simply with:

[source,java]
----
@Inject RxHttpClient client;
----

If no host is provided at the time of a request, a api:http.client.exceptions.NoHostException[] will be thrown.

==== API for Proxying Requests

A new API for writing API gateways and proxying requests has been added. See the documentation on the <<proxyClient, ProxyHttpClient>> for more information.

=== Serverless Improvements

==== Support for Google Cloud Function

You can now write Serverless functions that target Google Cloud Function using Micronaut. See the https://micronaut-projects.github.io/micronaut-gcp/2.0.x/guide/[Micronaut GCP] documentation and https://github.com/micronaut-projects/micronaut-gcp/tree/master/examples/hello-world-cloud-function[example application] for more information.

==== Support for Microsoft Azure Function

You can now write Serverless functions that target Microsoft Azure using Micronaut. See the https://micronaut-projects.github.io/micronaut-azure/1.0.x/guide/[Micronaut Azure] documentation and https://github.com/micronaut-projects/micronaut-azure/tree/master/examples/azure-functions-example[example application] for more information.

==== Improvements to Micronaut AWS

https://micronaut-projects.github.io/micronaut-aws/2.0.x/guide/#whatsNew[Micronaut AWS 2.0.0] includes a number of improvements to support for AWS Lambda and AWS in general including new client modules for AWS SDK 2.0, cold start improvements on Lambda and improvements to the support for Amazon Alexa.

=== Module Improvements

Micronaut is more modular than ever, with several components now available in separate modules and upgrades to those modules.

==== Micronaut Cache 2.0.0 Upgrade

Caching has been moved into a separate module and out of `micronaut-runtime`. If you need caching (including the annotations within `io.micronaut.cache.annotation`) you just need to add the individual module for the cache provider you are interested (for example Caffeine, Redis, Hazelcast etc.).

See the documentation for the https://micronaut-projects.github.io/micronaut-cache/2.0.x/guide/[Cache module] for more information.

==== Micronaut SQL 2.1.0 Upgrade

Micronaut SQL has been improved to default to Micronaut transaction management (making Spring management optional) and includes https://micronaut-projects.github.io/micronaut-sql/2.0.x/guide/#jdbi[support for Jdbi] (Thanks to https://github.com/drmaas[Dan Maas] for this contribution).

In addition, support has been added for https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[Oracle Universal Connection Pool]. Thanks to https://github.com/recursivecodes[Todd Sharp] for this contribution.

==== Micronaut Security 2.0.0 Upgrade

The security module has seen many changes to improve the API and introduce new features to support a wider array of use cases.

See the https://micronaut-projects.github.io/micronaut-security/2.0.x/guide[Security module] for more information.

==== New Reactive Modules

Whilst RxJava 2 remains the default, individual modules for other reactive libraries have been added.

For RxJava 3:

dependency:io.micronaut.rxjava3:micronaut-rxjava3[scope="compile"]

For Reactor:

dependency:io.micronaut.reactor:micronaut-reactor[scope="compile"]

And legacy support for RxJava 1:

dependency:io.micronaut.rxjava1:micronaut-rxjava1[scope="compile"]

Included within the new RxJava 3 and Reactor modules are variants of api:http.client.RxHttpClient[] called `Rx3HttpClient` and `ReactorHttpClient` respectively.

To use the RxJava 3 HTTP client add the following dependency:

dependency:io.micronaut.rxjava3:micronaut-rxjava3-http-client[scope="compile"]

To use the Reactor HTTP client add:

dependency:io.micronaut.rxjava3:micronaut-reactor-http-client[scope="compile"]

==== New Micronaut NATS module

A new messaging module for https://nats.io[Nats.io] has been included in Micronaut core.

See the documentation for https://micronaut-projects.github.io/micronaut-nats/latest/guide/[Micronaut Nats] for more information.

Thanks to https://github.com/grimmjo[Joachim Grimm] for this contribution.

==== Module Upgrades

* Micronaut Neo4j - `1.3.0` -> `2.0.0`
* Micronaut Mongo - `1.3.0` -> `2.0.0`
* Micronaut SQL - `1.3.0` -> `2.2.1`
* Micronaut Cache - `1.2.0` -> `2.0.0.RC1`
* Micronaut AWS - `1.3.9` -> `2.0.0.RC1`
* Micronaut Security - `1.4.0` -> `2.0.0.RC1`
* Micronaut Micrometer - `1.3.1` -> `2.0.0.RC2`
* Micronaut GCP - `1.1.0` -> `2.0.0.RC1`

==== Dependency Upgrades

* Hibernate `5.4.10.Final` -> `5.4.16.Final`
* Groovy `2.5.8` -> `3.0.3`
* Mongo Reactive Streams `1.13.0` -> `4.0.2`
* Mongo Java Driver `3.12.0` -> `4.0.2`
* Jaeger `1.0.0` -> `1.2.0`