Micronaut {version} includes the following changes:

=== Core Features

==== Jakarta Inject

The `jakarta.inject` inject annotations are now supported as an alternative to `javax.inject`. Micronaut 3 will change the default inject annotations to Jakarta, however the javax annotations will continue to be supported if added to your build explicitly.

Micronaut 3 will change the bean context API to return our custom provider contract, api:context.BeanProvider[]. We suggest existing applications to change to use that interface instead of `javax.inject.Provider`, however both the `jakarta.inject.Provider` and `javax.inject.Provider` interfaces will continue to be supported.

==== Core Nullability Annotations

With the future of JSR-305 unclear and issues with regards to the module system with existing solutions, Micronaut 2.4 will replace usages of Spotbugs with core nullability annotations: ann:core.annotation.Nullable[] and ann:core.annotation.NotNull[].

Existing applications should switch to using these annotations. If other annotations are preferable, the dependency should be added explicitly to your build because no third party `Nullable` or `NonNull` annotations will be available transitively in the next major version.

==== Improvements to Interceptor Binding

Micronaut's support for AOP interceptors has been improved allowing interceptors to be attached to any annotation through the use of api:inject.annotation.AnnotationMapper[] instances. It is also now possible to bind multiple api:aop.MethodInterceptor[] instances to a single annotation instead of there being a 1-to-1 mapping between annotation and interceptor.

From 2.4.x onwards the recommending way to define AOP advise is to use the ann:aop.InterceptorBinding[] annotation on the annotation you wish to trigger AOP advise:

snippet::io.micronaut.docs.aop.around.NotNull[tags="imports,annotation", indent=0, title="Around Advice Annotation Example"]

Then use ann:aop.InterceptorBean[] on the api:aop.MethodInterceptor[] you wish to bind to the above advise:

snippet::io.micronaut.docs.aop.around.NotNullInterceptor[tags="imports,interceptor", indent=0, title="MethodInterceptor Example"]

Multiple api:aop.MethodInterceptor[] types can bind to a single advise annotation and any given interceptor can bind to multiple annotations.

=== Micronaut Data

==== Support for Java 14+ Records with JDBC

Micronaut Data JDBC now https://micronaut-projects.github.io/micronaut-data/latest/guide/#javaRecords[supports using Java 14+ records to represent persistent entities], for example:

[source,java]
----
package example;

import edu.umd.cs.findbugs.annotations.Nullable;
import io.micronaut.data.annotation.*;
import java.util.Date;

@MappedEntity
record Book(
        @Id @GeneratedValue @Nullable Long id,
        @DateCreated @Nullable Date dateCreated,
        String title,
        int pages) {
    Book(String title, int pages) {
        this(null, null, title, pages)
    }
}
----

==== Persistence Events Support

Micronaut Data JPA, JDBC and R2DBC now support https://micronaut-projects.github.io/micronaut-data/latest/guide/#entityEvents[persistence events] on either entities or Micronaut beans. For example:

[source,java]
----
package example;

import io.micronaut.data.annotation.event.PrePersist;
import javax.inject.Singleton;

@Singleton
public class AccountUsernameValidator {
    @PrePersist
    void validateUsername(Account account) {
        final String username = account.getUsername();
        if (username == null || !username.matches("[a-z0-9]+")) {
            throw new IllegalArgumentException("Invalid username");
        }
    }
}
----

=== Integration with Oracle Coherence CE

We are pleased to announce a first milestone release of Micronaut integration with Oracle Coherence Community Edition, which makes implementation of Micronaut applications with a Coherence back end a breeze.

Below are some of the features supported by the various modules within `micronaut-coherence` project:

==== Micronaut Data Support

The `micronaut-coherence-data` module alows you to use https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#repository[Micronaut Data with Coherence as a back end data store].

==== Dependency Injection of Coherence-managed Objects

A new `micronaut-coherence` module provides factories for commonly used Coherence objects, such as `Cluster`, `Session`, `NamedMap`, `NamedCache`, `NamedTopic`, and many others, which allows you to https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#injection[easily inject those objects] into your application classes.

==== Listeners for Coherence Events

The `micronaut-coherence` module also provides support for Coherence https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#coherenceEvents[server-] and https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#mapEvents[client-side] events via Micronaut event listeners.

==== Micronaut Messaging Support

Finally, the `micronaut-coherence` module provides support for https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#messagingWithTopics[Micronaut Messaging using Coherence Topics].

==== Micronaut Caching Support

The `micronaut-coherence-cache` module adds support for https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#cache[using Coherence as a back end for Micronaut Cache].

==== Micronaut Distributed Config Support

The `micronaut-coherence-distributed-configuration` module adds support for https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#distributedConfiguration[using Coherence as a store for Micronaut Distributed Configuration].

==== Micronaut HTTP Sessions Support

The `micronaut-coherence-session` module adds support for https://micronaut-projects.github.io/micronaut-coherence/latest/guide/#coherenceHttpSessions[using Coherence as a store for Micronaut HTTP Sessions].

=== Cloud Features

==== Easier Configuration of Oracle Cloud Autonomous Database

A new `micronaut-oraclecloud-atp` has been added that makes it easier to https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#autonomousDatabase[automatically download the Oracle Wallet definition and connect to Autonomous Database] on Oracle Cloud.

==== Support for Oracle Cloud Monitoring via Micrometer

A new `micronaut-oraclecloud-micrometer` module has been added that adds support for https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#micrometer[exporting Micrometer metrics to Oracle Cloud].

==== Official Kubernetes Client

With the new `micronaut-kubernetes-client` module you can now inject apis objects from the https://github.com/kubernetes-client/java[official Kubernetes Java SDK] as regular beans.

In Micronaut 3 this new module will be used as primary kubernetes client, making the current one deprecated.

==== Micronaut AWS

Micronaut AWS now includes the new AWS SDK v2 that has support for GraalVM out of the box. Every service included in the module like S3, Parameter Store, SES, SQS,... is now compatible with Micronaut-GraalVM integration.

=== Module Upgrades

* Micronaut Oracle Cloud `1.1.1` -> `1.2.1`
* Micronaut Data `2.2.4` -> `2.3.0`
* Micronaut R2DBC `1.0.1` -> `1.1.0`
* Micronaut Kubernetes `2.2.0` -> `2.3.0`
* Micronaut AWS `2.3.0` -> `2.4.0`

=== Dependency Upgrades

* Jaeger Version `1.3.1` -> `1.5.0`
* Zipkin Version `2.15.0` -> `2.16.3`
