Micronaut {version} includes the following changes:

=== Support for GraalVM 19.3.0

Micronaut now supports creating native-images using GraalVM 19.3.0 for both JDK 8 and JDK 11.

=== Startup and Memory Usage Optimizations

Startup performance and memory usage (20%) have been improved.

=== Micronaut Data Integration

Micronaut Data has been added to the `micronaut-bom` and you can now use the CLI to create Micronaut Data projects:

.Setting up Micronaut Data JPA
[source,bash]
----
# add --build maven for maven
$ mn create-app myapp --features data-hibernate-jpa
----

.Setting up Micronaut Data JDBC
[source,bash]
----
# add --build maven for maven
$ mn create-app myapp --features data-jdbc
----

=== Initial Support for Kotlin Coroutines and Flow

Initial support for Kotlin Coroutines and the `Flow` type has been added when used as the return type of controller methods.

Thanks to https://github.com/konrad-kaminski[Konrad Kamiński] for this contribution.

=== Immutable `@ConfigurationProperties` and `@EachProperty`

Support for immutable ann:context.annotation.ConfigurationProperties[] has been added by annotating the constructor of any configuration class with ann:context.annotation.ConfigurationInject[]. See the documentation on <<immutableConfig, Immutable Configuration>> for more information.

snippet::io.micronaut.docs.config.itfce.EngineConfig[tags="imports,class",indent=0,title="@ConfigurationProperties Example"]

=== Ability to Configure Log Levels via Properties

Log levels can now be configured via properties defined in `application.yml` (and environment variables) with the `log.level` prefix:

[source,yaml]
----
logger:
    levels:
        foo.bar: ERROR
----

=== New Micronaut Cache Modules

https://micronaut-projects.github.io/micronaut-cache/1.0.x/guide/#introduction[Micronaut Cache] has been updated to support https://micronaut-projects.github.io/micronaut-cache/1.0.x/guide/#hazelcast[Hazelcast] and https://micronaut-projects.github.io/micronaut-cache/1.0.x/guide/#ehcache[Ehcache] as additional Cache providers.

=== New Micronaut Jackson XML Module

Support for parsing and serializing to XML has been added with a new https://github.com/micronaut-projects/micronaut-jackson-xml[Jackson XML module].

Thanks to https://github.com/svishnyakoff[Sergey] for this contribution.

=== Micronaut OpenAPI (Swagger) 1.3 Update

Micronaut OpenAPI has been updated with loads of improvements including the ability to https://micronaut-projects.github.io/micronaut-openapi/1.3.x/guide/index.html#openApiViews[automatically generate UIs for Swagger output] as part of your application. Thanks to https://github.com/croudet[croudet] for this contribution awesome contribution.

The module is also no longer regarded as experimental.

=== Micronaut Views 1.3 Update

Micronaut Views has been updated to and now features a new https://micronaut-projects.github.io/micronaut-views/1.3.x/guide/#soy[view renderer for Soy (Closure Templates)]. Thanks to https://github.com/sgammon[Sam Gammon] for this contribution.

=== Micronaut SQL 1.3 Update

Micronaut SQL includes the latest versions of Hibernate and adds support for the Vert.x MySQL and Postgres Clients. Thank you to https://github.com/shenzhou-6[shenzhou-6] for this contribution.

=== Micronaut Micrometer 1.3 Update

Micronaut Micrometer has been updated to support Micrometer 1.3.1.

=== Micronaut Kafka 1.4 Update

Micronaut Kafka 1.4 has been updated to support Kafka 2.4.0

=== Micronaut Neo4j 1.3 Update

Micronaut Neo4j 1.3 has been updated to support Neo4j Java Driver 1.7.5. In additional a new `2.0.0` version is available that supports Neo4j Java Driver 4.x line which is the latest version (in order to maintain semantic versioning the default is still 1.3 since the latest version includes changes to package names). See the https://micronaut-projects.github.io/micronaut-neo4j/latest/guide/[Micronaut Neo4j Documentation] for more information.

=== Micronaut GRPC 1.1 Update

Micronaut GRPC has been updated to the latest versions of GRPC and Protobuf.

=== @Requires OS

The ann:context.annotation.Requires[] annotation now has support for disabling beans based on the current operating system.

[source,java]
----
@Requires(os=Family.LINUX)
----

=== Basic Auth binding support

In the client and server, an argument of type api:http.BasicAuth[] can be used to generate or parse a basic authorization header.

[source,java]
----
@Post("/login")
String login(BasicAuth basicAuth) {
    ...
}
----

=== Request Certificate

For SSL requests, the certificate is now available as a request attribute. See api:http.HttpRequest#getCertificate--[HttpRequest#getCertificate]

=== Client Filter Matching By Annotation

Micronaut HTTP clients and client filters can now be matched by the presence of an annotation. Previously only URL matching was supported. See <<_filter_matching_by_annotation,the documentation>> to get started.

=== Dependency Upgrades

Required Third Party Dependencies:

* ASM `7.0` -> `7.2`
* Caffeine `2.5.6` -> `2.8.0`
* Jackson `2.9.9` -> `2.10.1`
* Reactive Streams `1.0.2` -> `1.0.3`

Optional Third Party Dependencies:

* Micrometer `1.2.1` -> `1.3.1`
* Mongo Reactive Driver `1.11.0` -> `1.13.0`
* Neo4j Java Driver `1.7.2` -> `1.7.5`
* Jaeger `0.35.5` -> `1.0.0`
* Kafka `2.3.0` -> `2.4.0`
* Spring `5.1.8` -> `5.2.3`
* Zipkin/Brave `5.6.5` -> `5.9.0`
* Groovy `2.5.7` -> `2.5.8`
* Gradle `5.5` -> `Gradle 6.1` (for new applications)
* Hibernate Core `5.4.6.Final` -> `5.4.10.Final`

Modules:

* Micronaut GRPC `1.0.1` -> `1.1.1`
* Micronaut Kafka `1.2.0` -> `1.4.0`
* Micronaut Micrometer `1.2.1` -> `1.3.0`
* Micronaut MongoDB `1.1.0` -> `1.2.0`
* Micronaut MongoDB `1.1.0` -> `1.3.0`
* Micronaut Neo4j `1.1.0` -> `1.3.0`
* Micronaut OpenAPI `1.2.0` -> `1.3.0`
* Micronaut Redis `1.1.0` -> `1.2.0`
* Micronaut SQL `1.2.3` -> `1.3.0`
* Micronaut Views `1.2.0` -> `1.3.0`

