Micronaut {version} includes the following changes:

=== Support for GraalVM 19.3.0

Micronaut now supports creating native-images using GraalVM 19.3.0 for both JDK 8 and JDK 11.

=== Native Bean Validation Support

Hibernate Validator is no longer a required dependency to activate bean validation, with a new <<beanValidation,native implementation of Bean Validation>> available that is reflection free and supports reactive and AST level validations now available.

The `micronaut-validation` dependency is all that it is needed now and provides the following benefits over Hibernate Validator:

* Reflection Free
* Compile Time Computed Bean Metadata resulting in lower memory requirements
* Reduction in JAR size by 2MB
* Reduction in startup time by 300ms which was the cost of initializing Hibernate validator
* Out-of-the-box GraalVM native image support
* Reduction in GraalVM native image size by 10MB

=== Reactive Bean Validation Support

In previous versions of Micronaut manual validation had to be applied to reactive flows. You can now declare `@Valid` on method parameters that receive a reactive type and validation will automatically be applied.

=== Implicit @Validated and @Valid

It is no longer necessary to apply the ann:validation.Validated[] annotation to beans that accept `@Valid` arguments or use any `javax.validation` annotation.

=== Micronaut Kubernetes 1.0 Release

There is a new https://micronaut-projects.github.io/micronaut-kubernetes/1.0.0/guide/[Micronaut Kubernetes] module, with an improved support for running Micronaut applications in a Kubernetes cluster, including support for Kubernetes' ``ConfigMap``s, ``Secret``s and more.

To get started, use the `kubernetes` feature:

----
mn create-app my-app --features kubernetes
----

=== Micronaut Security 1.2 Update

Support for OAuth 2.0 and OpenID clients has been added to the Micronaut security module through a new dependency: `micronaut-security-oauth2`. It is now very easy to add support for login through an OAuth providers. See the https://micronaut-projects.github.io/micronaut-security/latest/guide/#oauth[Oauth section] in the security documentation for more information.

=== Micronaut Micrometer 1.2 Update

https://micronaut-projects.github.io/micronaut-micrometer/1.2.x/guide/[Micronaut Micrometer has been updated to 1.2] which includes the following new features:

* Update to Micrometer 1.2.0
* Support for GraalVM native images
* Meter registry support for AppOptics, Azure Monitor, Datadog, Dynatrace, Elastic, Ganglia, Humio, Influx, Jmx, Kairos, New Relic, SignalFX, Stackdriver and Wavefront

Thanks to https://github.com/thiagolocatelli[Thiago Locatelli] for this contribution.

=== Micronaut SQL 1.2 Update

The https://micronaut-projects.github.io/micronaut-sql/1.2.x/guide/index.html[Micronaut SQL] module has been updated with support for the following new features:

* Improved Entity Scan support for JPA
* Integration with Micronaut 1.2 Validator for JPA
* GraalVM `native-image` metadata
* Support for https://www.jooq.org[JOOQ]. Thanks to https://github.com/lightoze[Vladimir Kulev].

=== Micronaut Kafka 1.2 Update

The https://micronaut-projects.github.io/micronaut-kafka/1.2.x/guide/index.html[Micronaut Kafka] module has been updated with support for the following new features:

* Support for Kafka 2.3.0
* Improved Exception Handling
* Support for GraalVM `native-image`

=== Micronaut Rabbit 1.1.1 Update

The https://micronaut-projects.github.io/micronaut-rabbitmq/1.1.x/guide/index.html[Micronaut RabbitMQ] module has been updated with support for GraalVM `native-image`.

=== Micronaut Test 1.1 Update

The https://micronaut-projects.github.io/micronaut-test/1.1.x/guide/index.html[Micronaut Test] module has been updated with support for the following new features:

* Updated to JUnit 5.5
* Support for Dependency Injection in Constructors and Methods for JUnit 5
* Support for https://github.com/kotlintest/kotlintest[Kotlin Test]

=== Optional Beans Returned from Factories

A ann:context.annotation.Factory[] bean can now return `null` if it is not possible to create the bean which will indicate to the dependency injection container that the bean does not exist. This allows for more complex logic within factory beans that can conditionally disable the bean if certain conditions are not met.

=== HashiCorp Vault Support

Initial support distributed configuration for https://www.vaultproject.io[HashiCorp Vault] has been added. See the documentation on <<distributedConfigurationVault,HashiCorp Vault Support>> for more information. Thanks to https://github.com/thiagolocatelli[Thiago Locatelli] for this contribution.

=== Oracle Cloud Support

Initial support for environment detection and cloud metadata for Oracle Cloud has been added. Thanks to https://github.com/recursivecodes[Todd Sharp] for this contribution.

=== @Client and Manual Service Discovery

If a service is configured statically with `micronaut.http.services.*`, it was previously not possible to override the configuration with the ann:http.client.annotation.Client[] annotation. It is now possible to override the configuration, which will result in a new client being created for the given client class.

=== Completable Support

The RxJava2 reactive type `io.reactivex.Completable` is now supported as a return type for controller and client methods.

=== Client and Server Host Resolution

New beans have been added to support lookup of the client address and the current server host. The implementations are aware of proxy headers and are configurable to look for custom headers. The api:http.server.util.HttpHostResolver[] can be injected to resolve the current server hostname and api:http.server.util.HttpClientAddressResolver[] can be injected to resolve the client address of the current request.

=== Default Implementation Support

When writing libraries for Micronaut, it is often the case that users will want to override part of your implementation. The most common way of doing so is creating custom beans that use the ann:context.annotation.Replaces[] annotation to replace your implementation. Because the ann:context.annotation.Replaces[] annotation requires a class argument to indicate which implementation to replace, it was required to make the implementation part of the public API. The class needed to be public because the user would need to reference the class directly in the annotation.

A new annotation has been added to solve this problem: ann:context.annotation.DefaultImplementation[]. See the section on <<replaces,Bean Replacements>> for more information.

=== HEAD Routes

For each route registered with the server that responds to GET requests, an additional route will be registered that responds to HEAD requests and will not include the body. This only applies to routes created by Micronaut through annotations. Any GET routes registered by custom route builders will not have corresponding HEAD routes added automatically.

=== Request Scope

A new bean scope has been created to allow for beans that only exist in the scope of a given HTTP request. See ann:runtime.http.scope.RequestScope[].

=== Environment Order and Priority

In previous versions of Micronaut, the property sources for an active environment had no priority over any other active environment. It was non deterministic which environment's properties would override other environments. Now the last environment supplied has the highest priority. For example, if an application is started with `-Dmicronaut.environments=first,second`, `application-second.yml` will override properties in `application-first.yml`. This change affects all sources of properties, including distributed configuration sources.

=== Environment Endpoint

This version includes a new `/env` endpoint with information about the environment and its property sources See the <<environmentEndpoint, documentation>> for more information.

=== RSS 2.0 Module Included in BOM

This version references the https://micronaut-projects.github.io/micronaut-rss/latest/guide/index.html[RSS configuration] which eases the generation of a RSS 2.0 feeds in a Micronaut app.

=== Dependency Upgrades

- Groovy `2.5.4` -> `2.5.6`
- Gradle `5.1.1` -> `Gradle 5.5` (for new applications)
- Micronaut SQL `1.1.1` -> `1.2.0`
- Micronaut Micrometer `1.1.0` -> `1.2.0`
- Micrometer `1.1.5` -> `1.2.0`
- Micronaut Security `1.1.1` -> `1.2.0`
- Micronaut Views `1.1.3` -> `1.2.0`
- Micronaut Test `1.0.4` -> `1.1.0`
- Netty `4.1.30.Final` -> `4.1.43.Final`
- Neo4j Driver `1.7.2` -> `1.7.5`
- Mongo Driver `3.8.0` -> `3.10.1`
- Mongo Reactive Streams `1.10.0` -> `1.11.0`
- Kafka `2.1.1` -> `2.3.0`
- Snake YAML `1.23` -> `1.24`
- Lettuce `5.1.3.RELEASE` -> `5.1.7.RELEASE`
- JUnit `5.3.2` -> `5.5.0`
- Picocli `3.5.2` -> `4.0.1`
- Jaeger `0.33.1` -> `0.35.5`
- Zipkin Reporter `2.8.4` -> `2.10.0`
- Open Tracing `0.31.0` -> `0.33.0`
