Micronaut {version} includes the following changes:

=== Core Features

==== Jakarta Inject

The `jakarta.inject` inject annotations are now supported as an alternative to `javax.inject`. Micronaut 3 will change the default inject annotations to Jakarta, however the javax annotations will continue to be supported if added to your build explicitly.

Micronaut 3 will change the bean context API to return our custom provider contract, api:context.BeanProvider[]. We suggest existing applications to change to use that interface instead of `javax.inject.Provider`, however both the `jakarta.inject.Provider` and `javax.inject.Provider` interfaces will continue to be supported.

==== Core Nullability Annotations

With the future of JSR-305 unclear and issues with regards to the module system with existing solutions, Micronaut 2.4 will replace usages of Spotbugs with core nullability annotations: ann:core.annotation.Nullable[] and ann:core.annotation.NotNull[].

Existing applications should switch to using these annotations. If other annotations are preferable, the dependency should be added explicitly to your build because no third party `Nullable` or `NonNull` annotations will be available transitively in the next major version.

=== Cloud Features

==== Easier Configuration of Oracle Cloud Autonomous Database

A new `micronaut-oraclecloud-atp` has been added that makes it easier to https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#autonomousDatabase[automatically download the Oracle Wallet definition and connect to Autonomous Database] on Oracle Cloud.

==== Support for Oracle Cloud Monitoring via Micrometer

A new `micronaut-oraclecloud-micrometer` module has been added that adds support for https://micronaut-projects.github.io/micronaut-oracle-cloud/latest/guide/#micrometer[exporting Micrometer metrics to Oracle Cloud].

=== Module Upgrades

* Micronaut Oracle Cloud `1.1.1` -> `1.2.1`

=== Dependency Upgrades

* Jaeger Version `1.3.1` -> `1.5.0`
* Zipkin Version `2.15.0` -> `2.16.3`
