Micronaut {version} includes the following changes:

=== Core Features

==== IO Stream Support

It is now possible to define a body argument of a controller method with an InputStream. For example `@Body InputStream inputStream`. Note that you must offload the execution to another thread pool to avoid blocking the event loop when reading the stream. `InputStream` can also be returned from controller methods. The stream will be read by Micronaut on the IO thread pool if the controller method is executed on the event loop.

==== HTTP to HTTPS redirect with Dual Protocol

If Dual Protocol is enabled, now it is possible to redirect all HTTP requests automatically to the HTTPS port. See more information <<dualProtocol, about how to enable and configure it>>.


=== Module Upgrades

==== Micronaut Micrometer 3.4.0

The https://micronaut-projects.github.io/micronaut-micrometer/latest/guide/[Micrometer module] has been upgraded and now supports repeated definitions of the https://micrometer.io/docs/concepts#_the_timed_annotation[@Timed] annotation as well as also supporting the `@Counted` annotation for counters when you add the `micronaut-micrometer-annotation` dependency to your annotation processor classpath.

=== Dependency Upgrades

TODO
