This section will document breaking changes between Micronaut 1.0 and Micronaut 2.0

=== @Executable No Longer Stereotype of @Around

In Micronaut 1.x the ann:context.annotation.Executable[] annotation was a meta-annotation specified on the ann:aop.Around[] and ann:aop.Introduction[] annotations. This meant that an api:inject.ExecutableMethod[] reference was generated for every usage of AOP advice which consumed additional memory unnecessarily.

In Micronaut 2.x and above this is no longer the case and if you need an api:inject.ExecutableMethod[] generated you should add the ann:context.annotation.Executable[] annotation to any custom AOP advice you specify otherwise the method will not be available via the api:inject.BeanDefinition[] interface (using for example the api:BeanDefinition.getExecutableMethods[] method).

=== Spot Bugs Instead of JSR-305 Nullable/NonNull Annotations

The JSR-305 annotations library (`com.google.code.findbugs:jsr305`) is no longer a dependency (replaced by `spotbugs-annotations`). If you need this library you will need to add it manually.

=== Events Renamed

The following events were renamed to avoid confusion with other events of similar names:

|===
| Old Name|New Name

| `io.micronaut.discovery.event.ServiceStartedEvent`
| api:discovery.event.ServiceReadyEvent[]

| `io.micronaut.discovery.event.ServiceShutdownEvent`
| api:discovery.event.ServiceStoppedEvent[]
|===

=== HTTP Clients No Longer Named Beans

HTTP clients declared with `micronaut.http.services` (see <<serviceDiscoveryManual,Manual Service Discovery Configuration>>) are no longer named beans in the context and cannot be injected with `javax.inject.Named`, for example given the configuration:

.Manually configuring services
[source,yaml]
----
micronaut:
    http:
        services:
            foo:
                urls:
                    - http://foo1
                    - http://foo2

----

You can lon longer inject an HTTP client with `@Named("foo")`:

[source,java]
----
@Inject
@Named("foo")
RxHttpClient httpClient;
----

Instead you should always use ann:http.client.annotation.Client[]:

[source,java]
----
@Inject
@Client("foo")
RxHttpClient httpClient;
----


=== Source Retention Annotations No Longer Retained in Runtime Metadata

In Micronaut 1.x annotations specified as source retention were still retained in the api:core.annotation.AnnotationMetadata[] interface. As of Micronaut 2.x this is no longer the case with source retention annotations only available within the compiler APIs.

If you wish to retain a particular source level annotation when upgrading you can write an api:inject.annotation.AnnotationTransformer[] that alters the `RetentionPolicy` of the annotation.

=== Iterable Beans No Longer Have An Implicit Primary

In Micronaut 1.x injecting a single instance of an iterable bean without qualifiers would inject the first bean. An iterable bean is typically anything annotated with `@EachProperty` or `@EachBean`. Those beans typically are referenced from configuration. The first bean in this context is the first item in configuration that matches what the annotation expects.

For example if you created a bean with `@EachProperty("cars")`, then specified the following in your config:

[source,yaml]
----
cars:
    ford:
        cylinders: 8
    subaru:
        cylinders: 4
----

Requesting a single instance of that bean would result in the "ford" instance being injected. Because that behavior is surprising and inconsistent with other types of beans, that is no longer the case and a `NonUniqueBeanException` will be thrown.

NOTE: This change does not apply to an explicit primary defined in the annotation (`@EachProperty(value = "cars", primary = "ford")`), nor requesting the instance by a qualifier (`@Named("ford") CarConfig carConfig`).

=== Invalid Configuration File Locations

Specifying a file with `micronaut.config.files`, either through the system property or environment variable, that does not exist or cannot be read will now result in the application failing to startup. In previous versions of Micronaut a warning would be logged and the file would be ignored.

=== Graal Dependency

The old Graal group name `com.oracle.substratevm` is no longer part of the Micronaut BOM.

=== PropertySourceLoader Changes

Some default interface methods are no longer default and require implementation.

=== Deprecation Removal

Most if not all deprecated classes and methods have been removed.
