To parse the request body, you first need to indicate to Micronaut the parameter which will receive the data. This is done with the api:http.annotation.Body[] annotation.

The following example implements a simple echo server that echos the body sent in the request:

.Using the @Body annotation
[source,java]
----
include::{testsuite}/server/body/MessageController.java[tags=imports, indent=0]

include::{testsuite}/server/body/MessageController.java[tags=class, indent=0]

include::{testsuite}/server/body/MessageController.java[tags=echo, indent=4]

}
----

<1> The api:io.micronaut.http.annotation.Post[] annotation is used with a api:http.MediaType[] of `text/plain` (the default is `application/json`).
<2> The api:http.annotation.Body[] annotation is used with a `javax.validation.constraints.Size` that limits the size of the body to at most 1MB
<3> The body is returned as the result of the method

Note that reading the request body is done in a non-blocking manner in that the request contents are read as the data becomes available and accumulated into the String passed to the method.

TIP: The `micronaut.server.maxRequestSize` setting in `application.yml` will limit the size of the data (the default maximum request size is 10MB) if no `@Size` constraint is specified.

Regardless of the limit, for a  large amount of data accumulating the data into a String in-memory may lead to memory strain on the server. A better approach is to include a Reactive library in your project (such as `RxJava 2.x`, `Reactor` or `Akka`) that supports the Reactive streams implementation and stream the data it becomes available:

.Using RxJava 2 to Read the request body
[source,java]
----
include::{testsuite}/server/body/MessageController.java[tags=echoReactive, indent=0]
----

<1> In this case the method is altered to receive and return an RxJava 2.x `Flowable` type
<2> A rx:Single[] is returned so that Micronaut will only emit the response once the operation completes without blocking.
<3> The `collect` method is used to accumulate the data in this simulated example, but it could for example write the data to logging service, database or whatever chunk by chunk


