To use Eclipse IDE, it is recommended you import your Micronaut project into Eclipse using either https://projects.eclipse.org/projects/tools.buildship[Gradle BuildShip] for Gradle or https://www.eclipse.org/m2e/[M2Eclipse] for Maven.

NOTE: The Micronaut framework requires Eclipse IDE 4.9 or higher

=== Eclipse and Gradle

Once you have set up Eclipse 4.9 or higher with https://projects.eclipse.org/projects/tools.buildship[Gradle BuildShip], first run the `gradle eclipse` task from the root of your project, then import the project by selecting `File -> Import` and choosing `Gradle -> Existing Gradle Project` and navigating to the root directory of your project (where the `build.gradle` file is located).

=== Eclipse and Maven

For Eclipse 4.9 and above with Maven you need the following Eclipse plugins:

* https://www.eclipse.org/m2e/[M2Eclipse for Maven]
* https://github.com/jbosstools/m2e-apt[Maven integration with Eclipse JDT Annotation Processor Toolkit]

Once these are installed, import the project by selecting `File -> Import` and choosing `Maven -> Existing Maven Project` and navigating to the root directory of your project (where the `pom.xml` file is located).

Then enable annotation processing by opening `Eclipse -> Preferences` and navigating to `Maven -> Annotation Processing` and selecting the option `Automatically configure JDT APT`.
