The Micronaut framework can be set up within Visual Studio Code in one of two ways.

==== Option 1) GraalVM Extension Pack for Java

The prefered way is using the https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm-pack[GraalVM Extension Pack for Java] which ships with an https://netbeans.apache.org/[Apache NetBeans] Language server.

NOTE: It is not possible to have both the official https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Java Extension Pack] and the GraalVM Extension Pack for Java installed at the same time so if you prefer the former, skip this section and go to Option 2)

The https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.graalvm[GraalVM Tools for Java] are preferred since they delegate to the build system for running applications and tests which means there is no additional setup or differences with regard to how javac is configured for annotation processing when compared to the https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Java Extension Pack] which is based on the Eclipse compiler.

The GraalVM Extension Pack also includes the https://marketplace.visualstudio.com/items?itemName=oracle-labs-graalvm.micronaut[GraalVM Tools for Micronaut] extension which features:

* An application creation wizard
* Code completion for YAML configuration
* Pallet commands to build, deploy, create Native Images etc.

==== Option 2) Red Hat/Microsoft Java Extension Pack

First install the https://marketplace.visualstudio.com/items?itemName=vscjava.vscode-java-pack[Java Extension Pack].

TIP: You can also optionally install https://marketplace.visualstudio.com/items?itemName=Pivotal.vscode-spring-boot[STS] to enable code completion for `application.yml`.

If you use Gradle, prior to opening the project in VSC run the following command from a terminal window:

[source,bash]
----
./gradlew eclipse
----

NOTE: If you don't run the above command beforehand then annotation processing will not be configured correctly and the application will not work.

Once the extension pack is installed just type `code .` in any project directory and the project will be automatically set up.

NOTE: For macOS, you need to install the `code` command https://code.visualstudio.com/docs/setup/mac[by following these instructions].
