package io.micronaut.ast.groovy.visitor


import io.micronaut.ast.transform.test.AbstractBeanDefinitionSpec
import io.micronaut.inject.ast.ClassElement
import io.micronaut.inject.ast.ElementQuery
import io.micronaut.inject.ast.EnumElement

class GroovyEnumElementSpec extends AbstractBeanDefinitionSpec {

    void "test is enum"() {
        given:
        def element = buildClassElement("""
package test

enum MyEnum {
    A, B
}
""")
        expect:
        element.isEnum()
        element.getPrimaryConstructor().get().getDeclaringType().isEnum()
    }

    void "test inner enum is enum"() {
        given:
        def element = buildClassElement("test.Foo","""
package test

class Foo {

    enum MyEnum {
        A, B
    }
}
""")
        expect:
        element.getEnclosedElement(ElementQuery.of(ClassElement.class)).get().getPrimaryConstructor().get().getDeclaringType().isEnum()
    }

    void "exclude Groovy autogenerated MAX_VALUE and MIN_VALUE"() {
        given:
        def element = (EnumElement) buildClassElement("""
package test

enum MyEnum {
    A, B
}
""")
        expect:
        !element.values().contains('MAX_VALUE')
        !element.values().contains('MIN_VALUE')
        element.values().size() == 2
    }

    void "get enum constant annotation"() {
        given:
        def element = (EnumElement) buildClassElement("""
package test

enum MyEnum {
    @io.micronaut.ast.groovy.visitor.EnumConstantAnn("C")
    A,
    B
}
""")
        expect:
        !element.values().contains('MAX_VALUE')
        !element.values().contains('MIN_VALUE')
        for (def enumConstant : element.elements()) {
            if (enumConstant.name != 'A') {
                continue
            }
            def enumConstantAnnotation = enumConstant.getAnnotation(EnumConstantAnn.class)
            enumConstantAnnotation != null
            enumConstantAnnotation.stringValue().get() == "C"
        }
    }
}
