package io.micronaut.ast.groovy.visitor

import io.micronaut.ast.transform.test.AbstractBeanDefinitionSpec
import io.micronaut.inject.ast.ClassElement
import io.micronaut.inject.ast.ElementQuery

class GroovyEnumElementSpec extends AbstractBeanDefinitionSpec {

    void "test is enum"() {
        given:
        def element = buildClassElement("""
package test

enum MyEnum {
    A, B
}
""")
        expect:
        element.isEnum()
        element.getPrimaryConstructor().get().getDeclaringType().isEnum()
    }

    void "test inner enum is enum"() {
        given:
        def element = buildClassElement("test.Foo","""
package test

class Foo {

    enum MyEnum {
        A, B
    }
}
""")
        expect:
        element.getEnclosedElement(ElementQuery.of(ClassElement.class)).get().getPrimaryConstructor().get().getDeclaringType().isEnum()
    }

    void "exclude Groovy autogenerated MAX_VALUE and MIN_VALUE"() {
        given:
        def element = (GroovyEnumElement) buildClassElement("""
package test

enum MyEnum {
    A, B
}
""")
        expect:
        !element.values().contains('MAX_VALUE')
        !element.values().contains('MIN_VALUE')
    }
}
