Kotlin coroutines allow you to create asynchronous applications with imperative style code. A Micronaut controller action can be a `suspend` function:

.Controller suspend function example
[source, kotlin]
----
include::{testsuitekotlin}/server/suspend/SuspendController.kt[tags="suspend", indent=0]
----

<1> The function is marked as `suspend`, though in reality it won't be suspended.

snippet::io.micronaut.docs.server.suspend.SuspendController.kt[tags="suspendDelayed", indent=0, title="Controller suspend function example"]

<1> The function is marked as `suspend`.
<2> The `delay` is called to make sure that a function is suspended and the response is returned from a different thread.

.Controller suspend function example
[source, kotlin]
----
include::{testsuitekotlin}/server/suspend/SuspendController.kt[tags="suspendStatus", indent=0]
----

<1> `suspend` function also works when all we want is to return a status.

.Controller suspend function example
[source, kotlin]
----
include::{testsuitekotlin}/server/suspend/SuspendController.kt[tags="suspendStatusDelayed", indent=0]
----

You can also use `Flow` type for streaming server and client. A streaming controller can return `Flow`, for example:

.Streaming JSON on the Server with Flow
[source, kotlin]
----
include::{testsuitekotlin}/streaming/HeadlineFlowController.kt[tags="streamingWithFlow", indent=0]
----

<1> A method `streamHeadlinesWithFlow` is defined that produces `application/x-json-stream`
<2> A `Flow` is created using `flow`
<3> This `Flow` emits 100 messages
<4> Emitting happens with `emit` `suspend` function
<5> There is a one second _delay_ between messages

A streaming client can simply return a `Flow`, for example:


.Streaming client with Flow
[source, kotlin]
----
include::{testsuitekotlin}/streaming/HeadlineFlowClient.kt[tags="imports,class, streamingWithFlow", indent=0]
----

<1> The `@Get` method is defined as processing responses of type `APPLICATION_JSON_STREAM`
<2> The return type is `Flow`
