Micronaut supports Session based authentication.

To use the Micronaut's session based authentication capabilities you must have the `security-session` dependency on your classpath. For example in `build.gradle`:

.build.gradle
[source,groovy]
----
compile "io.micronaut:security-session"
----

The following sequence illustrates the authentication flow:

image::sesssion_based_auth.svg[]

The following configuration properties are available to customize session based authentication behaviour:

|===

| Configuration Property | Default Value | Description

| `micronaut.security.session.enabled` | `false` | Session Authentication is disabled by default

| `micronaut.security.session.loginSuccessUrl` | `/` | URL where the user will be redirected ( 303 HTTP Status ) after login.

| `micronaut.security.session.loginFailureUrl` | `/` | URL where the user will be redirected ( 303 HTTP Status ) after an unsuccessful login attempt.

| `micronaut.security.session.logoutTargetUrl` | `/` | URL where the user will be redirected ( 303 HTTP Status ) after logout.

| `micronaut.security.session.unauthorizedTargetUrl` | `/` | URL where the user will be redirected ( 303 HTTP Status ) after an attempt to a access secured rule.

| `micronaut.security.session.forbiddenTargetUrl` | `/` | URL where the user will be redirected ( 303 HTTP Status ) after an attempt to a access secured rule but lacking enough privileges.

|===

See the api:security.session.SecuritySessionConfigurationProperties[] javadoc for more information.

== Example of Session-Based Authentication configuration

[source, yaml]
----
include::{testssecuritysession}/security/session/SessionAuthenticationSpec.groovy[tag=yamlconfig,indent=0]
----

TIP: Read the http://guides.micronaut.io/micronaut-security-session/guide/index.html[Session-Based Authentication Micronaut Guide] to learn more.