/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.annotation.processing.test.jdt

import groovy.json.JsonSlurper
import io.micronaut.annotation.processing.test.JavaFileObjects
import io.micronaut.annotation.processing.test.JavaParser
import io.micronaut.core.annotation.AnnotationMetadata
import io.micronaut.core.annotation.AnnotationValue
import io.micronaut.core.beans.BeanIntrospection
import io.micronaut.core.type.Argument
import io.micronaut.inject.BeanDefinition
import io.micronaut.inject.ExecutableMethod
import io.micronaut.inject.FieldInjectionPoint
import io.micronaut.inject.MethodInjectionPoint
import io.micronaut.inject.annotation.AbstractAnnotationMetadataBuilder
import spock.lang.Specification

import javax.tools.JavaFileObject

/**
 * Base class for specifications that compile the same source with javac and with the Eclipse JDT
 * compiler and assert that the annotation processors produced equivalent metadata.
 *
 * <p>The two compilers are both standards compliant, but they differ in the areas the
 * {@code javax.lang.model} specification leaves open - most notably the ordering of
 * {@link javax.lang.model.element.TypeElement#getEnclosedElements()}. Any difference in the
 * generated metadata is therefore a bug in Micronaut, not in the compiler.</p>
 *
 * @since 5.2.0
 */
abstract class AbstractCompilerParitySpec extends Specification {

    /**
     * Compiles the given sources with both compilers and asserts the resulting bean definitions and
     * introspections are described identically.
     *
     * @param className The name of the primary class
     * @param source The source code
     */
    protected void assertParity(String className, String source) {
        assertParity([(className): source])
    }

    /**
     * Compiles the given sources with both compilers and asserts the resulting bean definitions and
     * introspections are described identically.
     *
     * @param sources A map of class name to source
     */
    protected void assertParity(Map<String, String> sources) {
        String withJavac = describe(new JavaParser(), sources)
        String withJdt = describe(new JdtParser(), sources)
        if (withJavac != withJdt) {
            throw new AssertionError(
                    "Metadata generated by javac and the Eclipse JDT compiler differ.\n" +
                            renderDiff(withJavac, withJdt) as Object)
        }
    }

    /**
     * Compiles the given sources and returns a class loader over the generated classes.
     *
     * @param parser The parser to compile with
     * @param sources A map of class name to source
     * @return The class loader
     */
    protected static GeneratedClassLoader compile(JavaParser parser, Map<String, String> sources) {
        AbstractAnnotationMetadataBuilder.clearMutated()
        JavaFileObject[] files = sources.collect { JavaFileObjects.forSourceString(it.key, it.value) } as JavaFileObject[]
        return new GeneratedClassLoader(parser.generate(files))
    }

    /**
     * Compiles the sources and renders every generated bean definition and introspection as a
     * stable, comparable string.
     *
     * @param parser The parser to compile with
     * @param sources A map of class name to source
     * @return The description
     */
    protected static String describe(JavaParser parser, Map<String, String> sources) {
        try (parser) {
            AbstractAnnotationMetadataBuilder.clearMutated()
            JavaFileObject[] files = sources.collect { JavaFileObjects.forSourceString(it.key, it.value) } as JavaFileObject[]
            def generated = parser.generate(files)
            def classLoader = new GeneratedClassLoader(generated)
            def names = classLoader.generatedClassNames
            def out = new StringBuilder()
            out.append("generated classes:\n")
            names.toSorted().each { out.append("  ").append(it).append('\n') }
            out.append("generated resources:\n")
            generated.findAll { JavaFileObject it -> !it.name.endsWith('.class') }
                    .collect { JavaFileObject it -> resourcePath(it) }
                    .toSorted()
                    .each { out.append("  ").append(it).append('\n') }
            generated.findAll { JavaFileObject it -> isTextResource(it) }
                    .toSorted { JavaFileObject a, JavaFileObject b -> resourcePath(a) <=> resourcePath(b) }
                    .each { JavaFileObject it ->
                        out.append("resource ").append(resourcePath(it)).append('\n')
                        out.append(readResource(it)).append('\n')
                    }
            names.toSorted().each { String name ->
                if (name.endsWith('$Definition')) {
                    out.append(describeBeanDefinition(
                            (BeanDefinition) classLoader.loadClass(name).getDeclaredConstructor().newInstance()))
                } else if (name.endsWith('$Introspection')) {
                    out.append(describeIntrospection(
                            (BeanIntrospection) classLoader.loadClass(name).getDeclaredConstructor().newInstance()))
                }
            }
            // The index in the name of a generated evaluated expression class comes from a counter
            // that is static for the JVM rather than per compilation, so it keeps counting up
            // across the two compilations this comparison performs.
            return out.toString().replaceAll('\\$Expr\\d+', '\\$Expr<n>')
        }
    }

    private static String resourcePath(JavaFileObject file) {
        String name = file.name
        int i = name.indexOf('/CLASS_OUTPUT/')
        return i > -1 ? name.substring(i + '/CLASS_OUTPUT/'.length()) : name
    }

    private static boolean isTextResource(JavaFileObject file) {
        String path = resourcePath(file)
        return path.endsWith('.json') || path.startsWith('META-INF/services/')
    }

    private static String readResource(JavaFileObject file) {
        String content
        try {
            content = file.getCharContent(true).toString()
        } catch (Exception e) {
            return "<unreadable: ${e.message}>"
        }
        if (!resourcePath(file).endsWith('.json')) {
            return content
        }
        // The order in which the processors visit the classes of a compilation is up to the
        // compiler, so the order the entries of a metadata file contributed by *different*
        // classes appear in is not meaningful. Canonicalise it; the ordering that does matter
        // (the members of a single type) is asserted through the bean definitions and
        // introspections instead.
        try {
            return canonicalJson(new JsonSlurper().parseText(content))
        } catch (Exception e) {
            return content
        }
    }

    private static String canonicalJson(Object value) {
        if (value instanceof Map) {
            return ((Map<?, ?>) value).collect { k, v -> "${k}=${canonicalJson(v)}" }.toSorted().toString()
        }
        if (value instanceof List) {
            return ((List<?>) value).collect { canonicalJson(it) }.toSorted().toString()
        }
        return String.valueOf(value)
    }

    private static String describeBeanDefinition(BeanDefinition definition) {
        def out = new StringBuilder()
        out.append("bean definition ").append(definition.beanType.name).append('\n')
        out.append("  singleton: ").append(definition.singleton).append('\n')
        out.append("  scope: ").append(definition.scope.map { it.name }.orElse('none')).append('\n')
        out.append("  annotations: ").append(describeAnnotationMetadata(definition.annotationMetadata)).append('\n')
        out.append("  type arguments: ").append(definition.typeArguments.collect { describeArgument(it) }).append('\n')
        def constructor = definition.constructor
        out.append("  constructor:\n")
        constructor.arguments.eachWithIndex { Argument arg, int i ->
            out.append("    [").append(i).append("] ").append(describeArgument(arg)).append('\n')
        }
        out.append("  injected fields:\n")
        definition.injectedFields.toSorted { FieldInjectionPoint a, FieldInjectionPoint b -> a.name <=> b.name }
                .each { FieldInjectionPoint field ->
                    out.append("    ").append(field.name).append(' ')
                            .append(describeAnnotationMetadata(field.annotationMetadata)).append('\n')
                }
        out.append("  injected methods:\n")
        definition.injectedMethods.toSorted { MethodInjectionPoint a, MethodInjectionPoint b -> a.name <=> b.name }
                .each { MethodInjectionPoint method ->
                    out.append("    ").append(method.name).append('(')
                            .append(method.arguments.collect { describeArgument(it) }.join(', ')).append(") ")
                            .append(describeAnnotationMetadata(method.annotationMetadata)).append('\n')
                }
        out.append("  executable methods:\n")
        definition.executableMethods.toSorted { ExecutableMethod a, ExecutableMethod b ->
            (a.name + a.argumentTypes*.name.join(',')) <=> (b.name + b.argumentTypes*.name.join(','))
        }.each { ExecutableMethod method ->
            out.append("    ").append(describeArgument(method.returnType.asArgument())).append(' ')
                    .append(method.name).append('(')
                    .append(method.arguments.collect { describeArgument(it) }.join(', ')).append(") ")
                    .append(describeAnnotationMetadata(method.annotationMetadata)).append('\n')
        }
        out.append("  required components: ")
                .append(definition.requiredComponents.collect { it.name }.toSorted()).append('\n')
        return out.toString()
    }

    private static String describeIntrospection(BeanIntrospection introspection) {
        def out = new StringBuilder()
        out.append("introspection ").append(introspection.beanType.name).append('\n')
        out.append("  annotations: ").append(describeAnnotationMetadata(introspection.annotationMetadata)).append('\n')
        out.append("  constructor:\n")
        introspection.constructorArguments.eachWithIndex { Argument arg, int i ->
            out.append("    [").append(i).append("] ").append(describeArgument(arg)).append('\n')
        }
        out.append("  properties (declaration order):\n")
        introspection.beanProperties.each { property ->
            out.append("    ").append(property.name)
                    .append(" : ").append(describeArgument(property.asArgument()))
                    .append(" readOnly=").append(property.readOnly)
                    .append(" writeOnly=").append(property.writeOnly)
                    .append(' ').append(describeAnnotationMetadata(property.annotationMetadata)).append('\n')
        }
        return out.toString()
    }

    private static String describeArgument(Argument<?> argument) {
        def out = new StringBuilder()
        out.append(argument.name).append(':').append(argument.type.name)
        if (argument.typeParameters.length > 0) {
            out.append('<').append(argument.typeParameters.collect { describeArgument(it) }.join(', ')).append('>')
        }
        out.append(' ').append(describeAnnotationMetadata(argument.annotationMetadata))
        return out.toString()
    }

    private static String describeAnnotationMetadata(AnnotationMetadata metadata) {
        if (metadata == null || metadata.isEmpty()) {
            return '{}'
        }
        def names = metadata.annotationNames.toSorted()
        def rendered = names.collect { String name ->
            AnnotationValue<?> value = metadata.getAnnotation(name)
            if (value == null) {
                return name
            }
            def values = value.values.collectEntries { k, v -> [(k.toString()): renderValue(v)] }
                    .sort { it.key }
            return values.isEmpty() ? name : "$name$values"
        }
        def stereotypes = metadata.stereotypeAnnotationNames.toSorted()
        return "{annotations=$rendered, stereotypes=$stereotypes}"
    }

    private static String renderValue(Object v) {
        if (v == null) {
            return 'null'
        }
        if (v instanceof Object[]) {
            return ((Object[]) v).collect { renderValue(it) }.toString()
        }
        if (v instanceof AnnotationValue) {
            def av = (AnnotationValue) v
            return av.annotationName + av.values.collectEntries { k, o -> [(k.toString()): renderValue(o)] }.sort { it.key }
        }
        return v.toString()
    }

    private static String renderDiff(String javac, String jdt) {
        def javacLines = javac.readLines()
        def jdtLines = jdt.readLines()
        def out = new StringBuilder()
        int max = Math.max(javacLines.size(), jdtLines.size())
        for (int i = 0; i < max; i++) {
            String a = i < javacLines.size() ? javacLines[i] : '<missing>'
            String b = i < jdtLines.size() ? jdtLines[i] : '<missing>'
            if (a != b) {
                out.append("  javac: ").append(a).append('\n')
                out.append("  jdt  : ").append(b).append('\n')
            }
        }
        if (out.length() == 0) {
            out.append("(line counts differ only)\n")
        }
        return out.toString()
    }
}
