When operating Microservices in production it can be challenging to troubleshoot interactions between Microservices in a distributed architecture.

To solve this problem, a way to visualize interactions between Microservices in a distributed manner can be critical. Currently there are various distributed tracing solutions, the most popular of which are https://zipkin.io[Zipkin] and https://www.jaegertracing.io/[Jaeger], both of which provide different levels of support for the http://opentracing.io[Open Tracing] API.

Micronaut features integration with both Zipkin and Jaeger (via the Open Tracing API).

To enable tracing, add the `tracing` module to your build:

dependency:micronaut-tracing[]

== Tracing Annotations

The pkg:tracing.annotation[] package contains annotations that can be declared on methods to create new spans or continue existing spans.

The available annotations are:

* The ann:tracing.annotation.NewSpan[] annotation creates a new span, wrapping the method call or reactive type.
* The ann:tracing.annotation.ContinueSpan[] annotation continues an existing span, wrapping the method call or reactive type.
* The ann:tracing.annotation.SpanTag[] annotation can be used on method arguments to include the value of the argument within a Span's tags. When you use `@SpanTag` on an argument, you need either to annotate the method with `@NewSpan` or `@ContinueSpan`.

The following snippet presents an example of using the annotations:

.Using Trace Annotations
[source,java]
----
@Singleton
class HelloService {

    @NewSpan("hello-world") // <1>
    public String hello(@SpanTag("person.name") String name) { // <2>
        return greet("Hello " + name);
    }

    @ContinueSpan // <3>
    public String greet(@SpanTag("hello.greeting") String greet) {
        return greet;
    }
}
----

<1> The ann:tracing.annotation.NewSpan[] annotation starts a new span
<2> Use ann:tracing.annotation.SpanTag[] to include method arguments as tags for the span
<3> Use the ann:tracing.annotation.ContinueSpan[] annotation to continue an existing span and incorporate additional tags using `@SpanTag`

=== Tracing Instrumentation

In addition to explicit tracing tags, Micronaut includes a number of instrumentations to ensure that the Span context is propagated between threads and across Microservice boundaries.

These instrumentations are found in the `io.micronaut.tracing.instrument` package and include HTTP <<clientFilter, Client Filters>> and <<filters, Server Filters>> to propagate the necessary headers via HTTP.

== Tracing Beans

If the Tracing annotations and existing instrumentations are not sufficient, Micronaut's tracing integration registers a `io.opentracing.Tracer` bean which exposes the Open Tracing API and can be dependency-injected as needed.

Depending on the implementation you choose, there are also additional beans. For example for Zipkin `brave.Tracing` and `brave.SpanCustomizer` beans are available too.
