Service Discovery enables the ability for Microservices to find each other without necessarily knowing the physical location or IP address of associated services.

There are many ways Service Discovery can be implemented, including:

* You could manually implement Service Discovery using DNS without requiring a third party tool or component.
* You could use a discovery server such as https://github.com/Netflix/eureka[Eureka], https://www.consul.io[Consul] or https://zookeeper.apache.org[ZooKeeper].
* You could delegate the work to a container runtime, such as https://kubernetes.io[Kubernetes].

With that in mind Micronaut tries to flexible to support all of these approaches. As of this writing Micronaut features integrated support for the popular Service Discovery servers Eureka and Consul.

To include Service Discovery in your application simply the first step is to add the `discovery-client` dependency to your application, for example in `build.gradle`:

.build.gradle
[source,groovy]
----
compile "io.micronaut:discovery-client"
----

The `discovery-client` dependency provides implementations of the api:discovery.DiscoveryClient[] interface.

The api:discovery.DiscoveryClient[] is fairly simple and provides two main entry points:

* api:discovery.DiscoveryClient.getServiceIds()[] - Returns all discovered service IDs
* api:discovery.DiscoveryClient.getInstances(java.lang.String)[] - Returns all the api:discovery.ServiceInstance[] objects for a given service ID

Both methods return rs:Publisher[] instances since the operation to retrieve service ID information may result in a blocking network call depending on the underlying implementation.

The default implementation of the `DiscoveryClient` interface is api:discovery.client.CachingCompositeDiscoveryClient[] which merges all other `DiscoveryClient` beans into a single bean and provides caching of the results of the methods. The default behaviour is to cache for 30 seconds. This cache can be disabled in application configuration:

.Disabling the Discovery Client Cache
[source,yaml]
----
micronaut:
    caches:
        discovery-client:
            enabled: false
----

Alternatively you can alter the cache's expiration policy:

.Configuring the Discovery Client Cache
[source,yaml]
----
micronaut:
    caches:
        discovery-client:
            expireAfterAccess: 60s
----

See the api:discovery.client.DiscoveryClientCacheConfiguration[] class for available configuration options.