=== Picocli Feature

To create a project with Picocli support using the Micronaut CLI, supply the `picocli` feature to the `features` flag.

----
> mn create-app my-picocli-app --features picocli
----

This will create a project with the minimum necessary configuration for picocli.

=== Cli Profile

The Micronaut CLI includes a specialized profile for picocli-based command line applications. This profile will create a Micronaut app with picocli support, and _without_ an HTTP server (although you can add one if you desire). The profile also provides a command for generating picocli commands and subcommands.

To create a project using the cli profile, use the `--profile=cli` flag:

----
> mn create-app my-cli-app --profile cli
----

Don't build the project yet, let's first create a command.

Within the new project, you can now run the picocli-specific code generation commands:

----
> cd example
> ../mn
mn> create-command example.my-command
| Rendered template Command.java to destination src/main/java/example/MyCommand.java
| Rendered template CommandTest.java to destination src/test/java/example/MyCommandTest.java
----

The generated command looks like this:

.example.MyCommand.java generated by `create-command`
[source,java]
----
package example;

import io.micronaut.configuration.picocli.PicocliRunner;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(name = "my-command", description = "...",
        mixinStandardHelpOptions = true) // <1>
public class MyCommand implements Runnable { // <2>

    @Option(names = {"-v", "--verbose"}, description = "...") // <3>
    boolean verbose;

    public static void main(String[] args) throws Exception {
        PicocliRunner.run(MyCommand.class, args); // <4>
    }

    public void run() { // <5>
        // business logic here
        if (verbose) {
            System.out.println("Hi!");
        }
    }
}
----
<1> The picocli link:https://picocli.info/apidocs/picocli/CommandLine.Command.html[@Command] annotation designates this class as a command. The `mixinStandardHelpOptions` attribute adds `--help` and `--version` options to it.
<2> By implementing `Runnable` or `Callable` your application can be executed in a single line (<4>) and picocli takes care of handling invalid input and requests for usage help (`<cmd> --help`) or version information (`<cmd> --version`).
<3> An example option. Options can have any name and be of https://picocli.info/#_strongly_typed_everything[any type]. The generated code contains this example boolean flag option that lets the user request more verbose output.
<4> `PicocliRunner` lets picocli-based applications leverage the Micronaut DI container. `PicocliRunner.run` first creates an instance of this command with all services and resources injected, then parses the command line, while taking care of handling invalid input and requests for usage help or version information, and finally invokes the `run` method.
<5> Put the business logic of the application in the `run` or `call` method.

Before building the project, open the `gradle.build` file, and change the `mainClassName` line to:
----
mainClassName = "example.MyCommand"
----

TIP: The above step is only needed in M3 and won't be necessary in future releases.

=== Running the Application

Now you can build the project and start the application. The build will create a `${project-name}-all.jar` with all dependencies in `build/libs`.
Running this jar from Java will run the `MyCommand`.

----
> java -jar build/libs/example-0.1-all.jar -v
----
