=== Create-Cli-App Command
To create a project with picocli support using the Micronaut CLI, use the `create-cli-app` command.
This will add the dependencies for the `picocli` feature, and set the profile of the generated project to `cli`, so the `create-command` command is available to generate additional commands.

The main class of the project is set to the `*Command` class (based on the project name - e.g., `hello-world` will generate `HelloWorldCommand`):

----
$ mn create-cli-app my-cli-app
----

The generated command looks like this:

.my.cli.app.MyCliAppCommand.java generated by `create-cli-app`
[source,java]
----
package my.cli.app;

import io.micronaut.configuration.picocli.PicocliRunner;
import io.micronaut.context.ApplicationContext;

import picocli.CommandLine;
import picocli.CommandLine.Command;
import picocli.CommandLine.Option;
import picocli.CommandLine.Parameters;

@Command(name = "my-cli-app", description = "...",
        mixinStandardHelpOptions = true) // <1>
public class MyCliAppCommand implements Runnable { // <2>

    @Option(names = {"-v", "--verbose"}, description = "...") // <3>
    boolean verbose;

    public static void main(String[] args) throws Exception {
        PicocliRunner.run(MyCliAppCommand.class, args); // <4>
    }

    public void run() { // <5>
        // business logic here
        if (verbose) {
            System.out.println("Hi!");
        }
    }
}
----
<1> The picocli link:https://picocli.info/apidocs/picocli/CommandLine.Command.html[@Command] annotation designates this class as a command. The `mixinStandardHelpOptions` attribute adds `--help` and `--version` options to it.
<2> By implementing `Runnable` or `Callable` your application can be executed in a single line (<4>) and picocli takes care of handling invalid input and requests for usage help (`<cmd> --help`) or version information (`<cmd> --version`).
<3> An example option. Options can have any name and be of https://picocli.info/#_strongly_typed_everything[any type]. The generated code contains this example boolean flag option that lets the user request more verbose output.
<4> `PicocliRunner` lets picocli-based applications leverage the Micronaut DI container. `PicocliRunner.run` first creates an instance of this command with all services and resources injected, then parses the command line, while taking care of handling invalid input and requests for usage help or version information, and finally invokes the `run` method.
<5> Put the business logic of the application in the `run` or `call` method.


=== Running the Application

Now you can build the project and start the application. The build will create a `${project-name}-all.jar` with all dependencies in `build/libs`.
Running this jar from Java will run the generated `MyCliAppCommand`.

----
$ java -jar build/libs/my-cli-app-0.1-all.jar -v
----


=== Picocli Feature

Alternatively, to create a project with picocli support using the Micronaut CLI, supply the `picocli` feature to the `features` flag.

----
$ mn create-app my-picocli-app --features picocli
----

This will create a project with the `service` profile that has the minimum necessary configuration for picocli.

Note that no command is generated and the main class of the project is set to the default `Application` class.

=== Cli Profile

It is also possible to create a project with the `create-app` command and the `--profile=cli` flag.
This will create a Micronaut app with picocli support, without an HTTP server (although you can add one if you desire).
The `cli` profile provides a command for generating picocli commands and subcommands.

----
$ mn create-app example --profile cli
----

Note that the main class of the project is set to the default `Application` class.

If you want a picocli command to be the main class of this application, you need to first generate a command with `create-command`:

----
$ cd example
$ ../mn
mn> create-command example.my-command
| Rendered template Command.java to destination src/main/java/example/MyCommand.java
| Rendered template CommandTest.java to destination src/test/java/example/MyCommandTest.java
----


Then open the `gradle.build` file, and change the `mainClassName` line to the fully qualified class name of the command:
----
mainClassName = "example.MyCommand"
----

TIP: The `create-cli-app` command is more convenient, since it generates a project that includes a command from the beginning and sets the main class to this command.
