/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aop.internal;

import io.micronaut.aop.Interceptor;
import io.micronaut.context.BeanRegistration;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.UsedByGeneratedCode;

import java.util.List;

/**
 * Provides interceptor registrations retained by a generated proxy for lifecycle interception.
 *
 * <p>The AOP proxy writer implements this interface only on proxies whose target has post-construct or pre-destroy
 * interceptor bindings. The generated proxy stores the same registration list that was resolved for its constructor.
 * When lifecycle advice runs, the runtime reads that list and lets the {@code InterceptorRegistry} select registrations
 * applicable to the current lifecycle kind. This avoids resolving a second prototype interceptor for the same target.</p>
 *
 * <p>This is generated-code infrastructure, not an application extension point. Proxies generated by older Micronaut
 * versions do not implement this interface; the runtime detects that case and uses the original interceptor-resolution
 * path, preserving upgrade compatibility.</p>
 *
 * @author Denis Stepanov
 * @since 5.2.0
 */
@Internal
@UsedByGeneratedCode
public interface InterceptorRegistrationProvider {

    /**
     * Returns the interceptor registrations resolved for the proxy.
     *
     * <p>The returned list is the retained candidate set. The interceptor registry still filters it by binding and
     * interceptor kind before invoking a lifecycle chain.</p>
     *
     * @return The interceptor registrations resolved for the proxy
     */
    @SuppressWarnings("checkstyle:MethodName")
    List<BeanRegistration<Interceptor<?, ?>>> $getInterceptorRegistrations();
}
