defaults: &defaults
  working_directory: ~/repo
  docker:
    - image: circleci/openjdk:8-jdk-browsers
  environment:
    GRADLE_USER_HOME: ~/repo/.gradle


version: 2
jobs:
  checkout:
    <<: *defaults

    steps:
      - restore_cache:
          keys:
            - repo-v1-{{ .Branch }}-{{ .Revision}}
            - repo-v1-{{ .Branch }}-
            - repo-v1-

      - checkout

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*

  test:
    <<: *defaults

    steps:
      - attach_workspace:
          at: ~/repo


      - run:
          name: Gradle Check without Test-Suite:Test
          command: ./gradlew --console=plain check -x test-suite:test --no-daemon

      - run:
          name: Gradle Test-Suite:test
          command: ./gradlew --console=plain test-suite:test --no-daemon
          
      - run:
          name: Files
          command: find . -type f -name "*.xml" | grep "build/test-results"
          when: always

      - run:
          name: Test Results Folder
          command: mkdir ~/test-results
          when: always          

      - run:
          name: Copy Test Results
          command: find . -type f -name "*.xml" | grep "build/test-results" | xargs cp -t ~/test-results/
          when: always

      - store_test_results:
          path: ~/test-results
          when: always

      - save_cache:
          paths:
            - ~/repo
          key: repo-v1-{{ .Branch }}-{{ .Revision }}

      - persist_to_workspace:
          root: ~/repo
          paths:
            - ./*


workflows:
  version: 2

  main:
    jobs:
      - checkout
      - test:
          requires:
            - checkout
      - release_snapshot:
          requires:
            - test
          filters:
            branches:
              only: master
      - release:
          requires:
            - test
          filters:
            branches:
              only: release