The Micronaut framework integrates with https://www.vaultproject.io/[HashiCorp Vault] as a distributed configuration source.

To enable distributed configuration make sure <<bootstrap>> is enabled and create a `src/main/resources/bootstrap.[yml/toml/properties]` file with the following configuration:

.Integrating with HashiCorp Vault
[configuration]
----
micronaut:
  application:
    name: hello-world
  config-client:
    enabled: true

vault:
  client:
    config:
      enabled: true
----

See the https://micronaut-projects.github.io/micronaut-discovery-client/latest/guide/configurationreference.html#io.micronaut.discovery.vault.config.VaultClientConfiguration[configuration reference] for all configuration options.

The Micronaut framework uses the configured `micronaut.application.name` to lookup property sources for the application from Vault.

.Configuration Resolution Precedence
|===
|Directory|Description

|`/application`
|Configuration shared by all applications

|`/[APPLICATION_NAME]`
|Application-specific configuration

|`/application/[ENV_NAME]`
|Configuration shared by all applications for an active environment name

|`/[APPLICATION_NAME]/[ENV_NAME]`
|Application-specific configuration for an active environment name

|===

See the https://www.vaultproject.io/api-docs/secret/kv[Documentation for HashiCorp Vault] for more information on how to setup the server.
