Micronaut supports configuration sharing via AWS System Manager Parameter Store. You will need the following dependencies configured:

.Example `build.gradle` for AWS System Manager Parameter Store
[source,groovy]
----
compile "io.micronaut:discovery-client"
compile "io.micronaut.configuration:aws-common"
compile group: 'com.amazonaws', name: 'aws-java-sdk-ssm', version: '1.11.308'
----

You can configure shared properties by going into the AWS Console -> System Manager -> Parameter Store

Micronaut will use a hierarchy to read the configuration values, and supports `String`, `StringList`, and `SecureString` types.

You can make environment specific configurations as well by including the environment name after an underscore `_`. For example if your `micronaut.application.name` setting is set to `helloworld` then providing configuration values under `helloworld_test` will be applied only to the `test` environment.

For example:

.Names as Hierarchy
----
application/
    /specialConfig
application_test/
    /specialConfig2
application_dev
    /specialDevConfig
----

Each level of the tree can be composed of key=value pairs. If you want multiple key value pairs, set the type to 'StringList'.

For special secure information, like keys or passwords, use the type "SecureString". KMS will be automatically invoked when you
add and retrieve values and decrypt them with the default key store for your account. If you set the configuration to not use secure strings, they will be returned to you encrypted and you must manually decrypt them.

The following is an example configuration in `application.yml`:


.Configuration Properties Example
[source,yaml]
----
aws:
    client:
        system-manager:
            parameterstore:
                # true/false will turn on or off this feature
                enabled: true
                # true/false - ask AWS to automatically decrypt SecureString type with KMS
                useSecureParameters: true
                # String - you can use a custom root path the application will look for configurations in. The default is '/config/application'.
                rootHierarchyPath: /config/application
----




