https://www.consul.io[Consul] is a popular Service Discovery and Distributed Configuration server provided by HashiCorp. Micronaut features a native api:discovery.consul.client.v1.ConsulClient[] that is built using Micronaut's support for <<clientAnnotation, Declarative HTTP Clients>>.

==== Starting Consul

The quickest way to start using Consul is via Docker:

. Starting Consul with Docker
[source,bash]
----
docker run -p 8500:8500 consul
----

Alternatively you can https://www.consul.io/docs/install/index.html[install and run a local Consul instance].

==== Enabling Distributed Configuration with Consul

To enable distributed configuration, similar to Spring Boot and Grails, you need to create a `src/main/resources/bootstrap.yml` configuration file and configure Consul as well as enable the configuration client:

.bootstrap.yml
[source.yaml]
----
micronaut:
    application:
        name: hello-world
    config-client:
        enabled: true
consul:
    client:
        defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

Once you have enabled distributed configuration you need to store the configuration you wish the share in Consul's Key/Value store.

There are a number of different ways to do that.

==== Storing Configuration as Key/Value Pairs

One way is to store each key and value directly in Consul. In this case by default Micronaut will look for configuration in the `/config` folder of Consul.

Within the `/config` folder Micronaut will search values within the following folders in order of precedence:


.Micronaut Environment Detection
|===
|Folder|Description

|`/config/application`
|Configuration shared by all applications

|`/config/application,prod`
|Configuration shared by all applications for the `prod` api:context.env.Environment[]

|`/config/[APPLICATION_NAME]`
|Application specific configuration, example `/config/hello-world`

|`/config/[APPLICATION_NAME],prod`
|Application specific configuration for an active api:context.env.Environment[]


|===

The value of `APPLICATION_NAME` is whatever your have configured `micronaut.application.name` to be in `bootstrap.yml`.

To see this in action use the following curl command to store a property called `foo.bar` with a value of `myvalue` in the folder `/config/application`.

.Using curl to Write a Value
[source,bash]
----
curl -X PUT -d @- localhost:8500/v1/kv/config/application/foo.bar <<< myvalue
----

If you know define a `@Value("${foo.bar}")` the value `myvalue` will be resolved from Consul.