Micronaut supports configuration sharing via AWS System Manager Parameter Store. You will need the following dependencies configured:

.Example `build.gradle` for AWS System Manager Parameter Store
[source,groovy]
----
compile "io.micronaut:micronaut-discovery-client"
compile "io.micronaut.configuration:micronaut-aws-common"
compile group: 'com.amazonaws', name: 'aws-java-sdk-ssm', version: '1.11.308'
----

You can configure shared properties by going into the AWS Console -> System Manager -> Parameter Store

Micronaut will use a hierarchy to read the configuration values, and supports `String`, `StringList`, and `SecureString` types.

You can make environment specific configurations as well by including the environment name after an underscore `_`.  Providing configuration values under `application_test` will be applied only to the `test` environment. Please note currently environment specific values of application name are not supported (i.e. `helloworld_test`).

For example:

.Names as Hierarchy
----
application/
    /specialConfig
application_test/
    /specialConfig2
application_dev
    /specialDevConfig
----

Each level of the tree can be composed of key=value pairs. If you want multiple key value pairs, set the type to 'StringList'.

For special secure information, like keys or passwords, use the type "SecureString". KMS will be automatically invoked when you
add and retrieve values and decrypt them with the default key store for your account. If you set the configuration to not use secure strings, they will be returned to you encrypted and you must manually decrypt them.

The following is an example configuration in `bootstrap.yml`:


.Configuration Properties Example - bootstrap.yml
[source,yaml]
----
micronaut:
  config-client:
    enabled: true
aws:
    client:
        system-manager:
            parameterstore:
                # true/false will turn on or off this feature
                enabled: true
                # true/false - ask AWS to automatically decrypt SecureString type with KMS
                useSecureParameters: true
                # String - you can use a custom root path the application will look for configurations in. The default is '/config/application'.
                rootHierarchyPath: /config
----


.Configuration Properties Example - application.yml
[source,yaml]
----
micronaut:
  application:
    name: demo
---
endpoints:
    beans:
        enabled: true
        sensitive: false
    refresh:
        enabled: true
        sensitive: false
----


We can use the name of the application in the parameter store like so:

AWS Parameter Store Key: /config/demo/simple
AWS Parameter Store Value: some demo app specific value

If you don't have an application name set, or just want a global config use a key name like this:

/config/application/simple

Or do environments only values:

AWS Parameter Store Key: /config/application_dev/simple
AWS Parameter Store Value: some dev only text

AWS Parameter Store Key: /config/application_test/simple
AWS Parameter Store Value: some test only text


TIP: Keep in mind certain characters are not allowed for key names: https://docs.aws.amazon.com/systems-manager/latest/userguide/sysman-parameter-name-constraints.html

Check the https://github.com/micronaut-projects/micronaut-examples/aws repository for a sample application.

TIP: If you are using Lambda functions with Parameter Store, you will need to manually add the 'ec2' environment to the current environments.

