Micronaut provides support for invoking functions (either locally or deployed to a cloud provider) directly within the application context. To use the features described in this section, you will need to have the `function-client` dependency on your classpath. For example, in `build.gradle`

.build.gradle
[source,groovy]
----
compile "io.micronaut:function-client"
----

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI's `create-function` command, the `function-client` dependency is included by default.
====


The developer's primary use of this feature will be in defining interfaces that are annotated with link:{api}/io/micronaut/function/client/FunctionClient.html[FunctionClient]. When this annotation is applied, methods on the interface will become invokers of respective methods on the remote (or local) function associated with the interface.

In addition, the `function-client` works together with Micronaut's <<serviceDiscovery, Service Discovery>> functionality, identifying any functions that are registered with the current service discovery provider and making them available to the client application.

== FunctionClient

The ann:function.client.FunctionClient[] annotation makes it very straightforward to invoke local or remotely deployed functions. For example, the following Groovy function can be accessed using the `MathClient` interface listed below it.

.MaxFunction.groovy
[source,groovy]
----
include::{testsfunctionclient}/MaxFunction.groovy[tags=maxFunction, indent=0]
----

.Using @FunctionClient to Discover Function
[source,groovy]
----
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=import, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=beginFunctionClient, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=functionMax, indent=4]
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=endFunctionClient, indent=0]
----
<1> Method names in the interface will be mapped to methods on the target function, in this case `Long max()`


If you would like the names of the client interface and target function to be different, you can use the link:{jeeapi}/javax/inject/Named.html[Named] annotation to specify the target method name.

.RoundFunction.groovy
[source,groovy]
----
include::{testsfunctionclient}/RoundFunction.groovy[tags=rndFunction, indent=0]
----

.Using @Named to customize target method
[source,groovy]
----
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=import, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=beginFunctionClient, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=functionRnd, indent=4]
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=endFunctionClient, indent=0]
----

== Reactive FunctionClients

`@FunctionClient` interfaces support RxJava constructs, so the above interfaces could be implemented as shown below:

.RxMathClient.groovy
[source,groovy]
----
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=import, indent=0]
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=rxImport, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=rxFunctionClient, indent=0]
----

== Remote Functions

Once functions have been deployed to a cloud provider, you can specify endpoints in your client configuration. Micronaut will then create `FunctionDefinitions` for these remote functions, allowing you to access them through `FunctionClient` interfaces just as you would with local functions.


=== AWS Lambda

The configuration key path `aws.lambda.functions` can be used to specify function endpoints in an AWS Lambda environment.

.application.yml
[source,yaml]
----
aws:
    lambda:
        functions:
            hello:
                functionName: hello-world
                qualifer: foo
        region: us-east-1
----

In the above case a function named `hello` is mapped to the remote lambda function called `hello-world`. You can define multiple named functions under the `aws.lambda.functions` configuration. Each is configured by api:function.client.aws.AWSInvokeRequestDefinition[] that allows setting any property on the underlying `com.amazonaws.services.lambda.model.InvokeRequest`.

To configure credentials for invoking the function you can either define a `~/.aws/credentials` file or use `application.yml`. Micronaut registers a api:configurations.aws.EnvironmentAWSCredentialsProvider[] that resolves AWS credentials from the Micronaut <<environments, Environment>>.

NOTE: To invoke a function Micronaut configures a `AWSLambdaAsyncClient` using api:function.client.aws.AWSLambdaConfiguration[] that allows configuring any of the properties of the `AWSLambdaAsyncClientBuilder` class.

You can now write `FunctionClient` interfaces against the remote function, as shown below.

.HelloClient.groovy
[source,groovy]
----
import io.reactivex.*;

@FunctionClient
interface HelloClient {

    Single<String> hello(String name);
}
----