[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, use the `create-function` command to include the required dependencies and configuration for a serverless function. See the CLI documentation for <<createProject, Creating a Project>>.
====

To get started writing serverless function you must add the appropriate Micronaut `function` dependency to your classpath. In certain cases there are FaaS platform specific extension which you may wish to include. The following table includes the dependencies for each individual FaaS platform:

.Function Providers
|===
|Provider|Dependency

|AWS Lambda
| `io.micronaut:function-aws`
|===

NOTE: If you are using Groovy, there is a single compile-time dependency to be added: `"io.micronaut:function-groovy"` Please see <<groovyFunctions,Groovy Functions>>.

Add the appropriate dependency to your project, For example, in `build.gradle`:

.Example build.gradle
[source,groovy]
----
dependencies {
    ...
    compile "io.micronaut:function-aws"
    ...
}
----