Micronaut supports https://tools.ietf.org/html/rfc6750[RFC 6750 Bearer Token] specification out-of-the-box.

It is enabled by default but requires JWT Authentication to be enabled.

The next sequence illustrates the authentication flow:

image::jwt-bearer-token.svg[]

|===

| Configuration Property | Default Value | Description

| `micronaut.security.token.jwt.bearer.enabled` | `true` | link:{api}/io/micronaut/security/token/reader/BearerTokenReader.html[BearerTokenReader] is enabled by default

| `micronaut.security.token.jwt.bearer.headerName` | `Authorization` | Header name

| `micronaut.security.token.jwt.bearer.prefix` | `Bearer` | e.g. `Bearer XXXXXXXXXXX`

|===

== Sending tokens in the request

The token can be sent in the `Authorization` request header:

[source, bash]
.Accessing a protected resource using Authorization request header
----
GET /protectedResource HTTP/1.1
Host: micronaut.example
Authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJleHAiOjE0MjI5OTU5MjIsInN1YiI6ImppbWkiLCJyb2xlcyI6WyJST0xFX0FETUlOIiwiUk9MRV9VU0VSIl0sImlhdCI6MTQyMjk5MjMyMn0.rA7A2Gwt14LaYMpxNRtrCdO24RGrfHtZXY9fIjV8x8o
----