Often, you need to include the same HTTP headers or URL parameters in a set of requests against a third-party API or when calling another Microservice.

To simplify this, you can define api:http.filter.HttpClientFilter[] classes that are applied to all matching HTTP client requests.

As an example, say you want to build a client to communicate with the https://bintray.com/docs/api/[Bintray REST API]. It would be tedious to specify authentication for every single HTTP call.

To resolve this you can define a filter. The following is an example `BintrayService`:

snippet::io.micronaut.docs.client.ThirdPartyClientFilterSpec[tags="bintrayApiConstants, bintrayService", indent=0]


<1> An link:{micronautreactorapi}/client/ReactorHttpClient[ReactorHttpClient] is injected for the Bintray API
<2> The organization is configurable via configuration

The Bintray API is secured. To authenticate you add an `Authorization` header for every request. You can modify `fetchRepositories` and `fetchPackages` methods to include the necessary HTTP Header for each request, but using a filter is much simpler:

snippet::io.micronaut.docs.client.ThirdPartyClientFilterSpec[tags="bintrayFilter", indent=0]

<1> You can match only a subset of paths with a Client filter.
<2> The `username` and `token` are injected via configuration
<3> The `basicAuth` method includes HTTP Basic credentials

Now when you invoke the `bintrayService.fetchRepositories()` method, the `Authorization` HTTP header is included in the request.

=== Injecting Another Client into a HttpClientFilter

To create an link:{micronautreactorapi}/client/ReactorHttpClient[ReactorHttpClient], Micronaut needs to resolve all `HttpClientFilter` instances, which creates a circular dependency when injecting another link:{micronautreactorapi}/client.ReactorHttpClient[] or a `@Client` bean into an instance of a `HttpClientFilter`.

To resolve this issue, use the api:context.BeanProvider[] interface to inject another link:{micronautreactorapi}/client/ReactorHttpClient[ReactorHttpClient] or a `@Client` bean into an instance of `HttpClientFilter`.

The following example which implements a filter allowing https://cloud.google.com/run/docs/authenticating/service-to-service[authentication between services on Google Cloud Run] demonstrates how to use api:context.BeanProvider[] to inject another client:

snippet::io.micronaut.docs.client.filter.GoogleAuthFilter[tags="class"]

<1> The api:context.BeanProvider[] interface is used to inject another client, avoiding a circular reference
<2> The `get()` method of the `Provider` interface is used to obtain the client instance.

=== Filter Matching By Annotation

For cases where a filter should be applied to a client regardless of the URL, filters can be matched by the presence of an annotation applied to both the filter and the client. Given the following client:

snippet::io.micronaut.docs.client.filter.BasicAuthClient[tags="class"]

<1> The `@BasicAuth` annotation is applied to the client

The following filter will filter the client requests:

snippet::io.micronaut.docs.client.filter.BasicAuthClientFilter[tags="class"]

<1> The same annotation, `@BasicAuth`, is applied to the filter
<2> Normally the `@Filter` annotation makes filters singletons by default. Because the `@Filter` annotation is not used, the desired scope must be applied

The `@BasicAuth` annotation is just an example and can be replaced with your own.

snippet::io.micronaut.docs.client.filter.BasicAuth[tags="class"]

<1> The only requirement for custom annotations is that the ann:http.annotation.FilterMatcher[] annotation must be present
