Often, you need to include the same HTTP headers or URL parameters in a set of requests against a third-party API or when calling another Microservice.

To simplify this, Micronaut includes the ability to define api:http.filter.HttpClientFilter[] classes that are applied to all matching HTTP clients.

As an example say you want to build a client to communicate with the https://bintray.com/docs/api/[Bintray REST API]. It would be terribly tedious to have to specify authentication for every single HTTP call.

To resolve this burden you can define a filter. The following is an example `BintrayService`:

[source,groovy]
----
include::{testsdir}/client/ThirdPartyClientFilterSpec.groovy[tags=bintrayApiConstants, indent=0]
include::{testsdir}/client/ThirdPartyClientFilterSpec.groovy[tags=bintrayService, indent=0]
----

<1> An api:http.client.RxHttpClient[] is injected for the Bintray API
<2> The organization is configurable via configuration

The Bintray API is secured. To authenticate you need to add an `Authorization` header for every request. You could modify `fetchRepositories` and `fetchPackages` methods to include the necessary HTTP Header for each request. Using a filter is much simpler though:

[source,groovy]
----
include::{testsdir}/client/ThirdPartyClientFilterSpec.groovy[tags=bintrayFilter, indent=0]
----

<1> You can match only a subset of paths with a Client filter.
<2> The `username` and `token` are injected via configuration
<3> The `basicAuth` method is used include the HTTP BASIC credentials

Now, whenever you invoke the `bintrayService.fetchRepositories()` method, the `Authorization` HTTP header is included in the request.

