name: Bug Report
description: File a bug report
body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting an issue, please review the task list below before submitting the issue. Your issue report will be closed if the issue is incomplete and the below tasks not completed.

        NOTE: If you are unsure about something and the issue is more of a question a better place to ask questions is on Github Discussions :arrow_up:, [Stack Overflow](https://stackoverflow.com/tags/micronaut) or [Gitter](https://gitter.im/micronautfw/).
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
      placeholder: Tell us what should happen
    validations:
      required: false
  - type: textarea
    attributes:
      label: Actual Behaviour
      description: A concise description of what you're experiencing.
      placeholder: Tell us what happens instead
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. In this environment...
        2. With this config...
        3. Run '...'
        4. See error...
    validations:
      required: false
  - type: textarea
    attributes:
      label: Environment Information
      description: Environment information where the problem occurs.
      placeholder: |
        - Operating System:
        - JDK Version:
    validations:
      required: false
  - type: input
    id: example
    attributes:
      label: Example Application
      description: Example application link.
      placeholder: |
        Link to GitHub repository with an example that reproduces the issue
    validations:
      required: false
  - type: input
    id: version
    attributes:
      label: Version
      description: Micronaut version
    validations:
      required: true

