https://zeroturnaround.com/software/jrebel/[JRebel] is a proprietary reloading solution that involves an agent library, as well as sophisticated IDE support. The JRebel documentation includes detailed steps for IDE integration and usage of the tool. In this section, we will simply show how to install and configure the agent for Maven and Gradle projects.

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `jrebel` feature to preconfigure JRebel reloading in your project. Please note that you will still need to install JRebel and supply the correct path to the agent in the `gradle.properties` file (for Gradle) or `pom.xml` (for Maven). The steps necessary are described below.

----
$ mn create-app my-app --features jrebel
----
====

== Install/configure JRebel Agent

The simplest way to install JRebel is to download the "standalone" installation package from the https://zeroturnaround.com/software/jrebel/download[JRebel download page]. Unzip the downloaded file to a convenient location within your user's directory - for example, `~/bin/jrebel`

The installation directory will contain a `lib` directory containing the agent files. The appropriate agent based on your operating system, following the table below:

.JRebel Agent
|===
|OS|Agent

|Windows 64-bit JDK
| `[jrebel directory]\lib\jrebel64.dll`
|Windows 32-bit JDK
| `[jrebel directory]\lib\jrebel32.dll`
|Mac OS X 64-bit JDK
| `[jrebel directory]/lib/libjrebel64.dylib`
|Mac OS X 32-bit JDK
| `[jrebel directory]/lib/libjrebel32.dylib`
|Linux 64-bit JDK
| `[jrebel directory]/lib/libjrebel64.so`
|Linux 32-bit JDK
| `[jrebel directory]/lib/libjrebel32.so`
|===

Note the path to the appropriate agent, and add the value to your project build.

=== Gradle

Add the path to `gradle.properties` (create the file if necessary), as the `rebelAgent` property.

.gradle.properties
[source,properties]
----
#Assuming installation path of ~/bin/jrebel/
rebelAgent= -agentpath:~/bin/jrebel/lib/libjrebel64.dylib
----

Add the appropriate JVM arg to `build.gradle` (not necessary if using the CLI feature)

[source,groovy]
----
run.dependsOn(generateRebel)
if (project.hasProperty('rebelAgent')) {
    run.jvmArgs += rebelAgent
}
----

You can start the application with `./gradlew run`, and it will include the agent. See the section on <<gradleReload, Gradle Reloading>> or <<ideReload, IDE Reloading>> to set up the recompilation.

=== Maven

Configure the Micronaut Maven Plugin accordingly:

[source,xml]
----
<project xmlns="http://maven.apache.org/POM/4.0.0" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">

  <!-- ... -->

  <build>
    <plugins>

      <!-- ... -->

      <plugin>
        <groupId>io.micronaut.build</groupId>
        <artifactId>micronaut-maven-plugin</artifactId>
          <configuration>
            <jvmArguments>
              <jvmArgument>-agentpath:~/bin/jrebel/lib/jrebel6/lib/libjrebel64.dylib</jvmArgument>
            </jvmArguments>
          </configuration>
      </plugin>
      <plugin>
        <groupId>org.zeroturnaround</groupId>
        <artifactId>jrebel-maven-plugin</artifactId>
        <version>1.1.8</version>
        <executions>
          <execution>
            <id>generate-rebel-xml</id>
            <phase>process-resources</phase>
            <goals>
              <goal>generate</goal>
            </goals>
          </execution>
        </executions>
      </plugin>

      <!-- ... -->
    </plugins>
  </build>
</project>
----