To deploy a Micronaut application you create an executable JAR file by running `./gradlew assemble` or `./mvnw package`.

The constructed JAR file can then be executed with `java -jar`. For example:

[source,bash]
----
$ java -jar build/libs/hello-world-0.1-all.jar
----

if building with Gradle, or

[source,bash]
----
$ java -jar target/hello-world.jar
----

if building with Maven.

The executable JAR can be run locally, or deployed to a virtual machine or managed Cloud service that supports executable JARs.

To publish a layered application to a Docker container registry, configure your Docker image name in `build.gradle` for Gradle:

[source,groovy]
----
dockerBuild {
    images = ["[REPO_URL]/[NAMESPACE]/my-image:$project.version"]
}
----

Then use `dockerPush` to push a built image of the application:

[source,bash]
----
$ ./gradlew dockerPush
----

For Maven, define the following plugin in your POM:

[source,xml]
----
<plugin>
  <groupId>com.google.cloud.tools</groupId>
  <artifactId>jib-maven-plugin</artifactId>
  <configuration>
    <to>
      <image>docker.io/my-company/my-image:${project.version}</image>
    </to>
  </configuration>
</plugin>
----

Then invoke the `deploy` lifecycle phase specifying the packaging type as either `docker` or `docker-native`:

[source,bash]
----
$ ./mvnw deploy -Dpackaging=docker
----

=== Deployment Guides

See the following guides to learn more about deploying Micronaut Applications:

- https://guides.micronaut.io/latest/executable-jar.html[Create an Executable Jar of a Micronaut Application]
- https://guides.micronaut.io/latest/micronaut-creating-first-graal-app.html[Creating Your First Micronaut Graal Application]
- https://guides.micronaut.io/latest/micronaut-docker-image.html[Building a Docker Image of your Micronaut Application]
