Since Micronaut dependency injection is based on annotation processors and doesn't rely on reflection, it can be used on Android when using the Android plugin 3.0.0 or above.

This allows you to use the same application framework for both your Android client and server implementation.

== Configuring Your Android Build

To get started you must add the Micronaut annotation processors to the processor classpath using the `annotationProcessor` dependency configuration.

The Micronaut `micronaut-inject-java` dependency should be included in both the `annotationProcessor` and `compileOnly` scopes of your Android build configuration:

[source.multi-language-sample,gradle-groovy,title="Example Android build.gradle"]
----
dependencies {
    ...
    annotationProcessor "io.micronaut:micronaut-inject-java:{version}"
    compileOnly "io.micronaut:micronaut-inject-java:{version}"
    ...
}
----


[source.multi-language-sample,gradle-kotlin,title="Example Android build.gradle"]
----
dependencies {
    ...
    annotationProcessor("io.micronaut:micronaut-inject-java:{version}")
    compileOnly("io.micronaut:micronaut-inject-java:{version}")
    ...
}
----



If you use `lint` as part of your build you may also need to disable the invalid packages check since Android includes a hard coded check that regards the `javax.inject` package as invalid unless you are using Dagger:

[source.multi-language-sample,gradle-groovy,title="Configure lint within build.gradle"]
----

android {
    ...
    lintOptions {
        lintOptions { warning 'InvalidPackage' }
    }
}
----


[source.multi-language-sample,gradle-kotlin,title="Configure lint within build.gradle"]
----

android {
    ...
    lintOptions {
        lintOptions { warning("InvalidPackage") }
    }
}
----

You can find more information on https://developer.android.com/studio/build/gradle-plugin-3-0-0-migration.html#annotationProcessor_config[configuring annotations processors] in the Android documentation.

NOTE: Micronaut `inject-java` dependency uses https://developer.android.com/studio/write/java8-support.html[Android Java 8 support] features.

== Enabling Dependency Injection

Once you have configured the classpath correctly, the next step is start the link:{api}/io/micronaut/context/ApplicationContext.html[ApplicationContext].


The following example demonstrates creating a subclass of https://developer.android.com/reference/android/app/Application.html[android.app.Application] for that purpose:

.Example Android Application Class
[source, java]
----
import android.app.Activity;
import android.app.Application;
import android.os.Bundle;

import io.micronaut.context.ApplicationContext;
import io.micronaut.context.env.Environment;

public class BaseApplication extends Application { // <1>

    private ApplicationContext ctx;

    public BaseApplication() {
        super();
    }

    @Override
    public void onCreate() {
        super.onCreate();
        ctx = ApplicationContext.run(MainActivity.class, Environment.ANDROID); // <2>
        registerActivityLifecycleCallbacks(new ActivityLifecycleCallbacks() { // <3>
            @Override
            public void onActivityCreated(Activity activity, Bundle bundle) {
                ctx.inject(activity);
            }
            ... // shortened for brevity, it is not necessary to implement other methods
        });
    }
}

----

<1> Extend the `android.app.Application` class
<2> Run the `ApplicationContext` with the `ANDROID` environment
<3> To allow dependency injection of Android `Activity` instances register a `ActivityLifecycleCallbacks` instance

