The methods provided by Java's link:{jdkapi}/java/lang/reflect/AnnotatedElement.html[AnnotatedElement] API in general don't provide the ability to introspect annotations without loading the annotations themselves, nor do they provide any ability to introspect annotation stereotypes (Often called meta-annotations, an annotation stereotype is where an annotation is annotated with another annotation, essentially inheriting its behaviour).

To solve this problem many frameworks produce runtime metadata or perform expensive reflection to analyze the annotations of a class.

Micronaut instead produces this annotation metadata at compile time, avoiding expensive reflection and saving on memory.

The link:{api}/io/micronaut/context/BeanContext.html[BeanContext] API can be used to obtain a reference to a link:{api}/io/micronaut/inject/BeanDefinition.html[BeanDefinition] which implements the link:{api}/io/micronaut/core/annotation/AnnotationMetadata.html[AnnotationMetadata] interface.

For example the following code will obtain all bean definitions annotated with a particular stereotype:

.Lookup Bean Definitions by Stereotype
[source,java]
----
BeanContext beanContext = ... // obtain the bean context
Collection<BeanDefinition> definitions =
    beanContext.getBeanDefinitions(Qualifiers.byStereotype(Controller.class))

for(BeanDefinition definition : definitions) {
    AnnotationValue<Controller> controllerAnn = definition.getAnnotation(Controller.class);
    // do something with the annotation
}
----

The above example will find all api:inject.BeanDefinition[] annotated with `@Controller` regardless whether `@Controller` is used directly or inherited via an annotation stereotype.

Note that the `getAnnotation` method and the variations of the method return a api:core.annotation.AnnotationValue[] type and not a Java annotation. This is by design, and you should generally try to work with this API when reading annotation values, the reason being that synthesizing a proxy implementation is worse from a performance and memory consumption perspective.

If you absolutely require a reference to an annotation instance you can use the `synthesize` method, which will create a runtime proxy that implements the annotation interface:

.Synthesizing Annotation Instances
[source,java]
----
Controller controllerAnn = definition.synthesize(Controller.class);
----

This approach is not recommended however, as it requires reflection and increases memory consumption due to the use of runtime created proxies and should be used as a last resort (for example if you need an instance of the annotation to integrate with a third party library).

=== Aliasing / Mapping Annotations

There are times when you may want to alias the value of an annotation member to the value of another annotation member. To do this you can use the ann:io.micronaut.context.annotation.AliasFor[] annotation to alias the value of one member to the value of another.

A common use case is for example when an annotation defines the `value()` member, but also supports other members. For example the ann:io.micronaut.http.client.annotation.Client[] annotation:

.The @Client Annotation
[source,java]
----
include::http-client-core/src/main/java/io/micronaut/http/client/annotation/Client.java[tag=value]
}
----

<1> The `value` member also sets the `id` member
<2> The `id` member also sets the `value` member

With these aliases in place, regardless whether you define `@Client("foo")` or `@Client(id="foo")` both the `value` and `id` members are always set, making it much easier to parse and deal with the annotation.

If you do not have control over the annotation then another approach is to use a api:io.micronaut.inject.annotation.AnnotationMapper[]. To create a `AnnotationMapper` you must following the following steps:

* Implement the api:io.micronaut.inject.annotation.AnnotationMapper[] interface
* Define a `META-INF/services/io.micronaut.inject.annotation.AnnotationMapper` file referencing the implementation class
* Add the JAR file containing the implementation to the `annotationProcessor` classpath (`kapt` for Kotlin)

NOTE: Because `AnnotationMapper` implementations need to be on the annotation processor classpath they should generally be in a project that includes few external dependencies to avoid polluting the annotation processor classpath.

As an example the  `AnnotationMapper` that improves the introspection capabilities of JPA entities

.EntityIntrospectedAnnotationMapper Mapper Example
[source,java]
----
include::inject/src/main/java/io/micronaut/inject/beans/visitor/EntityIntrospectedAnnotationMapper.java[indent=0, tag="class"]
----

<1> The `map` method receives a api:io.micronaut.core.annotation.AnnotationValue[] with the values for the annotation.
<2> One or more annotations can be returned, in this case `@Transient`.

NOTE: The example above implements the api:io.micronaut.inject.annotation.NamedAnnotationMapper[] interface which allows for annotations to be mixed with runtime code. If you want to operate against a concrete annotation type then you should use api:io.micronaut.inject.annotation.TypedAnnotationMapper[] instead, though note it requires the annotation class itself to be on the annotation processor classpath.
