The methods provided by Java's link:{jdkapi}/java.base/java/lang/reflect/AnnotatedElement.html[AnnotatedElement] API in general don't provide the ability to introspect annotations without loading the annotations themselves. Nor do they provide any ability to introspect annotation stereotypes (often called meta-annotations; an annotation stereotype is where an annotation is annotated with another annotation, essentially inheriting its behaviour).

To solve this problem many frameworks produce runtime metadata or perform expensive reflection to analyze the annotations of a class.

The Micronaut framework instead produces this annotation metadata at compile time, avoiding expensive reflection and saving memory.

The link:{api}/io/micronaut/context/BeanContext.html[BeanContext] API can be used to obtain a reference to a link:{api}/io/micronaut/inject/BeanDefinition.html[BeanDefinition] which implements the link:{api}/io/micronaut/core/annotation/AnnotationMetadata.html[AnnotationMetadata] interface.

For example the following code obtains all bean definitions annotated with a particular stereotype:

.Lookup Bean Definitions by Stereotype
[source,java]
----
BeanContext beanContext = ... // obtain the bean context
Collection<BeanDefinition> definitions =
    beanContext.getBeanDefinitions(Qualifiers.byStereotype(Controller.class))

for (BeanDefinition definition : definitions) {
    AnnotationValue<Controller> controllerAnn = definition.getAnnotation(Controller.class);
    // do something with the annotation
}
----

The above example finds all api:inject.BeanDefinition[] instances annotated with `@Controller` whether `@Controller` is used directly or inherited via an annotation stereotype.

Note that the `getAnnotation` method and the variations of the method return an api:core.annotation.AnnotationValue[] type and not a Java annotation. This is by design, and you should generally try to work with this API when reading annotation values, since synthesizing a proxy implementation is worse from a performance and memory consumption perspective.

If you require a reference to an annotation instance you can use the `synthesize` method, which creates a runtime proxy that implements the annotation interface:

.Synthesizing Annotation Instances
[source,java]
----
Controller controllerAnn = definition.synthesize(Controller.class);
----

This approach is not recommended however, as it requires reflection and increases memory consumption due to the use of runtime generated proxies, and should be used as a last resort, for example if you need an instance of the annotation to integrate with a third-party library.

=== Annotation Inheritance

The Micronaut framework will respect the rules defined in Java's link:{jdkapi}/java.base/java/lang/reflect/AnnotatedElement.html[AnnotatedElement] API with regard to annotation inheritance:

* Annotations meta-annotated with link:{jdkapi}/java.base/java/lang/annotation/Inherited.html[Inherited] will be available via the `getAnnotation*` methods of the api:core.annotation.AnnotationMetadata[] API whilst those directly declared are available via the `getDeclaredAnnotation*` methods.
* Annotations not meta-annotated with link:{jdkapi}/java.base/java/lang/annotation/Inherited.html[Inherited] will not be included in the metadata

The Micronaut framework differs from the link:{jdkapi}/java.base/java/lang/reflect/AnnotatedElement.html[AnnotatedElement] API in that it extends these rules to methods and method parameters such that:

* Any annotations annotated with link:{jdkapi}/java.base/java/lang/reflect/AnnotatedElement.html[AnnotatedElement] and present on a method of interface or super class `A` that is overridden by child interface or class `B` will be inherited into the api:core.annotation.AnnotationMetadata[] retrievable via the api:inject.ExecutableMethod[] API from a api:inject.BeanDefinition[] or an <<aop, AOP interceptor>>.
* Any annotations annotated with link:{jdkapi}/java.base/java/lang/annotation/Inherited.html[Inherited] and present on a method parameter of interface or super class `A` that is overridden by child interface or class `B` will be inherited into the api:core.annotation.AnnotationMetadata[] retrievable via the api:core.type.Argument[] interface from the `getArguments` method of the api:inject.ExecutableMethod[] API.

In general behaviour which you may wish to override is not inherited by default including <<scopes, Bean Scopes>>, <<qualifiers, Bean Qualifiers>>, <<conditionalBeans, Bean Conditions>>, <<validation, Validation Rules>> and so on.

If you wish a particular scope, qualifier, or set of requirements to be inherited when subclassing then you can define a meta-annotation that is annotated with `@Inherited`. For example:

snippet::io.micronaut.docs.inject.anninheritance.SqlRepository[tags="imports, class", indent=0, title="Defining Inherited Meta Annotations"]

<1> The annotation is declared as `@Inherited`
<2> <<conditionalBeans, Bean Conditions>> will be inherited by child classes
<3> <<qualifiers, Bean Qualifiers>> will be inherited by child classes
<4> <<scopes, Bean Scopes>> will be inherited by child classes
<5> You can also alias annotations and they will be inherited

With this meta-annotation in place you can add the annotation to a super class:

snippet::io.micronaut.docs.inject.anninheritance.BaseSqlRepository[tags="class", indent=0, title="Using Inherited Meta Annotations on a Super Class"]

And then a subclass will inherit all the annotations:

snippet::io.micronaut.docs.inject.anninheritance.BookRepository[tags="imports, class", indent=0, title="Inherting Annotations in a Child Class"]

NOTE: A child class must at least have one bean definition annotation such as a scope or qualifier.

=== Aliasing / Mapping Annotations

There are times when you may want to alias the value of an annotation member to the value of another annotation member. To do this, use the ann:io.micronaut.context.annotation.AliasFor[] annotation.

A common use case is for example when an annotation defines the `value()` member, but also supports other members. for example the ann:io.micronaut.http.client.annotation.Client[] annotation:

.The @Client Annotation
[source,java]
----
include::http-client-core/src/main/java/io/micronaut/http/client/annotation/Client.java[tag=value]
}
----

<1> The `value` member also sets the `id` member
<2> The `id` member also sets the `value` member

With these aliases in place, whether you define `@Client("foo")` or `@Client(id="foo")`, both the `value` and `id` members will be set, making it easier to parse and work with the annotation.

==== Aliasing Members of Other Annotations

An alias can also target a member of a different annotation by setting the `annotation()` (or `annotationName()`) member of ann:io.micronaut.context.annotation.AliasFor[]. When the annotated member is set, the aliased annotation receives the value as a stereotype of the annotation being processed. If the targeted annotation is already declared as a stereotype, the aliased value *overrides* the declared member value instead of contributing a second annotation.

Two additional members refine this behaviour:

* `applyDefault()` - by default an alias only applies when the member is explicitly set at the use site. With `applyDefault = true` the alias also applies the member's *default* value. This allows modelling semantics such as `jakarta.validation.OverridesAttribute`, where the overriding member's default replaces the value declared on the composed constraint.
* `index()` - when the aliased annotation is repeatable and declared multiple times as a stereotype, `index` selects which occurrence (in declaration order, starting at zero) the alias overrides. The default of `-1` applies the alias to every declared occurrence, and an index outside the declared occurrences is ignored.

For example:

snippet::io.micronaut.docs.inject.aliasfor.ComposedZip[tags="imports, class", indent=0, title="Overriding a Member of a Declared Stereotype"]

<1> `@Size` is declared as a stereotype with `max` set to `5`
<2> The `max()` member aliases `Size.max`, overriding the declared value

Any use of `@ComposedZip` therefore produces `@Size(min = 5, max = 10)` in the metadata — `max` comes from the `max()` default because `applyDefault` is `true` — while `@ComposedZip(max = 20)` produces `@Size(min = 5, max = 20)`.

NOTE: `index()` is only computed for annotations processed from Java and Groovy sources. The Kotlin (KSP) annotation metadata builder does not extract repeatable stereotype containers, so a repeatable annotation declared multiple times on a Kotlin annotation class cannot be targeted by index.

Annotations that cannot depend on Micronaut can participate in alias resolution through an api:io.micronaut.inject.annotation.AnnotationTransformer[]: when an annotation member carries no literal `@AliasFor`, the registered transformers are applied to the member's annotations, and any produced `@AliasFor` values are processed as if declared directly (a produced alias without a `member` value defaults to the annotated member's own name). This is how, for example, `jakarta.validation.OverridesAttribute` can be remapped to `@AliasFor` by a validation annotation processor.

If you do not have control over the annotation, another approach is to use an api:io.micronaut.inject.annotation.AnnotationMapper[]. To create an `AnnotationMapper`, do the following:

* Implement the api:io.micronaut.inject.annotation.AnnotationMapper[] interface
* Define a `META-INF/services/io.micronaut.inject.annotation.AnnotationMapper` file referencing the implementation class
* Add the JAR file containing the implementation to the `annotationProcessor` classpath (`kapt` for Kotlin)

NOTE: Because `AnnotationMapper` implementations must be on the annotation processor classpath, they should generally be in a project that includes few external dependencies to avoid polluting the annotation processor classpath.

The following is an example `AnnotationMapper` that improves the introspection capabilities of JPA entities.

.EntityIntrospectedAnnotationMapper Mapper Example
[source,java]
----
include::core-processor/src/main/java/io/micronaut/inject/beans/visitor/EntityIntrospectedAnnotationMapper.java[indent=0, tag="class"]
----

<1> The `map` method receives a api:io.micronaut.core.annotation.AnnotationValue[] with the values for the annotation.
<2> One or more annotations can be returned.

NOTE: The example above implements the api:io.micronaut.inject.annotation.NamedAnnotationMapper[] interface which allows annotations to be mixed with runtime code. To operate against a concrete annotation type, use api:io.micronaut.inject.annotation.TypedAnnotationMapper[] instead. However, api:io.micronaut.inject.annotation.TypedAnnotationMapper[] requires both the mapper and the annotation class itself to be available on the annotation processor classpath of the consuming project. If the annotation and mapper are defined in regular application code and not packaged as an annotation-processor-visible dependency, use api:io.micronaut.inject.annotation.NamedAnnotationMapper[] instead.

=== Retaining Composed Annotations

api:core.annotation.AnnotationMetadata[] indexes annotations by name, so when an annotation is composed as a stereotype of another annotation the association between an individual occurrence and the annotation that introduced it is lost. Consider two annotations that each compose the same annotation with different members:

snippet::io.micronaut.docs.inject.retainable.MinLength[tags="imports, class", indent=0, title="An Annotation Composing @Limit"]

<1> `@Limit` is declared as a stereotype with `min` set to `5`
<2> The `value()` member aliases `Limit.min`, overriding the declared value

A second annotation, `@MaxLength`, composes `@Limit(max = 50)` in the same way and aliases `Limit.max`. Both are then applied to one bean:

snippet::io.micronaut.docs.inject.retainable.CodeValidator[tags="imports, class", indent=0, title="Applying Both Composing Annotations"]

For this bean `getAnnotationValuesByName(Limit.class)` reports two occurrences and `getAnnotationNamesByStereotype(Limit.class)` reports that both `@MinLength` and `@MaxLength` introduced a `@Limit`, but nothing says which occurrence came from which composing annotation — and the correspondence cannot be recovered from the order, since equal occurrences contributed by different annotations collapse into one.

Meta-annotating the composed annotation with ann:core.annotation.Retainable[] solves this. Every annotation that composes a retainable annotation keeps the composed occurrence on its own api:core.annotation.AnnotationValue[], in addition to flattening it into the element's stereotypes:

snippet::io.micronaut.docs.inject.retainable.Limit[tags="imports, class", indent=0, title="Declaring a Retainable Annotation"]

<1> The marker sits on the *composed* annotation, not on the annotations composing it
<2> Only annotations with `RUNTIME` retention are retained in the metadata written for runtime

The retained occurrences are read back with the `getStereotypes()` method of api:core.annotation.AnnotationValue[], with member overrides declared through ann:context.annotation.AliasFor[] already applied:

snippet::io.micronaut.docs.inject.retainable.RetainableSpec[tags="read", indent=0, title="Reading Retained Stereotypes"]

Here `min` is `@Limit(min = 3)` and `max` is `@Limit(max = 9)`: each composing annotation reports exactly the occurrence it introduced.

An annotation is retainable when ann:core.annotation.Retainable[] is present anywhere in its own stereotypes, so a framework annotation that is itself meta-annotated with `@Retainable` opts in a whole family of annotations at once. A retained occurrence in turn keeps its own retainable stereotypes, so `getStereotypes()` can be walked as a tree, and a transitive `@AliasFor` override cascades to every level of it.

Retention costs generated code proportional to the number of retainable occurrences at every use site, so it is opt-in and has no cost at all for annotations that compose nothing retainable. The marker itself is never retained.

NOTE: The retained occurrences are stored in the reserved annotation member `AnnotationUtil.STEREOTYPES_MEMBER` (`$stereotypes`), following the same convention as `$nonBinding`. It is not an attribute of the annotation: it is hidden from `getValues()`, `getMemberNames()`, the convertible values view and `toString()`, and it takes no part in equality. Read it through `getStereotypes()` rather than through the member.

==== When to Retain a Composed Annotation

Retention is worth adding when the *identity of the occurrence* matters, not just its presence or its merged values:

* *Composed constraints* - a validation-style annotation composes several constraints, and a violation has to be reported against the constraint that produced it. This is also what makes an individual occurrence addressable: `applyDefault` and `index` on ann:context.annotation.AliasFor[] (and the `jakarta.validation.OverridesAttribute` semantics they model) target one occurrence of a repeated composed constraint, which the name-keyed index cannot distinguish.
* *Interceptor binding* - ann:aop.InterceptorBinding[] is meta-annotated with `@Retainable`, so every annotation used to bind an interceptor retains its binding occurrence. Bindings are compared on the retained occurrence rather than on a copy of its members, and two annotations composing the same binding annotation with different members on one element — which the name-keyed index collapses into one — resolve to both bindings.
* *Behaviour driven by a meta-annotation contract* - when a api:inject.visitor.TypeElementVisitor[], interceptor or bean introspection acts on a meta-annotation you define, retaining it lets that code recover which user-written annotation asked for the behaviour, and with what members, instead of seeing one merged occurrence. Marking your meta-annotation `@Retainable` opts in every annotation built on it.
* *Diagnostics* - error messages and tooling can name the annotation the user actually wrote rather than the internal stereotype it expands to.

Retention is not needed to test for the presence of a stereotype, to read its merged values, or to find the annotations that introduced it by name. The `hasAnnotation`, `hasStereotype`, `getAnnotationValuesByName` and `getAnnotationNamesByStereotype` methods of api:core.annotation.AnnotationMetadata[] already answer those questions, and they cost nothing extra in the generated metadata.
