Micronaut supports a general event system through the context. The api:context.event.ApplicationEventPublisher[] API publishes events and the api:context.event.ApplicationEventListener[] API is used to listen to events. The event system is not limited to events that Micronaut publishes and supports custom events created by users.

=== Publishing Events

The api:context.event.ApplicationEventPublisher[] API supports events of any type, although all events that Micronaut publishes extend api:context.event.ApplicationEvent[].

To publish an event, use dependency injection to obtain an instance of api:context.event.ApplicationEventPublisher[] where the generic type is the type of event and invoke the `publishEvent` method with your event object.

snippet::io.micronaut.docs.context.events.SampleEvent,io.micronaut.docs.context.events.SampleEventEmitterBean[tags="class",indent=0,title="Publishing an Event]

WARNING: Publishing an event is *synchronous* by default! The `publishEvent` method will not return until all listeners have been executed. Move this work off to a thread pool if it is time-intensive.

=== Listening for Events

To listen to an event, register a bean that implements api:context.event.ApplicationEventListener[] where the generic type is the type of event.

snippet::io.micronaut.docs.context.events.application.SampleEventListener,io.micronaut.docs.context.events.application.SampleEventListenerSpec[tags="imports,class",indent=0,title="Listening for Events with `ApplicationEventListener`"]

NOTE: The link:{api}/io/micronaut/context/event/ApplicationEventListener.html#supports-E-[supports] method can be overridden to further clarify events to be processed.

Alternatively, use the ann:runtime.event.annotation.EventListener[] annotation if you do not wish to implement an interface or utilize one of the built-in events like api:context.event.StartupEvent[] and api:context.event.ShutdownEvent[]:

snippet::io.micronaut.docs.context.events.listener.SampleEventListener[tags="imports,class",indent=0,title="Listening for Events with `@EventListener`"]

If your listener performs work that might take a while, use the ann:scheduling.annotation.Async[] annotation to run the operation on a separate thread:

snippet::io.micronaut.docs.context.events.async.SampleEventListener,io.micronaut.docs.context.events.async.SampleEventListenerSpec[tags="imports,class",indent=0,title="Asynchronously listening for Events with `@EventListener`"]

The event listener by default runs on the `scheduled` executor. You can configure this thread pool as required in `application.yml`:

//TODO: Move YAML snippet to ExecutorServiceConfigSpec
.Configuring Scheduled Task Thread Pool
[source,yaml]
----
micronaut:
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 30
----
