In many cases, you may want to make available as a bean a class that is not part of your codebase such as those provided by third-party libraries. In this case, you cannot annotate the already compiled class. Instead, you should implement a ann:context.annotation.Factory[].

A factory is a class annotated with the link:{api}/io/micronaut/context/annotation/Factory.html[Factory] annotation that provides 1 or more methods annotated with a bean scope annotation. Which annotation you use depends on what scope you want the bean to be in. See the section on <<scopes, bean scopes>> for more information.

The return types of methods annotated with a bean scope annotation are the bean types. This is best illustrated by an example:

snippet::io.micronaut.docs.factories.CrankShaft,io.micronaut.docs.factories.V8Engine,io.micronaut.docs.factories.EngineFactory[tags="class",indent=0]

In this case, the `V8Engine` is built by the `EngineFactory` class' `v8Engine` method. Note that you can inject parameters into the method and these parameters will be resolved as beans. The resulting `V8Engine` bean will be a singleton.

A factory can have multiple methods annotated with bean scope annotations, each one returning a distinct bean type.

NOTE: If you take this approach, then you should not invoke other bean methods internally within the class. Instead, inject the types via parameters.

TIP: To allow the resulting bean to participate in the application context shutdown process, annotate the method with link:{api}/io/micronaut/context/annotation/Bean.html[@Bean] and set the `preDestroy` argument to the name of the method that should be called to close the bean.

=== Programmatically Disabling Beans

Factory methods can return throw api:context.exceptions.DisabledBeanException[] to allow for beans to be disabled conditionally. The use of ann:context.annotation.Requires[] should always be the preferred method to conditionally create beans and throwing an exception a factory method should only be done if using ann:context.annotation.Requires[] is not possible.

For example:

snippet::io.micronaut.docs.factories.nullable.Engine,io.micronaut.docs.factories.nullable.EngineConfiguration,io.micronaut.docs.factories.nullable.EngineFactory[tags="class",indent=0]


=== Injection Point

A common use case with factories is to take advantage of annotation metadata from the point at which an object is injected such that behaviour can be modified based on said metadata.

Consider an annotation such as the following:

snippet::io.micronaut.docs.injectionpoint.Cylinders[tags="class",indent=0]

The above annotation could be used to customize the type of engine we want to inject into a vehicle at the point at which the injection point is defined:

snippet::io.micronaut.docs.injectionpoint.Vehicle[tags="class",indent=0]

The above `Vehicle` class specifies an annotation value of `@Cylinders(6)` indicating an `Engine` of six cylinders is needed.

To implement this use case you can define a factory that accepts the api:inject.InjectionPoint[] instance which can be used to analyze the annotation values defined:

snippet::io.micronaut.docs.injectionpoint.EngineFactory[tags="class",indent=0]

<1> The factory method defines a parameter of type api:inject.InjectionPoint[].
<2> The annotation metadata is used to obtain the value of the `@Cylinder` annotation
<3> The value is used to construct an engine, throwing an exception if an engine cannot be constructed.

NOTE: It is important to note that the factory is declared as ann:context.annotation.Prototype[] scope so that the method is invoked for each injection point. If the `V8Engine` and `V6Engine` types are required to be singletons then the factory should use a map to ensure the objects are only constructed once.


