Since Micronaut 1.1, a compilation time replacement for the JDK's jdk:java.beans.Introspector[] class has been included.

The api:core.beans.BeanIntrospector[] and api:core.beans.BeanIntrospection[] interfaces allow looking up bean introspections that allow you to instantiate and read/write bean properties without using reflection or caching reflective metadata which consumes excessive memory for large beans.

=== Making a Bean Available for Introspection

Unlike the JDK's jdk:java.beans.Introspector[] every class is not automatically available for introspection, to make a class available for introspection you must as a minimum enable Micronaut's annotation processor (`micronaut-inject-java` for Java and Kotlin and `micronaut-inject-groovy` for Groovy) in your build and ensure you have a runtime time dependency on `micronaut-core`.

dependency::micronaut-inject-java[scope="annotationProcessor", version="{version}"]

NOTE: For Kotlin the `micronaut-inject-java` dependency should be in `kapt` scope and for Groovy you should have `micronaut-inject-groovy` in `compileOnly` scope.

dependency::micronaut-core[scope="runtime", version="{version}"]

Once your build is configured you have a few ways to generate introspection data.

==== Use the `@Introspected` Annotation

The ann:core.annotation.Introspected[] annotation can be used on any class which you want to make available for introspection, simply annotate the class with ann:core.annotation.Introspected[]:

snippet::io.micronaut.docs.ioc.beans.Person[tags="imports,class"]

Once introspection data has been produced at compilation time you can then retrieve it via the api:core.beans.BeanIntrospection[] API:

snippet::io.micronaut.docs.ioc.beans.IntrospectionSpec[tags="usage", indent=0]

<1> You can retrieve a api:core.beans.BeanIntrospection[] with the `getIntrospection` static method
<2> Once you have a api:core.beans.BeanIntrospection[] you can instantiate a bean with the `instantiate` method.
<3> A api:core.beans.BeanProperty[] can be retrieved from the introspection
<4> .. and the `set` method used to set the property value
<5> .. and the `get` method used to retrieve the property value

==== Constructor Methods

For classes with multiple constructors, it is possible to inform Micronaut which constructor should be used to instantiate the class. Apply the ann:core.annotation.Creator[] annotation to which constructor to be used.

snippet::io.micronaut.docs.ioc.beans.Vehicle[tags="class"]

<1> The ann:core.annotation.Creator[] annotation is used to denote which constructor should be used

NOTE: This class has no default constructor so calls to instantiate without arguments will throw an api:core.reflect.exception.InstantiationException[].

==== Static Creator Methods

For the use case of static methods being used to instantiate the class, the ann:core.annotation.Creator[] annotation can be applied to those methods to allow for the introspection to execute the method.

snippet::io.micronaut.docs.ioc.beans.Business[tags="class"]

<1> The ann:core.annotation.Creator[] annotation is applied to the static method which will be used to instantiate the class

TIP: There can be multiple "creator" methods annotated. If one exists without arguments, that will be used as the default construction method. The first method with arguments will be used as the primary construction method.

==== Enums

It is possible to introspect enums as well. Simply add the annotation to the enum and it can be constructed through the standard `valueOf` method.

==== Use the `@Introspected` Annotation on a Configuration Class

If the class you wish to introspect is already compiled and not under your control an alternative option is to define a configuration class with the `classes` member of the ann:core.annotation.Introspected[] annotation set.

snippet::io.micronaut.docs.ioc.beans.PersonConfiguration[tags="class"]

In the above example the `PersonConfiguration` class will generate introspections for the `Person` class.

NOTE: You can also use the `packages` member of the ann:core.annotation.Introspected[] which will package scan at compilation time and generate introspections for all classes within a package. Note however this feature is currently regarded as experimental.

==== Write an `AnnotationMapper` to Introspect Existing Annotations

If there is an existing annotation that you wish to introspect by default you can write an api:inject.annotation.AnnotationMapper[].

An example of this is https://github.com/micronaut-projects/micronaut-core/blob/master/inject/src/main/java/io/micronaut/inject/beans/visitor/EntityIntrospectedAnnotationMapper.java[EntityIntrospectedAnnotationMapper] which ensures all beans annotated with `javax.persistence.Entity` are introspectable by default.

NOTE: The `AnnotationMapper` should be on the annotation processor classpath.

=== The BeanWrapper API

A api:core.beans.BeanProperty[] provides raw access to read and write a property value for a given class and does not provide any automatic type conversion.

It is expected that the values you pass to the `set` and `get` methods match the underlying property type otherwise an exception will occur.

To provide additional type conversion smarts the api:core.beans.BeanWrapper[] interface allows wrapping an existing bean instance and setting and getting properties from the bean, plus performing type conversion as necessary.

snippet::io.micronaut.docs.ioc.beans.IntrospectionSpec[tags="wrapper", indent=0]

<1> The `getWrapper` static method can be used to obtain a api:core.beans.BeanWrapper[] for a bean instance.
<2> You can set properties and the api:core.beans.BeanWrapper[] will perform type conversion, or throw api:core.convert.exceptions.ConversionErrorException[] if conversion is not possible.
<3> You can retrieve a property using `getRequiredProperty` and request the appropriate type. If the property doesn't exist a api:core.beans.exceptions.IntrospectionException[] will be thrown and if it cannot be converted a api:core.convert.exceptions.ConversionErrorException[] will be thrown.


=== Jackson and Bean Introspection

Jackson is configured to use the api:core.beans.BeanIntrospection[] API to read and write property values and construct objects resulting in reflection-free serialization/deserialization which is beneficial from a performance perspective and requires less configuring to operate correctly with runtimes such as GraalVM native.

This feature is enabled by default, you can disable it by setting the `jackson.bean-introspection-module` configuration to `false`.

NOTE: Currently only bean properties (private field with public getter/setter) are supported and usage of public fields is not supported.

NOTE: This feature is currently regarded as experimental and may be subject to changes in the future.
