If you have multiple possible implementations for a given interface that you want to inject, you need to use a qualifier.

Once again Micronaut leverages JSR-330 and the link:{jeeapi}/javax/inject/Qualifier.html[Qualifier] and link:{jeeapi}/javax/inject/Named.html[Named] annotations to support this use case.

== Qualifying By Name

To qualify by name you can use the link:{jeeapi}/javax/inject/Named.html[Named] annotation. For example, consider the following classes:

snippet::io.micronaut.docs.inject.qualifiers.named.Engine,io.micronaut.docs.inject.qualifiers.named.V6Engine,io.micronaut.docs.inject.qualifiers.named.V8Engine,io.micronaut.docs.inject.qualifiers.named.Vehicle[tags="class",indent=0]

<1> The `Engine` interface defines the common contract
<2> The `V6Engine` class is the first implementation
<3> The `V8Engine` class is the second implementation
<4> The link:{jeeapi}/javax/inject/Named.html[javax.inject.Named] annotation is used to indicate the `V8Engine` implementation is required
<5> Calling the start method prints: `"Starting V8"`

You can also declare link:{jeeapi}/javax/inject/Named.html[@Named] at the class level of a bean to explicitly define the name of the bean.

== Qualifying By Annotation

In addition to being able to qualify by name, you can build your own qualifiers using the link:{jeeapi}/javax/inject/Qualifier.html[Qualifier] annotation. For example, consider the following annotation:

snippet::io.micronaut.docs.qualifiers.annotation.V8[tags="imports,class",indent=0]

The above annotation is itself annotated with the `@Qualifier` annotation to designate it as a qualifier. You can then use the annotation at any injection point in your code. For example:

snippet::io.micronaut.docs.qualifiers.annotation.Vehicle[tags="constructor",indent=0]

== Primary and Secondary Beans

api:context.annotation.Primary[] is a qualifier that indicates that a bean is the primary bean that should be selected in the case of multiple possible interface implementations.

Consider the following example:

snippet::io.micronaut.docs.context.annotation.primary.ColorPicker[tags="clazz", indent=0]

Given a common interface called `ColorPicker` that is implemented by multiple classes.

snippet::io.micronaut.docs.context.annotation.primary.Green[tags="imports,clazz", indent=0, title="The Primary Bean"]

The `Green` bean is a `ColorPicker`, but is annotated with `@Primary`.

snippet::io.micronaut.docs.context.annotation.primary.Blue[tags="imports,clazz", indent=0, title="Another Bean of the Same Type"]

The `Blue` bean is also a `ColorPicker` and hence you have two possible candidates when injecting the `ColorPicker` interface. Since `Green` is the primary it will always be favoured.

snippet::io.micronaut.docs.context.annotation.primary.TestController[tags="clazz", indent=0]

<1> Although there are two `ColorPicker` beans, `Green` gets injected due to the `@Primary` annotation.

If multiple possible candidates are present and no `@Primary` is defined then a api:context.exceptions.NonUniqueBeanException[] will be thrown.

In addition to `@Primary`, there is also a api:context.annotation.Secondary[] annotation which causes the opposite effect and allows de-prioritizing a bean.
