One significant difference between Micronaut's Dependency Injection system and Spring is the way beans can be replaced.

In a Spring application, beans have names and can effectively be overridden simply by creating a bean with the same name, regardless of the type of the bean. Spring also has the notion of bean registration order, hence in Spring Boot you have `@AutoConfigureBefore` and `@AutoConfigureAfter` that control how beans override each other.

This strategy leads to difficult to debug problems, for example:

* Bean loading order changes, leading to unexpected results
* A bean with the same name overrides another bean with a different type

To avoid these problems, Micronaut's DI has no concept of bean names or load order. Beans have a type and a api:context.Qualifier[]. You cannot override a bean of a completely different type with another.

A useful benefit of Spring's approach is that it allows overriding existing beans to customize behaviour. In order to support the same ability, Micronaut's DI provides an explicit ann:context.annotation.Replaces[] annotation, which integrates nicely with support for <<conditionalBeans, Conditional Beans>> and clearly documents and expresses the intention of the developer.

Any existing bean can be replaced by another bean that declares ann:context.annotation.Replaces[]. For example, consider the following class:

snippet::io.micronaut.docs.requires.JdbcBookService[tags="requires",indent=0, title="JdbcBookService"]

You can define a class in `src/test/java` that replaces this class just for your tests:

snippet::io.micronaut.docs.replaces.MockBookService[tags="class",indent=0, title="Using @Replaces"]

<1> The `MockBookService` declares that it replaces `JdbcBookService`

=== Factory Replacement

The `@Replaces` annotation also supports a `factory` argument. That argument allows the replacement of factory beans in their entirety or specific types created by the factory.

For example, it may be desired to replace all or part of the given factory class:

snippet::io.micronaut.docs.replaces.BookFactory[tags="class",indent=0, title="BookFactory"]

WARNING: To replace a factory in its entirety, it is necessary that your factory methods match the return types of all of the methods in the replaced factory.

In this example, the `BookFactory#textBook()` will *not* be replaced because this factory does not have a factory method that returns a TextBook.

snippet::io.micronaut.docs.replaces.CustomBookFactory[tags="class",indent=0, title="CustomBookFactory"]

It may be the case that you don't wish for the factory methods to be replaced, except for a select few. For that use case, you can apply the `@Replaces` annotation on the method and denote the factory that it should apply to.

snippet::io.micronaut.docs.replaces.TextBookFactory[tags="class",indent=0, title="TextBookFactory"]

The `BookFactory#novel()` method will not be replaced because the TextBook class is defined in the annotation.

=== Default Implementation

When exposing an API, it may be desirable for the default implementation of an interface to not be exposed as part of the public API. Doing so would prevent users from being able to replace the implementation because they would not be able to reference the class. The solution is to annotate the interface with api:context.annotation.DefaultImplementation[] to indicate which implementation should be replaced if a user creates a bean that `@Replaces(YourInterface.class)`.

For example consider:

A public API contract

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.ResponseStrategy[tags="clazz"]

The default implementation

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.DefaultResponseStrategy[tags="clazz"]

The custom implementation

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.CustomResponseStrategy[tags="clazz"]

In the above example, the `CustomResponseStrategy` will replace the `DefaultResponseStrategy` because the api:context.annotation.DefaultImplementation[] annotation points to the `DefaultResponseStrategy`.
