One significant difference between Micronaut's Dependency Injection system and Spring is the way beans can be replaced.

In a Spring application, beans have names and can effectively be overriden simply by creating a bean with the same name, regardless of the type of the bean. Spring also has the notion of bean registration order, hence in Spring Boot you have `@AutoConfigureBefore` and `@AutoConfigureAfter` the control how beans override each other.

This strategy leads to difficult to debug problems, for example:

* Bean loading order changes, leading to unexpected results
* A bean with the same name overrides another bean with a different type

To avoid these problems, Micronaut's DI has no concept of bean names or load order. Beans have a type and a api:context.Qualifier[]. You cannot override a bean of a completely different type with another.

A useful benefit of Spring's approach is that it allows overriding existing beans to customize behaviour. In order to support the same ability, Micronaut's DI provides an explicit ann:context.annotation.Replaces[] annotation, which integrates nicely with support for <<conditionalBeans, Conditional Beans>> and clearly documents and expresses the intention of the developer.

Any existing bean can be replaced by another bean that declares ann:context.annotation.Replaces[]. For example, consider the following class:

.JdbcBookService.java
[source,java]
----
include::{testsjava}/replaces/JdbcBookService.java[tags=replaces, indent=0]
}
----

You can define a class in `src/test/java` that replaces this class just for your tests:

.Using @Replaces
[source,java]
----
include::{testsjava}/replaces/MockBookService.java[tags=class, indent=0]
----

<1> The `MockBookService` declares that it replaces `JdbcBookService`
<2> But only for for the `test` environment
