One significant difference between Micronaut's Dependency Injection system and Spring's is the way beans are replaced.

In a Spring application, beans have names and are overridden by creating a bean with the same name, regardless of the type of the bean. Spring also has the notion of bean registration order, hence in Spring Boot you have `@AutoConfigureBefore` and `@AutoConfigureAfter` annotations that control how beans override each other.

This strategy leads to problems that are difficult to debug, for example:

* Bean loading order changes, leading to unexpected results
* A bean with the same name overrides another bean with a different type

To avoid these problems, Micronaut's DI has no concept of bean names or load order. Beans have a type and a api:context.Qualifier[]. You cannot override a bean of a completely different type with another.

A useful benefit of Spring's approach is that it allows overriding existing beans to customize behaviour. To support the same ability, Micronaut's DI provides an explicit ann:context.annotation.Replaces[] annotation, which integrates nicely with support for <<conditionalBeans, Conditional Beans>> and clearly documents and expresses the intention of the developer.

Any existing bean can be replaced by another bean that declares ann:context.annotation.Replaces[]. For example, consider the following class:

snippet::io.micronaut.docs.requires.JdbcBookService[tags="requires",indent=0, title="JdbcBookService"]

You can define a class in `src/test/java` that replaces this class just for your tests:

snippet::io.micronaut.docs.replaces.MockBookService[tags="class",indent=0, title="Using @Replaces"]

<1> The `MockBookService` declares that it replaces `JdbcBookService`

=== Factory Replacement

The `@Replaces` annotation also supports a `factory` argument. That argument allows the replacement of factory beans in their entirety or specific types created by the factory.

For example, it may be desired to replace all or part of the given factory class:

snippet::io.micronaut.docs.replaces.BookFactory[tags="class",indent=0, title="BookFactory"]

WARNING: To replace a factory entirely, your factory methods must match the return types of all methods in the replaced factory.

In this example, `BookFactory#textBook()` is *not* replaced because this factory does not have a factory method that returns a `TextBook`.

snippet::io.micronaut.docs.replaces.CustomBookFactory[tags="class",indent=0, title="CustomBookFactory"]

To replace one or more factory methods but retain the rest, apply the `@Replaces` annotation on the method(s) and denote the factory to apply to.

snippet::io.micronaut.docs.replaces.TextBookFactory[tags="class",indent=0, title="TextBookFactory"]

The `BookFactory#novel()` method will not be replaced because the TextBook class is defined in the annotation.

=== Default Implementation

When exposing an API, you may want to define an implementation of the interface that is used as the default when injecting a particular interface. For this you can use the ann:context.annotation.DefaultImplementation[] annotation.

It may also be desirable to not expose the default implementation of an interface as part of the public API by making it package private in Java.

Doing so prevents users from being able to replace the implementation because they will not be able to reference the class.

The ann:context.annotation.DefaultImplementation[] annotation allows the framework to establish the implementation to replace if a user creates a bean that declares `@Replaces(YourInterface.class)`.

For example consider:

A public API contract

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.ResponseStrategy[tags="clazz"]

The default implementation

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.DefaultResponseStrategy[tags="clazz"]

The custom implementation

snippet::io.micronaut.docs.qualifiers.replaces.defaultimpl.CustomResponseStrategy[tags="clazz"]

In the above example, the `CustomResponseStrategy` replaces the `DefaultResponseStrategy` because the api:context.annotation.DefaultImplementation[] annotation points to the `DefaultResponseStrategy`.
