In addition to being able to inject beans, Micronaut natively supports injecting the following types:

.Injectable Container Types
|===
|Type |Description |Example

|link:{jdkapi}/java/util/Optional.html[java.util.Optional]
|An `Optional` of a bean. `empty()` is injected if the bean doesn't exist
|`Optional<Engine>`

|link:{jdkapi}/java/lang/Collection.html[java.lang.Collection]
|An `Collection` or subtype of `Collection` (e.g. `List`, `Set`, etc.)
|`Collection<Engine>`

|link:{jdkapi}/java/util/stream/Stream.html[java.util.stream.Stream]
|A lazy `Stream` of beans
|`Stream<Engine>`

|link:{jdkapi}/java/lang/reflect/Array.html[Array]
|A native array of beans of a given type
|`Engine[]`

|link:{jeeapi}/javax/inject/Provider.html[Provider]
|A `javax.inject.Provider` if a circular dependency requires it, or to instantiate a prototype for each `get` call.
|`Provider<Engine>`

|link:{jakartaapi}/jakarta/inject/Provider.html[Provider]
|A `jakarta.inject.Provider` if a circular dependency requires it or to instantiate a prototype for each `get` call.
|`Provider<Engine>`

|api:context.BeanProvider[]
|A `io.micronaut.context.BeanProvider` if a circular dependency requires it or to instantiate a prototype for each `get` call.
|`BeanProvider<Engine>`

|===

NOTE: There are 3 different provider types supported, however the `BeanProvider` is the one we suggest to use.

[NOTE]
====
When injecting a `java.lang.Collection`, or `java.util.stream.Stream`, `Array` of beans into a bean matching the injection type, then the owning bean will not be be a member of the injected collection.  A common pattern demonstrating this is aggregation. For example:
```java
@Singleton
class AggregateEngine implements Engine {
  @Inject
  List<Engine> engines;

  @Override
  public void start() {
    engines.forEach(Engine::start);
  }

  ...
}
```
In this example, the injected member variable `engines` will not contain an instance of `AggregateEngine`
====

TIP: A prototype bean will have one instance created per place the bean is injected. When a prototype bean is injected as a provider, each call to `get()` creates a new instance.

=== Collection Ordering

When injecting a collection of beans, they are not ordered by default. Implement the api:core.order.Ordered[] interface to inject an ordered collection. If the requested bean type does not implement api:core.order.Ordered[], Micronaut searches for the ann:core.annotation.Order[] annotation on beans.

The ann:core.annotation.Order[] annotation is especially useful for ordering beans created by factories where the bean type is a class in a third-party library. In this example, both `LowRateLimit` and `HighRateLimit` implement the `RateLimit` interface.

snippet::io.micronaut.docs.config.env.RateLimitsFactory[tags="clazz", indent=0, title="Factory with @Order"]

When a collection of `RateLimit` beans are requested from the context, they are returned in ascending order based on the value in the annotation.

=== Injecting a Bean by Order

When injecting a single instance of a bean the ann:core.annotation.Order[] annotation can also be used to define which bean has the highest precedence and hence should be injected.

NOTE: The api:core.order.Ordered[] interface is not taken into account when selecting a single instance as this would require instantiating the bean to resolve the order.