The beans endpoint returns information about the loaded bean definitions in the application. The bean data returned by default is an object where the key is the bean definition class name and the value is an object of properties about the bean.

To execute the beans endpoint, send a GET request to /beans.

== Configuration

To configure the beans endpoint, supply configuration through `endpoints.beans`.

.Beans Endpoint Configuration Example
[source,yaml]
----
endpoints:
  beans:
    enabled: Boolean
    sensitive: Boolean
----

== Customization

The beans endpoint is composed of a bean definition data collector and a bean data implementation. The bean definition data collector (link:{api}/io/micronaut/management/endpoint/beans/BeanDefinitionDataCollector.html[BeanDefinitionDataCollector]) is responsible for returning a publisher that returns the data used in the response. The bean definition data (link:{api}/io/micronaut/management/endpoint/beans/BeanDefinitionData.html[BeanDefinitionData]) is responsible for returning data about an individual bean definition.

To override the default behavior for either of the helper classes, either extend the default implementations (link:{api}/io/micronaut/management/endpoint/beans/impl/DefaultBeanDefinitionDataCollector.html[DefaultBeanDefinitionDataCollector], link:{api}/io/micronaut/management/endpoint/beans/impl/DefaultBeanDefinitionData.html[DefaultBeanDefinitionData]), or implement the relevant interface directly. To ensure your implementation is used instead of the default, add the link:{api}/io/micronaut/context/annotation/Replaces.html[@Replaces] annotation to your class with the value being the default implementation.
