
The caches endpoint returns information about the caches in the application and
permits invalidating them.

To get a collection of all caches by name with their configuration, send a GET request to /caches.

[source,bash]
----
$ curl http://localhost:8080/caches
----

To get the configuration of a particular cache, include the cache name in your GET request. For
example, to access the configuration of the cache 'book-cache':

[source,bash]
----
$ curl http://localhost:8080/caches/book-cache
----

To invalidate all cached values within a single cache, send a DELETE request to the named cache URL.

[source,bash]
----
$ curl -X DELETE http://localhost:8080/caches/book-cache
----

To invalidate all caches, send a DELETE request to /caches.

[source,bash]
----
$ curl -X DELETE http://localhost:8080/caches
----

== Configuration

To configure the caches endpoint, supply configuration through `endpoints.caches`.

.Caches Endpoint Configuration Example
[source,yaml]
----
endpoints:
    caches:
        enabled: Boolean
        sensitive: Boolean
----

== Customization

The caches endpoint is composed of a cache data collector and a cache data implementation.
The cache data collector (link:{api}/io/micronaut/management/endpoint/caches/CacheDataCollector.html[CacheDataCollector])
is responsible for returning a publisher that will return the data used in the response.
The cache data (link:{api}/io/micronaut/management/endpoint/caches/CacheData.html[CacheData]) is responsible for returning
data about an individual cache.

To override the default behavior for either of the helper classes, either extend the default implementations
(link:{api}/io/micronaut/management/endpoint/caches/impl/RxJavaCacheDataCollector.html[RxJavaRouteDataCollector], link:{api}/io/micronaut/management/endpoint/caches/impl/DefaultCacheData.html[DefaultRouteData]),
or implement the relevant interface directly.
To ensure your implementation is used instead of the default, add the link:{api}/io/micronaut/context/annotation/Replaces.html[@Replaces]
annotation to your class with the value being the default implementation.
