The health endpoint returns information about the "health" of the application. The application health is determined by any number of "health indicators".

To execute the health endpoint, send a GET request to /health. Additionally the health endpoint exposes /health/liveness and /health/readiness health indicators.

== Configuration

To configure the health endpoint, supply configuration through `endpoints.health`.

.Health Endpoint Configuration Example
[source,yaml]
----
endpoints:
    health:
        enabled: Boolean
        sensitive: Boolean
        details-visible: String <1>
        status:
            http-mapping: Map<String, HttpStatus>
----

<1> One of api:management.endpoint.health.DetailsVisibility[]

The `details-visible` setting is used to control whether health detail should be exposed to users who are not authenticated.

For example setting:

.Using `details-visible`
[source,yaml]
----
endpoints:
    health:
        details-visible: ANONYMOUS
----

Will expose detailed information read from the various health indicators about the health status of the application to anonymous unauthenticated users.

The `endpoints.health.status.http-mapping` setting can be used to control what status codes are returned for each health status. The defaults are described in the table below:


|===
|Status | HTTP Code

|api:health.HealthStatus#UP[]
|api:http.HttpStatus#OK[] (200)

|api:health.HealthStatus#UNKNOWN[]
|api:http.HttpStatus#OK[] (200)

|api:health.HealthStatus#DOWN[]
|api:http.HttpStatus#SERVICE_UNAVAILABLE[] (503)

|===

You can provide custom mappings in `application.yml`:


.Custom Health Status Codes
[source,yaml]
----
endpoints:
    health:
        status:
            http-mapping:
                DOWN: 200
----

The above will return api:http.HttpStatus#OK[] (200) even when the api:health.HealthStatus[] is api:health.HealthStatus#DOWN[].


== Customization

The health endpoint consists of a health aggregator and any number of health indicators. To add a health indicator, simply create a bean class that implements link:{api}/io/micronaut/management/health/indicator/HealthIndicator.html[HealthIndicator]. It is recommended to also use either link:{api}/io/micronaut/health/indicator/annotation/Liveness.html[@Liveness] or link:{api}/io/micronaut/health/indicator/annotation/Readiness.html[@Readiness] qualifier. If no qualifier is used then the health incidator is part of /health and /health/readiness endpoints. A base class link:{api}/io/micronaut/management/health/indicator/AbstractHealthIndicator.html[AbstractHealthIndicator] has been provided for you to extend to make the process easier.

All of the health indicator beans will be collected together with the health aggregator. To provide your own implementation of the health aggregator, create a class that implements link:{api}/io/micronaut/management/health/aggregator/HealthAggregator.html[HealthAggregator] and register it as a bean. To ensure your implementation is used instead of the default, add the link:{api}/io/micronaut/context/annotation/Replaces.html[@Replaces] annotation to your class with the value being the link:{api}/io/micronaut/management/health/aggregator/RxJavaHealthAggregator.html[default implementation].

The default health aggregator returns an overall status that is calculated based on the health statuses of the indicators. A link:{api}/io/micronaut/health/HealthStatus.html[health status] consists of several pieces of information.

|=======
|Name |The name of the status
|Description |The description of the status
|Operational |Whether the functionality the indicator represents is functional
|Severity |How severe the status is. A higher number is more severe
|=======

The "worst" status will be returned as the overall status. A non operational status will be selected over an operational status. A higher severity will be selected over a lower severity.

== Provided Indicators

All micronaut provided health indicators are exposed on /health and /health/readiness endpoints.

=== Disk Space

A health indicator is provided that determines the health of the application based on the amount of free disk space. Configuration for the disk space health indicator can be provided under the `endpoints.health.disk-space` key.

.Disk Space Indicator Configuration Example
[source,yaml]
----
endpoints:
    health:
        disk-space:
            enabled: Boolean
            path: String #The file path used to determine the disk space
            threshold: String | Long #The minimum amount of free space
----

The threshold can be provided as a string like "10MB" or "200KB", or the number of bytes.

=== JDBC

The JDBC health indicator determines the health of your application based on the ability to successfully create connections to datasources in the application context. The only configuration option supported is to enable or disable the indicator by the `endpoints.health.jdbc.enabled` key.

=== Discovery Client

If your application is using service discovery, a health indicator will be included to monitor the health of the discovery client. The data returned can include a list of the services available.