The health endpoint returns information about the "health" of the application. The application health is determined by any number of "health indicators".

To execute the health endpoint, send a GET request to /health.

== Configuration

To configure the health endpoint, supply configuration through `endpoints.health`.

.Health Endpoint Configuration Example
[source,yaml]
----
endpoints:
    health:
        enabled: Boolean
        sensitive: Boolean
        id: String
----

== Customization

The health endpoint consists of a health aggregator and any number of health indicators. To add a health indicator, simply create a bean class that implements link:{api}/io/micronaut/management/health/indicator/HealthIndicator.html[HealthIndicator]. A base class link:{api}/io/micronaut/management/health/indicator/AbstractHealthIndicator.html[AbstractHealthIndicator] has been provided for you to extend to make the process easier.

All of the health indicator beans will be collected together with the health aggregator. To provide your own implementation of the health aggregator, create a class that implements link:{api}/io/micronaut/management/health/aggregator/HealthAggregator.html[HealthAggregator] and register it as a bean. To ensure your implementation is used instead of the default, add the link:{api}/io/micronaut/context/annotation/Replaces.html[@Replaces] annotation to your class with the value being the link:{api}/io/micronaut/management/health/aggregator/RxJavaHealthAggregator.html[default implementation].

The default health aggregator returns an overall status that is calculated based on the health statuses of the indicators. A link:{api}/io/micronaut/health/HealthStatus.html[health status] consists of several pieces of information.

|=======
|Name |The name of the status
|Description |The description of the status
|Operational |Whether the functionality the indicator represents is functional
|Severity |How severe the status is. A higher number is more severe
|=======

The "worst" status will be returned as the overall status. A non operational status will be selected over an operational status. A higher severity will be selected over a lower severity.

== Provided Indicators

=== Disk Space

A health indicator is provided that determines the health of the application based on the amount of free disk space. Configuration for the disk space health indicator can be provided under the `endpoints.health.disk-space` key.

.Disk Space Indicator Configuration Example
[source,yaml]
----
endpoints:
    health:
        disk-space:
            enabled: Boolean
            path: String #The file path used to determine the disk space
            threshold: String | Long #The minimum amount of free space
----

The threshold can be provided as a string like "10MB" or "200KB", or the number of bytes.

=== JDBC

The JDBC health indicator determines the health of your application based on the ability to successfully create connections to datasources in the application context. The only configuration option supported is to enable or disable the indicator by the `endpoints.health.jdbc.enabled` key.