The metrics endpoint returns information about the "metrics" of the application.

To execute the metrics endpoint, send a GET request to /metrics.  This will return a list of the metrics registered with the `MeterRegistry` bean.

== Configuration

Currently the metrics endpoint will only be enabled if you include the `micrometer-core` or one of the reporters (which transitively include the core library) such as `micrometer-statsd` or `micrometer-graphite`.  You will also need to have the global metrics flag enabled.

[source,yaml]
----
micronaut:
  metrics:
    enabled: true
----

To configure the metrics endpoint, supply configuration through `endpoints.metrics`.

.Metrics Endpoint Configuration Example
[source,yaml]
----
endpoints:
  metrics:
    enabled: Boolean
    sensitive: Boolean
    id: String
----

== Custom Metrics

To add metrics to your application you can inject the MeterRegistry bean to your class and use the provided methods to access counters, timers, etc.

See the Micrometer.io docs at https://micrometer.io/docs for more information.

.Custom Metrics Example
[source,java]
----
import io.micrometer.core.instrument.Counter;
import io.micrometer.core.instrument.MeterRegistry;
import io.micronaut.http.annotation.Controller;
import io.micronaut.http.annotation.Get;
import io.micronaut.http.annotation.QueryValue;
import io.micronaut.validation.Validated;
import io.reactivex.Single;

import javax.annotation.Nullable;
import javax.validation.constraints.NotBlank;

@Controller("/")
@Validated
public class IndexController {

    private MeterRegistry meterRegistry;

    public IndexController(MeterRegistry meterRegistry) {
        this.meterRegistry = meterRegistry;
    }

    @Get("/hello/{name}")
    public Single hello(@NotBlank String name) {
        meterRegistry
                .counter("web.access", "controller", "index", "action", "hello")
                .increment();
        return Single.just("Hello " + name);
    }

}
----

== Provided Metrics

The following metrics currently have binders and are enabled by default.  The settings listed below can disable the specific metric binders if you do not with to collect or report the specific metrics.

=== Jvm Metrics

The JVM metrics bindings will provide several jvm metrics.

*Control Property*: `micronaut.metrics.binders.jvm.enabled`

.Metrics provided
|=======
|*Name* 
| jvm.buffer.count 
| jvm.buffer.memory.used
| jvm.buffer.total.capacity
| jvm.classes.loaded
| jvm.classes.unloaded
| jvm.gc.live.data.size
| jvm.gc.max.data.size
| jvm.gc.memory.allocated
| jvm.gc.memory.promoted
| jvm.memory.committed
| jvm.memory.max
| jvm.memory.used
| jvm.threads.daemon
| jvm.threads.live
| jvm.threads.peak
|=======

=== Web Metrics

There is a default web filter provided for web metrics.  All routes, status codes, methods and exceptions will be timed and counted.

*Control Property*: `micronaut.metrics.binders.web.enabled`

.Filter Path
If enabled, be default the path `/**` will be intercepted.  If you wish to change which paths are run through the filter set the following property.

*Control Property*: `micronaut.metrics.http.path`

.Metrics provided
|=======
|*Name*
| http.server.requests
|=======

=== System Metrics

There are multiple metrics that can be separately toggled.

==== Uptime Metrics

The uptime metrics bindings will provide system uptime metrics.

*Control Property*: `micronaut.metrics.binders.uptime.enabled`

.Metrics provided
|=======
|*Name*
| process.uptime
| process.start.time
|=======

==== Processor Metrics

The processor metrics bindings will provide system processor metrics.

*Control Property*: `micronaut.metrics.binders.processor.enabled`

.Metrics provided
|=======
|*Name*
| system.load.average.1m
| system.cpu.usage
| system.cpu.count
| process.cpu.usage
|=======

==== File Descriptor Metrics

The file descriptor metrics bindings will provide system file descriptor metrics.

*Control Property*: `micronaut.metrics.binders.files.enabled`

.Metrics provided
|=======
|*Name*
| process.files.open
| process.files.max
|=======

=== Logback Metrics

The logging metrics bindings will provide logging metrics if using Logback.

*Control Property*: `micronaut.metrics.binders.logback.enabled`

.Metrics provided
|=======
|*Name*
| logback.events
|=======

== Metrics Registries & Reporters

By default there a metrics endpoint wired up and metrics are provided to it for viewing or retrieving via http.  If you want to register a specific type of reporter you will need to include a typed registry configuration.  The following are the currently supported libraries for reporting metrics.

=== Statsd Registry

You can include the statsd reporter via `io.micronaut.configuration:micrometer-registry-statsd:${micronaut.version}`

.Maven
[source,xml]
----
<dependency>
	<groupId>io.micronaut.configuration</groupId>
	<artifactId>micrometer-registry-statsd</artifactId>
	<version>${micronaut.version}</version>
</dependency>
----

You can configure this reporter using `micronaut.metrics.export.statsd`.  The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-statsd/src/main/java/io/micrometer/statsd/StatsdConfig.java[StatdsConfig] for more options

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|flavor |The type of metric to use (datadog, etsy or telegraf). Default: `datadog`
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|host |The host to communicate to statsd on. Default: `localhost`
|port |The port to communicate to statsd on. Default: `8125`
|=======

.Example Statsd Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      statsd:
        enabled: true
        flavor: datadog
        step: PT1M
        host: localhost
        port: 8125
----

=== Graphite Registry

You can include the graphite reporter via `io.micronaut.configuration:micrometer-registry-graphite:${micronaut.version}`

.Maven
[source,xml]
----
<dependency>
	<groupId>io.micronaut.configuration</groupId>
	<artifactId>micrometer-registry-graphite</artifactId>
	<version>${micronaut.version}</version>
</dependency>
----

You can configure this reporter using `micronaut.metrics.export.graphite`.  The most commonly changed configuration properties are listed below, but see https://github.com/micrometer-metrics/micrometer/blob/master/implementations/micrometer-registry-graphite/src/main/java/io/micrometer/graphite/GraphiteConfig.java[GraphiteConfig] for more options

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|host |The host to communicate to graphite on. Default: `localhost`
|port |The port to communicate to graphite on. Default: `2004`
|=======

.Example Graphite Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      graphite:
        enabled: true
        step: PT1M
        host: localhost
        port: 2004
----

=== Atlas Registry

You can include the atlas reporter via `io.micronaut.configuration:micrometer-registry-atlas:${micronaut.version}`

.Maven
[source,xml]
----
<dependency>
	<groupId>io.micronaut.configuration</groupId>
	<artifactId>micrometer-registry-atlas</artifactId>
	<version>${micronaut.version}</version>
</dependency>
----

You can configure this reporter using `micronaut.metrics.export.atlas`.  The most commonly changed configuration properties are listed below, but see https://github.com/Netflix/spectator/blob/master/spectator-reg-atlas/src/main/java/com/netflix/spectator/atlas/AtlasConfig.java[AtlasConfig] for more options

|=======
|*Name* |*Description*
|enabled |Whether to enable the reporter. Could disable to local dev for example. Default: `true`
|step |How frequently to report metrics. Default: `PT1M` (1 min).  See `java.time.Duration#parse(CharSequence)`
|uri |The uri for the atlas backend. Default: `http://localhost:7101/api/v1/publish`
|=======

.Example Graphite Config
[source,yml]
----
micronaut:
  metrics:
    enabled: true
    export:
      atlas:
        enabled: true
        uri: http://localhost:7101/api/v1/publish
        step: PT1M
----