The routes endpoint returns information about URIs available to be called for your application. By default the data returned includes the URI, allowed method, content types produced, and information about the method that would be executed.

To execute the routes endpoint, send a GET request to /routes.

== Configuration

To configure the routes endpoint, supply configuration through `endpoints.routes`.

.Routes Endpoint Configuration Example
[source,yaml]
----
endpoints:
  routes:
    enabled: Boolean
    sensitive: Boolean
----

== Customization

The routes endpoint is composed of a route data collector and a route data implementation. The route data collector (link:{api}/io/micronaut/management/endpoint/routes/RouteDataCollector.html[RouteDataCollector]) is responsible for returning a publisher that returns the data used in the response. The route data (link:{api}/io/micronaut/management/endpoint/routes/RouteData.html[RouteData]) is responsible for returning data about an individual route.

To override the default behavior for either of the helper classes, either extend the default implementations (link:{api}/io/micronaut/management/endpoint/routes/impl/DefaultRouteDataCollector.html[DefaultRouteDataCollector], link:{api}/io/micronaut/management/endpoint/routes/impl/DefaultRouteData.html[DefaultRouteData]), or implement the relevant interface directly. To ensure your implementation is used instead of the default, add the link:{api}/io/micronaut/context/annotation/Replaces.html[@Replaces] annotation to your class with the value being the default implementation.
