import org.graalvm.buildtools.gradle.tasks.BuildNativeImageTask

plugins {
    id("application")
    id("org.graalvm.buildtools.native") version "0.11.1"
}

repositories {
// %REPOSITORIES%
}

dependencies {
// %DEPENDENCIES%
    implementation(files("%PYRONAUT_PATH%"))
}

application {
    mainClass = "%MAIN_CLASS%"
}

sourceSets {
    java {
        main {
            resources.srcDir("%PYRONAUT_CONFIG%")
        }
    }
}

graalvmNative {
    binaries.all {
        resources.autodetect()
        verbose = true
        buildArgs.addAll([
                "-Dpolyglot.image-build-time.PreinitializeContexts=python",
                "--enable-native-access=org.graalvm.truffle",
                "--gc=G1",
                "-march=native"
        ])
    }
    binaries.main {
        imageName = "%IMAGE_NAME%"
    }
}

tasks.register("exportBinary", Sync) {
    from(tasks.named("nativeCompile").flatMap(BuildNativeImageTask::getOutputDirectory))
    into(file("%DESTINATION_DIR%"))
    doLast {
        println("Native Pyronaut application exported to %DESTINATION_DIR%")
    }
}
