Log levels can be configured via properties defined in your configuration file (e.g. `application.yml`) (and environment variables) with the `logger.levels` prefix:

[configuration]
----
logger:
  levels:
    foo.bar: ERROR
----

The same configuration can be achieved by setting the environment variable `LOGGER_LEVELS_FOO_BAR`. Note that there is currently no way to set log levels for unconventional prefixes such as `foo.barBaz`.

==== Custom Logback XML Configuration

[configuration]
----
logger:
  config: /foo/custom-logback.xml
----

You can also set a custom Logback XML configuration file to be used via `logger.config`.
The file is first checked on the classpath and then on the file system.

When any `logger.*` property is set, the Micronaut framework resets Logback and configures it again at startup and on every refresh event, before it applies the levels. A Logback XML configuration file set in Micronaut configuration wins: `logback.configurationFile`, unless its value is exactly that of the JVM system property of the same name, or `logger.config` when `logback.configurationFile` is not set. The framework configures Logback from that file even when a custom Logback `Configurator` is registered as a service, and startup fails when the file does not exist or cannot be parsed.

Otherwise, Logback is configured again the way Logback configures itself at startup, as described in the link:https://logback.qos.ch/manual/configuration.html#auto_configuration[Logback manual]: the `Configurator` services by rank, until one of them returns `DO_NOT_INVOKE_NEXT_IF_ANY`, then the file set with the `logback.configurationFile` JVM system property, `logback-test.xml` or `logback.xml` on the classpath, then the basic console configuration. Logback resolves the system property as a URL, then on the classpath, then on the file system. When it does not find the file, it goes on to `logback-test.xml` and `logback.xml`, and `logger.config` is not used. When Logback cannot parse the file it finds, it reports the error the way it does at startup, and the application still starts.

The framework adds one step to that lookup: a `logback.xml` file in the working directory is used when there is no `Configurator` service, the `logback.configurationFile` JVM system property is not set, and neither `logback-test.xml` nor `logback.xml` is on the classpath. Logback itself does not look in the working directory, so until the application context starts, such an application logs with the basic console configuration. The framework reads that file itself, so, as with a file set in Micronaut configuration, startup fails when it cannot be parsed.

==== Disabling a Logger with Properties

To disable a logger, you need to set the logger level to `OFF`:

[configuration]
----
logger:
  levels:
    io.verbose.logger.who.CriedWolf: OFF
----
- This will disable ALL logging for the class `io.verbose.logger.who.CriedWolf`


Note that the ability to control log levels via config is controlled via the api:logging.LoggingSystem[] interface. Currently, the Micronaut framework includes a single implementation that allows setting log levels for the Logback library. If you use another library, you should provide a bean that implements this interface.
