Log levels can be configured via properties defined in your configuration file (e.g. `application.yml`) (and environment variables) with the `logger.levels` prefix:

[configuration]
----
logger:
  levels:
    foo.bar: ERROR
----

The same configuration can be achieved by setting the environment variable `LOGGER_LEVELS_FOO_BAR`. Note that there is currently no way to set log levels for unconventional prefixes such as `foo.barBaz`.

==== Custom Logback XML Configuration

[configuration]
----
logger:
  config: /foo/custom-logback.xml
----

You can also set a custom Logback XML configuration file to be used via `logger.config`.
The file is first checked on the classpath and then on the file system.

When any `logger.*` property is set, the Micronaut framework resets Logback and configures it again at startup and on every refresh event, before it applies the levels. A Logback XML configuration file set in Micronaut configuration wins: `logback.configurationFile`, unless it is also set as a JVM system property, otherwise `logger.config`. The framework configures Logback from that file even when a custom Logback `Configurator` is registered as a service, and startup fails when the file does not exist.

Otherwise, Logback is configured again the way Logback configures itself at startup, as described in the link:https://logback.qos.ch/manual/configuration.html#auto_configuration[Logback manual]: the `Configurator` services by rank, until one of them returns `DO_NOT_INVOKE_NEXT_IF_ANY`, then the file set with the `logback.configurationFile` JVM system property, `logback-test.xml` or `logback.xml`, then the basic console configuration.

==== Disabling a Logger with Properties

To disable a logger, you need to set the logger level to `OFF`:

[configuration]
----
logger:
  levels:
    io.verbose.logger.who.CriedWolf: OFF
----
- This will disable ALL logging for the class `io.verbose.logger.who.CriedWolf`


Note that the ability to control log levels via config is controlled via the api:logging.LoggingSystem[] interface. Currently, the Micronaut framework includes a single implementation that allows setting log levels for the Logback library. If you use another library, you should provide a bean that implements this interface.
