Micronaut supports CSP (link:https://www.w3.org/TR/CSP2/[Content Security Policy Level 2]) out of the box. By default, CSP is disabled. To enable CSP, modify your configuration. For example with `application.yml`:

.CSP Configuration Example
[source,yaml]
----
micronaut:
    views:
        csp:
            enabled: true
            reportOnly: false
            policyDirectives: "default-src self"
----

In the above example, the policy directive enforces any resources (images, fonts, scripts, etc.) that are not on the same origin to be blocked from loading. In this case, if an attempt is made to load a script or a resource from a different origin, say from, \http://evil.com, the browser would block these from loading, optionally report such violations, which could be very useful in mitigating XSS attacks.

.CSP Reporting Example
[source,yaml]

----
micronaut:
    views:
        csp:
            enabled: true
            reportOnly: false
            policyDirectives: "default-src https:; report-uri /csp-violation-report-endpoint"
----

If you would like to dry run the policy, you could just report violations that would have occurred by enabling 'reportOnly' key in your CSP configuration.

The following example demonstrates a simple CSP reporting controller that can be used to process violations from the user-agent.

[source,groovy]
.CspReportController.groovy
----
include::{testsviews}/filters/CspReportController.groovy[tags=import, indent=0]

include::{testsviews}/filters/CspReportController.groovy[tags=classBegin, indent=0]

include::{testsviews}/filters/CspReportController.groovy[tags=type, indent=4]

include::{testsviews}/filters/CspReportController.groovy[tags=report, indent=4]
include::{testsviews}/filters/CspReportController.groovy[tags=classEnd, indent=0]
----
<1> Violation reports are standard JSON structures with a custom type set to 'application/csp-report'.

To process a link:https://www.w3.org/TR/CSP2/#violation-reports[violation report] using JSON codec, it has to be registered as an additional type in your application configuration.

.CSP Reporting Endpoint Custom Content Type
[source,yaml]
----
micronaut:
    codec:
        json:
            additionalTypes:
                - application/csp-report
----

An example violation from Chrome looks like:

.JSON report structure
[source,json]
----
{
  "csp-report": {
    "document-uri": "http://localhost:8080/",
    "referrer": "",
    "violated-directive": "img-src",
    "effective-directive": "img-src",
    "original-policy": "default-src https:; report-uri /report",
    "disposition": "enforce",
    "blocked-uri": "http://localhost:8080/favicon.ico",
    "status-code": 200,
    "script-sample": ""
  }
}
----