https://www.graalvm.org[GraalVM] is a new universal virtual machine from Oracle that supports a polyglot runtime environment and the ability to compile Java applications down to native machine code.

Any Micronaut application can be run using the GraalVM JVM, however special support has been added to Micronaut to support running Micronaut applications using https://www.graalvm.org/docs/reference-manual/aot-compilation/[GraalVM's `nativeimage` tool].

NOTE: Use of GraalVM's `nativeimage` tool is only supported in Java or Kotlin projects. Groovy relies heavily on reflection which is only partially supported by GraalVM.

To start using GraalVM you should first install the GraalVM SDK via the https://www.graalvm.org/docs/getting-started/[Getting Started] instructions or using SDKman:

.Installing GraalVM 1.0.0-rc6 with SDKman
[source,bash]
----
$ sdk install java 1.0.0-rc6-graal
$ sdk use java 1.0.0-rc6-graal
----

Note the above commands install the `1.0.0-rc6` version, and may need to be altered depending on the current release available.

WARNING: As of this writing, GraalVM is currently only available for Linux and Mac OS X systems.

Once you have installed the SDK you should make the `svm` dependency available via your local Maven cache. The easiest way to do this is via Maven's `install` command:

.Installing the SVM Dependency Locally
[source,bash]
----
$ mvn install:install-file -Dfile=${JAVA_HOME}/jre/lib/svm/builder/svm.jar \
                           -DgroupId=com.oracle.substratevm \
                           -DartifactId=svm \
                           -Dversion=GraalVM-1.0.0-rc6 \
                           -Dpackaging=jar
----
