For Java, Micronaut uses a Java api:annotation.processing.BeanDefinitionInjectProcessor[] annotation processor to process classes at compile time and produce api:inject.BeanDefinition[] classes.

The major advantage here is that you pay a slight cost at compile time, but at runtime Micronaut is largely reflection-free, fast and consumes very little memory.

== Using Micronaut with Java 9+

Micronaut is built with Java 8, however works fine with Java 9/10 and above as well. The classes that Micronaut generates sit alongside existing classes within the same package, hence do not violate anything regarding the Java module system.

There are some considerations to take into account when using Java 9/10 with Micronaut.

=== The javax.annotation package
[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, the `javax.annotation` dependency will be added to your project automatically if you are using Java 9+.
====

The `javax.annotation`, which includes `@PostConstruct`, `@PreDestroy` etc. is no longer part of the core JDK but instead a module. If you run under Java 9+ you will need to import the module or add the dependency to your classpath:

.Adding the `javax.annotation` dependency
[source,groovy]
----
implementation 'javax.annotation:javax.annotation-api:1.3.2'
----

== Incremental Annotation Processing with Gradle

Micronaut supports https://docs.gradle.org/current/userguide/java_plugin.html#sec:incremental_annotation_processing[Gradle incremental annotation processing] which helps speed up builds by compiling only classes that have changed avoiding a full recompilation.

However, the support is disabled by default since Micronaut allows the definition of custom meta-annotations (to for example define <<aop,custom AOP advice>>) that need to be configured for processing.

The following example demonstrates how to enable and configure incremental annotation processing for annotations you have defined under the `com.example` package:

.Enabling Incremental Annotation Processing
[source,groovy]
----
tasks.withType(JavaCompile) {
    options.compilerArgs = [
        '-Amicronaut.processing.incremental=true',
        '-Amicronaut.processing.annotations=com.example.*',
    ]
}
----

WARNING: If you do not enable processing for custom annotations you define these annotations will simple be ignored by Micronaut which may break your application.

== Using Project Lombok

https://projectlombok.org[Project Lombok] is a popular java library that adds a number of useful AST transformations to the Java language via annotation processors.

Since both Micronaut and Lombok use annotation processors, special care needs to be taken when configuring Lombok to ensure that the Lombok processor runs *before* Micronaut's processor.

For example in Gradle adding the following dependencies to the `dependencies` block:

.Configuring Lombok in Gradle
[source,groovy]
----
compileOnly 'org.projectlombok:lombok:1.16.20'
annotationProcessor "org.projectlombok:lombok:1.16.20"
...
// Micronaut processor define after Lombok
annotationProcessor "io.micronaut:micronaut-inject-java"
----

Or when using Maven:

.Configuring Lombok in Maven
[source,xml]
----
<annotationProcessorPaths>
  <path>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.18.0</version>
  </path>
  <path>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-inject-java</artifactId>
    <version>${micronaut.version}</version>
  </path>
</annotationProcessorPaths>
----

NOTE: In both cases (Gradle and Maven) the Micronaut processor should be configured after the Lombok processor, reversing the order of the declared dependencies will not work.


== Configuring an IDE

You can use any IDE to develop Micronaut applications, if you depend on your configured build tool (Gradle or Maven) to build the application.

However, if you wish to run tests within the IDE that is currently possible with http://jetbrains.com/idea[IntelliJ IDEA] or Eclipse 4.9 M2 or above.

See the section on <<ideSetup, IDE Setup>> in the Quick start for more information on how to configure IntelliJ or Eclipse.

== Retaining Parameter Names

By default with Java, the parameter name data for method parameters is not retained at compile time. This can be a problem for Micronaut if you do not define parameter names explicitly and depend on an external JAR that is already compiled.

Consider this interface:

.Client Interface
[source,java]
----
interface HelloOperations {
    @Get("/hello/{name}")
    String hello(String name);
}
----

At compile time the parameter name `name` is lost and becomes simply `arg0` when compiled against or read via reflection later. To avoid this problem you have two options. You can either declare the parameter name explicitly:

.Client Interface
[source,java]
----
interface HelloOperations {
    @Get("/hello/{name}")
    String hello(@QueryValue("name") String name);
}
----

Or alternatively it is recommended that you compile all byte code with `-parameters` flag to `javac`. See https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html[Obtaining Names of Method Parameters]. For example in `build.gradle`:

.build.gradle
[source,groovy]
----
compileJava.options.compilerArgs += '-parameters'
----
