For Java, Micronaut uses a Java api:annotation.processing.BeanDefinitionInjectProcessor[] annotation processor to process classes at compile time and produce api:inject.BeanDefinition[] classes.

The major advantage here is that you pay a slight cost at compile time, but at runtime Micronaut is largely reflection-free, fast and consumes very little memory.

== Using Micronaut with Java 9+

Micronaut is built with Java 8, however works fine with Java 9/10 and above as well. The classes that Micronaut generates sit alongside existing classes within the same package, hence do not violate anything regarding the Java module system.

There are some considerations to take into account when using Java 9/10 with Micronaut.

=== The javax.annotation package
[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, the `javax.annotation` dependency will be added to your project automatically if you are using Java 9+.
====

The `javax.annotation`, which includes `@PostConstruct`, `@PreDestroy` etc. is no longer part of the core JDK but instead a module. If you run under Java 9+ you will need to import the module or add the dependency to your classpath:

.Adding the `javax.annotation` dependency
dependency:javax.annotation:javax.annotation-api:1.3.2[scope="compile"]

== Using Project Lombok

https://projectlombok.org[Project Lombok] is a popular java library that adds a number of useful AST transformations to the Java language via annotation processors.

Since both Micronaut and Lombok use annotation processors, special care needs to be taken when configuring Lombok to ensure that the Lombok processor runs *before* Micronaut's processor.

For example in Gradle adding the following dependencies to the `dependencies` block:


[source,groovy]
----

----

[source.multi-language-sample,gradle-groovy,title="Configuring Lombok in build file"]
----
compileOnly 'org.projectlombok:lombok:1.16.20'
annotationProcessor "org.projectlombok:lombok:1.16.20" // or kapt for kotlin sources
// Micronaut processor must be defined *after* Lombok
annotationProcessor "io.micronaut:micronaut-inject-java" // for java sources
kapt "io.micronaut:micronaut-inject-java" // for kotlin sources
----

[source.multi-language-sample,gradle-kotlin]
----
compileOnly("org.projectlombok:lombok:1.16.20")
annotationProcessor("org.projectlombok:lombok:1.16.20") // or kapt for kotlin sources
// Micronaut processor must be defined *after* Lombok
annotationProcessor("io.micronaut:micronaut-inject-java") // for java sources
kapt("io.micronaut:micronaut-inject-java") // for kotlin sources
----

[source.multi-language-sample,maven]
----
<provided>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.20</version>
</provided>
<annotationProcessorPath>
    <groupId>org.projectlombok</groupId>
    <artifactId>lombok</artifactId>
    <version>1.16.20</version>
</annotationProcessorPath>
<!--  Micronaut processor must be defined *after* Lombok -->
<!-- For Java sources, use the following -->
<annotationProcessorPath>
    <groupId>io.micronaut</groupId>
    <artifactId>micronaut-inject-java/artifactId>
</annotationProcessorPath>
<!-- Following block only for kotlin sources -->
<execution>
    <id>kapt</id>
    <goals>
        <goal>kapt</goal>
    </goals>
    <configuration>
        <sourceDirs>
            <sourceDir>src/main/kotlin</sourceDir>
            <sourceDir>src/main/java</sourceDir>
        </sourceDirs>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.micronaut</groupId>
                <artifactId>micronaut-inject-java</artifactId>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
</execution>
----

NOTE: In both cases (Gradle and Maven) the Micronaut processor should be configured after the Lombok processor, reversing the order of the declared dependencies will not work.


== Configuring an IDE

You can use any IDE to develop Micronaut applications, if you depend on your configured build tool (Gradle or Maven) to build the application.

However, if you wish to run tests within the IDE that is currently possible with http://jetbrains.com/idea[IntelliJ IDEA] or Eclipse 4.9 M2 or above.

See the section on <<ideSetup, IDE Setup>> in the Quick start for more information on how to configure IntelliJ or Eclipse.

== Retaining Parameter Names

By default with Java, the parameter name data for method parameters is not retained at compile time. This can be a problem for Micronaut if you do not define parameter names explicitly and depend on an external JAR that is already compiled.

Consider this interface:

.Client Interface
[source,java]
----
interface HelloOperations {
    @Get("/hello/{name}")
    String hello(String name);
}
----

At compile time the parameter name `name` is lost and becomes simply `arg0` when compiled against or read via reflection later. To avoid this problem you have two options. You can either declare the parameter name explicitly:

.Client Interface
[source,java]
----
interface HelloOperations {
    @Get("/hello/{name}")
    String hello(@QueryValue("name") String name);
}
----

Or alternatively it is recommended that you compile all byte code with `-parameters` flag to `javac`. See https://docs.oracle.com/javase/tutorial/reflect/member/methodparameterreflection.html[Obtaining Names of Method Parameters]. For example in `build.gradle`:

.build.gradle
[source,groovy]
----
compileJava.options.compilerArgs += '-parameters'
----
