TIP: The <<cli, Command Line Interface>> for Micronaut includes special support for Kotlin. To create a Kotlin application use the `kotlin` lang option. For example:

[source,bash]
.Create a Micronaut Kotlin application
----
$ mn create-app hello-world -lang kotlin
----

Support for Kotlin in Micronaut is built upon the https://kotlinlang.org/docs/reference/kapt.html[Kapt] compiler plugin, which includes support for Java annotation processors. To use Kotlin in your Micronaut application, you will simply need to add the proper dependencies to configure and run kapt on your `kt` source files. Kapt will create Java "stub" classes for each of your Kotlin classes, which can then be processed by Micronaut's Java annotation processor. The stubs are not included in the final compiled application.

TIP: Learn more about kapt and its features from the https://kotlinlang.org/docs/reference/kapt.html[official documentation.]

If you are using Gradle, you can use the https://docs.gradle.org/current/userguide/application_plugin.html[Application] plugin to run your application with the kapt compilation step in your build:

[source,groovy]
.Example build.gradle
----
buildscript {
    repositories {
        mavenCentral()
    }

    dependencies {
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlinVersion"
    }
}

apply plugin: "kotlin" //<1>
apply plugin: 'kotlin-kapt'

apply plugin: "application"
mainClassName = "example.Application" //<2>

repositories {
    mavenCentral()
    mavenLocal()
}

dependencies {
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion" //<3>
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
    kapt "io.micronaut:inject-java" //<4>

    kaptTest "io.micronaut:inject-java" //<5>
}

test {
    useJUnitPlatform()
}

compileKotlin {
    kotlinOptions.jvmTarget = "1.8"
}

compileTestKotlin {
    kotlinOptions.jvmTarget = "1.8"
}
----
<1> Apply the Kotlin and Kapt plugins
<2> Set a `mainClassName` (required by the Application plugin)
<3> Add the Kotlin standard libraries
<4> Add the `inject-java` dependency under the `kapt` scope, so classes in `src/main` are processed
<5> Add the `inject-java` dependency under the `kaptTest` scope, so classes in `src/test` are processed.

With a `build.gradle` file similar to the above, you can now run your Micronaut application using the `run` task (provided by the Application plugin):

[source,bash]
$ ./gradlew run

You can now use Kotlin in your Micronaut project:

[source, kotlin]
.src/main/kotlin/example/HelloController.kt
----
package example

import io.micronaut.http.annotation.Controller
import io.micronaut.http.annotation.Get

@Controller("/")
class HelloController {

    @Get("/hello/{name}")
    fun hello(name: String): String {
        return "Hello $name"
    }
}
----

NOTE: The IntelliJ IDEA compiler does not support kapt! Classes must be compiled with the Gradle or Maven plugins.
