TIP: The <<cli, Command Line Interface>> for Micronaut includes special support for Kotlin. To create a Kotlin application use the `kotlin` lang option. For example:

[source,bash]
.Create a Micronaut Kotlin application
----
$ mn create-app hello-world --lang kotlin
----

Support for Kotlin in Micronaut is built upon the https://kotlinlang.org/docs/reference/kapt.html[Kapt] compiler plugin, which includes support for Java annotation processors. To use Kotlin in your Micronaut application, you will simply need to add the proper dependencies to configure and run kapt on your `kt` source files. Kapt will create Java "stub" classes for each of your Kotlin classes, which can then be processed by Micronaut's Java annotation processor. The stubs are not included in the final compiled application.

TIP: Learn more about kapt and its features from the https://kotlinlang.org/docs/reference/kapt.html[official documentation.]

The Micronaut annotation processors are declared in the `kapt` scope when using Gradle. For example:

[source.multi-language-sample,gradle-groovy,title="Required Dependencies"]
----
    compile "org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion" //<1>
    compile "org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion"
    kapt "io.micronaut:micronaut-inject-java" //<2>

    kaptTest "io.micronaut:micronaut-inject-java" //<3>
----

[source.multi-language-sample,gradle-kotlin]
----
    compile("org.jetbrains.kotlin:kotlin-stdlib-jdk8:$kotlinVersion") //<1>
    compile("org.jetbrains.kotlin:kotlin-reflect:$kotlinVersion")
    kapt("io.micronaut:micronaut-inject-java") //<2>

    kaptTest("io.micronaut:micronaut-inject-java") //<3>
----

[source.multi-language-sample,maven]
----
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-stdlib-jdk8</artifactId> <!--- <1> --->
    <version>${kotlin.version}</version>
</dependency>
<dependency>
    <groupId>org.jetbrains.kotlin</groupId>
    <artifactId>kotlin-reflect</artifactId>
    <version>${kotlin.version}</version>
</dependency>
<execution>
    <id>kapt</id>
    <goals>
        <goal>kapt</goal> <!--- <2> --->
    </goals>
    <configuration>
        <sourceDirs>
            <sourceDir>src/main/kotlin</sourceDir>
            <sourceDir>src/main/java</sourceDir>
        </sourceDirs>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.micronaut</groupId>
                <artifactId>micronaut-inject-java</artifactId>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
</execution>
<execution>
    <id>kapt</id>
    <goals>
        <goal>kapt-test</goal> <!--- <3> --->
    </goals>
    <configuration>
        <sourceDirs>
            <sourceDir>src/test/kotlin</sourceDir>
            <sourceDir>src/test/java</sourceDir>
        </sourceDirs>
        <annotationProcessorPaths>
            <annotationProcessorPath>
                <groupId>io.micronaut</groupId>
                <artifactId>micronaut-inject-java</artifactId>
            </annotationProcessorPath>
        </annotationProcessorPaths>
    </configuration>
</execution>
----


<1> Add the Kotlin standard libraries
<2> Add the `micronaut-inject-java` dependency under the `kapt` scope, so classes in `src/main` are processed
<3> Add the `micronaut-inject-java` dependency under the `kaptTest` scope, so classes in `src/test` are processed.

With a `build.gradle` file similar to the above, you can now run your Micronaut application using the `run` task (provided by the Application plugin):

[source,bash]
$ ./gradlew run

An example controller written in Kotlin can be seen below:

[source, kotlin]
.src/main/kotlin/example/HelloController.kt
----
package example

import io.micronaut.http.annotation.*

@Controller("/")
class HelloController {

    @Get("/hello/{name}")
    fun hello(name: String): String {
        return "Hello $name"
    }
}
----

