There are cases where you want to introduce a new bean based on the presence of an annotation on a method. An example of this is the ann:runtime.event.annotation.EventListener[] annotation which produces an implementation of api:context.event.ApplicationEventListener[] for each annotated method that invokes the annotated method.

For example the following snippet runs the logic contained within the method when the api:context.ApplicationContext[] starts up:

[source,java]
----
import io.micronaut.context.event.StartupEvent;
import io.micronaut.runtime.event.annotation.EventListener;
...

@EventListener
void onStartup(StartupEvent event) {
    // startup logic here
}
----

The presence of the ann:runtime.event.annotation.EventListener[] annotation causes the Micronaut framework to create a new class that implements api:context.event.ApplicationEventListener[] and invokes the `onStartup` method defined in the bean above.

The actual implementation of the ann:runtime.event.annotation.EventListener[] is trivial; it simply uses the ann:aop.Adapter[] annotation to specify which SAM (single abstract method) type it adapts:

[source,java]
----
include::context/src/main/java/io/micronaut/runtime/event/annotation/EventListener.java[tags=imports, indent=0]

include::context/src/main/java/io/micronaut/runtime/event/annotation/EventListener.java[tags=clazz, indent=0]
----

<1> The ann:aop.Adapter[] annotation indicates which SAM type to adapt, in this case api:context.event.ApplicationEventListener[].

NOTE: The Micronaut framework also automatically aligns the generic types for the SAM interface if they are specified.

Using this mechanism you can define custom annotations that use the ann:aop.Adapter[] annotation and a SAM interface to automatically implement beans for you at compile time.
