The most common type of advice you may want to apply is "Around" advice, which essentially allows you to decorate a methods behaviour.

== Writing Around Advice

The first step to defining Around advice is to implement a link:{api}/io/micronaut/aop/MethodInterceptor.html[MethodInterceptor]. For example the following interceptor disallows parameters with `null` values:

.MethodInterceptor Example
[source,java]
----
include::{testsjava}/aop/around/NotNullInterceptor.java[tags=imports, indent=0]

include::{testsjava}/aop/around/NotNullInterceptor.java[tags=interceptor, indent=0]
----

<1> An interceptor implements the link:{api}/io/micronaut/aop/MethodInterceptor.html[MethodInterceptor] interface
<2> The passed link:{api}/io/micronaut/aop/MethodInvocationContext.html[MethodInvocationContext] is used to find the first parameter that is `null`
<3> If a `null` parameter is found an exception is thrown
<4> Otherwise link:{api}/io/micronaut/aop/InvocationContext.html#proceed--[proceed()] is called to proceed with the method invocation.

NOTE: Micronaut AOP interceptors use no reflection which improves performance and reducing stack trace sizes, thus improving debugging.

To put the new `MethodInterceptor` to work the next step is to define an annotation that will trigger the `MethodInterceptor`:


.Around Advice Annotation Example
[source,java]
----
include::{testsjava}/aop/around/NotNull.java[tags=imports, indent=0]

include::{testsjava}/aop/around/NotNull.java[tags=annotation, indent=0]
----

<1> The retention policy of the annotation should be `RUNTIME`
<2> Generally you want to be able to apply advice at the class or method level so the target types are `TYPE` and `METHOD`
<3> The link:{api}/io/micronaut/aop/Around.html[Around] annotation is added to tell Micronaut that the annotation is Around advice
<4> The link:{api}/io/micronaut/context/annotation/Type.html[@Type] annotation is used to configure which type implements the advice (in this case the previously defined `NotNullInterceptor`)

With the interceptor and annotation implemented you can then simply apply the annotation to the target classes:

.Around Advice Usage Example
[source,java]
----
include::{testsjava}/aop/around/NotNullExample.java[tags=example, indent=0]
----

Whenever the type `NotNullExample` is injected into any class, a compile time generated proxy will instead be injected that decorates the appropriate method calls with the `@NotNull` advice defined earlier. You can verify that the advice works by writing a test. The following test uses a JUnit `ExpectedException` rule to verify the appropriate exception is thrown when an argument is `null`:

.Around Advice Test
[source,java]
----
include::{testsjava}/aop/around/AroundTest.java[tags=test, indent=0]
----

NOTE: Since Micronaut injection is done at compile time, generally the advice should be packaged in a dependent JAR file that is on the classpath when the above test is compiled and should not be in the same codebase since you don't want the test to be compiled before the advice itself is compiled.

== Customizing Proxy Generation

The default behaviour of the link:{api}/io/micronaut/aop/Around.html[Around] annotation is to generate a proxy at compile time that is a subclass of the class being proxied. In other words, in the previous example a compile time subclass of the `NotNullExample` class will be produced where methods that are proxied are decorated with interceptor handling and the original behaviour is invoked via a call to `super`.

This behaviour is more efficient as only one instance of the bean is required, however depending on the use case you are trying to implement you may wish to alter this behaviour and the `@Around` annotation supports various attributes that allow you to alter this behaviour including:

* `proxyTarget` (defaults to `false`) - If set to `true` instead of a subclass that calls `super`, the proxy will delegate to the original bean instance
* `hotswap` (defaults to `false`) - Same as `proxyTarget=true`, but in addition the proxy will implement link:{api}/io/micronaut/aop/HotSwappableInterceptedProxy.html[HotSwappableInterceptedProxy] which wraps each method call in a `ReentrantReadWriteLock` and allows swapping the target instance at runtime.
* `lazy` (defaults to `false`) - By default Micronaut will eagerly intialize the proxy target when the proxy is created. If set to `true` the proxy target will instead be resolved lazily for each method call.

== AOP Advice on @Factory Beans

The semantics of AOP advice when applied to <<factories,Bean Factories>> differs to regular beans, with the following rules applying:

1. AOP advice applied at the class level of a ann:context.annotation.Factory[] bean will apply the advice to the factory itself and not to any beans defined with the ann:context.annotation.Bean[] annotation.
2. AOP advice applied on a method annotated with a bean scope will apply the AOP advice to the bean that the factory produces.

Consider the following two examples:

.AOP Advice at the type level of a `@Factory`
[source,java]
----
@Cacheable("my-cache")
@Factory
class MyFactory {

    @Prototype
    MyBean myBean() {
        return new MyBean();
    }
}
----

The above example will cache creation of `MyBean` bean, according to the semantics defined by the ann:cache.annotation.Cacheable[] cache configuration.

Now consider this example:

.AOP Advice at the method level of a `@Factory`
[source,java]
----
@Factory
class MyFactory {

    @Prototype
    @Cacheable("my-cache")
    MyBean myBean() {
        return new MyBean();
    }
}
----

The above example will cache all of the public methods of the `MyBean` bean, but not the bean creation.

The rationale for this behaviour is that you may at times wish to apply advice to a factory and at other times apply advice to the bean produced by the factory.

Note that there is currently no way to apply advice at the method level to a ann:context.annotation.Factory[] bean and all advice for factories must be applied at the type level. You can control which methods have advice applied by defining methods as non-public (non-public methods do not have advice applied).
