The most common type of advice you may want to apply is "Around" advice, which lets you decorate a method's behaviour.

== Writing Around Advice


The first step is to define an annotation that will trigger a api:aop.MethodInterceptor[]:

snippet::io.micronaut.docs.aop.around.NotNull[tags="imports,annotation", indent=0, title="Around Advice Annotation Example"]

<1> The retention policy of the annotation should be `RUNTIME`
<2> Generally you want to be able to apply advice at the class or method level so the target types are `TYPE` and `METHOD`
<3> The ann:aop.Around[] annotation is added to tell the Micronaut framework that the annotation is Around advice

The next step to defining Around advice is to implement a api:aop.MethodInterceptor[]. For example the following interceptor disallows parameters with `null` values:

snippet::io.micronaut.docs.aop.around.NotNullInterceptor[tags="imports,interceptor", indent=0, title="MethodInterceptor Example"]

<1> The ann:aop.InterceptorBean[] annotation is used to indicate what annotation the interceptor is associated with. Note that ann:aop.InterceptorBean[] is meta-annotated with a default scope of `@Singleton` therefore if you want a new interceptor created and associated with each intercepted bean you should annotate the interceptor with ann:context.annotation.Prototype[].
<2> An interceptor implements the api:aop.MethodInterceptor[] interface.
<3> The passed link:{api}/io/micronaut/aop/MethodInvocationContext.html[MethodInvocationContext] is used to find the first parameter that is `null`
<4> If a `null` parameter is found an exception is thrown
<5> Otherwise link:{api}/io/micronaut/aop/InvocationContext.html#proceed--[proceed()] is called to proceed with the method invocation.

NOTE: Micronaut AOP interceptors use no reflection which improves performance and reducing stack trace sizes, thus improving debugging.

Apply the annotation to target classes to put the new `MethodInterceptor` to work:

snippet::io.micronaut.docs.aop.around.NotNullExample[tags="example", indent=0, title="Around Advice Usage Example"]

Whenever the type `NotNullExample` is injected into a class, a compile-time-generated proxy is injected that decorates method calls with the `@NotNull` advice defined earlier. You can verify that the advice works by writing a test. The following test verifies that the expected exception is thrown when the argument is `null`:

snippet::io.micronaut.docs.aop.around.AroundSpec[tags="test", indent=0, title="Around Advice Test"]

NOTE: Since Micronaut injection happens at compile time, generally the advice should be packaged in a dependent JAR file that is on the classpath when the above test is compiled. It should not be in the same codebase since you don't want the test to be compiled before the advice itself is compiled.

== Customizing Proxy Generation

The default behaviour of the link:{api}/io/micronaut/aop/Around.html[Around] annotation is to generate a proxy at compile time that is a subclass of the proxied class. In other words, in the previous example a compile-time subclass of the `NotNullExample` class will be produced where proxied methods are decorated with interceptor handling, and the original behaviour is invoked via a call to `super`.

This behaviour is more efficient as only one instance of the bean is required, however depending on the use case you may wish to alter this behaviour. The `@Around` annotation supports various attributes that allow you to alter this behaviour, including:

* `proxyTarget` (defaults to `false`) - If set to `true`, instead of a subclass that calls `super`, the proxy delegates to the original bean instance
* `hotswap` (defaults to `false`) - Same as `proxyTarget=true`, but in addition the proxy implements link:{api}/io/micronaut/aop/HotSwappableInterceptedProxy.html[HotSwappableInterceptedProxy] which wraps each method call in a `ReentrantReadWriteLock` and allows swapping the target instance at runtime.
* `lazy` (defaults to `false`) - By default the Micronaut framework eagerly initializes the proxy target when the proxy is created. If set to `true` the proxy target is instead resolved lazily for each method call.

== AOP Advice on @Factory Beans

The semantics of AOP advice when applied to <<factories,Bean Factories>> differs from regular beans, with the following rules applying:

. AOP advice applied at the class level of a ann:context.annotation.Factory[] bean applies the advice to the factory itself and not to any beans defined with the ann:context.annotation.Bean[] annotation.
. AOP advice applied on a method annotated with a bean scope applies the AOP advice to the bean that the factory produces.

Consider the following two examples:

snippet::io.micronaut.docs.aop.advice.type.MyFactory[tags="class", indent=0, title="AOP Advice at the type level of a `@Factory`"]

The above example logs the time it takes to create the `MyBean` bean.

Now consider this example:

snippet::io.micronaut.docs.aop.advice.method.MyFactory[tags="class", indent=0, title="AOP Advice at the method level of a `@Factory`"]

The above example logs the time it takes to execute the public methods of the `MyBean` bean, but not the bean creation.

The rationale for this behaviour is that you may at times wish to apply advice to a factory and at other times apply advice to the bean produced by the factory.

Note that there is currently no way to apply advice at the method level to a ann:context.annotation.Factory[] bean, and all advice for factories must be applied at the type level. You can control which methods have advice applied by defining methods as non-public which do not have advice applied.
