Similar to Spring and Grails, Micronaut provides a set of caching annotations within the link:{api}/io/micronaut/cache/package-summary.html[io.micronaut.cache] package.

The link:{api}/io/micronaut/cache/CacheManager.html[CacheManager] interface allows different cache implementations to be plugged in as necessary.

The link:{api}/io/micronaut/cache/SyncCache.html[SyncCache] interface provides a synchronous API for caching, whilst the link:{api}/io/micronaut/cache/AsyncCache.html[AsyncCache] API allows non-blocking operation.

== Cache Annotations

The following cache annotations are supported:

- link:{api}/io/micronaut/cache/annotation/Cacheable.html[@Cacheable] - Indicates a method is cacheable within the given cache name
- link:{api}/io/micronaut/cache/annotation/CachePut.html[@CachePut] - Indicates that the return value of a method invocation should be cached. Unlike `@Cacheable` the original operation is never skipped.
- link:{api}/io/micronaut/cache/annotation/CacheInvalidate.html[@CacheInvalidate] - Indicates the invocation of a method should cause the invalidation of one or many caches.


By using one of the annotations the api:cache.interceptor.CacheInterceptor[] is activated which in the case of `@Cacheable` will cache the return result of the method.

If the return type of the method is a non-blocking type (either link:{jdkapi}/java/util/concurrent/CompletableFuture.html[CompletableFuture] or an instance of rs:Publisher[] the emitted result will be cached.

In addition if the underlying Cache implementation supports non-blocking cache operations then cache values will be read from the cache without blocking, resulting in the ability to implement completely non-blocking cache operations.


== Configuring Caches

By default https://github.com/ben-manes/caffeine[Caffeine] is used for cache definitions which can be configured via application configuration. For example with `application.yml`:

.Cache Configuration Example
[source,yaml]
----
micronaut:
    caches:
        my-cache:
            maximum-size: 20
----

The above example will configure a cache called "my-cache" with a maximum size of 20.

[NOTE]
.Naming Caches
====
Names of caches under `micronaut.caches` should be defined in kebab case (lowercase and hyphen seperated), if camel case is used the names are normalized to kebab case. So for example specifing `myCache` will become `my-cache`. The kebab case form should be used when referencing caches in the ann:cache.annotation.Cacheable[] annotation.
====

To configure a weigher to be used with the `maximumWeight` configuration, create a bean that implements `io.micronaut.caffeine.cache.Weigher`. To associate a given weigher with only a specific cache, annotate the bean with `@Named(<cache name>)`. Weighers without a named qualifier will apply to all caches that don't have a named weigher. If no beans are found, a default implementation will be used.


include::{includedir}configurationProperties/io.micronaut.cache.DefaultCacheConfiguration.adoc[]

== Dynamic Cache Creation

For use cases where caches cannot be configured ahead of time, a api:cache.DynamicCacheManager[] bean can be registered. When a cache is attempted to be retrieved that was not predefined, the dynamic cache manager will be invoked to return a cache.

By default, if there is no other dynamic cache manager defined in the application, Micronaut registers an instance of api:cache.DefaultDynamicCacheManager[] that will create Caffeine caches with default values.

== Cache Value Conversion

By default, Micronaut will convert values returned from a cache to the requested type. This can have undesirable consequences in certain circumstances. To disable this behavior, set the `convert` configuration to false for the given cache.

.No Conversion Example
[source,yaml]
----
micronaut:
    caches:
        my-cache:
            convert: false

# Or if you are using the JCache manager
micronaut.jcache.convert: false
----

== Other Cache Implementations

Check the https://micronaut-projects.github.io/micronaut-cache/latest/guide/index.html[Micronaut Cache] project for more
information.
