Similar to Spring and Grails, Micronaut provides a set of caching annotations within the link:{api}/io/micronaut/cache/package-summary.html[io.micronaut.cache] package.

The link:{api}/io/micronaut/cache/CacheManager.html[CacheManager] interface allows different cache implementations to be plugged in as necessary.

The link:{api}/io/micronaut/cache/SyncCache.html[SyncCache] interface provides a synchronous API for caching, whilst the link:{api}/io/micronaut/cache/AsyncCache.html[AsyncCache] API allows non-blocking operation.

== Cache Annotations

The following cache annotations are supported:

- link:{api}/io/micronaut/cache/annotation/Cacheable.html[@Cacheable] - Indicates a method is cacheable within the given cache name
- link:{api}/io/micronaut/cache/annotation/CachePut.html[@CachePut] - Indicates that the return value of a method invocation should be cached. Unlike `@Cacheable` the original operation is never skipped.
- link:{api}/io/micronaut/cache/annotation/CacheInvalidate.html[@CacheInvalidate] - Indicates the invocation of a method should cause the invalidation of one or many caches.


By using one of the annotations the link:{api}/io/micronaut/cache/interceptor/CacheInterceptor.html[CacheInterceptor] is activated which in the case of `@Cacheable` will cache the return result of the method.

If the return type of the method is a non-blocking type (either link:{jdkapi}/java/util/concurrent/CompletableFuture.html[CompletableFuture] or an instance of link:{rsapi}/org/reactivestreams/Publisher.html[org.reactivestreams.Publisher]) the emitted result will be cached.

In addition if the underlying Cache implementation supports non-blocking cache operations then cache values will be read from the cache without blocking, resulting in the ability to implement completely non-blocking cache operations.


== Configuring Caches

By default https://github.com/ben-manes/caffeine[Caffeine] is used for cache definitions which can be configured via application configuration. For example with `application.yml`:

.Cache Configuration Example
[source,yaml]
----
micronaut:
    caches:
        myCache:
            maximumSize: 20
----

The above example will configure a cache called "myCache" with a maximum size of 20.

To configure a weigher to be used with the `maximumWeight` configuration, create a bean that implements `io.micronaut.caffeine.cache.Weigher`. To associate a given weigher with only a specific cache, annotate the bean with `@Named(<cache name>)`. Weighers without a named qualifier will apply to all caches that don't have a named weigher. If no beans are found, a default implementation will be used.

== Caching with Redis

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `redis-lettuce` feature to configure Redis/Lettuce in your project:
----
$ mn create-app my-app --features redis-lettuce
----
====

If you wish to use Redis to cache results then you need to have the Lettuce configuration dependency on your classpath. Lettuce is a non-blocking, reactive Redis client implementation and Micronaut provides an implementation that allows cached results to be read reactively.

To enable Lettuce, add the `redis-lettuce` dependency to your application:

.Lettuce Configuration build.gradle
[source,groovy]
----
dependencies {
    ...
    compile "io.micronaut.configuration:redis-lettuce"
    ...
}
----

Then within your application configuration configure the Redis URL and Redis caches:

.Cache Configuration Example
[source,yaml]
----
micronaut:
    redis:
        uri: redis://localhost
        caches:
            myCache:
                expireAfterWrite: "1h" # expire one hour after write
----
