Like Spring and Grails, the Micronaut framework features a api:scheduling.annotation.Scheduled[] annotation for scheduling background tasks.

== Using the @Scheduled Annotation

The api:scheduling.annotation.Scheduled[] annotation can be added to any method of a bean, and you should set one of the `fixedRate`, `fixedDelay`, or `cron` members. Scheduling requires the Micronaut Context dependency:

dependency::micronaut-context[]

`micronaut-context` is a transitive dependency of `micronaut-http`. If you use a Micronaut HTTP runtime, your project already includes the `Micronaut-context` dependency. 

NOTE: Remember that the scope of a bean impacts behaviour. A `@Singleton` bean shares state (the fields of the instance) each time the scheduled method is executed, while for a `@Prototype` bean a new instance is created for each execution.

=== Scheduling at a Fixed Rate

To schedule a task at a fixed rate, use the `fixedRate` member. For example:

snippet::io.micronaut.docs.aop.scheduled.ScheduledExample[tags="fixedRate", indent=0, title="Fixed Rate Example"]

The task above executes every five minutes.

=== Scheduling with a Fixed Delay

To schedule a task, so it runs five minutes after the termination of the previous task use the `fixedDelay` member. For example:

.Fixed Delay Example
snippet::io.micronaut.docs.aop.scheduled.ScheduledExample[tags="fixedDelay", indent=0, title="Fixed Delay Example"]

=== Scheduling a Cron Task

To schedule a https://en.wikipedia.org/wiki/Cron[Cron] task use the `cron` member:

snippet::io.micronaut.docs.aop.scheduled.ScheduledExample[tags="cron", indent=0, title="Cron Example"]

The above example runs the task every Monday morning at 10:15AM in the time zone of the server.

=== Scheduling with only an Initial Delay

To schedule a task, so it runs once after the server starts, use the `initialDelay` member:

snippet::io.micronaut.docs.aop.scheduled.ScheduledExample[tags="initialDelay", indent=0, title="Initial Delay Example"]

The above example only runs once, one minute after the server starts.

== Programmatically Scheduling Tasks

To programmatically schedule tasks, use the api:scheduling.TaskScheduler[] bean which can be injected as follows:

snippet::io.micronaut.docs.aop.scheduled.TaskSchedulerInjectExample[tags="inject", indent=0]

== Configuring Scheduled Tasks with Annotation Metadata

To make your application's tasks configurable, you can use annotation metadata and property placeholder configuration. For example:

snippet::io.micronaut.docs.aop.scheduled.ScheduledExample[tags="configured", indent=0, title="Allow tasks to be configured"]

The above example allows the task execution frequency to be configured with the property `my.task.rate`, and the initial delay to be configured with the property `my.task.delay`.

== Configuring the Scheduled Task Thread Pool

Tasks executed by `@Scheduled` are run by default on a link:{jdkapi}/java.base/java/util/concurrent/ScheduledExecutorService.html[ScheduledExecutorService] configured to have twice the number of threads as available processors.

You can configure this thread pool in your configuration file (e.g `application.yml`):

//TODO: Move YAML snippet to ExecutorServiceConfigSpec
[configuration,title="Configuring Scheduled Task Thread Pool"]
----
micronaut:
  executors:
    scheduled:
      type: scheduled
      core-pool-size: 30
----

include::{includedir}configurationProperties/io.micronaut.scheduling.executor.UserExecutorConfiguration.adoc[]

== Handling Exceptions

By default, the Micronaut framework includes a api:io.micronaut.scheduling.DefaultTaskExceptionHandler[] bean that implements the api:io.micronaut.scheduling.TaskExceptionHandler[] interface and simply logs the exception if an error occurs invoking a scheduled task.

If you have custom requirements you can replace this bean with your own implementation (for example to send an email or shutdown the context to fail fast). To do so, write your own api:io.micronaut.scheduling.TaskExceptionHandler[] and annotate it with `@Replaces(DefaultTaskExceptionHandler.class)`.
