/*
 * Copyright 2017-2025 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.inject.writer;

import io.micronaut.core.annotation.Internal;
import org.jspecify.annotations.Nullable;
import io.micronaut.inject.ast.ClassElement;
import io.micronaut.inject.visitor.VisitorContext;
import io.micronaut.sourcegen.bytecode.ByteCodeWriter;
import io.micronaut.sourcegen.model.ObjectDef;
import io.micronaut.core.reflect.ClassUtils;
import org.objectweb.asm.ClassWriter;

/**
 * The byte code writer utils.
 */
@Internal
public final class ByteCodeWriterUtils {

    private ByteCodeWriterUtils() {
    }

    /**
     * Generate the bytecode.
     *
     * @param objectDef      The object definition
     * @param visitorContext The context
     * @return The generated bytecode
     */
    public static byte[] writeByteCode(ObjectDef objectDef, @Nullable VisitorContext visitorContext) {
        ClassWriter classWriter;
        if (visitorContext != null) {
            classWriter = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES) {

                @Override
                protected String getCommonSuperClass(String type1, String type2) {
                    // Input validation to prevent unsafe class name injection
                    if (!isValidClassName(type1) || !isValidClassName(type2)) {
                        return getCommonSuperClassUsingVisitorContext(type1, type2);
                    }
                    
                    ClassLoader classLoader = getClassLoader();
                    
                    // Use ClassUtils.forName for safer class loading
                    String normalizedType1 = type1.replace('/', '.');
                    String normalizedType2 = type2.replace('/', '.');
                    
                    Class<?> class1 = ClassUtils.forName(normalizedType1, classLoader).orElse(null);
                    if (class1 == null) {
                        return getCommonSuperClassUsingVisitorContext(type1, type2);
                    }
                    
                    Class<?> class2 = ClassUtils.forName(normalizedType2, classLoader).orElse(null);
                    if (class2 == null) {
                        return getCommonSuperClassUsingVisitorContext(type1, type2);
                    }
                    if (class1.isAssignableFrom(class2)) {
                        return type1;
                    }
                    if (class2.isAssignableFrom(class1)) {
                        return type2;
                    }
                    if (class1.isInterface() || class2.isInterface()) {
                        return "java/lang/Object";
                    } else {
                        do {
                            class1 = class1.getSuperclass();
                        } while (!class1.isAssignableFrom(class2));
                        return class1.getName().replace('.', '/');
                    }
                }

                private String getCommonSuperClassUsingVisitorContext(String type1, String type2) {
                    ClassElement class1 = getClassElement(type1);
                    ClassElement class2 = getClassElement(type2);
                    if (class2.isAssignable(class1)) {
                        return type1;
                    }
                    if (class1.isAssignable(class2)) {
                        return type2;
                    }
                    if (class1.isInterface() || class2.isInterface()) {
                        return "java/lang/Object";
                    } else {
                        do {
                            class1 = class1.getSuperType().orElse(null);
                        } while (class1 != null && class1.isAssignable(class2));
                        if (class1 == null) {
                            return "java/lang/Object";
                        }
                        return class1.getName().replace('.', '/');
                    }
                }

                private ClassElement getClassElement(String type) {
                    return visitorContext.getClassElement(type.replace('/', '.'))
                        .orElseThrow(() -> new TypeNotPresentException("Type " + type + " not found", null));
                }
                
                /**
                 * Validates that the given string represents a valid Java class name.
                 * This helps prevent class name injection attacks.
                 * 
                 * @param className the class name to validate
                 * @return true if the class name is valid, false otherwise
                 */
                private boolean isValidClassName(String className) {
                    if (className == null || className.isEmpty()) {
                        return false;
                    }
                    
                    // Normalize the class name (convert ASM format to Java format)
                    String normalizedName = className.replace('/', '.');
                    
                    // Basic validation: should not contain dangerous characters
                    if (normalizedName.contains(";") || normalizedName.contains("[") || 
                        normalizedName.contains("<") || normalizedName.contains(">")) {
                        return false;
                    }
                    
                    // Should not be empty after normalization
                    if (normalizedName.trim().isEmpty()) {
                        return false;
                    }
                    
                    // Should not start or end with dots
                    if (normalizedName.startsWith(".") || normalizedName.endsWith(".")) {
                        return false;
                    }
                    
                    // Should not contain consecutive dots
                    if (normalizedName.contains("..")) {
                        return false;
                    }
                    
                    return true;
                }
            };
        } else {
            classWriter = new ClassWriter(ClassWriter.COMPUTE_MAXS | ClassWriter.COMPUTE_FRAMES);
        }
        new ByteCodeWriter().writeObject(classWriter, objectDef, null);
        return classWriter.toByteArray();
    }

}
