/*
 * Copyright 2017-2020 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.http.problem;

import io.micronaut.core.annotation.Introspected;
import io.micronaut.core.annotation.Nullable;

/**
 * @see <a href="https://tools.ietf.org/html/rfc7807">Problem Details for HTTP APIs</a>
 *
 * @author Sergio del Amo
 * @since 2.4.0
 */
@Introspected
public class Problem {


    /**
     * A URI reference that identifies the problem type.
     * This specification encourages that, when dereferenced, it provide human-readable documentation for the problem type.
     * When this member is not present, its value is assumed to be "about:blank".
     */
    @Nullable
    private String type;

    /**
     *  A short, human-readable summary of the problem type.
     *  It SHOULD NOT change from occurrence to occurrence of the problem, except for purposes of localization (e.g., using proactive content negotiation;
     */
    @Nullable
    private String title;

    /**
     * The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    @Nullable
    private Integer status;

    /**
     * A human-readable explanation specific to this occurrence of the problem.
     */
    @Nullable
    private String detail;

    /**
     * A URI reference that identifies the specific occurrence of the problem.
     * It may or may not yield further information if dereferenced.
     */
    @Nullable
    private String instance;

    /**
     *
     * @return A URI reference that identifies the problem type.
     */
    @Nullable
    public String getType() {
        return type;
    }

    /**
     *
     * @param type A URI reference that identifies the problem type.
     */
    public void setType(@Nullable String type) {
        this.type = type;
    }

    /**
     *
     * @return A short, human-readable summary of the problem type.
     */
    @Nullable
    public String getTitle() {
        return title;
    }

    /**
     *
     * @param title A short, human-readable summary of the problem type.
     */
    public void setTitle(@Nullable String title) {
        this.title = title;
    }

    /**
     *
     * @return The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    @Nullable
    public Integer getStatus() {
        return status;
    }

    /**
     *
     * @param status The HTTP status code generated by the origin server for this occurrence of the problem.
     */
    public void setStatus(@Nullable Integer status) {
        this.status = status;
    }

    /**
     *
     * @return A human-readable explanation specific to this occurrence of the problem.
     */
    @Nullable
    public String getDetail() {
        return detail;
    }

    /**
     *
     * @param detail A human-readable explanation specific to this occurrence of the problem.
     */
    public void setDetail(@Nullable String detail) {
        this.detail = detail;
    }

    /**
     *
     * @return A URI reference that identifies the specific occurrence of the problem.
     */
    @Nullable
    public String getInstance() {
        return instance;
    }

    /**
     *
     * @param instance A URI reference that identifies the specific occurrence of the problem.
     */
    public void setInstance(@Nullable String instance) {
        this.instance = instance;
    }

    public String toString() {
        return "Problem{" +
                "type='" + type + '\'' +
                ", title='" + title + '\'' +
                ", status=" + status +
                ", detail='" + detail + '\'' +
                ", instance='" + instance + '\'' +
                '}';
    }
}
