Out-of-the-box, Micronaut supports https://tools.ietf.org/html/rfc7617[RFC7617] defines the "Basic" Hypertext Transfer Protocol (HTTP) authentication scheme, which transmits credentials as user-id/password pairs, encoded using Base64.

Basic Auth is enabled by default. Once you enable Micronaut security:

[source, yaml]
----
include::{testssecurity}/security/token/basicauth/BasicAuthSpec.groovy[tag=yamlconfig,indent=0]
----

You can access a resource:

[source, bash]
.cURL command using Basic Auth
----
curl "http://localhost:8080/health" \
     -u 'user:password'
----

After credentials are read from the HTTP Header, they are feed into an link:{api}/io/micronaut/security/authentication/Authenticator.html[Authenticator]
which attempts to validate them.

See sections below to learn how to customize authentication behaviour.

The next configuration properties are available:

|===

| Configuration Property | Default Value | Description

| `micronaut.security.token.basicAuth.enabled` | `true` | link:{api}/io/micronaut/security/token/BasicAuthTokenReader.html[BasicAuthTokenReader] is disabled by default

| `micronaut.security.token.basicAuth.headerName` | `Authorization` | Header name

| `micronaut.security.token.basicAuth.prefix` | `Basic` | e.g. `Basic dXNlcjp1c2Vy`

|===


TIP: Read the http://guides.micronaut.io/micronaut-security-basicauth/guide/index.html[Basic Authentication Micronaut Guide] to learn more.