This section will outline some common requirements that will require custom code to implement and describe what to do in those cases.

### Authentication Data

The authentication object returned from a successful authentication request is by default an instance of UserDetails, which only contains the username and any roles associated with the user. To store additional data in the authentication, extend api:security.authentication.UserDetails[] with your own implementation that has fields for the additional data you wish to store.

To use this new implementation, you must override the api:security.ldap.DefaultContextAuthenticationMapper[] and provide your own implementation.

[source,java]
.MyContextAuthenticationMapper.java
----
@Singleton
@Replaces(DefaultContextAuthenticationMapper.class) // <1>
public class MyContextAuthenticationMapper implements ContextAuthenticationMapper {

    @Override
    public AuthenticationResponse map(ConvertibleValues<Object> attributes, String username, Set<String> groups) {
        // return an extended UserDetails or an AuthenticationFailed object
    }
}
----

<1> The usage of @Replaces will allow your bean to replace the default implementation in the context

### Groups

By default the groups found in LDAP, if enabled, will be returned as is without any processing. No additional groups from any other sources will be added to the list. It is a common requirement to retrieve additional groups from other sources, or to normalize the names of the groups in a specific format.

To extend this behavior, it is necessary to create your own implementation of api:security.ldap.group.LdapGroupProcessor[]. Likely it will be desired to extend the default implementation because it has the logic for querying the groups from LDAP and executes the other methods to process the groups and query for additional groups.

[source,java]
.MyLdapGroupProcessor.java
----
@Singleton
@Replaces(DefaultLdapGroupProcessor.class) // <1>
public class MyLdapGroupProcessor extends DefaultLdapGroupProcessor {

    Set<String> getAdditionalGroups(LdapSearchResult result) { // <2>
        //Use the result to query another source for additional groups (database, etc)
    }

    Optional<String> processGroup(String group) { // <3>
        //convert "Admin" to "ROLE_ADMIN" for example
        //return an empty optional to exclude the group
    }
}
----

<1> The usage of @Replaces will allow your bean to replace the default implementation in the context
<2> The link:{api}/io/micronaut/security/ldap/group/LdapGroupProcessor.html#getAdditionalGroups-io.micronaut.security.ldap.context.LdapSearchResult-[getAdditionalGroups] method allows you to add groups from other sources
<3> The link:{api}/io/micronaut/security/ldap/group/LdapGroupProcessor.html#processGroup-java.lang.String-[processGroup] method allows you to transform the name of the group, or exclude it

### Search Logic

To customize how LDAP searches are done, replace the default implementation with your own. See api:security.ldap.context.LdapSearchService[].

[source,java]
.MyLdapSearchService.java
----
@Singleton
@Replaces(DefaultLdapSearchService.class)
public class MyLdapSearchService implements LdapSearchService {

}
----

### Context Building

To customize how the LDAP context is built, replace the default implementation with your own. See api:security.ldap.context.ContextBuilder[].

[source,java]
.MyContextBuilder.java
----
@Singleton
@Replaces(DefaultContextBuilder.class)
public class MyContextBuilder implements ContextBuilder {

}
----
