https://www.consul.io[Consul] is a popular Service Discovery and Distributed Configuration server provided by HashiCorp. Micronaut features a native non-blocking api:discovery.consul.client.v1.ConsulClient[] that is built using Micronaut's support for <<clientAnnotation, Declarative HTTP Clients>>.

== Starting Consul

The quickest way to start using Consul is via Docker:

. Starting Consul with Docker.
[source,bash]
----
docker run -p 8500:8500 consul
----

Alternatively you can https://www.consul.io/docs/install/index.html[install and run a local Consul instance].

== Auto Registering with Consul

To register a Micronaut application with Consul simply add the necessary api:discovery.consul.ConsulConfiguration[]. A minimal example can be seen below:

.Auto Registering with Consul (application.yml)
[source,yaml]
----
micronaut:
    application:
        name: hello-world
consul:
  client:
    registration:
      enabled: true
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

TIP: Using the Micronaut CLI you can quickly create a new service setup with Consul using: `mn create-app my-app --features discovery-consul`

The `consul.client.defaultZone` settings accepts a list of Consul servers to be used by default.

NOTE: You could also simply set `consul.client.host` and `consul.client.port`, however api:discovery.consul.ConsulConfiguration[] allows you specify per zone discovery services for the purpose load balancing. A zone maps onto a AWS availability zone or a Google Cloud zone.

By default registering with Consul is disabled hence you should set `consul.client.registration.enabled` to `true`. Note that you may wish to do this only in your production configuration.


WARNING: Running multiple instances of a service may require an additional configuration param.  See below.

If you are running the same applications on the same port across different servers it is important to set the `micronaut.application.instance.id` property or you will experience instance registration collision.

[source,yaml]
----
micronaut:
  application:
    name: hello-world
    instance:
      id: ${random.shortuuid}
----

== Customizing Consul Service Registration

The api:discovery.consul.ConsulConfiguration[] class features a range of customization options for altering how an instance registers with Consul. You can customize the tags, the retry attempts, the fail fast behaviour and so on.

Notice too that `ConsulConfiguration` extends api:discovery.client.DiscoveryClientConfiguration[]  which in turn extends api:http.client.HttpClientConfiguration[] allowing you to customize the settings for the Consul client, including read timeout, proxy configuration and so on.

For example:

.Customizing Consul Registration Configuration
[source,yaml]
----
micronaut:
    application:
        name: hello-world
consul:
  client:
    registration:
      enabled: true
      # Alters the tags
      tags:
        - hello
        - world
      # Alters the metadata
      meta:
        some: value
        instance_type: t2.medium
      # Alters the retry count
      retry-count: 5
      # Alters fail fast behaviour
      fail-fast: false
    defaultZone: "${CONSUL_HOST:localhost}:${CONSUL_PORT:8500}"
----

== Discovery Services from Consul

To discovery other services you could manually interact with the api:discovery.DiscoveryClient[], however typically instead you use the <<clientAnnotation, Client Annotation>> to declare how an HTTP client maps to a service.

For example the configuration in the previous section declared a value for `micronaut.application.name` of `hello-world`. This is the value that will be used as the service ID when registering with Consul.

Other services can discovery instances of the `hello-world` service simply by declaring a client as follows:

.Using @Client to Discover Services
[source,java]
----
@Client(id = "hello-world")
interface HelloClient{
	...
}
----

Alternatively you can also use ann:http.client.annotation.Client[] as a qualifier to `@Inject` an instance of api:http.client.HttpClient[]:

.Using @Client to Discover Services
[source,java]
----
@Client(id = "hello-world")
@Inject
RxHttpClient httpClient;
----

== Consul Health Checks

By default when registering with Consul Micronaut will register a https://www.consul.io/docs/agent/checks.html[TTL check]. A TTL check basically means that if the application does not send a heartbeat back to Consul after a period of time the service is put in a failing state.

Micronaut applications feature a api:health.HeartbeatConfiguration[] which starts a thread using api:health.HeartbeatTask[] that fires api:health.HeartbeatEvent[] instances.

The api:discovery.consul.registration.ConsulAutoRegistration[] class listens for these events and sends a callback to the https://www.consul.io/api/agent/check.html[/agent/check/pass/:check_id] endpoint provided by Consul, effectively keeping the service alive.

With this arrangement the responsibility is on the Micronaut application to send TTL callbacks to Consul on a regular basis.

If you prefer you can push the responsibility for health checks to Consul itself by registering an HTTP check:

.Consul HTTP Check Configuration
[source,yaml]
----
consul:
  client:
    registration:
       check:
          http: true
----

With this configuration option in place Consul will assume responsibility of invoking the Micronaut applications <<healthEndpoint, Health Endpoint>>.

== Controlling IP/Host Registration

Occasionally, depending on the deployment environment you may wish to expose the IP address and not the host name, since by default Micronaut will register with Consul with either the value of the `HOST` environment variable or the value configured via `micronaut.server.host`.

You can use the `consul.client.registration.prefer-ip-address` setting to indicate you would prefer to register with the IP address.

Micronaut will by default perform an IP lookup to try and figure out the IP address, however you can use the `consul.client.registration.ip-addr` setting to specify the IP address of the service directly.

.Consul HTTP Check Configuration
[source,yaml]
----
consul:
  client:
    registration:
        ip-addr: <your base container ip>
        prefer-ip-address: true
----

This will tell Consul to register the IP that other instances can use to access your service and not the NAT IP it is running under (or 127.0.0.1).

If you use HTTP health checks (see the previous section) then Consul will use the configured IP address to check the Micronaut `/health` endpoint.

.Consul HTTP Check Configuration
[source,yaml]
----
consul:
  client:
    registration:
        ip-addr: <your base container ip>
        prefer-ip-address: true
        check:
            http: true
----
