/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aop.chain;

import io.micronaut.core.annotation.Internal;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.Set;
import java.util.concurrent.ConcurrentHashMap;

/**
 * Warns that an entry point kept for code generated by an earlier version was called, once per entry point.
 *
 * @since 5.3.0
 */
@Internal
final class LegacyGeneratedCode {
    private static final Logger LOG = LoggerFactory.getLogger(LegacyGeneratedCode.class);
    private static final Set<String> WARNED = ConcurrentHashMap.newKeySet();

    private LegacyGeneratedCode() {
    }

    /**
     * Logs a warning the first time the entry point is called.
     *
     * @param entryPoint The class and method called, as {@code Class.method}
     */
    static void warn(String entryPoint) {
        if (WARNED.add(entryPoint)) {
            LOG.warn("{} was called by code compiled with a Micronaut version before 5.3. Recompile the application "
                + "with Micronaut 5.3 or later; this entry point will be removed in a future release.", entryPoint);
        }
    }
}
