/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aop.chain;

import io.micronaut.aop.Interceptor;
import io.micronaut.context.BeanContext;
import io.micronaut.context.BeanRegistration;
import io.micronaut.context.BeanResolutionContext;
import io.micronaut.context.DefaultBeanContext;
import io.micronaut.context.Qualifier;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.UsedByGeneratedCode;
import io.micronaut.core.type.Argument;
import io.micronaut.inject.BeanDefinition;
import org.jspecify.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Selects the interceptor instances a proxy that holds its target separately invokes that target with.
 *
 * <p>The scenario is an {@code @Around(proxyTarget = true)} proxy, most often a scoped proxy, with a non-singleton
 * interceptor:</p>
 *
 * <pre>{@code
 * @Prototype
 * @InterceptorBean(Probed.class)
 * class ProbeInterceptor implements MethodInterceptor<Object, Object> { ... }
 *
 * @ThreadLocal @Probed
 * class Tracked { @PostConstruct void init() {} public void call() {} }
 * }</pre>
 *
 * <p>A non-singleton interceptor is one instance per intercepted bean, and the intercepted bean is the target. The
 * proxy is constructed with interceptors resolved once for itself, but its target is created separately, and a scoped
 * proxy stands for a new target in every scope. The target's post-construct and pre-destroy interception use instances
 * created with the target, so the proxy's own cannot serve its methods: for one target the phases would see different
 * instances, and every target would share the proxy's.</p>
 *
 * <p>The proxy therefore names its non-singleton interceptors on the resolution context it resolves the target with,
 * so the context creates the target's own instances, reusing any the target resolved for its lifecycle, and records
 * them against the target. Method calls then swap each of the proxy's non-singleton instances for the target's
 * instance of the same interceptor. Singleton interceptors are the same instance either way and are never swapped, and
 * a proxy bound to no non-singleton interceptor keeps the arrays it resolved.</p>
 *
 * <p>A proxy whose target is fixed swaps once, in its constructor, through the static methods. A lazy proxy resolves
 * its target on each call and swaps through an instance created in its constructor. Proxies generated by an earlier
 * version do neither and invoke every target with their own instances.</p>
 *
 * @author Denis Stepanov
 * @since 5.2.1
 */
@Internal
@UsedByGeneratedCode
public final class ProxyTargetInterceptors {

    private final Interceptor<?, ?>[][] interceptors;
    private final @Nullable DefaultBeanContext beanContext;
    private final NonSingletonInterceptors nonSingleton;

    /**
     * Creates the interceptor selection of a lazy proxy, whose target is resolved on each call.
     *
     * <p>Names the proxy's non-singleton interceptors on the resolution context the proxy resolves its target with,
     * which a lazy proxy keeps for itself, so every target it resolves is created with its own instances.</p>
     *
     * @param resolutionContext The resolution context the proxy resolves its target with
     * @param targetDefinition  The definition of the target
     * @param beanContext       The bean context
     * @param registrations     The interceptor registrations the proxy was constructed with
     * @param interceptors      The interceptors the proxy resolved for each of its methods
     */
    @UsedByGeneratedCode
    public ProxyTargetInterceptors(BeanResolutionContext resolutionContext,
                                   BeanDefinition<?> targetDefinition,
                                   BeanContext beanContext,
                                   List<? extends BeanRegistration<?>> registrations,
                                   Interceptor<?, ?>[][] interceptors) {
        this.interceptors = interceptors;
        this.nonSingleton = NonSingletonInterceptors.of(registrations);
        this.beanContext = nonSingleton.isEmpty() || !(beanContext instanceof DefaultBeanContext defaultBeanContext)
            ? null
            : defaultBeanContext;
        if (this.beanContext != null) {
            resolutionContext.setAttribute(
                BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS,
                Map.entry(targetDefinition, nonSingleton.registrations)
            );
        }
    }

    /**
     * Returns the interceptors to invoke a method on the given target with.
     *
     * @param index  The index of the method in the proxy
     * @param target The target the method is invoked on
     * @return The interceptors of the method, with the target's instance of each non-singleton interceptor
     */
    @UsedByGeneratedCode
    public Interceptor<?, ?>[] get(int index, Object target) {
        Interceptor<?, ?>[] methodInterceptors = interceptors[index];
        if (beanContext == null) {
            return methodInterceptors;
        }
        List<BeanRegistration<?>> targetRegistrations = beanContext.findProxyTargetInterceptorRegistrations(target);
        return targetRegistrations == null ? methodInterceptors : nonSingleton.swap(methodInterceptors, targetRegistrations);
    }

    /**
     * Resolves the target of a proxy whose target is fixed, creating it with its own instance of every non-singleton
     * interceptor bound to the proxy.
     *
     * @param resolutionContext The resolution context the proxy is constructed with
     * @param targetDefinition  The definition of the target
     * @param beanType          The bean type
     * @param qualifier         The qualifier
     * @param registrations     The interceptor registrations the proxy was constructed with
     * @param <T>               The bean type
     * @return The target
     */
    @UsedByGeneratedCode
    public static <T> T getProxyTargetBean(BeanResolutionContext resolutionContext,
                                           BeanDefinition<T> targetDefinition,
                                           Argument<T> beanType,
                                           @Nullable Qualifier<T> qualifier,
                                           List<? extends BeanRegistration<?>> registrations) {
        NonSingletonInterceptors nonSingleton = NonSingletonInterceptors.of(registrations);
        if (nonSingleton.isEmpty()) {
            return resolutionContext.getProxyTargetBean(targetDefinition, beanType, qualifier);
        }
        // The context is shared with whatever resolves this proxy, so restore rather than leave the attribute behind
        Object previous = resolutionContext.setAttribute(
            BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS,
            Map.entry(targetDefinition, nonSingleton.registrations)
        );
        try {
            return resolutionContext.getProxyTargetBean(targetDefinition, beanType, qualifier);
        } finally {
            if (previous == null) {
                resolutionContext.removeAttribute(BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS);
            } else {
                resolutionContext.setAttribute(BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS, previous);
            }
        }
    }

    /**
     * Returns the interceptors of a proxy whose target is fixed, with the target's instance of each non-singleton
     * interceptor.
     *
     * @param beanContext   The bean context
     * @param registrations The interceptor registrations the proxy was constructed with
     * @param interceptors  The interceptors the proxy resolved for each of its methods
     * @param target        The target
     * @return The interceptors to invoke the target with
     */
    @UsedByGeneratedCode
    public static Interceptor<?, ?>[][] resolve(BeanContext beanContext,
                                                List<? extends BeanRegistration<?>> registrations,
                                                Interceptor<?, ?>[][] interceptors,
                                                Object target) {
        NonSingletonInterceptors nonSingleton = NonSingletonInterceptors.of(registrations);
        if (nonSingleton.isEmpty() || !(beanContext instanceof DefaultBeanContext defaultBeanContext)) {
            return interceptors;
        }
        List<BeanRegistration<?>> targetRegistrations = defaultBeanContext.findProxyTargetInterceptorRegistrations(target);
        if (targetRegistrations == null) {
            return interceptors;
        }
        for (int i = 0; i < interceptors.length; i++) {
            interceptors[i] = nonSingleton.swap(interceptors[i], targetRegistrations);
        }
        return interceptors;
    }

    /**
     * The non-singleton interceptor registrations of a proxy.
     *
     * @param registrations The registrations
     */
    private record NonSingletonInterceptors(List<BeanRegistration<?>> registrations) {

        private static NonSingletonInterceptors of(List<? extends BeanRegistration<?>> registrations) {
            List<BeanRegistration<?>> nonSingleton = null;
            for (BeanRegistration<?> registration : registrations) {
                if (!registration.getBeanDefinition().isSingleton()) {
                    if (nonSingleton == null) {
                        nonSingleton = new ArrayList<>(registrations.size());
                    }
                    nonSingleton.add(registration);
                }
            }
            return new NonSingletonInterceptors(nonSingleton == null ? List.of() : nonSingleton);
        }

        boolean isEmpty() {
            return registrations.isEmpty();
        }

        /**
         * Swaps each of the proxy's non-singleton interceptor instances for the target's instance of the same
         * interceptor, leaving the given array untouched.
         */
        Interceptor<?, ?>[] swap(Interceptor<?, ?>[] methodInterceptors, List<BeanRegistration<?>> targetRegistrations) {
            Interceptor<?, ?>[] swapped = null;
            for (int i = 0; i < methodInterceptors.length; i++) {
                Object targetInterceptor = findTargetInterceptor(methodInterceptors[i], targetRegistrations);
                if (targetInterceptor != null && targetInterceptor != methodInterceptors[i]) {
                    if (swapped == null) {
                        swapped = methodInterceptors.clone();
                    }
                    swapped[i] = (Interceptor<?, ?>) targetInterceptor;
                }
            }
            return swapped == null ? methodInterceptors : swapped;
        }

        private @Nullable Object findTargetInterceptor(Interceptor<?, ?> proxyInterceptor,
                                                       List<BeanRegistration<?>> targetRegistrations) {
            for (BeanRegistration<?> registration : registrations) {
                if (registration.getBean() == proxyInterceptor) {
                    BeanDefinition<?> definition = registration.getBeanDefinition();
                    for (BeanRegistration<?> targetRegistration : targetRegistrations) {
                        if (targetRegistration.getBeanDefinition().equals(definition)) {
                            return targetRegistration.getBean();
                        }
                    }
                    return null;
                }
            }
            return null;
        }
    }
}
