/*
 * Copyright 2017-2026 original authors
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * https://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package io.micronaut.aop.chain;

import io.micronaut.aop.Interceptor;
import io.micronaut.aop.InterceptorRegistry;
import io.micronaut.context.BeanContext;
import io.micronaut.context.BeanRegistration;
import io.micronaut.context.BeanResolutionContext;
import io.micronaut.context.DefaultBeanContext;
import io.micronaut.context.Qualifier;
import io.micronaut.core.annotation.Internal;
import io.micronaut.core.annotation.UsedByGeneratedCode;
import io.micronaut.core.type.Argument;
import io.micronaut.inject.BeanDefinition;
import io.micronaut.inject.ExecutableMethod;
import io.micronaut.inject.annotation.AnnotationMetadataHierarchy;
import io.micronaut.inject.proxy.ProxyTargetInterceptorRegistrations;
import io.micronaut.inject.qualifiers.Qualifiers;
import org.jspecify.annotations.Nullable;

import java.util.ArrayList;
import java.util.List;
import java.util.Map;

/**
 * Selects the interceptors a proxy that holds its target separately invokes that target with.
 *
 * <p>The scenario is an {@code @Around(proxyTarget = true)} proxy, most often a scoped proxy, with a non-singleton
 * interceptor:</p>
 *
 * <pre>{@code
 * @Prototype
 * @InterceptorBean(Probed.class)
 * class ProbeInterceptor implements MethodInterceptor<Object, Object> { ... }
 *
 * @ThreadLocal @Probed
 * class Tracked { @PostConstruct void init() {} public void call() {} }
 * }</pre>
 *
 * <p>A non-singleton interceptor is one instance per intercepted bean, and the intercepted bean is the target. A scoped
 * proxy stands for a new target in every scope, and even a proxy with a single target is created separately from it,
 * while the target's post-construct and pre-destroy interception use instances created with the target. So the proxy
 * creates no instance of a non-singleton interceptor for itself: it is given only the singleton ones, finds the
 * definitions of the others from the bindings of its methods, and names them on the resolution context it resolves its
 * target with. The context then gives the target its own instances, reusing any the target resolved for its lifecycle,
 * and records them against the target. Each method is invoked with the singleton interceptors and the target's
 * instances of the others.</p>
 *
 * <p>A proxy whose target is fixed selects the interceptors once, in its constructor. A lazy proxy resolves its target
 * on each call, and a hot-swappable one can be given another, so both select the interceptors for the target of each
 * call, keeping the result on the target's registrations, which live exactly as long as the target. Proxies generated by an earlier version do none of this: they are given every interceptor and
 * invoke every target with their own instances.</p>
 *
 * @author Denis Stepanov
 * @since 5.2.1
 */
@Internal
@UsedByGeneratedCode
public final class ProxyTargetInterceptors {

    private final BeanContext beanContext;
    private final InterceptorRegistry interceptorRegistry;
    private final BeanDefinition<?> targetDefinition;
    private final ExecutableMethod<?, ?>[] methods;
    private final List<BeanRegistration<?>> singletons;
    private final List<BeanDefinition<?>> nonSingletons;
    private final Interceptor<?, ?> @Nullable [][] proxyInterceptors;
    private volatile Interceptor<?, ?> @Nullable [][] unownedInterceptors;

    /**
     * Creates the interceptor selection of a proxy.
     *
     * @param beanContext         The bean context
     * @param interceptorRegistry The interceptor registry
     * @param targetDefinition    The definition of the target
     * @param methods             The intercepted methods of the proxy, in the order of its method indexes
     * @param registrations       The interceptor registrations the proxy was constructed with
     */
    @UsedByGeneratedCode
    public ProxyTargetInterceptors(BeanContext beanContext,
                                   InterceptorRegistry interceptorRegistry,
                                   BeanDefinition<?> targetDefinition,
                                   ExecutableMethod<?, ?>[] methods,
                                   List<? extends BeanRegistration<?>> registrations) {
        this.beanContext = beanContext;
        this.interceptorRegistry = interceptorRegistry;
        this.targetDefinition = targetDefinition;
        this.methods = methods;
        List<BeanRegistration<?>> singletonRegistrations = new ArrayList<>(registrations.size());
        List<BeanDefinition<?>> nonSingletonDefinitions = new ArrayList<>(2);
        for (BeanRegistration<?> registration : registrations) {
            if (registration.getBeanDefinition().isSingleton()) {
                singletonRegistrations.add(registration);
            } else {
                // Only a list resolved without the singletons-only qualifier carries these
                addDefinition(nonSingletonDefinitions, registration.getBeanDefinition());
            }
        }
        if (methods.length > 0 && beanContext instanceof DefaultBeanContext) {
            for (BeanDefinition<Interceptor<?, ?>> definition : beanContext.getBeanDefinitions(
                Interceptor.ARGUMENT,
                // the hierarchy reverses the array it is given, and this one is the proxy's
                Qualifiers.byInterceptorBinding(new AnnotationMetadataHierarchy(methods.clone()))
            )) {
                if (!definition.isSingleton()) {
                    addDefinition(nonSingletonDefinitions, definition);
                }
            }
        }
        this.singletons = singletonRegistrations;
        if (nonSingletonDefinitions.isEmpty()) {
            this.nonSingletons = List.of();
            this.proxyInterceptors = resolve(singletonRegistrations);
        } else {
            this.nonSingletons = nonSingletonDefinitions;
            this.proxyInterceptors = null;
        }
    }

    /**
     * Resolves the target a non-lazy proxy is constructed with, creating it with its own instance of every
     * non-singleton interceptor bound to the proxy.
     *
     * @param resolutionContext The resolution context the proxy is constructed with
     * @param beanType          The bean type
     * @param qualifier         The qualifier
     * @param <T>               The bean type
     * @return The target
     */
    @UsedByGeneratedCode
    @SuppressWarnings("unchecked")
    public <T> T getProxyTargetBean(BeanResolutionContext resolutionContext,
                                    Argument<T> beanType,
                                    @Nullable Qualifier<T> qualifier) {
        BeanDefinition<T> definition = (BeanDefinition<T>) targetDefinition;
        if (nonSingletons.isEmpty()) {
            return resolutionContext.getProxyTargetBean(definition, beanType, qualifier);
        }
        // The context is shared with whatever resolves this proxy, so restore rather than leave the attribute behind
        Object previous = resolutionContext.setAttribute(
            BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS,
            Map.entry(targetDefinition, nonSingletons)
        );
        try {
            return resolutionContext.getProxyTargetBean(definition, beanType, qualifier);
        } finally {
            if (previous == null) {
                resolutionContext.removeAttribute(BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS);
            } else {
                resolutionContext.setAttribute(BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS, previous);
            }
        }
    }

    /**
     * Names the non-singleton interceptors on the resolution context a lazy proxy keeps for itself, so that every
     * target it resolves is created with its own instances.
     *
     * @param resolutionContext The resolution context the proxy resolves its targets with
     */
    @UsedByGeneratedCode
    public void bindLazyTargets(BeanResolutionContext resolutionContext) {
        if (!nonSingletons.isEmpty()) {
            resolutionContext.setAttribute(
                BeanResolutionContext.PROXY_INTERCEPTOR_REGISTRATIONS,
                Map.entry(targetDefinition, nonSingletons)
            );
        }
    }

    /**
     * Returns the interceptors of every method of a proxy whose target is fixed.
     *
     * @param target The target
     * @return The interceptors, indexed like the proxy's methods
     */
    @UsedByGeneratedCode
    public Interceptor<?, ?>[][] resolve(Object target) {
        if (proxyInterceptors != null) {
            return proxyInterceptors;
        }
        ProxyTargetInterceptorRegistrations targetRegistrations = findTargetRegistrations(target);
        return targetRegistrations == null ? unownedInterceptors() : resolve(combine(targetRegistrations));
    }

    /**
     * Returns the interceptors to invoke a method on the given target with, for a proxy whose target can change from
     * one call to the next: a lazy proxy, or a hot-swappable one.
     *
     * @param index  The index of the method in the proxy
     * @param target The target the method is invoked on
     * @return The interceptors of the method
     */
    @UsedByGeneratedCode
    public Interceptor<?, ?>[] get(int index, Object target) {
        if (proxyInterceptors != null) {
            return proxyInterceptors[index];
        }
        ProxyTargetInterceptorRegistrations targetRegistrations = findTargetRegistrations(target);
        if (targetRegistrations == null) {
            return unownedInterceptors()[index];
        }
        if (targetRegistrations.getResolvedInterceptors() instanceof Resolved resolved
            && resolved.targetDefinition.equals(targetDefinition)
            && resolved.interceptors.length == methods.length) {
            return resolved.interceptors[index];
        }
        Interceptor<?, ?>[][] interceptors = resolve(combine(targetRegistrations));
        targetRegistrations.setResolvedInterceptors(new Resolved(targetDefinition, interceptors));
        return interceptors[index];
    }

    private @Nullable ProxyTargetInterceptorRegistrations findTargetRegistrations(Object target) {
        return beanContext instanceof DefaultBeanContext defaultBeanContext
            ? defaultBeanContext.findProxyTargetInterceptorRegistrations(target)
            : null;
    }

    /**
     * The singleton interceptors of the proxy followed by the target's instance of each non-singleton one.
     */
    private List<BeanRegistration<?>> combine(ProxyTargetInterceptorRegistrations targetRegistrations) {
        List<BeanRegistration<?>> combined = new ArrayList<>(singletons.size() + nonSingletons.size());
        combined.addAll(singletons);
        for (BeanDefinition<?> definition : nonSingletons) {
            BeanRegistration<?> registration = findRegistration(targetRegistrations, definition);
            combined.add(registration == null ? beanContext.getBeanRegistration(definition) : registration);
        }
        return combined;
    }

    /**
     * The interceptors for a target the context recorded nothing for, such as one created without going through a
     * proxy, or a target that was swapped in by hand. Such a target has no instances of its own, so the proxy creates
     * one of each non-singleton interceptor, once, and uses them as proxies from earlier versions did. Nothing owns
     * them, so they are not destroyed with the proxy.
     */
    private Interceptor<?, ?>[][] unownedInterceptors() {
        Interceptor<?, ?>[][] interceptors = unownedInterceptors;
        if (interceptors == null) {
            synchronized (this) {
                interceptors = unownedInterceptors;
                if (interceptors == null) {
                    List<BeanRegistration<?>> registrations = new ArrayList<>(singletons.size() + nonSingletons.size());
                    registrations.addAll(singletons);
                    for (BeanDefinition<?> definition : nonSingletons) {
                        registrations.add(beanContext.getBeanRegistration(definition));
                    }
                    interceptors = resolve(registrations);
                    unownedInterceptors = interceptors;
                }
            }
        }
        return interceptors;
    }

    @SuppressWarnings({"unchecked", "rawtypes"})
    private Interceptor<?, ?>[][] resolve(List<BeanRegistration<?>> registrations) {
        Interceptor<?, ?>[][] interceptors = new Interceptor[methods.length][];
        for (int i = 0; i < methods.length; i++) {
            interceptors[i] = InterceptorChain.resolveAroundInterceptors(interceptorRegistry, (ExecutableMethod) methods[i], (List) registrations);
        }
        return interceptors;
    }

    private static void addDefinition(List<BeanDefinition<?>> definitions, BeanDefinition<?> definition) {
        if (!definitions.contains(definition)) {
            definitions.add(definition);
        }
    }

    private static @Nullable BeanRegistration<?> findRegistration(List<BeanRegistration<?>> registrations,
                                                                  BeanDefinition<?> definition) {
        for (BeanRegistration<?> registration : registrations) {
            if (registration.getBeanDefinition().equals(definition)) {
                return registration;
            }
        }
        return null;
    }

    /**
     * The interceptors a proxy selected for one target, kept on the target's registrations.
     *
     * @param targetDefinition The definition of the target the proxy was generated for
     * @param interceptors     The interceptors, indexed like the proxy's methods
     */
    private record Resolved(BeanDefinition<?> targetDefinition, Interceptor<?, ?>[][] interceptors) {
    }
}
