To use the Micronaut's integration with https://flywaydb.org/[Flyway] you need to add the following dependency to your
classpath.

.build.gradle
[source,groovy]
----
compile "io.micronaut.configuration:micronaut-flyway"
----

.pom.xml
[source,xml]
----
<dependency>
    <groupId>io.micronaut.configuration</groupId>
    <artifactId>micronaut-flyway</artifactId>
</dependency>
----

You can define Flyway configuration for each datasource. The following example demonstrates using it:

[source, yaml]
.src/main/resources/application.yml
----
include::{testsflyway}/groovy/io/micronaut/dbmigration/flyway/FlywaySpec.groovy[tag=yamlconfig,indent=0]
----

<1> Disable schema DDL creation.
<2> Configure flyway configuration for `default` data source.
<3> The migrations directory is `src/main/resources/databsemigrations`.


In that directory you need to include all your migrations, for example:

[source,sql]
.resources/databasemicrations/V1__create-books-schema.sql
----
include::{testsflyway}/resources/databasemigrations/V1__create-books-schema.sql[indent=0]
----

There are several options available for configuration:

include::{includedir}configurationProperties/io.micronaut.dbmigration.flyway.FlywayConfigurationProperties.adoc[]

NOTE: By default Micronaut will configure Flyway to use the datasources defined under `datasources` configuration key. If
you want to use a different datasource you need to define the properties `+flyway.*.url+`, `+flyway.*.user+` and
`+flyway.*.password+`.


=== Endpoint

Micronaut also provides a built-in endpoint to expose all the applied migrations in `/flyway`.

To enable the endpoint add the following to the configuration:

[source,yaml]
.resources/application.yml
----
endpoints:
    flyway:
        enabled: true # <1>
        sensitive: false # <2>
----
<1> `/flyway` endpoint is enabled (this is the default).
<2> `/flyway` endpoint is open for unauthenticated access.

[source,bash]
----
$ curl http://localhost:8080/flyway

[{
    "name": "default",
    "migrations": [{
        "checksum": 1952043475,
        "installedOn": "2018-11-12T11:32:52.000+0000",
        "executionTime": 96,
        "installedRank": 1,
        "version": {
            "version": "1"
        },
        "description": "init",
        "installedBy": "root",
        "state": "SUCCESS",
        "type": "SQL",
        "script": "V1__init.sql"
    }, {
        "checksum": -1926058189,
        "installedOn": "2018-11-12T11:32:52.000+0000",
        "executionTime": 10,
        "installedRank": 2,
        "version": {
            "version": "2"
        },
        "description": "testdata",
        "installedBy": "root",
        "state": "SUCCESS",
        "type": "SQL",
        "script": "V2__testdata.sql"
    }]
}]
----

TIP: `installedOn` is an link:{jdkapi}/java/time/Instant.html[Instant] and by default it is rendered as a long. If you
want to render as a _human readable_ date, add the following to `application.yml` `jackson.serialization.writeDatesAsTimestamps: false`

NOTE: See the section on <<providedEndpoints, Built-in endpoints>> in the user guide for more information about endpoints.
