==== Setting up a Hibernate/JPA EntityManager

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `hibernate-jpa` feature to include a Hibernate JPA configuration in your project:
----
$ mn create-app my-app --features hibernate-jpa
----
====

The Micronaut framework includes support for configuring a https://hibernate.org[Hibernate] / JPA `EntityManager` that builds on the <<sqlSupport, SQL DataSource support>>.

Once you have <<sqlSupport, configured one or more DataSources>> to use Hibernate, add the `hibernate-jpa` dependency to your build:

dependency:micronaut-hibernate-jpa[groupId="io.micronaut.sql"]

For more information see the https://micronaut-projects.github.io/micronaut-sql/latest/guide/#hibernate[Configuring Hibernate] section of the https://github.com/micronaut-projects/micronaut-sql[Micronaut SQL libraries] project.

==== Using GORM for Hibernate

For Groovy users and users familiar with the Grails framework, special support for https://gorm.grails.org[GORM for Hibernate] is available. To use GORM for Hibernate *do not* include Micronaut's built-in <<sqlSupport, SQL Support>> or the `hibernate-jpa` dependency since GORM itself takes responsibility for creating the `DataSource`, `SessionFactory`, etc.

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `hibernate-gorm` feature to include GORM, a basic connection pool configuration, and a default H2 database driver in your project:
----
$ mn create-app my-app --features hibernate-gorm
----
====

See the https://micronaut-projects.github.io/micronaut-groovy/latest/guide/#gorm[GORM Modules] section of the https://github.com/micronaut-projects/micronaut-groovy[Micronaut Groovy user guide].
