To use the Micronaut's integration with http://www.liquibase.org[Liquibase] you must have the `micronaut-liquibase` dependency on your classpath. For example in `build.gradle`:

.build.gradle
[source,groovy]
----
compile "io.micronaut.configuration:micronaut-liquibase"
----

You can define liquibase configuration for each datasource. The following example demonstrates using it:

[source, yaml]
.src/main/resources/application.yml
----
include::{testsliquibase}/groovy/io/micronaut/docs/dbmigration/liquibase/LiquibaseSpec.groovy[tag=yamlconfig,indent=0]
----

<1> Disable schema DDL creation.
<2> Configure liquibase configuration for `default` data source.
<3> Root changelog under `src/main/resources/db/liquibase-changelog.xml`



Often, you will have a root changelog:

[source, xml]
.resources/db/liquibase-changelog.xml
----
include::{testsliquibase}/resources/db/liquibase-changelog.xml[indent=0]
----

which imports changelogs which you keep generating as your app evolves:

[source, xml]
.resources/db/changelog/01-create-books-schema.xml
----
include::{testsliquibase}/resources/db/changelog/01-create-books-schema.xml[indent=0]
----

There are several options available for configuration:

include::{includedir}configurationProperties/io.micronaut.dbmigration.liquibase.LiquibaseConfigurationProperties.adoc[]


=== Endpoint

Micronaut also provides a built-in endpoint to expose all the applied migrations in the built-in endpoing `/liquibase`.

To enable the endpoint add the following to the configuration:

[source,yaml]
.resources/application.yml
----
endpoints:
    liquibase:
        enabled: true # <1>
        sensitive: false # <2>
----
<1> `/liquibase` endpoint is enabled.
<2> `/liquibase` endpoint is open for unauthenticated access.

[source,bash]
----
$ curl http://localhost:8080/liquibase

[{
    "name": "default",
    "changeSets": [{
        "author": "sdelamo",
        "changeLog": "classpath:db/changelog/01-create-books-and-author-schema.xml",
        "comments": "",
        "contexts": [],
        "dateExecuted": 1540830785.000000000,
        "deploymentId": "0830784929",
        "description": "createTable tableName=books; createTable tableName=authors; addForeignKeyConstraint baseTableName=books, constraintName=author_fk, referencedTableName=authors",
        "execType": "EXECUTED",
        "id": "01",
        "labels": [],
        "checksum": "8:140eb966bb6a14bccade2c2d9133b7d3",
        "orderExecuted": 1,
        "tag": null
    }, {
        "author": "sdelamo",
        "changeLog": "classpath:db/changelog/02-insert-data-authors.xml",
        "comments": "Inserting Authors",
        "contexts": [],
        "dateExecuted": 1540830785.000000000,
        "deploymentId": "0830784929",
        "description": "insert tableName=authors; insert tableName=authors; insert tableName=authors; insert tableName=authors; insert tableName=authors",
        "execType": "EXECUTED",
        "id": "02",
        "labels": [],
        "checksum": "8:6204c525ce5c1c55f064888d078b8f05",
        "orderExecuted": 2,
        "tag": null
    }]
}]
----


NOTE: See the section on <<providedEndpoints, Built-in endpoints>> in the user guide for more information.
