==== Setting up the Native MongoDB Driver

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `mongo-reactive` feature to configure the native MongoDB driver in your project:
----
$ mn create-app my-app --features mongo-reactive
----
====

The Micronaut framework can automatically configure the native MongoDB Java driver. To use this, add the following dependency to your build:

dependency:micronaut-mongo-reactive[groupId="io.micronaut.mongodb"]

Then configure the URI of the MongoDB server in your configuration file (e.g `application.yml`):

.Configuring a MongoDB server
[configuration]
----
mongodb:
  uri: mongodb://username:password@localhost:27017/databaseName
----

TIP: The `mongodb.uri` follows the https://www.mongodb.com/docs/manual/reference/connection-string/[MongoDB Connection String] format.

A non-blocking Reactive Streams https://mongodb.github.io/mongo-java-driver-reactivestreams/1.8/javadoc/com/mongodb/reactivestreams/client/MongoClient.html[MongoClient] is then available for dependency injection.

To use the blocking driver, add a dependency to your build on the mongo-java-driver:

[source,groovy]
----
runtimeOnly "org.mongodb:mongo-java-driver"
----

Then the blocking https://mongodb.github.io/mongo-java-driver/3.7/javadoc/com/mongodb/MongoClient.html[MongoClient] will be available for injection.

See the https://micronaut-projects.github.io/micronaut-mongodb/latest/guide/[Micronaut MongoDB] documentation for further information on configuring and using MongoDB within Micronaut.
