The Micronaut Framework features dedicated support for automatically configuring the https://neo4j.com/docs/developer-manual/current/drivers/[Neo4j Bolt Driver] for the popular https://neo4j.com/[Neo4j] Graph Database.

[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `neo4j-bolt` feature to configure the Neo4j Bolt driver in your project:
----
$ mn create-app my-app --features neo4j-bolt
----
====

To configure the Neo4j Bolt driver, first add the `neo4j-bolt` module to your build:

dependency::micronaut-neo4j-bolt[groupId="io.micronaut.neo4j"]

Then configure the URI of the Neo4j server in your configuration file (e.g `application.yml`):

.Configuring `neo4j.uri`
[configuration]
----
neo4j:
  uri: bolt://localhost
----

TIP: The `neo4j.uri` setting must be in the format as described in the https://neo4j.com/docs/developer-manual/current/drivers/client-applications/#driver-connection-uris[Connection URIs] section of the Neo4j documentation

Once you have the above configuration in place you can inject an instance of the `org.neo4j.driver.v1.Driver` bean, which features both a synchronous blocking API and a non-blocking API based on `CompletableFuture`.

See the https://micronaut-projects.github.io/micronaut-neo4j/latest/guide/[Micronaut Neo4j] documentation for further information on configuring and using Neo4j within Micronaut.
