Micronaut supports reactive and non-blocking client to connect to Postgres using https://github.com/reactiverse/reactive-pg-client[reactive-pg-client], allowing  to handle many database connections with a single thread.

== Configuring the Reactive Postgres Client

To configure the Reactive Postgres you should first add `postgres-reactive` module to your classpath:

[source,groovy]
.build.gradle
----
include::test-suite/build.gradle[tags=postgres-reactive-dependencies,indent=0]
----

In addition, you might also need to add following Vert.x dependencies:

[source,groovy]
.build.gradle
----
include::test-suite/build.gradle[tags=vertx-dependencies,indent=0]
----

You should then configure the URI or https://reactiverse.io/reactive-pg-client/apidocs/index.html[`PoolOptions`] of the Postgres server you wish to communicate with in `application.yml`:

[source,yaml]
.application.yml
----
reactive:
	pg.client:
		port: 5432
		host: the-host
		database: the-db
		user: test
		password: test
		maxSize: 5
----

TIP: You can also connect to Postgres using `connectionUri`.

Once you have the above configuration in place then you can inject instance of the `io.reactiverse.reactivex.pgclient.PgPool` bean. Following is the simplest way to connect, query:

[source,groovy]
----
include::{testsuite}/configuration/postgres/reactive/PostgresReactiveSpec.groovy[tags=query,indent=0]
----

<1> `client` is an instance of the `io.reactiverse.reactivex.pgclient.PgPool` bean.

For more information on running queries on Postgres using the reactive client please read the "Running quries" section in the documentation of https://reactiverse.io/reactive-pg-client/guide/groovy/index.html[reactive-pg-client].

== Using Testcontainers for testing

We are using https://github.com/testcontainers/testcontainers-java[testcontainers-java] to use a containerized instance of a PostgresSQL database to test with our reactive Postgres client.

To get started with Testcontainers add the following `testCompile` dependencies to your project `build.gradle`:

[source,groovy]
.build.gradle
----
include::test-suite/build.gradle[tags=testcontainers-dependencies,indent=0]
----

Now, in your Spec file create a Postgres testcontainer, start it and get the configurations for reactive Postgres client as following:

[source,groovy]
----
include::{testsuite}/configuration/postgres/reactive/PostgresReactiveSpec.groovy[tags=appcontext-import,indent=0]
include::{testsuite}/configuration/postgres/reactive/PostgresReactiveSpec.groovy[tags=pg-testcontainer-import,indent=0]
include::{testsuite}/configuration/postgres/reactive/PostgresReactiveSpec.groovy[tags=pg-testcontainer,indent=0]
include::{testsuite}/configuration/postgres/reactive/PostgresReactiveSpec.groovy[tags=pg-client-conf,indent=0]
----
For more information on Testcontainers, read the original docs https://www.testcontainers.org/[here].

== Postgres Health Checks

When the `postgres-reactive` module is activated a api:configuration.postgres.reactive.health.PgPoolHealthIndicator[] is activated resulting in the `/health` endpoint and api:health.CurrentHealthStatus[] interface resolving the health of the Postgres connection

See the section on the <<healthEndpoint, Health Endpoint>> for more information.