The Micronaut framework features automatic configuration of the https://lettuce.io[Lettuce] driver for https://redis.io[Redis] via the `redis-lettuce` module.

== Configuring Lettuce
[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `redis-lettuce` feature to configure the Lettuce driver in your project:
----
$ mn create-app my-app --features redis-lettuce
----
====

To configure the Lettuce driver, first add the `redis-lettuce` module to your build:

.build.gradle
[source,groovy]
----
compile "io.micronaut.redis:micronaut-redis-lettuce"
----

Then configure the URI of the Redis server in your configuration file (e.g `application.yml`):

.Configuring `redis.uri`
[configuration]
----
redis:
  uri: redis://localhost
----

TIP: The `redis.uri` setting must be in the format as described in the https://github.com/lettuce-io/lettuce-core/wiki/Redis-URI-and-connection-details[Connection URIs] section of the Lettuce wiki

You can also specify multiple Redis URIs using `redis.uris`, in which case a `RedisClusterClient` is created instead.

For more information and further documentation see the https://micronaut-projects.github.io/micronaut-redis/latest/guide[Micronaut Redis] documentation.
