Java data sources can be configured for one of three currently provided implementations. Apache DBCP2, Hikari, and Tomcat are supported by default.

== Configuring a JDBC DataSource

[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply one of the `jdbc-tomcat`, `jdbc-hikari`, or `jdbc-dbcp` features to preconfigure a simple JDBC connection in your project, along with a default H2 database driver:
----
$ mn create-app my-app --features jdbc-tomcat
----
====

To get started, simply add a dependency to one of the JDBC configurations that corresponds to the implementation you would like to use. Choose one of the following:

dependency:micronaut-jdbc-tomcat[groupId="io.micronaut.sql", scope="runtime"]

dependency:micronaut-jdbc-hikari[groupId="io.micronaut.sql",scope="runtime"]

dependency:micronaut-jdbc-dbcp[groupId="io.micronaut.sql",scope="runtime"]

dependency:micronaut-jdbc-ucp[groupId="io.micronaut.sql",scope="runtime"]


You also need to add a JDBC driver dependency to your classpath. For example to add the http://www.h2database.com[H2 In-Memory Database]:

dependency:h2[groupId="com.h2database",scope="runtime"]

For more information see the https://micronaut-projects.github.io/micronaut-sql/latest/guide/#jdbc[Configuring JDBC] section of the https://github.com/micronaut-projects/micronaut-sql[Micronaut SQL libraries] project.