Micronaut allows the customization of the response that is sent when a request is not authorized to access a resource, or is not authenticated and the resource requires authentication.

To control this response, it is necessary to register a api:io.micronaut.security.handlers.RejectionHandler[] and ensure your bean replaces the default implementation.

If both beans (api:io.micronaut.security.handlers.UnauthorizedRejectionUriProvider[], api:io.micronaut.security.handlers.ForbiddenRejectionUriProvider[]) exists, then api:io.micronaut.security.handlers.RedirectRejectionHandler[],
               a generic redirect handler, is registered as a `RedirectHandler`.

You can create your own `RejectionHandler`. You will need to replace the current `RejectionHandler`.

For those using JWT based security, replace api:io.micronaut.security.handlers.HttpStatusCodeRejectionHandler[].

For example:

[source,java]
----
include::{testssecurityjwt}/rejection/MyRejectionHandler.java[tag=clazz,indent=0]
----

For those using session based security, replace api:io.micronaut.security.session.SessionSecurityfilterRejectionHandler[].

NOTE: If you are using session based security to use the `RedirectRejectionHandler` you will need to disable `SessionSecurityfilterRejectionHandler` with `micronaut.security.session.legacy-redirect-handler: false`.