You can create type safe configuration by creating classes that are annotated with
 ann:io.micronaut.context.annotation.ConfigurationProperties[].

Micronaut will produce a reflection-free `@ConfigurationProperties` bean and will also at compile time calculate the property paths to evaluate, greatly improving the speed and efficiency of loading `@ConfigurationProperties`.

An example of a configuration class can be seen below:

snippet::io.micronaut.docs.config.properties.EngineConfig[tags="imports,class",indent=0,title="@ConfigurationProperties Example"]

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> You can use `javax.validation` to validate the configuration
<3> Default values can be assigned to the property
<4> Static inner classes can provided nested configuration
<5> Optional configuration values can be wrapped in a `java.util.Optional`

Once you have prepared a type safe configuration it can simply be injected into your objects like any other bean:

snippet::io.micronaut.docs.config.properties.EngineImpl[tags="class",indent=0,title="@ConfigurationProperties Dependency Injection"]

<1> Inject the `EngineConfig` bean
<2> Use the configuration properties

Configuration values can then be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

snippet::io.micronaut.docs.config.properties.VehicleSpec[tags="start",indent=0,title="Supply Configuration"]

The above example prints: `"Ford Engine Starting V8 [rodLength=6.0]"`

Note for more complex configurations you can structure ann:context.annotation.ConfigurationProperties[] beans through inheritance.

For example creating a subclass of `EngineConfig` with `@ConfigurationProperties('bar')` will resolve all properties under the path `my.engine.bar`.

== Property Type Conversion

When resolving properties Micronaut will use the api:io.micronaut.core.convert.ConversionService[] bean to convert properties. You can register additional converters for types not supported by micronaut by defining beans that implement the api:io.micronaut.core.convert.TypeConverter[] interface.


Micronaut features some built-in conversions that are useful, which are detailed below.

=== Duration Conversion

Durations can be specified by appending the unit with a number. Supported units are `s`, `ms`, `m` etc. The following table summarizes examples:

.Duration Conversion
|===
|Configuration Value |Resulting Value

|`10ms` | `Duration` of 10 milliseconds

|`10m` | `Duration` of 10 minutes

|`10s` | `Duration` of 10 seconds

|`10d` | `Duration` of 10 days

|`10h` | `Duration` of 10 hours

|`10ns` | `Duration` of 10 nanoseconds

|`PT15M` | Duration of 15 minutes using ISO-8601 format

|===

For example to configure the default HTTP client read timeout:

.Using Duration Values
[source,yaml]
----
micronaut:
    http:
        client:
            read-timeout: 15s
----

=== List / Array Conversion

Lists and arrays can be specified in Java properties files as comma-separated values or in YAML using native YAML lists. The generic types are used to convert the values. For example in YAML:

.Specifying lists or arrays in YAML
[source,yaml]
----
my:
    app:
        integers:
            - 1
            - 2
        urls:
            - http://foo.com
            - http://bar.com
----

Or in Java properties file format:

.Specifying lists or arrays in Java properties comma-separated
[source,properties]
----
my.app.integers=1,2
my.app.urls=http://foo.com,http://bar.com
----

Alternatively you can use an index:

.Specifying lists or arrays in Java properties using index
[source,properties]
----
my.app.integers[0]=1
my.app.integers[1]=2
----

For the above example configurations you can define properties to bind to with the target type supplied via generics:

[source,java]
List<Integer> integers;
List<URL> urls;


=== Readable Bytes

You can annotate any setter parameter with ann:io.micronaut.core.convert.format.ReadableBytes[] to allow the value to be set using a shorthand syntax for specifying bytes, kilobytes etc. For example the following is taken from api:io.micronaut.http.client.HttpClientConfiguration[]:

.Using `@ReadableBytes`
[source,java]
----
public void setMaxContentLength(@ReadableBytes int maxContentLength) {
    this.maxContentLength = maxContentLength;
}
----

With the above in place you can set `micronaut.http.client.max-content-length` using the following values:

.@ReadableBytes Conversion
|===
|Configuration Value |Resulting Value

|`10mb` | 10 megabytes

|`10kb` | 10 kilobytes

|`10gb` | 10 gigabytes

|`1024` | A raw byte length

|===

=== Formatting Dates

The ann:io.micronaut.core.convert.format.Format[] annotation can be used on any setter to allow the date format to be specified when binding `javax.time` date objects.

.Using `@Format` for Dates
[source,java]
----
public void setMyDate(@Format("yy-mm-dd") LocalDate date) {
    this.myDate = date;
}
----

== Configuration Builder

Many existing frameworks and tools already use builder-style classes to construct configuration.

To support the ability for a builder style class to be populated with configuration values, the link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[@ConfigurationBuilder] annotation can be used. link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[ConfigurationBuilder] can be added to a field or method in a class annotated with link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties].

Since there is no consistent way to define builders in the Java world, one or more method prefixes can be specified in the annotation to support builder methods like `withXxx` or `setXxx`. If the builder methods have no prefix, assign an empty string to the parameter.

A configuration prefix can also be specified to tell Micronaut where to look for configuration values. By default, the builder methods will use the configuration prefix defined at the class level link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation.

For example:

.@ConfigurationBuilder Example
snippet::io.micronaut.docs.config.builder.EngineConfig[tags="imports,class"]

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> The first builder can be configured without the class configuration prefix; it will inherit from the above.
<3> The second builder can be configured with the class configuration prefix + the `configurationPrefix` value.
<4> The third builder demonstrates that the annotation can be applied to a method as well as a property.

NOTE: By default, only builder methods that take a single argument are supported. To support methods with no arguments, set the `allowZeroArgs` parameter of the annotation to true.

Just like in the previous example, we can construct an `EngineImpl`. Since we are using a builder, a factory class can be used to build the engine from the builder.

.Factory Bean
snippet::io.micronaut.docs.config.builder.EngineFactory[tags="imports,class"]

The engine that was returned can then be injected anywhere an engine is depended on.

Configuration values can be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
snippet::io.micronaut.docs.config.builder.VehicleSpec[tags="start"]

The above example prints: `"Subaru Engine Starting V4 [rodLength=4.0, sparkPlug=Iridium(NGK 6619 LFR6AIX)]"`

== MapFormat

For some use cases it may be desirable to accept a map of arbitrary configuration properties that can be supplied to a bean, especially if the bean represents a third-party API where not all of the possible configuration properties are known by the developer. For example, a datasource may accept a map of configuration properties specific to a particular database driver, allowing the user to specify any desired options in the map without coding every single property explicitly.

For this purpose, the api:core.convert.format.MapFormat[] annotation allows you to bind a map to a single configuration property, and specify whether to accept a flat map of keys to values, or a nested map (where the values may be additional maps].

snippet::io.micronaut.docs.config.mapFormat.EngineConfig[tags="imports,class",indent=0,title="@MapFormat Example"]
<1> Note the `transformation` argument to the annotation; possible values are `MapTransformation.FLAT` (for flat maps) and `MapTransformation.NESTED` (for nested maps)

snippet::io.micronaut.docs.config.mapFormat.EngineImpl[tags="class",indent=0,title="EngineImpl"]

Now a map of properties can be supplied to the `my.engine.sensors` configuration property.

snippet::io.micronaut.docs.config.mapFormat.VehicleSpec[tags="start",indent=0,title="Use Map Configuration"]

The above example prints: `"Engine Starting V8 [sensors=2]"`
