Like Spring Boot and Grails, you can create type safe configuration by creating classes that are annotated with link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[ConfigurationProperties].

Micronaut, however, will produce a reflection free `@ConfigurationProperties` bean and will also at compile time calculate the property paths to evaluate, greatly improving the speed and efficiency of loading `@ConfigurationProperties`.

An example of a configuration class can be seen below:

.@ConfigurationProperties Example
[source,groovy]
----
include::{testsdir}/config/properties/EngineConfig.groovy[tags=imports, indent=0]

include::{testsdir}/config/properties/EngineConfig.groovy[tags=class, indent=0]
----

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> You can use `javax.validation` to validate the configuration
<3> Default values can be assigned to the property
<4> Static inner classes can provided nested configuration
<5> Optional configuration values can be wrapped in a `java.util.Optional`

Once you have prepared a type safe configuration it can simply be injected into your objects like any other bean:

.@ConfigurationProperties Dependency Injection
[source,groovy]
----
include::{testsdir}/config/properties/EngineImpl.groovy[tags=class, indent=0]
----

<1> Inject the `EngineConfig` bean
<2> Use the configuration properties

Configuration values can then be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
[source,groovy]
----
include::{testsdir}/config/properties/VehicleSpec.groovy[tags=start, indent=0]
----

The above example prints: `"Ford Engine Starting V8 [rodLength=6.0]"`

Note for more complex configurations you can structure ann:context.annotation.ConfigurationProperties[] beans through inheritance.

For example creating a subclass of `EngineConfig` with `@ConfigurationProperties('bar')` will resolve all properties under the path `my.engine.bar`.

== Configuration Builder

Many existing frameworks and tools already use builder-style classes to construct configuration.

To support the ability for a builder style class to be populated with configuration values, the link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[@ConfigurationBuilder] annotation can be used. link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[ConfigurationBuilder] can be added to a field or method in a class annotated with link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties].

Since there is no consistent way to define builders in the Java world, one or more method prefixes can be specified in the annotation to support builder methods like `withXxx` or `setXxx`. If the builder methods have no prefix, assign an empty string to the parameter.

A configuration prefix can also be specified to tell Micronaut where to look for configuration values. By default, the builder methods will use the configuration prefix defined at the class level link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation.

For example:

.@ConfigurationBuilder Example
[source,groovy]
----
include::{testsdir}/config/builder/EngineConfig.groovy[tags=imports, indent=0]

include::{testsdir}/config/builder/EngineConfig.groovy[tags=class, indent=0]
----

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> The first builder can be configured with the class configuration prefix
<3> The second builder can be configured with the class configuration prefix + the `configurationPrefix` value.

NOTE: By default, only builder methods that take a single argument are supported. To support methods with no arguments, set the `allowZeroArgs` parameter of the annotation to true.

Just like in the previous example, we can construct an `EngineImpl`. Since we are using a builder, a factory class can be used to build the engine from the builder.

.Factory Bean
[source,groovy]
----
include::{testsdir}/config/builder/EngineFactory.groovy[tags=imports, indent=0]

include::{testsdir}/config/builder/EngineFactory.groovy[tags=class, indent=0]
----

The engine that was returned can then be injected anywhere an engine is depended on.

Configuration values can be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
[source,groovy]
----
include::{testsdir}/config/builder/VehicleSpec.groovy[tags=start, indent=0]
----

The above example prints: `"Subaru Engine Starting V4 [rodLength=4.0]"`

== MapFormat

For some use cases it may be desirable to accept a map of arbitrary configuration properties that can be supplied to a bean, especially if the bean represents a third-party API where not all of the possible configuration properties are known by the developer. For example, a datasource may accept a map of configuration properties specific to a particular database driver, allowing the user to specify any desired options in the map without coding every single property explicitly.

For this purpose, the api:core.convert.format.MapFormat[] annotation allows you to bind a map to a single configuration property, and specify whether to accept a flat map of keys to values, or a nested map (where the values may be additional maps].

.@MapFormat Example
[source,groovy]
----
include::{testsdir}/config/mapFormat/EngineConfig.groovy[tags=imports, indent=0]

include::{testsdir}/config/mapFormat/EngineConfig.groovy[tags=class, indent=0]
----
<1> Note the `transformation` argument to the annotation; possible values are `MapTransformation.FLAT` (for flat maps) and `MapTransformation.NESTED` (for nested maps)

.EngineImpl
[source,groovy]
----
include::{testsdir}/config/mapFormat/EngineImpl.groovy[tags=class, indent=0]
----

Now a map of properties can be supplied to the `my.engine.sensors` configuration property.


.Use Map Configuration
[source,groovy]
----
include::{testsdir}/config/mapFormat/VehicleSpec.groovy[tags=start, indent=0]
----

The above example prints: `"Engine Starting V8 [sensors=2]"`
