You can create type-safe configuration by creating classes that are annotated with
 ann:io.micronaut.context.annotation.ConfigurationProperties[].

The Micronaut framework will produce a reflection-free `@ConfigurationProperties` bean and will also at compile time calculate the property paths to evaluate, greatly improving the speed and efficiency of loading `@ConfigurationProperties`.

For example:

snippet::io.micronaut.docs.config.properties.EngineConfig[tags="imports,class",indent=0,title="@ConfigurationProperties Example"]

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> You can use `jakarta.validation` annotations to validate the configuration
<3> Default values can be assigned to the property
<4> Static inner classes can provide nested configuration
<5> Optional configuration values can be wrapped in `java.util.Optional`

Once you have prepared a type-safe configuration it can be injected into your beans like any other bean:

snippet::io.micronaut.docs.config.properties.EngineImpl[tags="class",indent=0,title="@ConfigurationProperties Dependency Injection"]

<1> Inject the `EngineConfig` bean
<2> Use the configuration properties

Configuration values can then be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

snippet::io.micronaut.docs.config.properties.VehicleSpec[tags="start",indent=0,title="Supply Configuration"]

The above example prints: `"Ford Engine Starting V8 [rodLength=6.0]"`

You can directly reference configuration properties in `@Requires` annotation to conditionally load beans using the following syntax: `@Requires(bean=Config.class, beanProperty="property", value="true")`

Note for more complex configurations you can structure ann:context.annotation.ConfigurationProperties[] beans through inheritance.

For example creating a subclass of `EngineConfig` with `@ConfigurationProperties('bar')` will resolve all properties under the path `my.engine.bar`.

[NOTE]
====
YAML Reserved Words
~~~~~~~~~~~~~~~~~~~~

When using YAML configuration files, certain words are reserved by the YAML specification and will be automatically converted to boolean values. These include:

* `yes` / `no`
* `true` / `false`
* `on` / `off`

If you use these words as unquoted property keys in YAML, they will be parsed as booleans instead of strings:

[source,yaml]
----
foo:
  bar:
    yes: "1"     # yes is parsed as true (boolean)
    no: "2"      # no is parsed as false (boolean)
----

To use these words as property names, you must quote the keys:

[source,yaml]
----
foo:
  bar:
    "yes": "1"   # forces YAML to treat as string
    "no": "2"    # forces YAML to treat as string
----

This is a limitation of YAML/SnakeYAML parsing and not specific to Micronaut. For more information, see the link:https://yaml.org/spec/1.2/spec.html#id2765879[YAML 1.2 Specification].
====

== Includes / Excludes

For the cases where the configuration properties class inherits properties from a parent class, it may be desirable to exclude properties from the parent class. The `includes` and `excludes` members of the ann:io.micronaut.context.annotation.ConfigurationProperties[] annotation allow for that functionality. The list applies to both local properties and inherited properties.

The names supplied to the includes/excludes list must be the "property" name. For example if a setter method is injected, the property name is the de-capitalized setter name (`setConnectionTimeout` -> `connectionTimeout`).

[[configurationPropertiesAccessorsStyle]]
== Change accessors style

Since 3.3, the Micronaut framework supports defining different accessors prefixes for getters and setter other than the default `get` and `set` defined for Java Beans. Annotate your POJO or `@ConfigurationProperties` class with the link:{api}/io/micronaut/core/annotation/AccessorsStyle.html[@AccessorsStyle] annotation.

This is useful when you write the getters and setters in a fluent way. For example:

.Using `@AccessorsStyle`
[source,java]
----
import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.core.annotation.AccessorsStyle;

@AccessorsStyle(readPrefixes = "", writePrefixes = "") // <1>
@ConfigurationProperties("my.engine")
public class EngineConfig {

    private String manufacturer;
    private int cylinders;

    public EngineConfig(String manufacturer, int cylinders) {
        this.manufacturer = manufacturer;
        this.cylinders = cylinders;
    }

    public String manufacturer() { // <2>
        return manufacturer;
    }

    public void manufacturer(String manufacturer) { // <2>
        this.manufacturer = manufacturer;
    }

    public int cylinders() { // <2>
        return cylinders;
    }

    public void cylinders(int cylinders) { // <2>
        this.cylinders = cylinders;
    }

}
----
<1> The Micronaut framework will use an empty prefix for getters and setters.
<2> Define the getters and setters with an empty prefix.

Now you can inject `EngineConfig` and use it with `engineConfig.manufacturer()` and `engineConfig.cylinders()` to retrieve the values from configuration.

== Property Type Conversion

The Micronaut framework uses the api:io.micronaut.core.convert.ConversionService[] bean to convert values when resolving properties. You can register additional converters for types not supported by Micronaut by defining beans that implement the api:io.micronaut.core.convert.TypeConverter[] interface.

The Micronaut framework features some built-in conversions that are useful, which are detailed below.

=== Duration Conversion

Durations can be specified by appending the unit with a number. Supported units are `s`, `ms`, `m` etc. The following table summarizes examples:

.Duration Conversion
|===
|Configuration Value |Resulting Value

|`10ms` | `Duration` of 10 milliseconds

|`10m` | `Duration` of 10 minutes

|`10s` | `Duration` of 10 seconds

|`10d` | `Duration` of 10 days

|`10h` | `Duration` of 10 hours

|`10ns` | `Duration` of 10 nanoseconds

|`PT15M` | `Duration` of 15 minutes using ISO-8601 format

|===

For example to configure the default HTTP client read timeout:

[configuration,title="Using Duration Values"]
----
micronaut:
  http:
    client:
      read-timeout: 15s
----

=== List / Array Conversion

Lists and arrays can be specified in Java properties files as comma-separated values, or in YAML using native YAML lists. The generic types are used to convert the values. For example in YAML:

[configuration,title="Specifying lists or arrays in YAML"]
----
my:
  app:
    integers:
      - 1
      - 2
    urls:
      - http://foo.com
      - http://bar.com
----

For the above example configurations you can define properties to bind to with the target type supplied via generics:

[source,java]
List<Integer> integers;
List<URL> urls;

=== Readable Bytes

You can annotate any setter parameter with ann:io.micronaut.core.convert.format.ReadableBytes[] to allow the value to be set using a shorthand syntax for specifying bytes, kilobytes etc. For example the following is taken from api:io.micronaut.http.client.HttpClientConfiguration[]:

.Using `@ReadableBytes`
[source,java]
----
public void setMaxContentLength(@ReadableBytes int maxContentLength) {
    this.maxContentLength = maxContentLength;
}
----

With the above in place you can set `micronaut.http.client.max-content-length` using the following values:

.@ReadableBytes Conversion
|===
|Configuration Value |Resulting Value

|`10mb` | 10 megabytes

|`10kb` | 10 kilobytes

|`10gb` | 10 gigabytes

|`1024` | A raw byte length

|===

=== Formatting Dates

The ann:io.micronaut.core.convert.format.Format[] annotation can be used on setters to specify the date format to use when binding `java.time` date objects.

.Using `@Format` for Dates
[source,java]
----
public void setMyDate(@Format("yyyy-MM-dd") LocalDate date) {
    this.myDate = date;
}
----

== Configuration Builder

Many frameworks and tools already use builder-style classes to construct configuration.

You can use the link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[@ConfigurationBuilder] annotation to populate a builder-style class with configuration values. link:{api}/io/micronaut/context/annotation/ConfigurationBuilder.html[ConfigurationBuilder] can be applied to fields or methods in a class annotated with link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties].

Since there is no consistent way to define builders in the Java world, one or more method prefixes can be specified in the annotation to support builder methods like `withXxx` or `setXxx`. If the builder methods have no prefix, assign an empty string to the parameter.

A configuration prefix can also be specified to tell the Micronaut framework where to look for configuration values. By default, builder methods use the configuration prefix specified in a class-level link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation.

For example:

.@ConfigurationBuilder Example
snippet::io.micronaut.docs.config.builder.EngineConfig[tags="imports,class"]

<1> The `@ConfigurationProperties` annotation takes the configuration prefix
<2> The first builder can be configured without the class configuration prefix; it inherits from the above.
<3> The second builder can be configured with the class configuration prefix + the `configurationPrefix` value.
<4> The third builder demonstrates that the annotation can be applied to a method as well as a property.

NOTE: By default, only single-argument builder methods are supported. For methods with no arguments, set the `allowZeroArgs` parameter of the annotation to `true`.

Like in the previous example, we can construct an `EngineImpl`. Since we are using a builder, we can use a factory class to build the engine from the builder.

.Factory Bean
snippet::io.micronaut.docs.config.builder.EngineFactory[tags="imports,class"]

The engine that was returned can then be injected anywhere an engine is required.

Configuration values can be supplied from one of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
snippet::io.micronaut.docs.config.builder.VehicleSpec[tags="start"]

The above example prints: `"Subaru Engine Starting V4 [rodLength=4.0, sparkPlug=Iridium(NGK 6619 LFR6AIX)]"`

== MapFormat

For some use cases it may be desirable to accept a map of arbitrary configuration properties that can be supplied to a bean, especially if the bean represents a third-party API where not all the possible configuration properties are known. For example, a datasource may accept a map of configuration properties specific to a particular database driver, allowing the user to specify any desired options in the map without coding each property explicitly.

For this purpose, the api:core.convert.format.MapFormat[] annotation lets you bind a map to a single configuration property, and specify whether to accept a flat map of keys to values, or a nested map (where the values may be additional maps).

snippet::io.micronaut.docs.config.mapFormat.EngineConfig[tags="imports,class",indent=0,title="@MapFormat Example"]
<1> Note the `transformation` argument to the annotation; possible values are `MapTransformation.FLAT` (for flat maps) and `MapTransformation.NESTED` (for nested maps)

snippet::io.micronaut.docs.config.mapFormat.EngineImpl[tags="class",indent=0,title="EngineImpl"]

Now a map of properties can be supplied to the `my.engine.sensors` configuration property.

snippet::io.micronaut.docs.config.mapFormat.VehicleSpec[tags="start",indent=0,title="Use Map Configuration"]

The above example prints: `"Engine Starting V8 [sensors=2]"`

== Configuration Metadata

At compilation time, the Micronaut framework writes metadata about every `@ConfigurationProperties` and `@EachProperty` type, which tooling uses to complete, document, and validate configuration:

* `META-INF/spring-configuration-metadata.json` lists the groups and properties of the module, with their types, descriptions, and default values.
* `META-INF/micronaut-configuration-schemas/<class>.json` is a https://json-schema.org/draft/2020-12/schema[JSON Schema (Draft 2020-12)] of each configuration class. The configuration validator of https://micronaut-projects.github.io/micronaut-json-schema/latest/guide/[Micronaut JSON Schema] uses these schemas to validate the configuration of an application.

The description of a property comes from its Javadoc, and its default value from ann:core.bind.annotation.Bindable[] `defaultValue` or, for the JSON schema, a `DEFAULT_<PROPERTY_NAME>` constant of the class, such as `DEFAULT_AUTO_OFFSET_RESET`. The JSON schema of a property also reflects its type and annotations:

|===
|Java type or annotation |JSON schema

|`boolean`, integer, and decimal types
|`type` `boolean`, `integer`, or `number`

|An enum
|`type` `string` and `enum` with the constants of the enum

|`URI` or `URL`, and `Duration`
|`type` `string` and `format` `uri` or `duration`

|A collection or an array, and a `Map`
|`type` `array` with the schema of the elements as `items`, and `type` `object` with the schema of the values as `additionalProperties`

|`@NotNull` and `@NotBlank`
|The property is `required`

|`@Size`, `@NotEmpty`, `@NotBlank`
|`minLength` and `maxLength`, `minItems` and `maxItems`, or `minProperties` and `maxProperties`

|`@Min`, `@Max`, `@DecimalMin`, `@DecimalMax`, `@Positive`, `@PositiveOrZero`, `@Negative`, `@NegativeOrZero`
|`minimum`, `maximum`, `exclusiveMinimum`, and `exclusiveMaximum`

|`@Pattern`, `@Digits`, and `@Email`
|`pattern`, and `format` `email`

|`@AssertTrue` and `@AssertFalse`
|`const` `true` or `false`

|ann:core.annotation.AllowedValues[]
|`enum` with the values of the annotation

|`@Deprecated`
|`deprecated` `true`
|===

=== Allowed Values

When a property only accepts some values, but its type does not list them, such as a `String` option of a third-party library, annotate the field, the setter, or the record component with ann:core.annotation.AllowedValues[]. The values become the `enum` of the property in its JSON schema, so the configuration validator rejects any other value:

.@AllowedValues Example
[source,java]
----
@ConfigurationProperties("my.consumer")
public class ConsumerConfiguration {

    @AllowedValues({"earliest", "latest", "none"}) // <1>
    private String autoOffsetReset = "latest";

    @AllowedValues({"1", "2", "4"}) // <2>
    private int threads = 1;

    @AllowedValues({"gzip", "snappy", "zstd"}) // <3>
    private List<String> codecs = List.of();

    // getters and setters
}
----

<1> The schema of `my.consumer.auto-offset-reset` is `{"type":"string","enum":["earliest","latest","none"]}`
<2> The values are written with the JSON type of the property, here `[1,2,4]`. A value that does not convert to the type of the property, or for an enum property is not one of its constants, fails the compilation
<3> For a collection or an array, the values apply to its elements, and for a `Map` to its values

On an enum property, ann:core.annotation.AllowedValues[] narrows the constants that the configuration accepts. You can also annotate your own annotation with ann:core.annotation.AllowedValues[] to reuse a set of values across properties.

NOTE: ann:core.annotation.AllowedValues[] is metadata for tooling: binding the property does not check its value. To validate the value at runtime, also use a constraint such as `@Pattern` with <<beanValidation, Bean Validation>>.

TIP: See the guide for https://guides.micronaut.io/latest/micronaut-configuration.html[@Configuration and @ConfigurationBuilder] to learn more.
