Like Spring Boot and Grails, you can create type safe configuration by creating classes that are annotated with link:{api}/org/particleframework/context/annotation/ConfigurationProperties.html[ConfigurationProperties].

Unlike the aforementioned frameworks, however, Micronaut uses ASM to generate a class that avoids the use of reflection and dynamic parsing so that loading the configuration is an efficient as possible with minimal impact on startup time.

An example of a configuration class can be seen below:

.@ConfigurationProperties Example
[source,groovy]
----
include::{testsdir}/config/properties/EngineConfig.groovy[tags=imports, indent=0]

include::{testsdir}/config/properties/EngineConfig.groovy[tags=class, indent=0]
----

<1> The `@ConfigProperties` annotation takes the configuration prefix
<2> You can use `javax.validation` to validate the configuration
<3> Default values can be assigned to the property
<4> Static inner classes can provided nested configuration
<5> Optional configuration values can be wrapped in a `java.util.Optional`

Once you have prepared a type safe configuration it can simply be injected into your objects like any other bean:

.@ConfigurationProperties Dependency Injection
[source,groovy]
----
include::{testsdir}/config/properties/EngineImpl.groovy[tags=class, indent=0]
----

Configuration values can then be supplied from one of the link:{api}/org/particleframework/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
[source,groovy]
----
include::{testsdir}/config/properties/VehicleSpec.groovy[tags=start, indent=0]
----

The above example prints: `"Ford Engine Starting V8 [rodLength=6.0]"`

== Configuration Builder

To support the ability for a builder style class to be populated with configuration values, the link:{api}/org/particleframework/context/annotation/ConfigurationBuilder.html[@ConfigurationBuilder] annotation can be used. link:{api}/org/particleframework/context/annotation/ConfigurationBuilder.html[ConfigurationBuilder] can be added to a field or method in a class annotated with link:{api}/org/particleframework/context/annotation/ConfigurationProperties.html[@ConfigurationProperties].

One or more method prefixes can be specified in the annotation to support builder methods like "withXxx" or "setXxx". If the builder methods have no prefix, assign an empty string to the parameter.

A configuration prefix can also be specified to tell Micronaut where to look for configuration values. By default, the builder methods will use the configuration prefix defined at the class level link:{api}/org/particleframework/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation.

For example:

.@ConfigurationBuilder Example
[source,groovy]
----
include::{testsdir}/config/builder/EngineConfig.groovy[tags=imports, indent=0]

include::{testsdir}/config/builder/EngineConfig.groovy[tags=class, indent=0]
----

<1> The `@ConfigProperties` annotation takes the configuration prefix
<2> The first builder can be configured with the class configuration prefix
<3> The second builder can be configured with the class configuration prefix + the `configurationPrefix` value.

NOTE: By default, only builder methods that take a single argument are supported. To support methods with no arguments, set the `allowZeroArgs` parameter of the annotation to true.

Just like in the previous example, we can construct an `EngineImpl`. Since we are using a builder, a factory class can be used to build the engine from the builder.

.Factory Bean
[source,groovy]
----
include::{testsdir}/config/builder/EngineFactory.groovy[tags=imports, indent=0]

include::{testsdir}/config/builder/EngineFactory.groovy[tags=class, indent=0]
----

The engine that was returned can then be injected anywhere an engine is depended on.

Configuration values can be supplied from one of the link:{api}/org/particleframework/context/env/PropertySource.html[PropertySource] instances. For example:

.Supply Configuration
[source,groovy]
----
include::{testsdir}/config/builder/VehicleSpec.groovy[tags=start, indent=0]
----

The above example prints: `"Subaru Engine Starting V4 [rodLength=4.0]"`