Micronaut features a built in type conversion mechanism that is extensible. To add additional type converters you register beans of type api:core.convert.TypeConverter[].

The following example shows how to use one of the built-in converters (Map to an Object) or create your own.

Consider the following api:context.annotation.ConfigurationProperties[]:

[source, groovy]
----
include::{testsdir}/config/converters/MyConfigurationProperties.groovy[tags=class, indent=0]
----

The type `MyConfigurationProperties` features a property called `updatedAt` which is of type jdk:java.time.LocalDate[].

Now let's say you want to allow binding to this property from a map via configuration:

[source, groovy]
----
include::{testsdir}/config/converters/MyConfigurationPropertiesSpec.groovy[tags=runContext, indent=0]
----

This won't work by default, since there is no built in conversion from `Map` to `LocalDate`. To resolve this you can define a custom api:core.convert.TypeConverter[]:

[source, groovy]
----
include::{testsdir}/config/converters/MapToLocalDateConverter.groovy[tags=imports, indent=0]

include::{testsdir}/config/converters/MapToLocalDateConverter.groovy[tags=class, indent=0]
----

<1> The class implements api:core.convert.TypeConverter[] which takes two generic arguments. The type you are converting from and the type you are converting to
<2> The implementation delegate to the default shared conversion service to convert the parts of the map that make the day, month and year into a `LocalDate`
<3> If an exception occurs you can call `reject(..)` which propagates additional information to the container if something goes wrong during binding



