The link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation is great for a single configuration class, but sometimes you want multiple instances each with their own distinct configuration. That is where link:{api}/io/micronaut/context/annotation/EachProperty.html[EachProperty] comes in.


The ann:context.annotation.EachProperty[] annotation will create a `ConfigurationProperties` bean for each sub-property within the given property. As an example consider the following class:

snippet::io.micronaut.docs.config.env.DataSourceConfiguration[tags="eachProperty", indent=0, title="Using @EachProperty"]

<1> The `@EachProperty` annotation defines the property name that should be handled.
<2> The `@Parameter` annotation can be used to inject the name of the sub-property that defines the name of the bean (which is also the bean qualifier)
<3> Each property of the bean is bound to configuration.

The above `DataSourceConfiguration` defines a `url` property to configure one or many hypothetical data sources of some sort. The URLs themselves can be configured using any of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances evaluated to Micronaut:

snippet::io.micronaut.docs.config.env.EachPropertyTest[tags="config", indent=0, title="Providing Configuration to @EachProperty"]

In the above example two data sources (called `one` and `two`) are defined under the `test.datasource` prefix defined earlier in the `@EachProperty` annotation. Each of these configuration entries triggers the creation of a new `DataSourceConfiguration` bean such that the following test succeeds:

snippet::io.micronaut.docs.config.env.EachPropertyTest[tags="beans", indent=0, title="Evaluating Beans Built by @EachProperty"]

<1> All beans of type `DataSourceConfiguration` can be retrieved using `getBeansOfType`
<2> Individual beans can be achieved by using the `byName` qualifier.

=== List Based Binding

The default behavior of ann:context.annotation.EachProperty[] is to bind from a map style of configuration where the key is the named qualifier of the bean and the value is the data to bind from. For cases where map style configuration doesn't make sense, it is possible to inform Micronaut the class should be bound from a list. Simply set the `list` member on the annotation to true.

