The link:{api}/io/micronaut/context/annotation/ConfigurationProperties.html[@ConfigurationProperties] annotation is great for a single configuration class, but sometimes you want multiple instances each with their own distinct configuration. That is where link:{api}/io/micronaut/context/annotation/EachProperty.html[EachProperty] comes in.


The link:{api}/io/micronaut/context/annotation/EachProperty.html[@EachProperty] annotation will create a `ConfigurationProperties` bean for each sub-property within the given property. As an example consider the following class:

.Using @EachProperty
[source,java]
----
include::{testsjava}/env/DataSourceConfiguration.java[tags=eachProperty, indent=0]
----

<1> The `@EachProperty` annotation defines the property name that should be handled.
<2> The `@Parameter` annotation can be used to inject the name of the sub-property that defines the name of the bean (which is also the bean qualifier)
<3> Each property of the bean is bound to configuration.

The above `DataSourceConfiguration` defines a `url` property to configure one or many hypothetical data sources of some sort. The URLs themselves can be configured using any of the link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances evaluated to Micronaut:

.Providing Configuration to @EachProperty
[source,java]
----
include::{testsjava}/env/EachPropertyTest.java[tags=config, indent=0]
----

In the above example two data sources (called `one` and `two`) are defined under the `test.datasource` prefix defined earlier in the `@EachProperty` annotation. Each of these configuration entries triggers the creation of a new `DataSourceConfiguration` bean such that the following test succeeds:

.Evaluating Beans Built by @EachProperty
[source,java]
----
include::{testsjava}/env/EachPropertyTest.java[tags=beans, indent=0]
----

<1> All beans of type `DataSourceConfiguration` can be retrieved using `getBeansOfType`
<2> Individual beans can be achieved by using the `byName` qualifier.
