Since 1.3, Micronaut framework supports the definition of immutable configuration.

There are two ways to define immutable configuration. The preferred way is to define an interface annotated with ann:context.annotation.ConfigurationProperties[]. For example:

snippet::io.micronaut.docs.config.itfce.EngineConfig[tags="imports,class",indent=0,title="@ConfigurationProperties Example"]

<1> The ann:context.annotation.ConfigurationProperties[] annotation takes the configuration prefix and is declared on an interface
<2> You can use ann:core.bind.annotation.Bindable[] to set a default value
<3> Validation annotations can also be used
<4> You can also specify references to other ann:context.annotation.ConfigurationProperties[] beans.
<5> You can nest immutable configuration
<6> Optional configuration can be indicated by returning an `Optional` or specifying `@Nullable`

In this case the Micronaut framework provides a compile-time implementation that delegates all getters to call the `getProperty(..)` method of the api:context.env.Environment[] interface.

This has the advantage that if the application configuration is <<refreshable, refreshed>> (for example by invoking the `/refresh` endpoint), the injected interface automatically sees the new values.

NOTE: If you try to specify any other abstract method other than a getter, a compilation error occurs (default methods are supported).

Another way to implement immutable configuration is to define a class and use the ann:context.annotation.ConfigurationInject[] annotation on a constructor of a ann:context.annotation.ConfigurationProperties[] or ann:context.annotation.EachProperty[] bean.

For example:

snippet::io.micronaut.docs.config.immutable.EngineConfig[tags="imports,class",indent=0,title="@ConfigurationProperties Example"]

<1> The ann:context.annotation.ConfigurationProperties[] annotation takes the configuration prefix
<2> The ann:context.annotation.ConfigurationInject[] annotation is defined on the constructor
<3> You can use ann:core.bind.annotation.Bindable[] to set a default value
<4> Validation annotations can be used too
<5> You can nest immutable configuration
<6> Optional configuration can be indicated with `@Nullable`

The ann:context.annotation.ConfigurationInject[] annotation provides a hint to the Micronaut framework to prioritize binding values from configuration instead of injecting beans.

NOTE: Using this approach, to make the configuration refreshable, add the ann:runtime.context.scope.Refreshable[] annotation to the class as well. This allows the bean to be re-created in the case of a <<refreshable,runtime configuration refresh event>>.

There are a few exceptions to this rule. Micronaut framework will not perform configuration binding for a parameter if any of these conditions is met:

* The parameter is annotated with `@Value` (explicit binding)
* The parameter is annotated with `@Property` (explicit binding)
* The parameter is annotated with `@Parameter` (parameterized bean handling)
* The parameter is annotated with `@Inject` (generic bean injection)
* The type of the parameter is annotated with a bean scope (such as `@Singleton`)

Once you have prepared a type-safe configuration it can be injected into your beans like any other bean:

snippet::io.micronaut.docs.config.immutable.Engine[tags="class",indent=0,title="@ConfigurationProperties Dependency Injection"]

<1> Inject the `EngineConfig` bean
<2> Use the configuration properties

Configuration values can then be supplied when running the application. For example:

snippet::io.micronaut.docs.config.immutable.VehicleSpec[tags="start",indent=0,title="Supply Configuration"]

The above example prints: `"Ford Engine Starting V8 [rodLength=7B.0]"`

==== Using Java Record Classes to define immutable configuration

For Java language applications, it's also possible to use https://docs.oracle.com/en/java/javase/17/language/records.html[Java Record Classes] for immutable configuration with ann:context.annotation.ConfigurationProperties[]. For example:

snippet::io.micronaut.docs.config.immutable.ValueAddedTaxConfiguration[tags="imports,class",title="Java Record Example"]

<1> The `percentage` field defines a configuration property for "vat"

NOTE: From a performance perspective Java records are better than interfaces.

== Customizing accessors

As already explained in <<configurationPropertiesAccessorsStyle, Change accessors style>>, it is also possible to customize the accessors when creating immutable configuration properties:

[source, java]
----
import io.micronaut.context.annotation.ConfigurationProperties;
import io.micronaut.core.annotation.AccessorsStyle;
import io.micronaut.core.bind.annotation.Bindable;

import jakarta.validation.constraints.Min;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import java.util.Optional;

@ConfigurationProperties("my.engine") // <1>
@AccessorsStyle(readPrefixes = "read") // <2>
public interface EngineConfigAccessors {

    @Bindable(defaultValue = "Ford")
    @NotBlank
    String readManufacturer(); // <3>

    @Min(1L)
    int readCylinders(); // <3>

    @NotNull
    CrankShaft readCrankShaft(); // <3>

    @ConfigurationProperties("crank-shaft")
    @AccessorsStyle(readPrefixes = "read") // <4>
    interface CrankShaft {
        Optional<Double> readRodLength(); // <5>
    }
}
----
<1> The ann:context.annotation.ConfigurationProperties[] annotation takes the configuration prefix and is declared on an interface
<2> The ann:core.annotation.AccessorsStyle[] annotation defines the `readPrefixes` as `read`.
<3> The getters are all prefixed with `read`.
<4> Nested immutable configuration can also be annotated with ann:context.annotation.ConfigurationProperties[].
<5> The getter is prefixed with `read`.
