Additional api:io.micronaut.context.env.PropertySource[] instances can be added to the environment prior to initializing the api:context.ApplicationContext[].

snippet::io.micronaut.docs.context.env.EnvironmentSpec[tags="envProps",indent=0,title="Initializing the Environment"]

The link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource.of] method can be used to create a `ProperySource` from a map of values.

Alternatively one can register a link:{api}/io/micronaut/context/env/PropertySourceLoader.html[PropertySourceLoader] by creating a `META-INF/services/io.micronaut.context.env.PropertySourceLoader` containing a reference to the class name of the `PropertySourceLoader`.

=== Included PropertySource Loaders

Micronaut by default contains `PropertySourceLoader` implementations that load properties from the given locations and priority:

1. Command line arguments
2. Properties from `SPRING_APPLICATION_JSON` (for Spring compatibility)
3. Properties from `MICRONAUT_APPLICATION_JSON`
4. Java System Properties
5. OS environment variables
6. Configuration files loaded in order from the system property 'micronaut.config.files' or the environment variable `MICRONAUT_CONFIG_FILES`. The value can be a comma separated list of paths with the last file have precedence. The files can be referenced from the file system as a path or the classpath with a `classpath:` prefix.
7. Enviroment-specific properties from `application-{environment}.{extension}`
8. Application-specific properties from `application.{extension}`

TIP: `.properties`, `.json`, `.yml` are supported out of the box. For Groovy users `.groovy` is supported as well.

CAUTION: Custom configuration options that are camel-case (e.g., `fooBar`) may behave unexpectedly when evaluating against the property list above. Specifically, there is no way for an OS environment variable to specify a value for an option named `fooBar`. Micronaut would translate `FOO_BAR` to `foo_bar`, `foo.bar`, but not `fooBar`. Similarly it would translate `FOOBAR` to `foobar` but not `fooBar`. 

=== Property Value Placeholders

Micronaut includes a property placeholder syntax which can be used to reference configuration properties both within configuration values and with any Micronaut annotation (see ann:io.micronaut.context.annotation.Value[] and the section on <<valueAnnotation,Configuration Injection>>).

TIP: Programmatic usage is also possible via the api:io.micronaut.context.env.PropertyPlaceholderResolver[] interface.

The basic syntax is to wrap a reference to a property in `${...}`. For example in `application.yml`:

.Defining Property Placeholders
[source,yaml]
----
myapp:
    endpoint: http://${micronaut.server.host}:${micronaut.server.port}/foo
----

The above example embeds references to the `micronaut.server.host` and `micronaut.server.port` properties.

You can specify default values by defining a value after the `:` character. For example:

.Using Default Values
[source,yaml]
----
myapp:
    endpoint: http://${micronaut.server.host:localhost}:${micronaut.server.port:8080}/foo
----

The above example will default to `localhost` and port `8080` if no value is found (rather than throwing an exception). Note that if default value itself contains a `:` character, you should escape it using back ticks:

.Using Backticks
[source,yaml]
----
myapp:
    endpoint: ${server.address:`http://localhost:8080`}/foo
----

The above example tries to read a `server.address` property otherwise fallbacks back to `http://localhost:8080`, since the address has a `:` character we have to escape it with back ticks.

=== Property Value Binding

Note that these property references should always be in kebab case (lowercase and hyphen-separated) when placing references in code or in placeholder values. In other words you should use for example `micronaut.server.default-charset` and not `micronaut.server.defaultCharset`.

Micronaut still allows specifying the latter in configuration, but normalizes the properties into kebab case form to optimize memory consumption and reduce complexity when resolving properties. The following table summarizes how properties are normalized from different sources:

.Property Value Normalization
|===
|Configuration Value |Resulting Properties|Property Source

|`myApp.myStuff` | `my-app.my-stuff` | Properties, YAML etc.

|`my-app.myStuff` | `my-app.my-stuff` | Properties, YAML etc.
|`myApp.my-stuff` | `my-app.my-stuff` | Properties, YAML etc.

|`MYAPP_MYSTUFF` | `myapp.mystuff`, `myapp-mystuff` | Environment Variable

|`MY_APP_MY_STUFF` | `my.app.my.stuff`, `my.app.my-stuff`, `my.app-my.stuff`, `my.app-my-stuff`, `my-app.my.stuff`, `my-app.my-stuff`, `my-app-my.stuff`, `my-app-my-stuff`  | Environment Variable
|===

Environment variables are given special treatment to allow the definition of environment variables to be more flexible.

IMPORTANT: Because the number of properties generated is exponential based on the number of `_` characters in the environment variable, it is recommended to refine which, if any, environment variables are included in configuration if the number of environment variables with a large number of underscores is high.

To control how environment properties participate in configuration, call the respective methods on the `Micronaut` builder.

snippet::io.micronaut.docs.context.Application[tags="imports,class",title="Application class"]

NOTE: The configuration above does not have any impact on property placeholders. It is still possible to reference an environment variable in a placeholder regardless of whether environment configuration is disabled, or even if the specific property is explicitly excluded.

=== Using Random Properties

You can use `random` values by using the following properties.  These can be used in configuration files as variables like the following.

[source,yaml]
----
micronaut:
  application:
    name: myapplication
    instance:
      id: ${random.shortuuid}
----

.Random Values
|===
|Property |Value

|random.port
|An available random port number

|random.int
|Random int

|random.integer
|Random int

|random.long
|Random long

|random.float
|Random float

|random.shortuuid
|Random UUID of only 10 chars in length (Note: As this isn't full UUID, collision COULD occur)

|random.uuid
|Random UUID with dashes

|random.uuid2
|Random UUID without dashes
|===

=== Fail Fast Property Injection

For beans that inject required properties, the injection and potential failure will not occur until the bean is requested. To verify at startup that the properties exist and can be injected, the bean can be annotated with ann:io.micronaut.context.annotation.Context[]. Context scoped beans will be injected at startup time and thus will fail at startup time if any required properties are missing or could not be converted to the required type.

IMPORTANT: To maintain a fast startup time, it is recommended to use this feature as sparingly as possible.

=== Controlling Log Levels with Properties

Log levels can be configured via properties defined in `application.yml` (and environment variables) with the `log.level` prefix:

[source,yaml]
----
logger:
    levels:
        foo.bar: ERROR
----

Note that the ability to control log levels via config is controlled via the api:logging.LoggingSystem[] interface. Currently Micronaut ships with a single implementation that allows setting log levels for the Logback library. If another library is chosen you should provide a bean that implements this interface.
