Additional link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource] instances can be added to the environment prior to initializing the link:{api}/io/micronaut/context/ApplicationContext.html[ApplicationContext].

.Initializing the Environment
[source,java]
----
include::{testsjava}/env/EnvironmentTest.java[tags=envProps, indent=0]
----

The link:{api}/io/micronaut/context/env/PropertySource.html[PropertySource.of] method can be used to create a `ProperySource` from a map of values.

Alternatively one can register a link:{api}/io/micronaut/context/env/PropertySourceLoader.html[PropertySourceLoader] by creating a `META-INF/services/io.micronaut.context.env.PropertySourceLoader` containg a reference to the class name of the `PropertySourceLoader`.

Micronaut by default contains `PropertySourceLoader` implementations that load properties from the given locations and priority:

* Command line arguments
* Properties from `SPRING_APPLICATION_JSON` (for Spring compatibility)
* Properties from `MICRONAUT_APPLICATION_JSON`
* Java System Properties
* OS environment variables
* Enviroment-specific properties from `application-{environment}.{extension}` (Either `.properties`, `.json`, `.yml` or `.groovy` property formats supported)
* Application-specific properties from `application.{extension}` (Either `.properties`, `.json`, `.yml` or `.groovy` property formats supported)


