Like Spring Boot and Grails, you can inject configuration values into beans with Micronaut using the link:{api}/io/micronaut/context/annotation/Value.html[Value] annotation.

For example:

.@Value Example
[source,groovy]
----
include::{testsdir}/config/value/EngineImpl.groovy[tags=imports, indent=0]

include::{testsdir}/config/value/EngineImpl.groovy[tags=class, indent=0]
----

<1> The `@Value` annotation accepts a string that is the name of a property to be used as the source for the value. A default value can be optionally supplied after the colon.
<2> The injected value can then be used within code.

Unlike the aforementioned frameworks, Micronaut will use ASM to generate reflection free bytecode to optimize startup time and value injection performance.

Note that there is nothing special about `@Value` itself regarding the resolution of property value placeholders. Due to Micronaut's extensive support for annotation metadata you can in fact use property placeholder expressions on any annotation. For example, to make the path of a `@Controller` configurable you can do:

[source,java]
----
@Controller("${hello.controller.path:/hello}")
class HelloController {
    ...
}
----

In the above case if `hello.controller.path` is specified in configuration then the controller will be mapped to the path specified otherwise it will be mapped to `/hello`.

NOTE: If the default value contains a colon then you will need to escape the value with back ticks. For example: ``@Value("${hello.url:`http://hello.com`}")``
