The ann:http.client.Client[] annotation can also handle streaming HTTP responses.

=== Streaming JSON with @Client

For example, to write a client that streams data from the controller defined in the <<clientStreaming, JSON Streaming>> section of the documentation, you can define a client that returns an unbound rs:Publisher[] such as a RxJava rx:Flowable[] or Reactor `Flux`:

snippet::io.micronaut.docs.streaming.HeadlineClient[tags="imports, class, endclass", indent=0, title="HeadlineClient.java"]

<1> The `@Get` method processes responses of type `APPLICATION_JSON_STREAM`
<2> The return type is rx:Flowable[]

The following example shows how the previously defined `HeadlineClient` can be invoked from a test:

snippet::io.micronaut.docs.streaming.HeadlineControllerSpec[tags="streamingClient", indent=0, title="Streaming HeadlineClient"]

<1> The client is retrieved from the api:context.ApplicationContext[]
<2> The `firstElement` method returns the first emitted item from the rx:Flowable[] as a rx:Maybe[].
<3> The `blockingGet()` method retrieves the result in the test.

=== Streaming Clients and Response Types

The example defined in the previous section expects the server to respond with a stream of JSON objects, and the content type to be `application/x-json-stream`. For example:

.A JSON Stream
[source,json]
----
{"title":"The Stand"}
{"title":"The Shining"}
----

The reason for this is simple; a sequence of JSON object is not, in fact, valid JSON and hence the response content type cannot be `application/json`. For the JSON to be valid it would have to return an array:

.A JSON Array
[source,json]
----
[
    {"title":"The Stand"},
    {"title":"The Shining"}
]
----

Micronaut's client does however support streaming of both individual JSON objects via `application/x-json-stream` and also JSON arrays defined with `application/json`.

If the server returns `application/json` and a non-single rs:Publisher[] is returned (such as a rx:Flowable[] or a Reactor `Flux`), the client streams the array elements as they become available.

=== Streaming Clients and Read Timeout

When streaming responses from servers, the underlying HTTP client will not apply the default `readTimeout` setting (which defaults to 10 seconds) of the api:http.client.HttpClientConfiguration[] since the delay between reads for streaming responses may differ from normal reads.

Instead, the `read-idle-timeout` setting (which defaults to 5 minutes) dictates when to close a connection after it becomes idle.

If you stream data from a server that defines a longer delay than 5 minutes between items, you should adjust `readIdleTimeout`. The following configuration in `application.yml` demonstrates how:

.Adjusting the readIdleTimeout
[source,yaml]
----
micronaut:
  http:
    client:
      read-idle-timeout: 10m
----

The above example sets the `readIdleTimeout` to ten minutes.

=== Streaming Server Sent Events

Micronaut features a native client for Server Sent Events (SSE) defined by the interface api:http.client.sse.SseClient[].

You can use this client to stream SSE events from any server that emits them.

NOTE: Although SSE streams are typically consumed by a browser `EventSource`, there are cases where you may wish to consume an SSE stream via api:http.client.sse.SseClient[], such as in unit tests or when a Micronaut service acts as a gateway for another service.

The ann:http.client.Client[] annotation also supports consuming SSE streams. For example, consider the following controller method that produces a stream of SSE events:

snippet::io.micronaut.docs.sse.HeadlineController[tags="streaming", indent=0, title="SSE Controller"]

<1> The controller defines a ann:http.annotation.Get[] annotation that produces a `MediaType.TEXT_EVENT_STREAM`
<2> The method uses Reactor to emit a `Headline` object
<3> The `repeat` method repeats the emission 100 times
<4> With a delay of one second between each

Notice that the return type of the controller is also api:http.sse.Event[] and that the `Event.of` method creates events to stream to the client.

To define a client that consumes the events, define a method that processes `MediaType.TEXT_EVENT_STREAM`:

snippet::io.micronaut.docs.sse.HeadlineClient[tags="class", indent=0, title="SSE Client"]

The generic type of the `Flux` or `Flowable` can be either an api:http.sse.Event[], in which case you will receive the full event object, or a POJO, in which case you will receive only the data contained within the event converted from JSON.
