The previous example presented a trivial example that uses the parameters of a method to represent the body of a `POST` request:

.PetOperations.java
[source,java]
----
include::{testsclient}/annotation/PetOperations.java[tags=save, indent=0]
----

////
NOTE: for some weird reason every time I try to replace this with a snippet it creates the following error

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':publishGuide'.
> org.jruby.exceptions.RaiseException: (TypeError) cannot convert instance of class org.jruby.RubyObject to interface org.asciidoctor.ast.DocumentRuby

I found a closed issue on github that sounds similar https://github.com/asciidoctor/asciidoctorj/issues/267 but not really certain
////

The `save` method when called will perform an HTTP `POST` with the following JSON by default:

.Example Produced JSON
[source,json]
----
{"name":"Dino", "age":10}
----

You may however want to customize what is sent as the body, the parameters, URI variables and so on. The ann:http.client.annotation.Client[] annotation is very flexible in this regard and supports the same pkg:http.annotation[HTTP Annotations] as Micronaut's HTTP server.

For example, the following defines a URI template and the `name` parameter is used as part of the URI template, whilst ann:http.annotation.Body[] is used to declare that the contents to send to the server are represented by the `Pet` POJO:

.PetOperations.java
[source,java]
----
@Post("/{name}")
Single<Pet> save(
    @NotBlank String name, // <1>
    @Body @Valid Pet pet) // <2>
----

<1> The name parameter, included as part of the URI, and declared `@NotBlank`
<2> The `pet` parameter, used to encode the body and declared `@Valid`

The following table summarizes the parameter annotations, their purpose, and provides an example:

.Parameter Binding Annotations
|===
|Annotation|Description |Example

|ann:http.annotation.Body[]
|Allows to specify the parameter that is the body of the request
|`@Body String body`

|ann:http.annotation.CookieValue[]
|Allows specifying parameters that should be sent as cookies
|`@CookieValue String myCookie`

|ann:http.annotation.Header[]
|Allows specifying parameters that should be sent as HTTP headers
|`@Header String requestId`

|ann:http.annotation.QueryValue[]
|Allows customizing the name of the URI parameter to bind from
|`@QueryValue("userAge") Integer age`

|ann:http.annotation.PathVariable[]
|Used to bind a parameter exclusively from a <<routing, Path Variable>>.
|`@PathVariable Long id`

|ann:http.annotation.RequestAttribute[]
|Allows specifying parameters that should be set as request attributes
|`@RequestAttribute Integer locationId`

|===

IMPORTANT: Always use ann:http.annotation.Produces[] or ann:http.annotation.Consumes[] instead of supplying a header for `Content-Type` or `Accept`.

==== Type Based Binding Parameters

Some parameters are recognized by their type instead of their annotation. The following table summarizes the parameter types, their purpose, and provides an example:

|===
|Type |Description |Example

|api:http.BasicAuth[]
|Allows binding of basic authorization credentials
|`BasicAuth basicAuth`

|===

==== Custom Binding

The api:http.client.bind.ClientArgumentRequestBinder[] API is what is responsible for binding client arguments to the request. Custom binder classes registered as beans will automatically be used during the binding process. Annotation based binders are searched for first, with type based binders being searched if a binder was not found.

IMPORTANT: This is an experimental feature in 2.1 and subject to change! One limitation of binding is that binders may not manipulate or set the request URI because it can be a combination of many arguments.

===== Binding By Annotation

To control how an argument is bound to the request based on the annotation applied to the argument, create a bean of type api:http.client.bind.AnnotatedClientArgumentRequestBinder[]. Any custom annotations must be annotated with ann:core.bind.annotation.Bindable[].

In this example, see the following client:

snippet::io.micronaut.docs.http.client.bind.annotation.MetadataClient[tags="clazz", indent=0, title="Client With @Metadata Argument"]

The argument is annotated with the following annotation:

snippet::io.micronaut.docs.http.client.bind.annotation.Metadata[tags="clazz", indent=0, title="@Metadata Annotation"]

Without any additional code, the client will attempt to convert the metadata to a string and append it as a query parameter. In this case that isn't the desired effect so a custom binder must be created.

The following binder will handle arguments passed to clients that are annotated with the `@Metadata` annotation and then mutate the request to contain the desired headers. The implementation could be modified to accept more types of data other than `Map`.

snippet::io.micronaut.docs.http.client.bind.annotation.MetadataClientArgumentBinder[tags="clazz", indent=0, title="Annotation Argument Binder"]

===== Binding By Type

To bind to the request based on the type of the argument, create a bean of type api:http.client.bind.TypedClientArgumentRequestBinder[].

In this example, see the following client:

snippet::io.micronaut.docs.http.client.bind.type.MetadataClient[tags="clazz", indent=0, title="Client With Metadata Argument"]

Without any additional code, the client will attempt to convert the metadata to a string and append it as a query parameter. In this case that isn't the desired effect so a custom binder must be created.

The following binder will handle arguments passed to clients that are of the `Metadata` type and then mutate the request to contain the desired headers.

snippet::io.micronaut.docs.http.client.bind.type.MetadataClientArgumentBinder[tags="clazz", indent=0, title="Typed Argument Binder"]
