Customizing the request headers deserves special mention as there are several ways that can be accomplished.

== Populating Headers Using Configuration

The ann:http.annotation.Header[] annotation can be declared at the type level and is repeatable such that it is possible to drive the request headers sent via configuration using annotation metadata.

The following example serves to illustrate this:

snippet::io.micronaut.docs.annotation.headers.PetClient[tags="class", indent=0, title="Defining Headers via Configuration"]

The above example defines a ann:http.annotation.Header[] annotation on the `PetClient` interface that reads the `pet.client.id` property using property placeholder configuration.

Then set the following in your configuration file (e.g. `application.yml`) to populate the value:

.Configuring Headers
[configuration]
----
pet:
  client:
    id: foo
----

Alternatively you can supply a `PET_CLIENT_ID` environment variable and the value will be populated.

== Populating Headers using a Client Filter

Alternatively, to dynamically populate headers, another option is to use a <<clientFilter, Client Filter>>.

For more information on writing client filters see the <<clientFilter, Client Filters>> section of the guide.
