[TIP]
.Using the CLI
====
If you create your project using the Micronaut CLI, supply the `netflix-hystrix` feature to configure Hystrix in your project:
----
$ mn create-app my-app --features netflix-hystrix
----
====

https://github.com/Netflix/Hystrix[Netflix Hystrix] is a fault tolerance library developed by the Netflix team and is designed to improve resilience of interprocess communication.

Micronaut integrates with Hystrix through the `netflix-hystrix` module, which you can add to your build:

dependency:io.micronaut.netflix:micronaut-netflix-hystrix[]

== Using the @HystrixCommand Annotation

With the above dependency declared you can annotate any method (including methods defined on `@Client` interfaces) with the link:{micronauthystrixapi}/annotation.HystrixCommand.html[HystrixCommand] annotation, and method's execution will be wrapped in a Hystrix command. For example:

.Using @HystrixCommand
[source,groovy]
----
@HystrixCommand
String hello(String name) {
    return "Hello $name"
}
----

NOTE: This works for reactive return types such as reactor:Flux[], and the reactive type will be wrapped in a `HystrixObservableCommand`.

The link:{micronauthystrixapi}/annotation.HystrixCommand.html[HystrixCommand] annotation also integrates with Micronaut's support for <<retry, Retry Advice>> and <<clientFallback, Fallbacks>>

TIP: For information on how to customize the Hystrix thread pool, group, and properties, see the Javadoc for link:{micronauthystrixapi}/annotation.HystrixCommand.html[HystrixCommand].

== Enabling Hystrix Stream and Dashboard

You can enable a Server Sent Event stream to feed into the https://github.com/Netflix-Skunkworks/hystrix-dashboard[Hystrix Dashboard] by setting the `hystrix.stream.enabled` setting to `true` in `application.yml`:

.Enabling Hystrix Stream
[source,yaml]
----
hystrix:
  stream:
    enabled: true
----

This exposes a `/hystrix.stream` endpoint with the format the https://github.com/Netflix-Skunkworks/hystrix-dashboard[Hystrix Dashboard] expects.
