[TIP]
.Using the CLI
====
If you are creating your project using the Micronaut CLI, supply the `netflix-hystrix` feature to configure Hystrix in your project:
----
$ mn create-app my-app --features netflix-hystrix
----
====

https://github.com/Netflix/Hystrix[Netflix Hystrix] is a fault tolerance library developed by the Netflix team and designed to improve resilience of inter process communication.

Micronaut features integration with Hystrix through the `netflix-hystrix` module, which you can add to your `build.gradle` or `pom.xml`:

dependency:io.micronaut.netflix:micronaut-netflix-hystrix[]

== Using the @HystrixCommand Annotation

With the above dependency declared you can annotate any method (including methods defined on `@Client` interfaces) with the ann:configuration.hystrix.annotation.HystrixCommand[] annotation and it will wrap the methods execution in a Hystrix command. For example:

.Using @HystrixCommand
[source,groovy]
----
@HystrixCommand
String hello(String name) {
    return "Hello $name"
}
----

NOTE: This works for reactive return types such as rx:Flowable[] etc. as well and the reactive type will be wrapped in a `HystrixObservableCommand`.

The ann:configuration.hystrix.annotation.HystrixCommand[] annotation also integrates with Micronauts support for <<retry, Retry Advice>> and <<clientFallback, Fallbacks>>

TIP: For information on how to customize the Hystrix thread pool, group and properties see the javadoc for ann:configuration.hystrix.annotation.HystrixCommand[].

== Enabling Hystrix Stream & Dashboard

You can enable a Server Sent Event stream to feed into the https://github.com/Netflix-Skunkworks/hystrix-dashboard[Hystrix Dashboard] by setting the `hystrix.stream.enabled` setting to `true` in `application.yml`:

.Enabling Hystrix Stream
[source,yaml]
----
hystrix:
    stream:
        enabled: true
----

This exposes a `/hystrix.stream` endpoint with the format the https://github.com/Netflix-Skunkworks/hystrix-dashboard[Hystrix Dashboard] expects.