To run your function as a web application as described in this section, you will need the `function-web` dependency on your classpath. For example, in `build.gradle`

.build.gradle
[source,groovy]
----
dependencies {
    ...
    runtime "io.micronaut:function-web"
    runtime "io.micronaut:http-server-netty" //<1>
    ...
}
----
<1> In order to run the function as a web application, you will need an HTTP server, such as the `http-server-netty` dependency

Once the dependencies have been added to the project, you can run the function via an `Application` class.

.Example Application class
[source,java]
----
include::{testsuite}/server/intro/Application.java[tags=imports, indent=0]

include::{testsuite}/server/intro/Application.java[tags=class, indent=0]
----

You can now make requests against the function with a REST client.

----
$ curl -X GET http://localhost:8080/hello
----

The URI mapped to is defined by the either the value of the ann:function.FunctionBean[] annotation for Java or, in the case of Groovy, the name of the function defined in the function script. The following tables summarizes the convention:


.Function URI Mapping with @FunctionBean
|===
|Annotation|URI

|`@FunctionBean("hello")` | `/hello`
|`@FunctionBean("helloWorld")` | `/helloWorld`
|`@FunctionBean("hello-world")` | `/hello-world`

|===

.Function URI Mapping with Groovy Function Script
|===
|Method Name|URI

|`hello` | `/hello`
|`helloWorld` | `/hello-world`

|===

Functions that only return a value are mapped to HTTP `GET` requests, whilst functions that accept an input require an HTTP `POST`.

In addition, the function will be registered by the configured <<serviceDiscovery, Service Discovery>> provider, and be made accessible to clients via the ann:function.client.FunctionClient[] annotation.

TIP: For further information on the use of `@FunctionClient`, please see <<callingFunctions, Calling Functions>>.

== Testing Functions

Functions can also be run as part of the Micronaut application context for ease of testing. Similarly to the example above, this approach requires the `function-web` and an HTTP server dependency on the classpath for tests. For example, in `build.gradle`:

.build.gradle
[source,groovy]
----
dependencies {
    ...
    testRuntime "io.micronaut:function-web"
    testRuntime "io.micronaut:http-server-netty" //<1>
    ...
}
----
<1> In order to run the function as a web application, you will need an HTTP server, such as the `http-server-netty` dependency

Create a ann:function.client.FunctionClient[] interface as shown below:

.MathClient.groovy
[source,groovy]
----
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=import, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=beginFunctionClient, indent=0]

include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=functionMax, indent=4]
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=functionRnd, indent=4]
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=endFunctionClient, indent=0]
----

TIP: For further information on the use of `@FunctionClient`, please see <<callingFunctions, Calling Functions>>.

Now you can start up the Micronaut application and access your function via the client interface in your test.

[source,java]
----
include::{testsfunctionclient}/LocalFunctionInvokeSpec.groovy[tags=invokeLocalFunction, indent=0]
----
