plugins {
    id "io.micronaut.build.internal.convention-library"
}

import java.time.Duration


dependencies {
	annotationProcessor projects.micronautInjectJava
    api projects.micronautHttp
    api projects.micronautHttpClientCore
    api projects.micronautInject
    api projects.micronautAop

    implementation libs.managed.reactor

    testImplementation projects.micronautInjectGroovy
}

tasks.named("test") {
    timeout = Duration.ofMinutes(5)
}
