TIP: Read http://guides.micronaut.io/micronaut-function-aws-lambda/guide/index.html[Micronaut Functions deployed in AWS Lambda] guide for a step by step tutorial.

For Java & Kotlin functions, support for http://aws.amazon.com[AWS Lambda] can be enabled by adding the `function-aws` dependency to your classpath.

dependency:micronaut-function-aws[]

For Groovy functions, the `function-groovy` dependency is sufficient for AWS Lambda support.

dependency:micronaut-function-groovy[]

== Configuration

Configuration properties specific to AWS Lambda environments can be supplied in an `application-aws` configuration file in `src/main/resources`.

.application-aws.yml
[source,yaml]
----
production:
    property: 44
----

== Manual Deployment

You can deploy your function to AWS Lambda manually by building and uploading an executable JAR file. Various build plugins offer this capability.

=== Gradle Shadow plugin

The https://plugins.gradle.org/plugin/com.github.johnrengelman.shadow[Gradle Shadow] plugin provides a `shadowJar` task to generate a self-contained executable JAR file, which is suitable for AWS Lambda deployments.

[source.multi-language-sample,gradle-groovy,title="Example gradle file"]
----
buildscript {
    repositories {
        maven { url "https://plugins.gradle.org/m2/" } //<1>
    }
    dependencies {
        classpath "com.github.jengelman.gradle.plugins:shadow:2.0.4"
        // ...
    }
}

apply plugin:"com.github.johnrengelman.shadow"

shadowJar {
    mergeServiceFiles()
}

----

[source.multi-language-sample,gradle-kotlin]
----
buildscript {
    repositories {
        maven("https://plugins.gradle.org/m2/") //<1>
    }
    dependencies {
        classpath("com.github.jengelman.gradle.plugins:shadow:2.0.4")
        // ...
    }
}

apply plugin = "com.github.johnrengelman.shadow"

shadowJar {
    mergeServiceFiles()
}
----
<1> The Gradle Shadow plugin is hosted in the `http://plugins.gradle.org` repository

The executable JAR file can now be built using the `shadowJar` task.

[source,bash]
----
$ ./gradlew shadowJar
----

=== Maven Shade plugin

The https://maven.apache.org/plugins/maven-shade-plugin/[Maven Shade] plugin will generate an executable JAR file for Maven projects. For further details, consult the https://docs.aws.amazon.com/lambda/latest/dg/java-create-jar-pkg-maven-no-ide.html[AWS Lambda Documentation.]

.Example pom.xml
[source,xml]
----
<project>

    <build>
        <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-shade-plugin</artifactId>
                <version>3.1.0</version>
                <executions>
                    <execution>
                        <phase>package</phase>
                        <goals>
                            <goal>shade</goal>
                        </goals>
                        <configuration>
                            <transformers>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ManifestResourceTransformer">
                                    <mainClass>${exec.mainClass}</mainClass>
                                </transformer>
                                <transformer implementation="org.apache.maven.plugins.shade.resource.ServicesResourceTransformer"/>
                            </transformers>
                        </configuration>
                    </execution>
                </executions>
            </plugin>
        </plugins>
    </build>
</project>
----

The executable JAR file can now be built using the `package` phase.

[source,bash]
----
$ ./mvnw package
----


== Gradle AWS Plugin

For Gradle projects, deployment can be made even more straightforward using the https://github.com/classmethod/gradle-aws-plugin[Gradle AWS Plugin]. This plugin provides a `deploy` task which can push your function to AWS Lambda directly, as well as a `AWSLambdaInvokeTask` which can be used to invoke your function when it is deployed.

.Example build.gradle
[source.multi-language-sample,gradle-groovy,title="Example gradle file]
----
import com.amazonaws.services.lambda.model.InvocationType
import jp.classmethod.aws.gradle.lambda.AWSLambdaInvokeTask
import jp.classmethod.aws.gradle.lambda.AWSLambdaMigrateFunctionTask
import com.amazonaws.services.lambda.model.Runtime

buildscript {
    repositories {
        ...
        maven { url "https://plugins.gradle.org/m2/" } //<1>
    }
    dependencies {
        classpath "jp.classmethod.aws:gradle-aws-plugin:0.22"
    }
}

apply plugin: 'jp.classmethod.aws.lambda' //<2>

...
task deploy(type: AWSLambdaMigrateFunctionTask, dependsOn: shadowJar) {
    functionName = "hello-world"
    handler = "example.HelloWorldFunction::hello"
    role = "arn:aws:iam::${aws.accountId}:role/lambda_basic_execution" //<3>
    runtime = Runtime.Java8
    zipFile = shadowJar.archivePath
    memorySize = 256
    timeout = 60
}

task invoke(type: AWSLambdaInvokeTask) {
    functionName = "hello-world"
    invocationType = InvocationType.RequestResponse
    payload = '{"name":"Fred"}'
    doLast {
        println "Lambda function result: " + new String(invokeResult.payload.array(), "UTF-8")
    }
}
----

[source.multi-language-sample,gradle-kotlin]
----
import com.amazonaws.services.lambda.model.InvocationType
import jp.classmethod.aws.gradle.lambda.AWSLambdaInvokeTask
import jp.classmethod.aws.gradle.lambda.AWSLambdaMigrateFunctionTask
import com.amazonaws.services.lambda.model.Runtime

buildscript {
    repositories {
        ...
        maven("https://plugins.gradle.org/m2/") //<1>
    }
    dependencies {
        classpath("jp.classmethod.aws:gradle-aws-plugin:0.22")
    }
}

apply(plugin = "jp.classmethod.aws.lambda") //<2>

// ...
tasks.register<AWSLambdaMigrateFunctionTask>("deploy") {
    dependsOn = shadowJar
    functionName = "hello-world"
    handler = "example.HelloWorldFunction::hello"
    role = "arn:aws:iam::${aws.accountId}:role/lambda_basic_execution" //<3>
    runtime = Runtime.Java8
    zipFile = shadowJar.archivePath
    memorySize = 256
    timeout = 60
}

tasks.register<AWSLambdaInvokeTask>("invoke") {
    functionName = "hello-world"
    invocationType = InvocationType.RequestResponse
    payload = "{"name" ="Fred"}"
    doLast {
        println "Lambda function result = " + new String(invokeResult.payload.array(), "UTF-8")
    }
}
----
<1> The AWS Gradle plugin is hosted from the `https://plugins.gradle.org` repository
<2> Apply the Gradle AWS plugin
<3> The Gradle AWS plugin will resolve your AWS credentials from `.aws/credentials` file, which is the default location used by the https://aws.amazon.com/cli/[AWS CLI] to set up your environment

Note that the value of the `handler` property of the `deploy` task should be either:

* In this case of Java or Kotlin: `io.micronaut.function.aws.MicronautRequestStreamHandler`
* In the case of Groovy function definitions: A reference to the function (in the above case `example.HelloWorldFunction::hello`)

The reason for this is the `function-groovy` dependency applies additional code transformations to make it possible to reference the function directly.

With the above build configuration, the function can be deployed to AWS Lambda using the `deploy` task.

[source,bash]
----
$ ./gradlew deploy
----

The deployed function can then be invoked.

[source,bash]
----
$ ./gradlew invoke
Hello, Fred
----

Consult the https://github.com/classmethod/gradle-aws-plugin[Gradle AWS plugin documentation] for more details on the use of the plugin.