All the examples up until now have used the same HTTP method i.e `GET`. The api:http.HttpRequest[] interface has factory methods for all the different HTTP methods. The following table summarizes the available methods:

.HttpRequest Factory Methods
|===
|Method |Description|Allows Body

| api:http.HttpRequest.GET(java.lang.String)[]
| Constructs an HTTP `GET` request
| `false`

| api:http.HttpRequest.OPTIONS(java.lang.String)[]
| Constructs an HTTP `OPTIONS` request
| `false`

| api:http.HttpRequest.HEAD(java.lang.String)[]
| Constructs an HTTP `HEAD` request
| `false`

| api:http.HttpRequest.POST(java.lang.String,T)[]
| Constructs an HTTP `POST` request
| `true`

| api:http.HttpRequest.PUT(java.lang.String,T)[]
| Constructs an HTTP `PUT` request
| `true`

| api:http.HttpRequest.PATCH(java.lang.String,T)[]
| Constructs an HTTP `PATCH` request
| `true`

| api:http.HttpRequest.DELETE(java.lang.String)[]
| Constructs an HTTP `DELETE` request
| `true`

|===

A `create` method also exists to construct a request for any api:http.HttpMethod[] type. Since the `POST`, `PUT` and `PATCH` methods require a body, a second argument which is the body object is required.

The following example demonstrates how to send a simply `String` body:

.Sending a `String` body
[source,java]
----
TODO - example showing:
import static HttpRequest.*;
client.exchange(
    POST("/foo/bar", "My Body") <1>
    .contentType(MediaType.TEXT_PLAIN) <2>
).subscribe(response ->
     // handle response
)
----

<1> The `POST` method is used with the first argument being the URI and the second argument the body
<2> The content type is set to `text/plain` (the default content type is `application/json`)

==== Sending JSON

The previous example sends plain text, if you wish send JSON you can simply pass the object you wish to encode as JSON, whether that be a map or a POJO. As long as Jackson is able to encode it.

For example, given a class `Book` that looks like the following:

.Example POJO
[source,java]
----
TODO - example showing:
class Book {
..
}
----

If you create an instance and pass it to the `POST` method:

.Sending a JSON body
[source,java]
----
TODO - example showing:
import static HttpRequest.*;

Book book = new Book("The Stand")
client.exchange(
    POST("/foo/bar", book)
).subscribe(response ->
    // handle response
)
----

Then the following JSON will be sent as the body of the request:

.Resulting JSON
[source,json]
----
{"title":"The Stand"}
----

The JSON itself can be customized however you want using https://github.com/FasterXML/jackson-annotations[Jackson Annotations].

==== Using a URI Template

If some of the properties of the object need to be in the URI being posted to you can use a URI template. For example:

.Sending a JSON body with a URI template
[source,java]
----
TODO - example showing:
import static HttpRequest.*;

Book book = new Book("The Stand")
client.exchange(
    POST("/book/{title}", book)
).subscribe(response ->
    // handle response
)
----

In the above case the `title` property of the passed object will be included in the URI being posted to.

==== Sending Form Data

You can also encode a POJO or a map as regular form data instead of JSON. Just send the content type on the post request:

.Sending a Form Data
[source,java]
----
TODO - example showing:
import static HttpRequest.*;

Book book = new Book("The Stand")
client.exchange(
    POST("/foo/bar", book)
        .contentType(MediaType.APPLICATION_FORM_URLENCODED)
).subscribe(response ->
    // handle response
)
----
