Micronaut's HTTP client includes support for streaming data over HTTP via the api:http.client.RxStreamingHttpClient[] interface which includes methods specific to HTTP streaming including:

.HTTP Streaming Methods
|===
|Method |Description

| `dataStream(HttpRequest<I> request)`
| Returns a stream of data as a rx:Flowable[] of api:core.io.buffer.ByteBuffer[]

| `exchangeStream(HttpRequest<I> request)`
| Returns the api:http.HttpResponse[] wrapping a rx:Flowable[] of api:core.io.buffer.ByteBuffer[]

| `jsonStream(HttpRequest<I> request)`
| Returns a non-blocking stream of JSON objects

|===

In order to do JSON streaming you should on the server side declare a controller method that returns a `application/x-json-stream` of JSON objects. For example:

.Streaming JSON on the Server
[source,java]
----
include::{testsclient}/streaming/HeadlineController.java[tags=imports, indent=0]

include::{testsclient}/streaming/HeadlineController.java[tags=streaming, indent=0]
----

<1> A method `streamHeadlines` is defined that produces `application/x-json-stream`
<2> A rx:Flowable[] is created from a `Callable` function (note no blocking occurs within the function so this is ok, otherwise you would want to `subscribeOn` an I/O thread pool).
<3> The rx:Flowable[] is set to repeat 100 times
<4> The rx:Flowable[] will emit items with a delay of 1 second between each item

NOTE: The server does not have to be written in Micronaut, any server that supports JSON streaming will do.

Then on the client simply subscribe to the stream using `jsonStream` and every time the server emits a JSON object the client will decode and consume it:

.Streaming JSON on the Client
[source,java]
----
include::{testsclient}/streaming/HeadlineControllerTest.java[tags=streaming, indent=0]
----

<1> The `jsonStream` method is used return a rx:Flowable[]
<2> A `CompletableFuture` is used in the example to receive a value, but what you do with each emitted item is application specific
<3> The rs:Subscription[] is used to request a single item. You can use the rs:Subscription[] to regulate back pressure and demand.
<4> The `onNext` method is called when an item is emitted
<5> The `onError` method is called when an error occurs
<6> The `onComplete` method is called when all `Headline` instances have been emitted

Note neither the server or the client in the example above perform blocking I/O at any point.