All the examples up until now have used the same HTTP method i.e `GET`. The api:http.HttpRequest[] interface has factory methods for all the different HTTP methods. The following table summarizes the available methods:

.HttpRequest Factory Methods
|===
|Method |Description|Allows Body

| api:http.HttpRequest.GET(java.lang.String)[]
| Constructs an HTTP `GET` request
| `false`

| api:http.HttpRequest.OPTIONS(java.lang.String)[]
| Constructs an HTTP `OPTIONS` request
| `false`

| api:http.HttpRequest.HEAD(java.lang.String)[]
| Constructs an HTTP `HEAD` request
| `false`

| api:http.HttpRequest.POST(java.lang.String,T)[]
| Constructs an HTTP `POST` request
| `true`

| api:http.HttpRequest.PUT(java.lang.String,T)[]
| Constructs an HTTP `PUT` request
| `true`

| api:http.HttpRequest.PATCH(java.lang.String,T)[]
| Constructs an HTTP `PATCH` request
| `true`

| api:http.HttpRequest.DELETE(java.lang.String)[]
| Constructs an HTTP `DELETE` request
| `true`

|===

A `create` method also exists to construct a request for any api:http.HttpMethod[] type. Since the `POST`, `PUT` and `PATCH` methods require a body, a second argument which is the body object is required.

The following example demonstrates how to send a simply `String` body:

.Sending a `String` body
[source,java]
----
include::{testsclient}/basics/HelloControllerTest.java[tags=poststring, indent=0]
----

<1> The `POST` method is used with the first argument being the URI and the second argument the body
<2> The content type and accepted type are set to `text/plain` (the default content type is `application/json`)
<3> The expected response type is a `String`

== Sending JSON

The previous example sends plain text, if you wish send JSON you can simply pass the object you wish to encode as JSON, whether that be a map or a POJO. As long as Jackson is able to encode it.

For example, the `Message` class from the previous section, you can create an instance and pass it to the `POST` method:

.Sending a JSON body
[source,java]
----
include::{testsclient}/basics/HelloControllerTest.java[tags=postpojo, indent=0]
----

<1> And instance of `Message` is created and passed to the `POST` method
<2> The same class is used to decode the response

With the above example the following JSON will be sent as the body of the request:

.Resulting JSON
[source,json]
----
{"text":"Hello John"}
----

The JSON itself can be customized however you want using https://github.com/FasterXML/jackson-annotations[Jackson Annotations].

== Using a URI Template

If some of the properties of the object need to be in the URI being posted to you can use a URI template.

For example imagine you have a class `Book` that has a property called `title`. You can represent the `title` property in the URI template and then populate it from an instance of `Book`. For example:

.Sending a JSON body with a URI template
[source,java]
----
include::{testsclient}/basics/BookControllerTest.java[tags=posturitemplate, indent=0]
----

In the above case the `title` property of the passed object will be included in the URI being posted to.

== Sending Form Data

You can also encode a POJO or a map as regular form data instead of JSON. Just set the content type to `application/x-www-form-urlencoded` on the post request:

.Sending a Form Data
[source,java]
----
include::{testsclient}/basics/BookControllerTest.java[tags=postform, indent=0]
----

Note that Jackson is used to bind form data too, so to customize the binding process you can use https://github.com/FasterXML/jackson-annotations[Jackson annotations].

